// RichChapterContent.swift
// ────────────────────────────────────────────────────────────────────────────
// Swift mirror of the TypeScript RichChapterContent shape produced by
// scripts/build-content-packs.ts. Decodes the per-book pack JSON.
//
// JSON shape (top level of a pack):
//   {
//     "book_slug": "genesis",
//     "book_name": "Genesis",
//     "pack_version": 1,
//     "generated_at": "...",
//     "chapters": {
//       "1": { ...RichChapterContent... },
//       "2": { ...RichChapterContent... },
//       ...
//     }
//   }

import Foundation

struct ContentPack: Codable, Sendable {
    let bookSlug: String
    let bookName: String
    let packVersion: Int
    let generatedAt: String
    /// JSON keys are stringified chapter numbers ("1", "2", ...).
    let chapters: [String: RichChapterContent]

    enum CodingKeys: String, CodingKey {
        case bookSlug = "book_slug"
        case bookName = "book_name"
        case packVersion = "pack_version"
        case generatedAt = "generated_at"
        case chapters
    }

    /// Convenience — sorted chapter numbers as Ints.
    var chapterNumbers: [Int] {
        chapters.keys.compactMap(Int.init).sorted()
    }

    func chapter(_ n: Int) -> RichChapterContent? {
        chapters[String(n)]
    }
}

// MARK: - Rich chapter shape (mirrors src/data/study-chapters/types.ts)

struct RichChapterContent: Codable, Sendable {
    var bookSlug: String
    var bookName: String
    var chapter: Int
    var intros: [String]
    var tapHint: String?
    var showKjvNote: Bool?
    var opener: Opener?
    var sections: [RichSection]
    var bottomShare: BottomShare?
    var hasHebrew: Bool?

    /// External research resources (museums, manuscript collections, etc.)
    /// referenced inline via `VerseSpan.resource(_:resourceId:)`. The reader
    /// renders these as a "Further study" section at the bottom of the
    /// chapter, with auto-numbered superscripts that anchor back to the
    /// inline marks. See `src/data/study-chapters/types.ts → ResourceLink`.
    var resources: [ResourceLink]?

    /// Author-ordered thematic topic slugs (most-salient first). Used by
    /// the artwork resolver for topical-fallback matching on chapters
    /// without scene-specific plates. Web vocabulary lives in
    /// `src/data/art/topics.ts`.
    var topicTags: [String]?

    /// Per-tier estimated reading time, in whole minutes. Generated by
    /// the audit pass at `scripts/audit-and-tag-depth.ts`. Surface in
    /// the depth picker so users see real per-chapter time.
    var estimatedMinutes: EstimatedMinutes?

    /// Polished one-paragraph summary for the /christ index page on
    /// web. iOS currently doesn't surface this anywhere but decoding it
    /// keeps the data round-trippable for future Christ Index features.
    var christIndexSummary: String?

    /// Audience-aware overrides applied when the reader picks 'youth'.
    /// Kids audience uses a separate schema (out of scope for this
    /// decoder — see `src/data/kids-chapters/types-kids.ts`).
    var youth: YouthOverrides?

    /// Named characters who appear in this chapter, drawn from the
    /// shared library at `src/data/study-chapters/characters.ts`.
    /// Renders as a "People in this chapter" ribbon between intros and
    /// the first section. Bios deepen with the active study level.
    var characters: [ChapterCharacter]?

    /// Optional inline map for narrative chapters. Lightweight inline
    /// SVG over a preset silhouette — no third-party GIS dependency.
    var map: ChapterMap?

    enum CodingKeys: String, CodingKey {
        case bookSlug, bookName, chapter
        case intros, tapHint, showKjvNote, opener, sections, bottomShare, hasHebrew
        case resources, topicTags, estimatedMinutes, christIndexSummary, youth, characters, map
    }

    struct Opener: Codable, Sendable {
        let matchTitle: SerializedRegex?
        let matchArtist: SerializedRegex?
        let artworkSlug: String?
        let caption: String
    }

    struct BottomShare: Codable, Sendable {
        let quote: String
        let snippet: String
        let ref: String
        let label: String?
    }
}

struct RichSection: Codable, Sendable {
    var ref: String?
    var title: String?
    var blocks: [AnnotatedBlock]
    /// 3–5 cross-references surfacing places elsewhere in Scripture where
    /// the same theme echoes. Rendered after the section's last block.
    /// Curated per-section by authors; falls back to a chapter-level pool
    /// when omitted. The build script bakes the resolved set into the
    /// pack so iOS doesn't need to ship a fallback table.
    var crossRefs: [CrossRef]?
}

// MARK: - Reader prefs (study level + audience)
//
// Mirrors the TS enums in `src/data/study-chapters/types.ts` and the
// shared persistence contract in `src/lib/readerPrefs.ts`.

/// Study depth — Beginner / Standard / Deep. Drives which Blocks are
/// rendered. Numeric rank in `LEVEL_RANK` defines the partial order.
enum StudyLevel: String, Codable, Sendable, Hashable, CaseIterable {
    case beginner
    case intermediate
    case deep
}

private let LEVEL_RANK: [StudyLevel: Int] = [
    .beginner: 1,
    .intermediate: 2,
    .deep: 3,
]

/// `>=` over StudyLevels — used to decide whether a block whose
/// `effectiveMinLevel` is `min` survives at active level `level`.
func isAtLeastLevel(_ level: StudyLevel, _ min: StudyLevel) -> Bool {
    (LEVEL_RANK[level] ?? 0) >= (LEVEL_RANK[min] ?? 0)
}

/// Reader audience — orthogonal to StudyLevel. Adults and Youth share
/// the same chapter file; Kids is a separate schema that bypasses
/// `RichChapterContent` entirely (the kids registry is consulted by
/// the route, not by this decoder).
enum Audience: String, Codable, Sendable, Hashable, CaseIterable {
    case adults
    case youth
    case kids
}

// MARK: - Block metadata

/// Per-block override for Youth audience. Use for commentary / christ /
/// carry / reflection blocks where the adult version is work / marriage /
/// parenting-coded and the teen-relevant version should be school /
/// friends / identity-coded.
struct YouthOverride: Codable, Sendable, Hashable {
    /// Replacement HTML for blocks rendered with `html` (commentary,
    /// christ, carry). Other fields on the block stay the same.
    var html: String?
    /// Replacement reflection prompt. Only meaningful on `kind:
    /// 'reflection'`.
    var prompt: String?
    /// Replacement title. Only meaningful on titled blocks (christ).
    var title: String?
}

/// Per-block render-control metadata — flat sidecar to the kind-specific
/// payload in `Block`. Mirrors the TS Block schema's three "every block
/// can carry these" fields. Decoded from the same JSON object as the
/// Block payload itself (see `AnnotatedBlock.Codable`).
struct BlockMeta: Codable, Sendable, Hashable {
    /// Author-set minimum study level. When omitted, the block kind's
    /// default applies (see `defaultMinLevel`).
    var minLevel: StudyLevel?
    /// When true, hide this block when the reader's audience is `.youth`.
    var hideForYouth: Bool?
    /// Per-block text swap applied when audience is `.youth`. Only
    /// commentary / christ / carry / reflection blocks honor this.
    var youthOverride: YouthOverride?

    init(
        minLevel: StudyLevel? = nil,
        hideForYouth: Bool? = nil,
        youthOverride: YouthOverride? = nil
    ) {
        self.minLevel = minLevel
        self.hideForYouth = hideForYouth
        self.youthOverride = youthOverride
    }

    private enum Keys: String, CodingKey {
        case minLevel, hideForYouth, youthOverride
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: Keys.self)
        self.minLevel = try c.decodeIfPresent(StudyLevel.self, forKey: .minLevel)
        self.hideForYouth = try c.decodeIfPresent(Bool.self, forKey: .hideForYouth)
        self.youthOverride = try c.decodeIfPresent(YouthOverride.self, forKey: .youthOverride)
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: Keys.self)
        try c.encodeIfPresent(minLevel, forKey: .minLevel)
        try c.encodeIfPresent(hideForYouth, forKey: .hideForYouth)
        try c.encodeIfPresent(youthOverride, forKey: .youthOverride)
    }
}

/// A `Block` payload paired with its render-control `BlockMeta`. JSON
/// representation is one flat object — both halves decode from / encode
/// to the same KeyedEncodingContainer, using disjoint key sets.
///
/// Why a wrapper rather than adding the meta fields to every Block case:
/// the meta fields are universal across all 10 block kinds (every TS
/// case carries optional `minLevel`/`hideForYouth`; four cases carry
/// `youthOverride`). Adding them as associated values on each enum case
/// would multiply the case shapes and force every existing switch
/// pattern to update. The wrapper keeps `Block`'s pattern-matching API
/// stable and isolates the universal concerns.
struct AnnotatedBlock: Sendable {
    var block: Block
    var meta: BlockMeta

    init(block: Block, meta: BlockMeta = BlockMeta()) {
        self.block = block
        self.meta = meta
    }
}

extension AnnotatedBlock: Codable {
    init(from decoder: Decoder) throws {
        self.block = try Block(from: decoder)
        self.meta = try BlockMeta(from: decoder)
    }

    func encode(to encoder: Encoder) throws {
        try block.encode(to: encoder)
        try meta.encode(to: encoder)
    }
}

// MARK: - Level / audience helpers

/// Default `minLevel` for a block kind when the author hasn't set one.
/// Scripture / christ / carry are the spine of every chapter and appear
/// at every level. Commentary is the teaching layer — Intermediate up.
/// Hebrew / Greek / Reflection / Artwork are the deepest layer. Dividers
/// take the lowest level so they never orphan content above.
///
/// Mirrors `defaultMinLevel` in `src/data/study-chapters/types.ts`.
func defaultMinLevel(_ block: Block) -> StudyLevel {
    switch block {
    case .scripture, .christ, .carry:
        return .beginner
    case .commentary:
        return .intermediate
    case .hebrew, .greek, .reflection, .artwork:
        return .deep
    case .divider:
        return .beginner
    case .unknown:
        return .beginner
    }
}

/// A block's effective minimum study level — explicit override or kind
/// default.
func effectiveMinLevel(_ annotated: AnnotatedBlock) -> StudyLevel {
    annotated.meta.minLevel ?? defaultMinLevel(annotated.block)
}

/// True iff the annotated block should render at the given active level.
func isVisible(_ annotated: AnnotatedBlock, atLevel level: StudyLevel) -> Bool {
    isAtLeastLevel(level, effectiveMinLevel(annotated))
}

// MARK: - Block (sum type — decoded by the `kind` discriminator)

enum Block: Sendable {
    case scripture(chapter: Int, lines: [VerseLine])
    case commentary(id: String?, html: String)
    case hebrew(id: String, title: String, script: String, translit: String, description: String)
    case greek(id: String, title: String, script: String, translit: String, description: String)
    case christ(id: String, title: String, html: String)
    case carry(html: String)
    case reflection(id: String, prompt: String)
    case artwork(matchTitle: SerializedRegex?, matchArtist: SerializedRegex?, artworkSlug: String?, caption: String)
    case divider
    /// Forward-compat: any future block kind we haven't taught Swift about
    /// yet decodes as .unknown so the pack still renders.
    case unknown(kind: String)
}

extension Block: Codable {
    private enum Keys: String, CodingKey {
        case kind, id, html, chapter, lines
        case title, script, translit, description
        case prompt
        case matchTitle, matchArtist, artworkSlug, caption
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: Keys.self)
        let kind = try c.decode(String.self, forKey: .kind)
        switch kind {
        case "scripture":
            let chap = try c.decode(Int.self, forKey: .chapter)
            let lines = try c.decode([VerseLine].self, forKey: .lines)
            self = .scripture(chapter: chap, lines: lines)
        case "commentary":
            let id = try c.decodeIfPresent(String.self, forKey: .id)
            let html = try c.decode(String.self, forKey: .html)
            self = .commentary(id: id, html: html)
        case "hebrew":
            self = .hebrew(
                id: try c.decode(String.self, forKey: .id),
                title: try c.decode(String.self, forKey: .title),
                script: try c.decode(String.self, forKey: .script),
                translit: try c.decode(String.self, forKey: .translit),
                description: try c.decode(String.self, forKey: .description)
            )
        case "greek":
            self = .greek(
                id: try c.decode(String.self, forKey: .id),
                title: try c.decode(String.self, forKey: .title),
                script: try c.decode(String.self, forKey: .script),
                translit: try c.decode(String.self, forKey: .translit),
                description: try c.decode(String.self, forKey: .description)
            )
        case "christ":
            self = .christ(
                id: try c.decode(String.self, forKey: .id),
                title: try c.decode(String.self, forKey: .title),
                html: try c.decode(String.self, forKey: .html)
            )
        case "carry":
            self = .carry(html: try c.decode(String.self, forKey: .html))
        case "reflection":
            self = .reflection(
                id: try c.decode(String.self, forKey: .id),
                prompt: try c.decode(String.self, forKey: .prompt)
            )
        case "artwork":
            self = .artwork(
                matchTitle: try c.decodeIfPresent(SerializedRegex.self, forKey: .matchTitle),
                matchArtist: try c.decodeIfPresent(SerializedRegex.self, forKey: .matchArtist),
                artworkSlug: try c.decodeIfPresent(String.self, forKey: .artworkSlug),
                caption: try c.decode(String.self, forKey: .caption)
            )
        case "divider":
            self = .divider
        default:
            self = .unknown(kind: kind)
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: Keys.self)
        switch self {
        case .scripture(let chapter, let lines):
            try c.encode("scripture", forKey: .kind)
            try c.encode(chapter, forKey: .chapter)
            try c.encode(lines, forKey: .lines)
        case .commentary(let id, let html):
            try c.encode("commentary", forKey: .kind)
            try c.encodeIfPresent(id, forKey: .id)
            try c.encode(html, forKey: .html)
        case .hebrew(let id, let title, let script, let translit, let description):
            try c.encode("hebrew", forKey: .kind)
            try c.encode(id, forKey: .id)
            try c.encode(title, forKey: .title)
            try c.encode(script, forKey: .script)
            try c.encode(translit, forKey: .translit)
            try c.encode(description, forKey: .description)
        case .greek(let id, let title, let script, let translit, let description):
            try c.encode("greek", forKey: .kind)
            try c.encode(id, forKey: .id)
            try c.encode(title, forKey: .title)
            try c.encode(script, forKey: .script)
            try c.encode(translit, forKey: .translit)
            try c.encode(description, forKey: .description)
        case .christ(let id, let title, let html):
            try c.encode("christ", forKey: .kind)
            try c.encode(id, forKey: .id)
            try c.encode(title, forKey: .title)
            try c.encode(html, forKey: .html)
        case .carry(let html):
            try c.encode("carry", forKey: .kind)
            try c.encode(html, forKey: .html)
        case .reflection(let id, let prompt):
            try c.encode("reflection", forKey: .kind)
            try c.encode(id, forKey: .id)
            try c.encode(prompt, forKey: .prompt)
        case .artwork(let matchTitle, let matchArtist, let artworkSlug, let caption):
            try c.encode("artwork", forKey: .kind)
            try c.encodeIfPresent(matchTitle, forKey: .matchTitle)
            try c.encodeIfPresent(matchArtist, forKey: .matchArtist)
            try c.encodeIfPresent(artworkSlug, forKey: .artworkSlug)
            try c.encode(caption, forKey: .caption)
        case .divider:
            try c.encode("divider", forKey: .kind)
        case .unknown(let kind):
            try c.encode(kind, forKey: .kind)
        }
    }
}

// MARK: - Verse spans

struct VerseLine: Codable, Sendable, Identifiable {
    let number: Int
    let spans: [VerseSpan]
    var id: Int { number }
}

enum VerseSpan: Sendable {
    case text(String)
    case mark(tone: String, text: String, jumpTo: String)
    /// Plain (un-highlighted) text with a small superscript number rendered
    /// immediately after it. The number is auto-assigned in document order
    /// and anchors down to the matching entry in
    /// `RichChapterContent.resources`.
    case resource(text: String, resourceId: String)
}

extension VerseSpan: Codable {
    private enum Keys: String, CodingKey { case kind, text, tone, jumpTo, resourceId }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: Keys.self)
        let kind = try c.decode(String.self, forKey: .kind)
        switch kind {
        case "text":
            self = .text(try c.decode(String.self, forKey: .text))
        case "mark":
            self = .mark(
                tone: try c.decode(String.self, forKey: .tone),
                text: try c.decode(String.self, forKey: .text),
                jumpTo: try c.decode(String.self, forKey: .jumpTo)
            )
        case "resource":
            self = .resource(
                text: try c.decode(String.self, forKey: .text),
                resourceId: try c.decode(String.self, forKey: .resourceId)
            )
        default:
            // Unknown span kind — render as plain text.
            let text = (try? c.decode(String.self, forKey: .text)) ?? ""
            self = .text(text)
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: Keys.self)
        switch self {
        case .text(let s):
            try c.encode("text", forKey: .kind)
            try c.encode(s, forKey: .text)
        case .mark(let tone, let text, let jumpTo):
            try c.encode("mark", forKey: .kind)
            try c.encode(tone, forKey: .tone)
            try c.encode(text, forKey: .text)
            try c.encode(jumpTo, forKey: .jumpTo)
        case .resource(let text, let resourceId):
            try c.encode("resource", forKey: .kind)
            try c.encode(text, forKey: .text)
            try c.encode(resourceId, forKey: .resourceId)
        }
    }

    /// Plain text content of the span (loses highlight styling and any
    /// superscript resource marker — that's a render-layer concern).
    var text: String {
        switch self {
        case .text(let s): return s
        case .mark(_, let text, _): return text
        case .resource(let text, _): return text
        }
    }
}

// MARK: - SerializedRegex
// The pack builder marshals JS RegExp as { pattern, flags }. We don't need
// to actually run these on the device for v1 — they're metadata for the
// artwork-matching logic on the web. Decode + keep as opaque structs.

struct SerializedRegex: Codable, Sendable {
    let pattern: String
    let flags: String?
}

// MARK: - CrossRef
// Per-section cross-reference card. 3–5 entries pointing at places elsewhere
// in Scripture where the same theme echoes. See
// `src/data/study-chapters/types.ts → CrossRef`.

struct CrossRef: Codable, Sendable, Hashable {
    /// Display label, e.g. "John 1:1–3", "Hebrews 11:3".
    let ref: String
    /// Short passage snippet so readers preview without leaving.
    let snippet: String
    /// Destination URL — defaults to the canonical Learn of Christ chapter
    /// page when omitted (`/study/<book>/<chapter>`).
    let href: String?
    /// Optional one-line note explaining *why* this passage echoes.
    let note: String?
}

// MARK: - Resources (Further study)
// Curated external links surfaced at the bottom of a chapter and anchored
// from inline `VerseSpan.resource` marks. See
// `src/data/study-chapters/types.ts → ResourceLink`.

struct ResourceLink: Codable, Sendable, Identifiable, Hashable {
    /// Stable id referenced by inline `.resource` spans. Lowercase + hyphens.
    let id: String
    /// Source institution / publisher (rendered in small caps).
    let source: String
    /// Short, scannable title of the artifact / paper.
    let label: String
    /// Stable, institutional URL.
    let url: String
    /// One-sentence (occasionally two) explanation of what + why.
    let description: String
    /// Badge driver — one of: museum, manuscript, archaeology, lexicon,
    /// study, archive.
    let kind: String
}

// MARK: - EstimatedMinutes
// Per-tier reading time written by the depth-audit pass.

struct EstimatedMinutes: Codable, Sendable, Hashable {
    let beginner: Int
    let intermediate: Int
    let deep: Int
}

// MARK: - Characters
// "People in this chapter" ribbon, drawn from the shared character library.

struct ChapterCharacter: Codable, Sendable, Hashable {
    /// Stable slug into `src/data/study-chapters/characters.ts`.
    let slug: String
    /// Optional per-chapter role override (e.g. "the rejected king" for
    /// Saul in 1 Samuel 16). Falls back to the library's default role.
    let role: String?
}

// MARK: - Map
// Lightweight inline SVG map rendered just below the chapter opener for
// narrative chapters. Coordinates normalized to a 0–1 box over a preset
// silhouette so we never ship a full GIS dataset.

struct ChapterMap: Codable, Sendable, Hashable {
    /// Preset silhouette identifier: one of `holy-land`, `mediterranean`,
    /// `sinai`, `mesopotamia`, `judea`. Kept as String for forward-compat
    /// when the web adds presets the iOS render layer hasn't taught itself
    /// about yet.
    let preset: String
    /// Places appearing in this chapter, in narrative order.
    let places: [ChapterMapPlace]
    /// When set, draws thin lines connecting `places` by index in this
    /// order (e.g. [0, 1, 2, 3]) so readers can trace the journey.
    let route: [Int]?
    /// Caption beneath the map.
    let caption: String?
}

struct ChapterMapPlace: Codable, Sendable, Hashable {
    /// Display name, e.g. "Philippi", "Bethlehem".
    let name: String
    /// X in 0–1 space within the preset's bounding box (0 = left).
    let x: Double
    /// Y in 0–1 space within the preset's bounding box (0 = top).
    let y: Double
    /// Marker emphasis: `origin` (starting point), `visit` (waypoint), or
    /// `travel-to` (destination). Optional.
    let kind: String?
    /// Optional short legend note.
    let note: String?
}

// MARK: - Youth overrides
// Audience-aware overrides applied at render time when audience == 'youth'.
// Only the fields the author wants to swap need to be set; everything else
// falls through to the canonical chapter fields. Adults always get the
// canonical chapter; Kids uses a separate schema entirely.

struct YouthOverrides: Codable, Sendable, Hashable {
    /// Replacement intros (full list, not patch).
    let intros: [String]?
    /// Replacement bottom-share card.
    let bottomShare: RichChapterContent.BottomShare?
    /// Replacement Christ Index summary.
    let christIndexSummary: String?
}

// NOTE — per-block youth overrides (`hideForYouth`, `youthOverride`,
// `minLevel`) live on individual `Block` cases and are not yet modeled
// here. The block-level audience filter is the next decoder extension
// after this one — see the iOS port audit punch-list item #1b /
// item #10 (Translation + Depth + Audience picker UI).
