#!/usr/bin/env node
/**
 * Ingest Metropolitan Museum of Art (Met) Open Access biblical works
 * into Supabase.
 *
 * Reads src/data/art/met.ts (auto-generated by harvest-met.mjs), then:
 *   1. Upserts every distinct artist record.
 *   2. Reuses existing scene records (created during Doré ingestion).
 *   3. For each plate:
 *        - Upserts artwork (idempotent via source + external_id)
 *        - Upserts artwork_scripture_refs
 *        - Upserts artwork_scenes join
 *
 * `source = 'met_openaccess'` is a single cross-artist source — Met
 * holdings span hundreds of hands and the canonical image URL points
 * at the Met's own image CDN (images.metmuseum.org).
 *
 * Every artwork lands with status='published' but moderation_status
 * defaults to 'pending'. The reader-facing feed only renders
 * moderation_status='approved' rows, so a human still has to clear
 * each image through /admin/artwork-moderation before it surfaces.
 *
 * Usage:
 *   SUPABASE_SERVICE_ROLE_KEY=your_key node scripts/ingest-met.mjs
 *
 * Idempotent — safe to re-run.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SUPABASE_URL = 'https://uqcgieillyvefzmohzpn.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

// ───────── Supabase helpers ─────────

async function supabaseRequest(method, path, body) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    method,
    headers: {
      'Content-Type': 'application/json',
      apikey: SUPABASE_SERVICE_KEY,
      Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
      Prefer: 'return=representation,resolution=merge-duplicates',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`${method} ${path} -> ${res.status}: ${text}`);
  return text ? JSON.parse(text) : null;
}

async function supabaseSelect(table, params = '') {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`, {
    headers: {
      apikey: SUPABASE_SERVICE_KEY,
      Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
    },
  });
  if (!res.ok) throw new Error(`Select ${table} -> ${res.status}: ${await res.text()}`);
  return res.json();
}

async function upsert(table, rows, onConflict) {
  if (rows.length === 0) return [];
  return supabaseRequest('POST', `${table}?on_conflict=${onConflict}`, rows);
}

// ───────── Parse met.ts without TS/bundler ─────────

function loadMetData() {
  const path = resolve(__dirname, '../src/data/art/met.ts');
  const source = readFileSync(path, 'utf8');

  const cleaned = source
    .replace(/export type [\s\S]*?^};/gm, '')
    .replace(/export const (\w+): [^=]+=/g, 'export const $1 =');

  const artistsMatch = cleaned.match(/export const MET_ARTISTS\s*=\s*(\[[\s\S]*?^\]);/m);
  const platesMatch = cleaned.match(/export const MET_PLATES\s*=\s*(\[[\s\S]*?^\]);/m);
  if (!artistsMatch || !platesMatch) {
    throw new Error('Failed to parse met.ts — expected MET_ARTISTS and MET_PLATES arrays');
  }
  const artists = new Function(`return ${artistsMatch[1]};`)();
  const plates = new Function(`return ${platesMatch[1]};`)();
  return { artists, plates };
}

// ───────── Main ─────────

async function main() {
  if (!SUPABASE_SERVICE_KEY) {
    console.error('Missing SUPABASE_SERVICE_ROLE_KEY env var');
    process.exit(1);
  }

  console.log('=== Met Open Access Biblical Works Ingest ===\n');

  const { artists, plates } = loadMetData();
  console.log(`Loaded ${artists.length} artists and ${plates.length} plates from met.ts`);

  // 1. Artists
  console.log('\n→ Upserting artists');
  const BATCH = 100;
  const upsertedArtists = [];
  for (let i = 0; i < artists.length; i += BATCH) {
    const chunk = artists.slice(i, i + BATCH).map((a) => ({
      slug: a.slug,
      name: a.name,
      birth_year: a.birthYear,
      death_year: a.deathYear,
      nationality: a.nationality,
      bio: a.bio,
      wikipedia_url: a.wikipediaUrl,
    }));
    const rows = await upsert('artists', chunk, 'slug');
    upsertedArtists.push(...rows);
    console.log(`   batch ${Math.floor(i / BATCH) + 1}: ${rows.length} upserted`);
  }
  const artistBySlug = new Map(upsertedArtists.map((a) => [a.slug, a]));

  // 2. Scenes (reuse existing)
  const scenes = await supabaseSelect('scenes', 'select=id,slug');
  const sceneBySlug = new Map(scenes.map((s) => [s.slug, s.id]));
  console.log(`\n   reusing ${scenes.length} existing scenes`);

  // 3. Books
  const books = await supabaseSelect('books', 'select=id,slug');
  const bookBySlug = new Map(books.map((b) => [b.slug, b.id]));

  // 4. Artworks
  console.log(`\n→ Building ${plates.length} artwork rows`);
  const artworkRows = [];
  const unknownArtists = [];

  for (const p of plates) {
    const artist = artistBySlug.get(p.creatorSlug);
    if (!artist) {
      unknownArtists.push(p.externalId);
      continue;
    }

    const description = [
      p.objectDate && p.objectDate !== String(p.year) ? `Dated ${p.objectDate}.` : null,
      p.classification ? `Classification: ${p.classification}.` : null,
      p.department ? `${p.department}, The Metropolitan Museum of Art.` : null,
    ]
      .filter(Boolean)
      .join(' ') || null;

    artworkRows.push({
      slug: p.externalId,
      title: p.title,
      artist_id: artist.id,
      year: p.year,
      medium: p.medium,
      source: 'met_openaccess',
      source_url: p.objectURL,
      external_id: String(p.objectId),
      image_url: p.primaryImage,
      thumbnail_url: p.primaryImageSmall || p.primaryImage,
      license: 'public_domain',
      license_note: p.creditLine
        ? `Public domain via The Metropolitan Museum of Art (Open Access). ${p.creditLine}.`
        : 'Public domain via The Metropolitan Museum of Art (Open Access).',
      description,
      status: 'published',
    });
  }

  if (unknownArtists.length > 0) {
    console.warn(`   ! ${unknownArtists.length} plate(s) had unknown creatorSlug and were skipped`);
  }

  console.log(`\n→ Upserting ${artworkRows.length} artworks`);
  const upsertedArtworks = [];
  for (let i = 0; i < artworkRows.length; i += BATCH) {
    const chunk = artworkRows.slice(i, i + BATCH);
    const rows = await upsert('artworks', chunk, 'source,external_id');
    upsertedArtworks.push(...rows);
    console.log(`   batch ${Math.floor(i / BATCH) + 1}: ${rows.length} upserted`);
  }
  const artworkByExternal = new Map(upsertedArtworks.map((a) => [a.external_id, a]));

  // 5. Scripture refs
  const scriptureRefs = [];
  const unknownBooks = [];
  for (const p of plates) {
    const artwork = artworkByExternal.get(String(p.objectId));
    if (!artwork) continue;
    const bookId = bookBySlug.get(p.bookSlug);
    if (!bookId) {
      unknownBooks.push(`${p.externalId}: ${p.bookSlug}`);
      continue;
    }
    scriptureRefs.push({
      artwork_id: artwork.id,
      book_id: bookId,
      chapter: p.chapter,
      verse_start: null,
      verse_end: null,
      is_primary: true,
    });
  }
  if (unknownBooks.length > 0) {
    console.warn(`   ! unknown book slugs:\n     ${unknownBooks.slice(0, 10).join('\n     ')}${unknownBooks.length > 10 ? `\n     ...and ${unknownBooks.length - 10} more` : ''}`);
  }

  console.log(`\n→ Upserting ${scriptureRefs.length} scripture refs`);
  for (let i = 0; i < scriptureRefs.length; i += BATCH) {
    const chunk = scriptureRefs.slice(i, i + BATCH);
    await upsert(
      'artwork_scripture_refs',
      chunk,
      'artwork_id,book_id,chapter,verse_start,verse_end',
    );
  }

  // 6. Scene joins
  const sceneJoins = [];
  const unknownScenes = [];
  for (const p of plates) {
    if (!p.sceneSlug) continue;
    const artwork = artworkByExternal.get(String(p.objectId));
    if (!artwork) continue;
    const sceneId = sceneBySlug.get(p.sceneSlug);
    if (!sceneId) {
      unknownScenes.push(`${p.externalId}: ${p.sceneSlug}`);
      continue;
    }
    sceneJoins.push({ artwork_id: artwork.id, scene_id: sceneId });
  }
  if (unknownScenes.length > 0) {
    console.warn(`   ! unknown scene slugs:\n     ${unknownScenes.slice(0, 10).join('\n     ')}`);
  }

  console.log(`\n→ Upserting ${sceneJoins.length} artwork↔scene joins`);
  for (let i = 0; i < sceneJoins.length; i += BATCH) {
    const chunk = sceneJoins.slice(i, i + BATCH);
    if (chunk.length > 0) {
      await upsert('artwork_scenes', chunk, 'artwork_id,scene_id');
    }
  }

  // ───────── Summary ─────────
  console.log('\n=== Done ===');
  console.log(`Artists upserted:           ${upsertedArtists.length}`);
  console.log(`Artworks upserted:          ${upsertedArtworks.length}`);
  console.log(`Scripture refs upserted:    ${scriptureRefs.length}`);
  console.log(`Scene joins upserted:       ${sceneJoins.length}`);
  if (unknownArtists.length > 0) console.log(`Plates skipped (artist):    ${unknownArtists.length}`);
  if (unknownBooks.length > 0)   console.log(`Refs skipped (book):        ${unknownBooks.length}`);
  if (unknownScenes.length > 0)  console.log(`Joins skipped (scene):      ${unknownScenes.length}`);
  console.log('\nNext step: bulk-moderate → human review at /admin/artwork-moderation');
  console.log('  node scripts/moderate-all-artworks.mjs');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
