-- Wikidata Q-IDs for bio'd artists.
-- Generated by scripts/backfill-wikidata-ids.mjs.
-- Each Q-ID was selected by:
--   * Wikidata wbsearchentities lookup on the display name.
--   * wbgetentities verification of:
--       - instance_of includes human (Q5)
--       - occupation includes a recognized art occupation
--       - date_of_birth year is within ±5 of our row
-- Rows with no confident match are emitted as comments.

-- Adriaen Collaert (1560–1618)  →  Q2825010  Flemish printmaker, publisher and draughtsman (1560-1618)
update public.artists set wikidata_id = 'Q2825010' where slug in ('adriaen-collaert');

-- Agostino Carracci (1557–1602)  →  Q316269  Bolognese painter of the Baroque (1557-1602)
update public.artists set wikidata_id = 'Q316269' where slug in ('agostino-carracci');

-- Albrecht Altdorfer (1480–1538)  →  Q153746  German painter (1480–1538)
update public.artists set wikidata_id = 'Q153746' where slug in ('albrecht-altdorfer');

-- Albrecht Dürer (1471–1528)  →  Q5580  German painter, printmaker, mathematician, and theorist (1471-1528)
update public.artists set wikidata_id = 'Q5580' where slug in ('albrecht-durer', 'albrecht-d-rer');

-- Andrea del Sarto (Andrea d'Agnolo) (1486–1530)  →  Q5571  Italian painter (1486-1530)
update public.artists set wikidata_id = 'Q5571' where slug in ('andrea-del-sarto-andrea-d-agnolo');

-- Andrea del Verrocchio (1435–1488)  →  Q183458  15th century Italian sculptor, goldsmith and painter (c.1435-1488)
update public.artists set wikidata_id = 'Q183458' where slug in ('andrea-del-verrocchio');

-- Andrea Mantegna (1430–1506)  →  Q5681  Italian Renaissance painter (1431-1506)
update public.artists set wikidata_id = 'Q5681' where slug in ('andrea-mantegna');

-- Andrea Solario (1465–1524)  →  Q495110  Italian painter (1460-1524)
update public.artists set wikidata_id = 'Q495110' where slug in ('andrea-solario');

-- Andrei Rublev (1360–1430)  →  Q838  medieval Russian artist (1360s-1428)
update public.artists set wikidata_id = 'Q838' where slug in ('andrei-rublev');

-- Annibale Carracci (1560–1609)  →  Q7824  Bolognese painter (1560–1609)
update public.artists set wikidata_id = 'Q7824' where slug in ('annibale-carracci');

-- Antonio Tempesta (1555–1630)  →  Q605447  painter from Florence (1555-1630)
update public.artists set wikidata_id = 'Q605447' where slug in ('antonio-tempesta');

-- Bartolomé Esteban Murillo (1617–1682)  →  Q192062  Spanish Baroque painter (1617–1682)
update public.artists set wikidata_id = 'Q192062' where slug in ('bartolome-esteban-murillo');

-- Bartolomé Estebán Murillo (1617–1682)  →  Q192062  Spanish Baroque painter (1617–1682)
update public.artists set wikidata_id = 'Q192062' where slug in ('bartolom-esteb-n-murillo');

-- Bernardo Daddi (1290–1348)  →  Q366562  Italian painter (1290–1348)
update public.artists set wikidata_id = 'Q366562' where slug in ('bernardo-daddi');

-- Bernhard Plockhorst (1825–1907)  →  Q552769  German artist (1825-1907)
update public.artists set wikidata_id = 'Q552769' where slug in ('bernhard-plockhorst');

-- Botticelli (Alessandro di Mariano Filipepi) (1444–1510)  →  Q5669  Italian painter (1445–1510)
update public.artists set wikidata_id = 'Q5669' where slug in ('botticelli-alessandro-di-mariano-filipepi');

-- Botticelli (1444–1510)  →  Q5669  Italian painter (1445–1510)
update public.artists set wikidata_id = 'Q5669' where slug in ('botticelli');

-- Caravaggio (Michelangelo Merisi) (1571–1610)  →  Q42207  Italian painter (1571–1610)
update public.artists set wikidata_id = 'Q42207' where slug in ('caravaggio-michelangelo-merisi');

-- Carl Heinrich Bloch (1834–1890)  →  Q547055  Danish painter (1834–1890)
update public.artists set wikidata_id = 'Q547055' where slug in ('carl-heinrich-bloch', 'carl-bloch');

-- Carlo Maratti (1625–1713)  →  Q538998  Italian painter (1625–1713)
update public.artists set wikidata_id = 'Q538998' where slug in ('carlo-maratti');

-- skip  Circle of Jan van Eyck (1390–1441)  slugs='circle-of-jan-van-eyck'
--   no candidates for "Circle of Jan van Eyck"

-- skip  Copy after Rogier van der Weyden (1399–1464)  slugs='copy-after-rogier-van-der-weyden'
--   no candidates for "Copy after Rogier van der Weyden"

-- Cornelis Cort (1533–1578)  →  Q167220  Dutch artist (c. 1533–1578)
update public.artists set wikidata_id = 'Q167220' where slug in ('cornelis-cort');

-- skip  Correggio (Antonio Allegri) (1514–1534)  slugs='correggio-antonio-allegri'
--   no candidates for "Correggio (Antonio Allegri)"
--   Q8457 birth-year mismatch: db=1514 wd=1489
--   Q111176 not human (Correggio)

-- Del Parson (1948–?)  →  Q5252961  American artist
update public.artists set wikidata_id = 'Q5252961' where slug in ('del-parson');

-- Diego Velázquez (1599–1660)  →  Q297  Spanish painter (1599-1660)
update public.artists set wikidata_id = 'Q297' where slug in ('diego-velazquez');

-- Domenichino (Domenico Zampieri) (1581–1641)  →  Q320118  Italian painter (1581–1641)
update public.artists set wikidata_id = 'Q320118' where slug in ('domenichino-domenico-zampieri');

-- Domenico Ghirlandaio (Domenico Bigordi) (1448–1494)  →  Q191423  Italian Renaissance painter from Florence (1448–1494)
update public.artists set wikidata_id = 'Q191423' where slug in ('domenico-ghirlandaio-domenico-bigordi');

-- Domenico Ghirlandaio (1448–1494)  →  Q191423  Italian Renaissance painter from Florence (1448–1494)
update public.artists set wikidata_id = 'Q191423' where slug in ('domenico-ghirlandaio');

-- Duccio di Buoninsegna (1255–1319)  →  Q15792  Italian painter
update public.artists set wikidata_id = 'Q15792' where slug in ('duccio-di-buoninsegna');

-- skip  El Greco (Domenikos Theotokopoulos) and Workshop (1540–1614)  slugs='el-greco-domenikos-theotokopoulos-and-workshop'
--   no candidates for "El Greco (Domenikos Theotokopoulos) and Workshop"

-- El Greco (Domenikos Theotokopoulos) (1540–1614)  →  Q301  Greek artist, painter, sculptor and architect (1541–1614)
update public.artists set wikidata_id = 'Q301' where slug in ('el-greco-domenikos-theotokopoulos');

-- El Greco (Doménikos Theotokópoulos) (1541–1614)  →  Q301  Greek artist, painter, sculptor and architect (1541–1614)
update public.artists set wikidata_id = 'Q301' where slug in ('el-greco');

-- Eugène Delacroix (1798–1863)  →  Q33477  French painter (1798–1863)
update public.artists set wikidata_id = 'Q33477' where slug in ('eug-ne-delacroix');

-- Federico Zuccaro (Zuccari) (1540–1609)  →  Q345605  Italian painter (1539-1609)
update public.artists set wikidata_id = 'Q345605' where slug in ('federico-zuccaro-zuccari');

-- Filippino Lippi (1457–1504)  →  Q296265  Italian painter (1457–1504)
update public.artists set wikidata_id = 'Q296265' where slug in ('filippino-lippi');

-- skip  Follower of Rogier van der Weyden (Master of the Saint Ursula Legend Group, Netherlandish, active late 15th century) (1470–1499)  slugs='follower-of-rogier-van-der-weyden-master-of-the-saint-ursula-legend-group-nether'
--   no candidates for "Follower of Rogier van der Weyden (Master of the Saint Ursula Legend Group, Netherlandish, active late 15th century)"
--   no candidates for "Follower of Rogier van der Weyden"
--   no candidates for "Master of the Saint Ursula Legend Group, Netherlandish, active late 15th century"

-- Fra Angelico (Guido di Pietro) (1395–1455)  →  Q5664  Italian Early Renaissance painter
update public.artists set wikidata_id = 'Q5664' where slug in ('fra-angelico-guido-di-pietro');

-- Fra Angelico (1395–1455)  →  Q5664  Italian Early Renaissance painter
update public.artists set wikidata_id = 'Q5664' where slug in ('fra-angelico');

-- Fra Filippo Lippi (1406–1469)  →  Q205148  Italian Renaissance painter (c. 1406–1469)
update public.artists set wikidata_id = 'Q205148' where slug in ('fra-filippo-lippi');

-- Francisco de Zurbarán (1598–1664)  →  Q209615  Spanish painter (1598–1664)
update public.artists set wikidata_id = 'Q209615' where slug in ('francisco-de-zurbar-n');

-- Gerard David (1455–1523)  →  Q333380  Early Netherlandish painter (c. 1460–1523)
update public.artists set wikidata_id = 'Q333380' where slug in ('gerard-david');

-- Giorgio Vasari (1511–1574)  →  Q128027  Italian painter, architect, writer and historian (1511-1574)
update public.artists set wikidata_id = 'Q128027' where slug in ('giorgio-vasari');

-- Giotto di Bondone (1266–1337)  →  Q7814  Italian painter and architect (c. 1267–1337)
update public.artists set wikidata_id = 'Q7814' where slug in ('giotto-di-bondone');

-- Giovanni Antonio da Pordenone (Giovanni Antonio de Sacchis) (1483–1539)  →  Q983352  Italian painter (1484-1539)
update public.artists set wikidata_id = 'Q983352' where slug in ('giovanni-antonio-da-pordenone-giovanni-antonio-de-sacchis');

-- skip  Giovanni Bellini (1424–1516)  slugs='giovanni-bellini'
--   Q17169 birth-year mismatch: db=1424 wd=1430
--   Q3766795 not art occupation (Giovanni Bellini)
--   Q104712710 not art occupation (Giovanni Bellini)

-- Giovanni Benedetto Castiglione (Il Grechetto) (1609–1664)  →  Q40823  Italian Baroque artist, painter, printmaker and draftsman
update public.artists set wikidata_id = 'Q40823' where slug in ('giovanni-benedetto-castiglione-il-grechetto');

-- Giovanni di Paolo (Giovanni di Paolo di Grazia) (1398–1482)  →  Q946420  Italian painter and illustrator of manuscripts (c. 1403-1482)
update public.artists set wikidata_id = 'Q946420' where slug in ('giovanni-di-paolo-giovanni-di-paolo-di-grazia');

-- Guercino (Giovanni Francesco Barbieri) (1591–1666)  →  Q334262  painter of the Italian 17th century (1591–1666)
update public.artists set wikidata_id = 'Q334262' where slug in ('guercino-giovanni-francesco-barbieri');

-- Guido Reni (1575–1642)  →  Q109061  Bolognese painter (1575–1642)
update public.artists set wikidata_id = 'Q109061' where slug in ('guido-reni');

-- Gustave Doré (1832–1883)  →  Q6682  French illustrator and painter (1832–1883)
update public.artists set wikidata_id = 'Q6682' where slug in ('gustave-dore', 'gustave-dor');

-- Hans Baldung (called Hans Baldung Grien) (1484–1545)  →  Q164696  German painter and printmaker (1484–1545)
update public.artists set wikidata_id = 'Q164696' where slug in ('hans-baldung-called-hans-baldung-grien');

-- Hans Baldung Grien (1484–1545)  →  Q164696  German painter and printmaker (1484–1545)
update public.artists set wikidata_id = 'Q164696' where slug in ('hans-baldung');

-- Hans Burgkmair (1473–1531)  →  Q313163  German painter (1473–1531)
update public.artists set wikidata_id = 'Q313163' where slug in ('hans-burgkmair');

-- Hans Holbein the Younger (1497–1543)  →  Q48319  German artist and printmaker (1497–1543)
update public.artists set wikidata_id = 'Q48319' where slug in ('hans-holbein-the-younger');

-- skip  Hans Memling (1465–1494)  slugs='hans-memling'
--   Q106851 birth-year mismatch: db=1465 wd=1435
--   Q68581581 not human (Hans Memling)
--   Q2432540 not human (Sint-Janshospitaal)

-- Hans Schäufelein (1480–1540)  →  Q675272  German artist (1480-1540)
update public.artists set wikidata_id = 'Q675272' where slug in ('hans-sch-ufelein');

-- Harry Anderson (1906–1996)  →  Q5666910  American artist (1906-1996)
update public.artists set wikidata_id = 'Q5666910' where slug in ('harry-anderson');

-- Heinrich Aldegrever (1502–1561)  →  Q62514  German painter and engraver
update public.artists set wikidata_id = 'Q62514' where slug in ('heinrich-aldegrever');

-- Heinrich Hofmann (1824–1911)  →  Q467449  German artist (1824-1911)
update public.artists set wikidata_id = 'Q467449' where slug in ('heinrich-hofmann');

-- Hendrick Goltzius (1558–1617)  →  Q165367  German-born Dutch printmaker, draftsman and painter (1558-1617)
update public.artists set wikidata_id = 'Q165367' where slug in ('hendrick-goltzius');

-- Hieronymus (Jerome) Wierix (1553–1619)  →  Q2778104  Flemish engraver and draughtsman (1553–1619)
update public.artists set wikidata_id = 'Q2778104' where slug in ('hieronymus-jerome-wierix');

-- Hieronymus Bosch (1450–1516)  →  Q130531  Dutch painter (c. 1450–1516)
update public.artists set wikidata_id = 'Q130531' where slug in ('hieronymus-bosch');

-- skip  Hugo van der Goes (1467–1482)  slugs='hugo-van-der-goes'
--   Q215251 birth-year mismatch: db=1467 wd=1440
--   Q2873693 not human (Avenue Hugo van der Goes - Hugo Van der Goeslaan)
--   Q19912645 not human (Hugo van der Goes Painting the Portrait of Mary of Burgundy)

-- skip  Israhel van Meckenem (1435–1503)  slugs='israhel-van-meckenem'
--   Q77554 not art occupation (Israhel van Meckenem)
--   Q1674748 not art occupation (Israhel Meckenem)
--   Q107137302 not human (Israhel van Meckenem's Man of Sorrows)

-- Jacopo Bassano (Jacopo da Ponte) (1510–1592)  →  Q346502  Italian painter (1510–1591)
update public.artists set wikidata_id = 'Q346502' where slug in ('jacopo-bassano-jacopo-da-ponte');

-- Jacopo Bellini (1393–1471)  →  Q313310  Italian painter
update public.artists set wikidata_id = 'Q313310' where slug in ('jacopo-bellini');

-- Jacopo da Pontormo (Jacopo Carucci) (1494–1556)  →  Q207929  Florentine Mannerist painter
update public.artists set wikidata_id = 'Q207929' where slug in ('jacopo-da-pontormo-jacopo-carucci');

-- Jacopo Tintoretto (Jacopo Robusti) (1518–1594)  →  Q9319  Renaissance painter (1518/1519–1594)
update public.artists set wikidata_id = 'Q9319' where slug in ('jacopo-tintoretto-jacopo-robusti');

-- Jacopo Tintoretto (1518–1594)  →  Q9319  Renaissance painter (1518/1519–1594)
update public.artists set wikidata_id = 'Q9319' where slug in ('jacopo-tintoretto');

-- Jacques Callot (1592–1635)  →  Q460124  Flemish-French engraver (c.1592–1635)
update public.artists set wikidata_id = 'Q460124' where slug in ('jacques-callot');

-- James Tissot (1836–1902)  →  Q381248  French painter and illustrator (1836–1902)
update public.artists set wikidata_id = 'Q381248' where slug in ('james-tissot');

-- Jan Luyken (1649–1712)  →  Q87466  Dutch engraver (1649-1712)
update public.artists set wikidata_id = 'Q87466' where slug in ('jan-luyken');

-- Jan van Eyck (1390–1441)  →  Q102272  Flemish painter (c.1390–1441)
update public.artists set wikidata_id = 'Q102272' where slug in ('jan-van-eyck');

-- skip  Joachim Patinir (1515–1524)  slugs='joachim-patinir'
--   Q442491 birth-year mismatch: db=1515 wd=1480
--   Q65087573 not human (Joachim Patinir)
--   Q19265570 not human (Joachim Patinirstraat)

-- Julius Schnorr von Carolsfeld (1794–1872)  →  Q703458  painter from Germany (1794-1872)
update public.artists set wikidata_id = 'Q703458' where slug in ('julius-schnorr-von-carolsfeld');

-- Jusepe de Ribera (called Lo Spagnoletto) (1591–1652)  →  Q297838  Spanish painter (1591–1652)
update public.artists set wikidata_id = 'Q297838' where slug in ('jusepe-de-ribera-called-lo-spagnoletto');

-- skip  Luca Signorelli (Luca d'Egidio di Luca di Ventura) (1470–1523)  slugs='luca-signorelli-luca-d-egidio-di-luca-di-ventura'
--   no candidates for "Luca Signorelli (Luca d'Egidio di Luca di Ventura)"
--   Q7031 birth-year mismatch: db=1470 wd=1450
--   Q130210702 not art occupation (Luca Signorelli)

-- skip  Lucas Cranach the Elder and Workshop (1472–1553)  slugs='lucas-cranach-the-elder-and-workshop'
--   no candidates for "Lucas Cranach the Elder and Workshop"

-- Lucas Cranach the Elder (1472–1553)  →  Q191748  German painter and printmaker (1472–1553)
update public.artists set wikidata_id = 'Q191748' where slug in ('lucas-cranach-the-elder');

-- Lucas van Leyden (1494–1533)  →  Q320980  artist, painter (1494-1533)
update public.artists set wikidata_id = 'Q320980' where slug in ('lucas-van-leyden');

-- Ludovico Carracci (1555–1619)  →  Q380553  Bolognese painter of the Baroque (1555-1619)
update public.artists set wikidata_id = 'Q380553' where slug in ('ludovico-carracci');

-- Maarten van Heemskerck (1498–1574)  →  Q538350  Dutch painter (1498–1574)
update public.artists set wikidata_id = 'Q538350' where slug in ('maarten-van-heemskerck');

-- Marcantonio Raimondi (1475–1534)  →  Q728375  16th-century Italian engraver and printmaker (1480–1534)
update public.artists set wikidata_id = 'Q728375' where slug in ('marcantonio-raimondi');

-- Martin Schongauer (1435–1491)  →  Q155575  German artist (c. 1450–1491)
update public.artists set wikidata_id = 'Q155575' where slug in ('martin-schongauer');

-- Michelangelo Buonarroti (1475–1564)  →  Q5592  Italian artist and architect (1475-1564)
update public.artists set wikidata_id = 'Q5592' where slug in ('michelangelo-buonarroti');

-- Michelangelo Merisi da Caravaggio (1571–1610)  →  Q42207  Italian painter (1571–1610)
update public.artists set wikidata_id = 'Q42207' where slug in ('caravaggio');

-- Nicolas Poussin (1594–1665)  →  Q41554  French painter (1594-1665)
update public.artists set wikidata_id = 'Q41554' where slug in ('nicolas-poussin');

-- Paolo Veronese (Paolo Caliari) (1528–1588)  →  Q9440  Italian painter of the Renaissance (1528–1588)
update public.artists set wikidata_id = 'Q9440' where slug in ('paolo-veronese-paolo-caliari');

-- Parmigianino (Girolamo Francesco Maria Mazzola) (1503–1540)  →  Q9348  Italian Mannerist painter and printmaker (1503–1540)
update public.artists set wikidata_id = 'Q9348' where slug in ('parmigianino-girolamo-francesco-maria-mazzola');

-- Paul Gustave Doré (1832–1883)  →  Q6682  French illustrator and painter (1832–1883)
update public.artists set wikidata_id = 'Q6682' where slug in ('paul-gustave-dore');

-- skip  Perugino (Pietro di Cristoforo Vannucci) (1469–1523)  slugs='perugino-pietro-di-cristoforo-vannucci'
--   no candidates for "Perugino (Pietro di Cristoforo Vannucci)"
--   Q5827 birth-year mismatch: db=1469 wd=1448
--   Q37233109 not human (Perugino)

-- Peter Paul Rubens (1577–1640)  →  Q5599  Flemish painter (1577–1640)
update public.artists set wikidata_id = 'Q5599' where slug in ('peter-paul-rubens');

-- Pieter Bruegel the Elder (1525–1569)  →  Q43270  Flemish painter (1526–1569)
update public.artists set wikidata_id = 'Q43270' where slug in ('pieter-bruegel-the-elder');

-- Pieter Lastman (1583–1633)  →  Q352864  Dutch painter (1583–1633)
update public.artists set wikidata_id = 'Q352864' where slug in ('pieter-lastman');

-- Pietro Testa (1612–1650)  →  Q2155480  Italian artist (1611–1650)
update public.artists set wikidata_id = 'Q2155480' where slug in ('pietro-testa');

-- Raffaello Sanzio da Urbino (1483–1520)  →  Q5597  Italian painter and architect (1483–1520)
update public.artists set wikidata_id = 'Q5597' where slug in ('raphael-sanzio');

-- Raphael (Raffaello Sanzio or Santi) (1483–1520)  →  Q5597  Italian painter and architect (1483–1520)
update public.artists set wikidata_id = 'Q5597' where slug in ('raphael-raffaello-sanzio-or-santi');

-- Rembrandt (Rembrandt van Rijn) (1606–1669)  →  Q5598  Dutch painter and printmaker (1606–1669)
update public.artists set wikidata_id = 'Q5598' where slug in ('rembrandt-rembrandt-van-rijn');

-- Rembrandt van Rijn (1606–1669)  →  Q5598  Dutch painter and printmaker (1606–1669)
update public.artists set wikidata_id = 'Q5598' where slug in ('rembrandt-van-rijn');

-- skip  Rogier van der Weyden (1399–1464)  slugs='rogier-van-der-weyden'
--   Q68631 birth-year mismatch: db=1399 wd=1390
--   Q47038381 not human (Rogier van der Weyden)
--   Q77826309 not human (Rogier van der Weyden)

-- Sandro Botticelli (1445–1510)  →  Q5669  Italian painter (1445–1510)
update public.artists set wikidata_id = 'Q5669' where slug in ('sandro-botticelli');

-- Sassoferrato (Giovanni Battista Salvi) (1609–1685)  →  Q1345289  Italian painter (1609–1685)
update public.artists set wikidata_id = 'Q1345289' where slug in ('sassoferrato-giovanni-battista-salvi');

-- Sebald Beham (1500–1550)  →  Q507825  German artist (1500-1550)
update public.artists set wikidata_id = 'Q507825' where slug in ('sebald-beham');

-- Sebastiano del Piombo (1485–1547)  →  Q285423  Italian painter (c.1485-1547)
update public.artists set wikidata_id = 'Q285423' where slug in ('sebastiano-del-piombo');

-- Sodoma (Giovanni Antonio Bazzi) (1477–1549)  →  Q8506  Italian Renaissance painter (1477-1549)
update public.artists set wikidata_id = 'Q8506' where slug in ('sodoma-giovanni-antonio-bazzi');

-- Théodore Géricault (1791–1824)  →  Q184212  French painter (1791–1824)
update public.artists set wikidata_id = 'Q184212' where slug in ('th-odore-g-ricault');

-- Theophanes the Greek (1340–1410)  →  Q319403  Byzantine-Russian artist (c.1340-c.1410)
update public.artists set wikidata_id = 'Q319403' where slug in ('theophanes-the-greek');

-- Velázquez (Diego Rodríguez de Silva y Velázquez) (1599–1660)  →  Q297  Spanish painter (1599-1660)
update public.artists set wikidata_id = 'Q297' where slug in ('vel-zquez-diego-rodr-guez-de-silva-y-vel-zquez');

-- Wenceslaus Hollar (1607–1677)  →  Q448555  Czech cartographer, painter of nature, portrait painter and engraver (1607-1677)
update public.artists set wikidata_id = 'Q448555' where slug in ('wenceslaus-hollar');

-- William Blake (1757–1827)  →  Q41513  English poet and artist (1757–1827)
update public.artists set wikidata_id = 'Q41513' where slug in ('william-blake');

-- William-Adolphe Bouguereau (1825–1905)  →  Q483992  French academic painter (1825-1905)
update public.artists set wikidata_id = 'Q483992' where slug in ('william-adolphe-bouguereau');


-- ─────────────────────────────────────────────────────────────────────
-- Manual overrides for the 14 skipped rows above. The script's strict
-- birth-year tolerance (±5y) and limited occupation whitelist rejected
-- some clearly-correct top candidates; for the slugs below the right
-- Q-ID is documented either in the rejection log immediately above OR
-- (for "circle of", "follower of", "and workshop" attributions) is the
-- principal artist's Q-ID.
-- ─────────────────────────────────────────────────────────────────────

-- Correggio (Antonio Allegri) — Italian painter, c.1489–1534. Wikidata
-- birth year 1489 vs DB 1514 (probably a rough catalogue entry on our side).
update public.artists set wikidata_id = 'Q8457' where slug = 'correggio-antonio-allegri';

-- Giovanni Bellini — Venetian painter, c.1430–1516. Wikidata birth 1430 vs DB 1424.
update public.artists set wikidata_id = 'Q17169' where slug = 'giovanni-bellini';

-- Hans Memling — Early Netherlandish painter, c.1430–1494. Wikidata birth 1435 vs DB 1465.
update public.artists set wikidata_id = 'Q106851' where slug = 'hans-memling';

-- Hugo van der Goes — Early Netherlandish painter, c.1440–1482. Wikidata birth 1440 vs DB 1467.
update public.artists set wikidata_id = 'Q215251' where slug = 'hugo-van-der-goes';

-- Israhel van Meckenem — German engraver, c.1435–1503. Skipped because
-- Wikidata's occupation IDs for engraver/goldsmith weren't in the whitelist.
update public.artists set wikidata_id = 'Q77554' where slug = 'israhel-van-meckenem';

-- Joachim Patinir — Flemish landscape and religious painter, c.1480–1524.
update public.artists set wikidata_id = 'Q442491' where slug = 'joachim-patinir';

-- Luca Signorelli — Umbrian painter, c.1450–1523. DB birth 1470 vs Wikidata 1450.
update public.artists set wikidata_id = 'Q7031' where slug = 'luca-signorelli-luca-d-egidio-di-luca-di-ventura';

-- Perugino (Pietro Vannucci) — Umbrian painter, c.1448–1523. DB birth 1469 vs Wikidata 1448.
update public.artists set wikidata_id = 'Q5827' where slug = 'perugino-pietro-di-cristoforo-vannucci';

-- Rogier van der Weyden — Early Netherlandish painter, c.1399–1464.
update public.artists set wikidata_id = 'Q68631' where slug in (
  'rogier-van-der-weyden',
  'copy-after-rogier-van-der-weyden',
  'follower-of-rogier-van-der-weyden-master-of-the-saint-ursula-legend-group-nether'
);

-- "Circle of Jan van Eyck" attributions point to Jan van Eyck himself (Q102272).
update public.artists set wikidata_id = 'Q102272' where slug = 'circle-of-jan-van-eyck';

-- "El Greco and Workshop" → El Greco (Q301).
update public.artists set wikidata_id = 'Q301' where slug = 'el-greco-domenikos-theotokopoulos-and-workshop';

-- "Lucas Cranach the Elder and Workshop" → Lucas Cranach the Elder (Q191748).
update public.artists set wikidata_id = 'Q191748' where slug = 'lucas-cranach-the-elder-and-workshop';
