-- Notable works (phase 1) — original-prose, single-paragraph essays on
-- the most-famous biblical works of ten anchor artists. Populates the
-- `notable_works` JSONB column added in 025.
--
-- Schema (from src/lib/supabase.ts ArtistNotableWork): each entry is
-- { artwork_slug, paragraph } with paragraph rendered as a single <p>
-- under the work's title and thumbnail in the "Notable works in detail"
-- section of /art/artist/[slug].
--
-- Conventions:
--   * Each artwork_slug is verified against the live DB; rows that do
--     not exist will simply not render (the page filters by linked work).
--   * Each paragraph is one tight prose paragraph, ~180–280 words.
--   * Original prose, no double quotes inside the paragraph string so
--     the JSON parses cleanly under postgres jsonb cast.
--   * Exact slug matching (no name ILIKE), so multi-slug artists get
--     the same notable_works array on every variant.

-- ─── Caravaggio ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"caravaggio-calling-of-saint-matthew","paragraph":"The Calling of Saint Matthew, painted between 1599 and 1600 for the Contarelli Chapel in San Luigi dei Francesi in Rome, is the canonical Caravaggio. A shaft of late-afternoon sunlight rakes across a darkened tavern from the right; Christ enters from the same side, his arm extended in a gesture borrowed almost note-for-note from Michelangelo's Creation of Adam on the Sistine ceiling. Matthew, the tax collector, sits at a wooden counting table with four companions in contemporary sixteenth-century Roman dress — feathered hats, slashed sleeves, a pile of coins — and points incredulously at his own chest. The painting hangs to this day in the chapel for which it was made, opposite Caravaggio's own Martyrdom of Saint Matthew on the facing wall, with the Inspiration of Saint Matthew above the altar between them. The three together formed Caravaggio's first major public commission and made his Roman reputation overnight in 1600."},
  {"artwork_slug":"caravaggio-conversion-of-saint-paul","paragraph":"Conversion on the Way to Damascus, painted in 1601 for the Cerasi Chapel in Santa Maria del Popolo in Rome, shows Saul fallen to the ground beside the enormous body of his horse, blinded by the light from heaven described in Acts 9. There is no traditional theatrical sky-rending — no parting of the clouds, no Christ in glory, no celestial host. The miracle is rendered as a single shaft of off-canvas light that illuminates the white belly of the horse, the inside of Saul's open palms, and the soles of his outstretched boots. The groom holding the horse barely registers what is happening. The composition was rejected by Caravaggio's patron Tiberio Cerasi as too eccentric and immediately repainted; this is the second version, and it became one of the foundational pictures of European Baroque tenebrism. Annibale Carracci's classicizing Assumption of the Virgin hangs on the chapel's facing wall, the canonical pairing of the two opposing tendencies of early-seventeenth-century Roman religious painting."},
  {"artwork_slug":"caravaggio-judith-beheading-holofernes","paragraph":"Judith Beheading Holofernes, painted around 1602 and now in the Galleria Nazionale d'Arte Antica in the Palazzo Barberini in Rome, illustrates the climactic moment of the deuterocanonical Book of Judith: the young Hebrew widow saws through the neck of the drunken Assyrian general in his own command tent. Caravaggio places the act at the literal center of the canvas. Judith leans back from the spurting blood with an expression of fastidious disgust; the elderly servant Abra leans in, holding open the linen sack into which the head will fall. The sword is already half through the neck; the eyes of Holofernes are still open. The painting was rediscovered in a Roman bank vault in the early twentieth century and remains the principal Caravaggesque treatment of one of the most-painted Old Testament subjects of the early modern period — anticipating, by about a decade, Artemisia Gentileschi's even more violent Naples and Uffizi versions of the same scene."},
  {"artwork_slug":"caravaggio-taking-of-christ","paragraph":"The Taking of Christ, painted around 1602 and rediscovered in 1990 hanging unidentified in the dining room of a Jesuit residence in Dublin, depicts the moment of arrest in Gethsemane. Judas leans in to deliver the kiss; an armored Roman guard reaches across him to grip Christ's neck; a young John flees screaming from the left edge of the frame, his red cloak whipping out of view; and at the far right, holding up a lantern to light the scene, is the artist's own self-portrait — Caravaggio inserting himself as the man whose lamp makes the betrayal visible. The painting was identified by the Italian art historians Sergio Benedetti and Francesca Cappelletti from cleaning records and inventory traces; it is now on long-term loan to the National Gallery of Ireland in Dublin and is the most consequential single Caravaggio rediscovery of the modern period."},
  {"artwork_slug":"caravaggio-incredulity-of-thomas","paragraph":"The Incredulity of Saint Thomas, painted around 1602 for the Marchese Vincenzo Giustiniani and now in the Bildergalerie at Sanssouci in Potsdam, illustrates the moment in John 20 when Christ invites the doubting apostle to thrust his finger into the wound in his side. Caravaggio paints the contact with extraordinary literal-mindedness: Thomas's index finger disappears into the actual gap in Christ's flesh, the skin pulled visibly aside by the apostle's other hand, while two more apostles lean in over Thomas's shoulder. The light comes from the left as in nearly all Caravaggio's paintings of this period; the figures are cropped tightly, with no architectural background and no setting beyond the four men and the dark space behind them. The painting is among the most reproduced single religious images of Caravaggio's career and was widely imitated in seventeenth-century Italian and Spanish painting."},
  {"artwork_slug":"caravaggio-david-head-of-goliath-1610","paragraph":"David with the Head of Goliath, painted in 1610 in Naples or possibly Rome and now in the Galleria Borghese in Rome, is one of the last paintings Caravaggio completed before his death later that year on the Tuscan coast at age thirty-eight. A young David, half-stripped, holds the severed head of the Philistine giant out toward the viewer — and the head is unmistakably Caravaggio's own self-portrait, eyes still half-open, mouth slack, a final act of pictorial confession by an artist who was at the time under sentence of beheading by the papal courts for the 1606 killing of Ranuccio Tomassoni in a Roman ball-court brawl. The painting is widely read as Caravaggio's plea to Cardinal Scipione Borghese — a key intermediary in negotiating the papal pardon Caravaggio was hoping to receive — and entered the Borghese collection shortly after his death."}
]$JSON$::jsonb
where slug in ('caravaggio', 'caravaggio-michelangelo-merisi');

-- ─── Michelangelo ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"michelangelo-last-judgment","paragraph":"The Last Judgment, painted in fresco between 1536 and 1541 on the entire altar wall of the Sistine Chapel, depicts the Second Coming of Christ and the final judgment of all souls. Christ stands at the center as a beardless, athletic youth — closer to a classical Apollo than to the medieval European bearded Christ — his right hand raised, the elect rising to his right, the damned falling to his left into a Charon-piloted boat that ferries them across to a devil-tormented underworld. Over four hundred figures fill the composition, almost all of them originally nude. The painting was condemned almost immediately by some Roman clergy as inappropriate for the Pope's private chapel; in 1564 Daniele da Volterra was commissioned to paint loincloths and drapery over the most exposed figures, earning him the nickname Il Braghettone (the breeches-maker), and the censorship campaign continued in waves for two centuries. The 1980s–1994 conservation campaign cleaned the fresco of centuries of candle-soot and varnish, restored its true blue ground, and removed many of the post-Council-of-Trent additions."},
  {"artwork_slug":"michelangelo-doni-tondo","paragraph":"The Doni Tondo, painted around 1507 in oil and tempera on a circular wooden panel approximately 120 centimeters in diameter, is Michelangelo's only surviving finished panel painting and the centerpiece of his small painted output. Commissioned by the Florentine merchant Agnolo Doni — possibly to celebrate his 1503 marriage to Maddalena Strozzi — it depicts the Holy Family in the foreground, with Mary twisting back to receive the Christ Child from Joseph, and a band of nude classical youths in the middle distance behind a low parapet. The young John the Baptist watches from between the two zones. The composition combines Michelangelo's lifelong commitment to the muscular human figure with an unusually saturated chromatic palette — pinks, oranges, electric blues — that the recent cleaning campaign has restored to its original brightness. The frame, also designed by Michelangelo and carved with lions, crescent moons, and grotesque heads, survives intact. The painting hangs today in the Uffizi in Florence, in the room dedicated to it alone."},
  {"artwork_slug":"michelangelo-sistine-01-separation-of-light-from-darkness","paragraph":"The Separation of Light from Darkness is the first of the nine central narrative panels of the Sistine Chapel ceiling, painted between 1508 and 1512 for Pope Julius II. Reading the ceiling chronologically — from the altar wall back toward the entrance — it is the opening scene of the Genesis program: God the Father, his arms thrown apart, separates the primordial light from the primordial darkness in a single foreshortened gesture. The figure floats in pure space without ground, throne, or attendant angels — a deliberate rejection of the medieval iconographic conventions for divine figures. Vasari reports that Michelangelo painted the ceiling himself with a small group of plasterers and color-grinders, against Pope Julius's repeated insistence on a larger workshop, and that this first scene was the last one Michelangelo completed because he proceeded across the ceiling in reverse narrative order, working backward from Noah's Drunkenness toward the Creation. By the time he reached this panel his fresco technique had matured to its supreme economy of brushwork and figural compression."},
  {"artwork_slug":"michelangelo-sistine-prophet-jeremiah","paragraph":"The Prophet Jeremiah, one of the seven Old Testament prophets and five sibyls along the side spandrels of the Sistine Chapel ceiling, was painted between 1508 and 1512. Jeremiah sits hunched, his left hand pressing against his beard, his eyes lowered into the middle distance — the unmistakable visual posture of grief. He is the only one of the twelve prophets and sibyls who looks downward; the others all turn either toward open scriptural rolls or upward to the source of revelation. The figure has long been read as a self-portrait — Michelangelo's projection of his own physical and spiritual state during the four-year frescoing of the chapel — and the resemblance to the artist's late drawn self-portraits is unmistakable. Two attendant putti stand behind him in the niche, one with hands folded, one looking out from behind the prophet's shoulder. The figure is among the most reproduced individual elements of the entire ceiling and a touchstone for every later European treatment of the seated melancholic prophet."},
  {"artwork_slug":"michelangelo-sistine-brazen-serpent","paragraph":"The Brazen Serpent occupies one of the four corner spandrels of the Sistine Chapel ceiling, painted in 1511 along with the other three corner pendentives (Judith and Holofernes, David and Goliath, the Punishment of Haman). The scene illustrates Numbers 21: in punishment for their grumbling, the Israelites are bitten by fiery serpents in the wilderness, and Moses is commanded to lift up a bronze serpent on a pole so that those who look upon it will live. Michelangelo packs the spandrel with two distinct halves — on the right, a tangle of writhing nude bodies wrapped in serpents in agony; on the left, the rescued who have looked at the bronze image and live, gesturing upward. The composition compresses an enormous figural mass into the awkward triangular shape of the spandrel and is widely held to be the most virtuoso individual element of the corner pendentives. The bronze serpent itself is read in the New Testament (John 3:14) as a typological prefiguration of the lifting up of Christ on the cross — the connection that gave the subject its standing in Christian iconography from late antiquity onward."},
  {"artwork_slug":"michelangelo-pauline-conversion-of-saul","paragraph":"The Conversion of Saul is one of the two enormous frescoes Michelangelo painted between 1542 and 1545 in the Pauline Chapel — Pope Paul III's private chapel in the Vatican Palace, completed shortly after the Last Judgment in the Sistine. The scene shows Saul knocked off his horse on the road to Damascus, blinded by the light from heaven, while the divine appears at the upper left as a foreshortened Christ pulling apart the clouds and dispatching a stream of figures down toward the earthbound apostle. The figures are weighty, somber, and almost monochromatic compared to the chromatic intensity of the Sistine ceiling thirty years earlier. The Pauline Chapel was, until 2009, almost never opened to the public; the 2002–2009 restoration cleaned both this fresco and its companion Crucifixion of Saint Peter and revealed the late Michelangelo's distinctive rough handling of fresco — looser, denser, more saturated — that anticipated the dramatic visual register the next generation of Roman Mannerists would develop."}
]$JSON$::jsonb
where slug = 'michelangelo-buonarroti';

-- ─── Rembrandt ─────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"rembrandt-christ-preaching-hundred-guilder","paragraph":"Christ Preaching, traditionally called The Hundred Guilder Print after the extraordinary price the etching reportedly fetched at one of the early sales — it would still be a record-setting sum even today, adjusted for inflation — is among the most ambitious and most carefully reworked etchings in Rembrandt's catalogue. Composed around 1648, it gathers in a single horizontal sheet several discrete moments from Matthew 19: Christ healing the sick, blessing the children brought by their mothers, debating the Pharisees, and meeting the rich young ruler. The composition is built around a single shaft of light pouring down from the upper left onto Christ's pale figure, with the petitioners and skeptics massed in tonal gradations of progressively deeper shadow on either side. Rembrandt reworked the plate over several years through multiple states; the Rijksmuseum and the Metropolitan Museum hold the principal early impressions. The print is widely considered the supreme single-sheet achievement of seventeenth-century Dutch etching."},
  {"artwork_slug":"rembrandt-storm-sea-galilee","paragraph":"Christ in the Storm on the Sea of Galilee, painted in 1633 and Rembrandt's only surviving seascape, depicts the Mark 4 episode in which the apostles wake the sleeping Christ in the boat as the tempest threatens to capsize them. The composition is built diagonally across the canvas — a torn sail at the upper left, the bow of the fishing boat plunging into a wave, twelve disciples in extreme poses of fear and effort, and the remarkably calm figure of Christ awakening at the stern. A thirteenth figure, looking directly at the viewer with one hand gripping a rope, is widely read as Rembrandt's own self-portrait inserted into the scene. The painting was stolen from the Isabella Stewart Gardner Museum in Boston in March 1990 in the largest art theft in modern American history and has not been recovered. Its empty frame still hangs in the museum's Dutch Room as a memorial to the loss."},
  {"artwork_slug":"rembrandt-three-crosses","paragraph":"The Three Crosses, etched and dry-pointed in 1653, is one of the most ambitious single-plate religious prints of Rembrandt's late career. The composition shows the Crucifixion at the moment of Christ's death, with the centurion at the foot of the cross looking up in sudden recognition, the soldiers and onlookers scattering in panic, and the two thieves still alive on their crosses to either side. A single shaft of light from the upper left isolates Christ against a roiling black sky. Rembrandt reworked the plate through five distinct states over the next decade; the third state — the most reproduced and most collected — has the supreme dramatic intensity. The fourth state of about 1660 reworked the entire composition almost beyond recognition, darkening the sky to almost solid black and resketching several of the lower figures, leaving the print as one of the most thorough demonstrations of Rembrandt's late technique of using the etching plate itself as a continuously revisable artistic instrument."},
  {"artwork_slug":"rembrandt-belshazzar-feast","paragraph":"Belshazzar's Feast, painted around 1635 and now in the National Gallery in London, depicts the moment in Daniel 5 when the disembodied hand writes the words Mene Mene Tekel Upharsin on the wall of the Babylonian king's banquet hall. Belshazzar lurches back from the table in startled horror, his arms thrown wide, knocking over a gold cup whose wine arcs across the canvas. The Hebrew letters of the inscription are written in the upper right corner in vertical columns rather than the conventional horizontal — a detail Rembrandt is believed to have learned from the seventeenth-century Dutch Sephardic rabbi and Hebraist Menasseh ben Israel, his Amsterdam neighbor and friend. The painting is one of Rembrandt's most theatrical compositions, with intense single-source candlelight, deep saturated reds and golds, and the kind of sudden frozen-moment psychological action that reads as the seventeenth-century pictorial equivalent of operatic recitative."},
  {"artwork_slug":"rembrandt-jacob-wrestling-with-angel","paragraph":"Jacob Wrestling with the Angel, painted around 1659 and now in the Gemäldegalerie in Berlin, illustrates the encounter at the ford of the Jabbok in Genesis 32 in which the patriarch wrestles all night with a divine figure who at dawn blesses him and renames him Israel. Rembrandt strips the scene almost to its essentials: two figures locked in an embrace that is half struggle and half tender, the angel's enormous wing curving up around them both, Jacob's head tilted onto the angel's shoulder. There is no landscape, no riverbank, no patriarchal entourage — only the two bodies against a darkened ground. The painting is widely read as one of the supreme expressions of the late Rembrandt's interest in the inward, almost mystical religious encounter, and as one of the most original reinterpretations of the Genesis subject in the entire history of European Christian painting."},
  {"artwork_slug":"rembrandt-sacrifice-of-isaac","paragraph":"The Sacrifice of Isaac, painted in 1635 and now in the Hermitage in Saint Petersburg, depicts the climactic moment of Genesis 22: an angel, swooping down from the upper left, grips Abraham's right wrist in midair and forces the patriarch to drop the knife with which he is about to kill his bound son on the altar. Isaac, blindfolded with his father's mantle, lies pinned face-up across the firewood. The composition is built on a single diagonal sweep from the angel's outstretched arm down through Abraham's startled face to Isaac's exposed chest. Rembrandt produced a second version of the same composition with the same overall pose almost a year later, signed by his pupil Govaert Flinck and inscribed Rembrandt verändert und übermalt 1636 (altered and overpainted by Rembrandt 1636); the two paintings together count among the most studied workshop teaching documents of the entire Dutch Golden Age."}
]$JSON$::jsonb
where slug in ('rembrandt-van-rijn', 'rembrandt-rembrandt-van-rijn');

-- ─── James Tissot ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"tissot-magi","paragraph":"The Adoration of the Magi is one of the 365 watercolor compositions of the Life of Christ that Tissot produced between 1886 and 1894 after his religious conversion. The series — published as La Vie de Notre-Seigneur Jésus-Christ in Paris in 1896–1897 and acquired in 1900 by the Brooklyn Museum, where it remains the principal collection of his Bible watercolors — traces the Gospels in chronological order from the Nativity through the Resurrection and Ascension. Tissot researched the topography, costume, and architecture of the Holy Land in person on three trips to Palestine and Egypt between 1886 and 1889; the resulting watercolors set every scene in plausibly observed first-century Jewish settings rather than in the European Renaissance idiom that had defined Christian painting for the previous four hundred years. The Magi composition shows the three travelers and their retinue arriving at a low Bethlehem dwelling, with the Holy Family seated inside, lit from within against a desert evening sky."},
  {"artwork_slug":"tissot-pilate-washes","paragraph":"Pilate Washes His Hands, from the same Life of Christ watercolor cycle of 1886–1894, illustrates Matthew 27 — the Roman governor publicly absolving himself of responsibility for the death of Jesus by performing the ritual hand-washing in front of the assembled crowd. Tissot stages the moment from a vantage point inside the Praetorium courtyard, looking out at the steps where Pilate stands in profile and a servant pours water from a metal ewer over his hands into a wide basin. The crowd gathered below is rendered with Tissot's characteristic ethnographic care — Roman soldiery, Jewish religious authorities, and ordinary onlookers in distinct period dress. The composition is among the most reproduced and most quoted in twentieth-century Christian devotional materials; its image of public, performative absolution recurs throughout sermon illustrations, Sunday-school teaching aids, and printed devotional books for over a century."},
  {"artwork_slug":"tissot-what-saviour-saw","paragraph":"What Our Saviour Saw from the Cross, completed around 1890 in the Life of Christ watercolor series, is one of Tissot's most original contributions to the Crucifixion iconography. The viewer occupies the position of Christ on the cross looking down at the scene below: the Virgin and the women, the centurion's horse, the soldiers casting lots, the foreshortened crowd around Golgotha, and at the far edge the city of Jerusalem fading into late-afternoon haze. The vantage point — adopted by no major European Crucifixion painter before Tissot — turns the spectator into a participant in the suffering and the seeing rather than an observer of it from below. The watercolor is the single best-known piece of the series and has been reproduced in countless devotional books, prayer cards, and illustrated children's Bibles since its publication in the 1890s."},
  {"artwork_slug":"tissot-the-pilgrims-of-emmaus-on-the-road","paragraph":"The Pilgrims of Emmaus on the Road, from the Brooklyn Museum Life of Christ series, illustrates Luke 24: the risen Christ joining the two disciples on the road to the village of Emmaus on the afternoon of the Resurrection, the disciples not yet recognizing him. Tissot paints the three figures walking in a single horizontal band across the foreground, the disciples in animated mid-conversation, the cloaked figure of Christ slightly behind them in profile. The landscape — a dusty Judean road winding through low rocky hills, with the village in the distance — was sketched on Tissot's own walks in the Holy Land during his 1886–1889 Palestine and Egypt travels. The composition was one of the most-quoted in late nineteenth and early twentieth-century English-language Bible illustration and shaped the visual vocabulary of countless subsequent Emmaus images."},
  {"artwork_slug":"tissot-mary-magdalene-questions-the-angels-in-the-tomb","paragraph":"Mary Magdalene Questions the Angels in the Tomb, from the same 1886–1894 Life of Christ cycle, illustrates the moment in John 20 when Mary, having returned to the tomb after the disciples had left, looks in and sees two angels in white seated where the body of Christ had been. Tissot frames the scene from a low angle through the rough opening in the rock, with the bowed Magdalene foregrounded in profile and the two angels seated in soft mutual symmetry on either side of the empty linen-strewn shelf. The light comes from above and behind, leaving the front of the chamber in deep shadow. The composition is among the most reproduced of Tissot's watercolors of the Resurrection sequence and was widely copied in late-nineteenth-century Catholic and Protestant devotional publishing on both sides of the Atlantic."},
  {"artwork_slug":"tissot-the-resurrection","paragraph":"The Resurrection, from the closing sequence of the Life of Christ watercolors, depicts the moment of the rising itself — Christ standing fully clothed in white at the mouth of the open tomb, the soldiers fallen unconscious or fleeing, the burial linens still folded behind him. Tissot characteristically refuses the Renaissance conventions of triumph: there is no banner, no flag, no upward-pointing gesture; the figure stands quietly in the predawn light. Two angels seated above the tomb and a small group of women still some distance away complete the composition. The watercolor closes the Resurrection cycle of the series and was one of the principal pieces in the touring exhibitions of the original 365 watercolors that Tissot organized in Paris and London in 1894–1895 to enormous popular acclaim before the entire collection was acquired by public subscription for the Brooklyn Museum in 1900."}
]$JSON$::jsonb
where slug = 'james-tissot';

-- ─── Albrecht Dürer ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"durer-four-horsemen","paragraph":"The Four Horsemen of the Apocalypse is the fourth of the fifteen woodcuts of Dürer's Apocalypse, published as Apocalypsis cum Figuris in Nuremberg in 1498 — a printed book of which Dürer himself was the publisher, designer, and woodblock cutter. The image illustrates Revelation 6: as the Lamb opens the first four seals, four horsemen are summoned forth — Conquest with a bow, War with a sword, Famine with scales, and Death on a pale horse with the open mouth of Hell beneath him. Dürer compresses the four into a single thundering horizontal motion across the upper half of the sheet, with the trampled bodies of an emperor, a bishop, a peasant, and a child crushed beneath the hooves. The print made Dürer famous across Europe at twenty-seven and became the canonical visual treatment of the Four Horsemen for the next four centuries. The original blocks survive in the Albertina in Vienna; impressions exist in every major print collection."},
  {"artwork_slug":"durer-woman-of-the-apocalypse","paragraph":"The Woman of the Apocalypse and the Seven-Headed Dragon, the tenth of the fifteen Apocalypse woodcuts of 1498, illustrates the central vision of Revelation 12: a woman clothed with the sun, the moon under her feet, and a crown of twelve stars upon her head, with the great red dragon waiting to devour her child. Dürer compresses the chapter into a single dense composition — the woman aloft and crowned in the upper half of the print, an angel handing her the eagle wings she will need to fly to safety, and below her the seven-headed dragon coiled and snarling in a roiling sky lit by sun and moon together. The print is among the most reproduced and most copied of the entire Apocalypse cycle and carried Dürer's iconographic invention into the standard visual vocabulary of European Reformation and Counter-Reformation illustrated Bibles for over a century."},
  {"artwork_slug":"durer-saint-michael-dragon","paragraph":"Saint Michael Fighting the Dragon, the eleventh of the Apocalypse woodcuts of 1498, depicts the war in heaven described in Revelation 12: the archangel Michael and his hosts battle the great red dragon, identified in the chapter with the ancient serpent and with Satan, until the dragon and his angels are cast down to earth. Dürer composes the scene in two distinct registers — the heavenly battle in the upper two thirds, with Michael in the act of driving his spear down through the dragon's open mouth and three other angels engaging the dragon's allies on every side — and a peaceful, almost pastoral landscape of Northern European fields and a small town in the lower third. The contrast between the apocalyptic violence above and the unaware, sunlit countryside below is one of the most quoted Dürer compositional inventions and was directly imitated in countless later Northern European depictions of the same subject."},
  {"artwork_slug":"durer-lp-last-supper","paragraph":"The Last Supper is one of the twelve woodcuts of the Large Passion, the cycle Dürer worked on intermittently from 1497 to 1510 and published in Nuremberg in 1511 with newly composed Latin verses by the humanist Benedictus Chelidonius. The composition shows Christ at the center of a long horizontal table seated under a coffered Renaissance arch, the twelve apostles arranged on either side, John leaning into Christ's chest and Judas isolated in profile in the right foreground. The setting is unmistakably Northern late-Gothic-into-Renaissance: tiled floor, mullioned window opening onto a starry sky, an interior architecture worked out in careful linear perspective. The Large Passion combined old and new at the moment of its publication — the earliest plates predating Dürer's first Italian trip and the latest reflecting the lessons of his second — and is one of the most studied serial woodcut projects of the Northern Renaissance."},
  {"artwork_slug":"durer-lp-crucifixion","paragraph":"The Crucifixion, the eighth of the twelve Large Passion woodcuts, was completed around 1498 in the first phase of Dürer's work on the cycle. The composition shows the moment immediately after Christ's death: the swooning Virgin in the arms of John on the left, the soldier piercing the side with the lance on the right, the two thieves still alive on their crosses to either side, and below the cross the Magdalene kneeling and clinging to its base. The scene is staged in front of an architectural backdrop of the city of Jerusalem, with mounted Roman soldiery and bystanders moving across the background. The combination of dense narrative incident, careful chiaroscuro modeling, and confident anatomical drawing demonstrates Dürer's full mastery of the engraved-line tradition descending from Martin Schongauer; the print became one of the standard sixteenth-century European visual treatments of the subject and was directly copied by engravers across Italy, France, and the Low Countries within a decade of its publication."}
]$JSON$::jsonb
where slug in ('albrecht-durer', 'albrecht-d-rer');

-- ─── Giotto di Bondone ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"giotto-scrovegni-36-lamentation","paragraph":"The Lamentation, painted in fresco around 1305 on the lower north wall of the Scrovegni Chapel in Padua, is among the most reproduced and most pivotal images in the history of Western Christian painting. Giotto stages the moment after the Deposition: the body of Christ has been laid on a low rock at ground level, the Virgin holds her dead son's head in her lap, John flings his arms back in grief, and Mary Magdalene kneels at the feet. A diagonal rocky outcrop runs across the upper register and frames a sky filled with weeping angels, ten of them, each in a distinct posture of grief — clutching their faces, tearing their hair, holding their hands to their cheeks. The composition rejects the conventions of Italo-Byzantine tradition: the figures have weight and turn in space, the emotion is legible and individual rather than hieratic, and the Virgin is allowed to express the maternal grief that the older tradition had largely suppressed. The fresco is the central document of the Giottesque revolution that opens the entire history of European painting."},
  {"artwork_slug":"giotto-scrovegni-31-kiss-of-judas","paragraph":"The Kiss of Judas, painted around 1305 in the second register of the Scrovegni Chapel walls in Padua, depicts the moment of the betrayal in Gethsemane. Judas embraces Christ, his cloak swinging out around them both to fill the center of the composition; their faces are inches apart in profile, Christ's calm and steady, Judas's set in a fixed and ugly stare. Around the central pair the soldiers crowd in with raised lances and torches, Peter on the left side cuts off the ear of the high priest's servant Malchus, and a hooded figure on the right blows a long shofar-like horn into the night. The yellow of Judas's cloak — read in late-medieval iconography as the color of treachery — became, through Giotto's invention, the standard color for the Judas figure in subsequent Italian painting. The composition is one of the most reproduced single panels of the entire Scrovegni cycle."},
  {"artwork_slug":"giotto-scrovegni-40-last-judgment","paragraph":"The Last Judgment fills the entire entrance wall of the Scrovegni Chapel — the wall the worshipper sees on leaving the chapel after Mass — in a vast composition painted around 1305. Christ enthroned in glory inside a great rainbow-colored mandorla occupies the center; the apostles flank him on either side; the resurrected dead rise from their graves below; the elect are led toward heaven on the left, and the damned tumble into a graphic, flaming hell on the right. At the foot of the cross in the lower-center foreground kneels Enrico Scrovegni — the wealthy banker who commissioned the chapel as a pious atonement for his father's documented usury — offering a model of the chapel itself to the Virgin and two attendant angels. The fresco is both a visual program of Christian eschatology and an unusually direct documentary record of the patron-painter relationship at the dawn of the Italian Trecento."},
  {"artwork_slug":"giotto-scrovegni-17-nativity","paragraph":"The Nativity, painted in the upper register of the Scrovegni Chapel walls around 1305, depicts the birth of Jesus in a thatched lean-to under a starry sky. Mary reclines on the straw with her newborn son in her arms; Joseph sits crouched at the foot of the manger, his head bowed and his hand to his cheek in a posture of weary contemplation that Giotto effectively invented for the Joseph figure and that subsequent Italian painting would imitate for two hundred years. The ox and the ass occupy the back of the stable; angels announce the birth to a small group of shepherds in the upper-right corner of the field. The composition combines the new Giottesque commitment to legible weighted figures and shallow architectural space with a tender naturalism in the Virgin's gesture toward the newborn that was unprecedented in earlier medieval Italian painting."},
  {"artwork_slug":"giotto-scrovegni-25-raising-of-lazarus","paragraph":"The Raising of Lazarus, painted in the second register of the south wall of the Scrovegni Chapel around 1305, illustrates the climactic miracle of John 11. Christ stands on the left side of the composition with his right arm extended in command; the bound, bandaged figure of Lazarus stands upright in the open tomb on the right side, just emerging from the dead; the sisters Martha and Mary kneel between them at Christ's feet. Behind Lazarus, two attendants hold their noses and avert their faces from the smell of decomposition that the Gospel text specifically names. The composition crystallizes Giotto's central pictorial achievement: the moving body in legible space, conveying scriptural narrative with both theological seriousness and observed human reaction. The Lazarus figure became the canonical visual treatment of the subject in Italian painting; almost every subsequent Quattrocento and Renaissance treatment of the scene refers back to this Paduan fresco."},
  {"artwork_slug":"giotto-scrovegni-24-marriage-at-cana","paragraph":"The Marriage at Cana, painted in the upper register of the south wall of the Scrovegni Chapel around 1305, illustrates the first public miracle of Christ as recorded in John 2: the conversion of water into wine at the wedding feast. Giotto stages the scene at a long horizontal table running the full width of the composition, with the bride and groom seated under a baldachin at the right, Christ and his disciples ranged along the left, and the master of the feast tasting from one of six enormous jars in the center foreground. The Virgin sits next to her son; an attendant pours fresh water into another of the jars at the moment of the miracle. The composition is among the most reproduced from the Scrovegni cycle and a foundational treatment of a New Testament subject that the next four centuries of European painting — Veronese above all — would return to repeatedly as an excuse for elaborate banqueting scenes."}
]$JSON$::jsonb
where slug = 'giotto-di-bondone';

-- ─── Gustave Doré ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"dore-crucifixion","paragraph":"The Crucifixion is one of the 230 wood-engraved illustrations Doré produced for La Sainte Bible (Tours, 1866), the great two-volume French Bible that became the most-reproduced illustrated Bible of the nineteenth century. Doré stages the scene from a low oblique angle, with the cross of Christ rising in dramatic foreshortening across the foreground and the city of Jerusalem fading into a darkening sky beyond. The Virgin and Magdalene kneel at the foot of the cross; the centurion looks up from horseback in the moment of recognition; the two thieves on their crosses recede into a stormy distance. Doré's signature combination of theatrical lighting, panoramic landscape, and dense narrative incident is here at its most concentrated. The plate was reprinted in countless editions of the Doré Bible across France, England, the United States, and the Spanish-speaking world for the next century and remains one of the most widely reproduced single religious images of the entire nineteenth century."},
  {"artwork_slug":"dore-tower-of-babel","paragraph":"The Tower of Babel, from the 1866 Doré Bible, illustrates Genesis 11: the great post-Flood building project on the plain of Shinar that the LORD halts by confusing the language of the builders. Doré frames the unfinished tower as a vast spiraling step-pyramid receding into low cloud cover at the upper right, with hundreds of small workers scattered across its terraces — hauling blocks, mixing mortar, raising scaffolds, gesturing in dispute. In the lower foreground, a princely figure with attendants surveys the project from a flagstone terrace; below them, herders and beasts of burden cross a quay loaded with cut stone. The composition combines the panoramic Romantic landscape sensibility of the early nineteenth century with the architectural fantasy of the eighteenth-century engraver Giovanni Battista Piranesi, and remains the canonical visualization of the Genesis subject in Western Christian art."},
  {"artwork_slug":"dore-cain-slays-abel","paragraph":"Cain Slays Abel, from the 1866 Doré Bible, illustrates the first murder in human history as told in Genesis 4. Doré places the act in a wild and stony landscape; Cain swings down a heavy club in mid-strike from above the fallen Abel, whose body is sprawled across the foreground rocks beside the smouldering remains of the offering whose acceptance has provoked the killing. A single shaft of light from the upper left isolates the figures against a darkening sky; in the deep distance, a small flock of grazing sheep — the original cause of the brothers' competing offerings — continues to feed in unaware contrast. The composition is one of the most reproduced of Doré's Genesis sequence and shaped the visual vocabulary of every subsequent illustrated children's Bible that depicts the subject."},
  {"artwork_slug":"dore-jacob-wrestling-with-the-angel","paragraph":"Jacob Wrestles with the Angel, from the 1866 Doré Bible, illustrates the encounter at the ford of the Jabbok in Genesis 32. Doré places the scene at the riverbank in the predawn light, with the figure of Jacob locked in a powerful upright embrace with a fully winged angel — the two figures isolated against a turbulent night sky — while in the deep distance the patriarch's caravan of family and herds can just be made out crossing the ford. The composition leans into the Romantic dramatic-figure tradition descending from Géricault and Delacroix, with strong contrapposto and intense single-source lighting. The plate is one of the most reproduced of Doré's Genesis illustrations and was the principal visual reference for Eugène Delacroix's earlier Saint-Sulpice mural treatment of the same subject in the eyes of the late nineteenth-century French Catholic public."},
  {"artwork_slug":"dore-death-of-absalom","paragraph":"The Death of Absalom, from the 1866 Doré Bible, illustrates the climactic episode of 2 Samuel 18: the death of King David's rebellious son Absalom, his long hair caught in the branches of a great oak as he tries to flee on muleback. Doré frames the moment of the killing — Absalom suspended helpless in the tree while Joab's three soldiers thrust their spears up into him from below — against a dense forest and a roiling stormy sky. The mule, freed of its rider, gallops away into the lower foreground. The composition combines the vertical drama of the suspended figure with the dense Romantic woodland setting that defined Doré's late landscape-illustration manner. The plate became, by repeated reproduction, the single most-recognized image of the Absalom episode in subsequent Christian art and remains the standard visual reference for the subject."},
  {"artwork_slug":"dore-judgment-of-solomon","paragraph":"The Judgment of Solomon, from the 1866 Doré Bible, illustrates the founding case of Hebrew judicial wisdom recorded in 1 Kings 3 — two women claim the same living infant, and Solomon proposes to settle the dispute by having the child cut in half and divided between them. Doré stages the scene in the king's pillared throne room, with Solomon enthroned at the upper left, the soldier with raised sword in the center foreground holding the infant by one foot, and the true mother crying out in horror from the right side of the composition while the false claimant looks on impassively from the left. The architectural setting — heavy Egypto-Mesopotamian columns, deep shadow, and a single overhead light source — was widely imitated in nineteenth and early twentieth-century theatrical and cinematic depictions of the same subject. The plate remains one of the most reproduced single illustrations from the Doré Bible."}
]$JSON$::jsonb
where slug in ('gustave-dore', 'gustave-dor', 'paul-gustave-dore');

-- ─── Botticelli ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435730","paragraph":"Madonna and Child with Two Angels, painted around 1464 in tempera on wood and now in the Metropolitan Museum of Art in New York, is one of the small early Madonnas from the years immediately after Botticelli left Fra Filippo Lippi's workshop and set up on his own in Florence. The Virgin sits in a window niche with the Christ Child standing on her lap, her right hand cradling his shoulder; two child angels — closer in age and expression to ordinary Florentine children than to celestial messengers — flank the niche, one looking out at the viewer, the other at the Christ Child. The chromatic palette of soft rose, sky blue, and pale gold; the elongated proportions of the Virgin's face; and the sweet melancholy that would become Botticelli's lifelong signature are all already present in this small early panel. The painting entered the Metropolitan's collection in the 1880s and remains one of the principal Botticelli devotional paintings in any American collection."},
  {"artwork_slug":"met-435731","paragraph":"The Coronation of the Virgin, painted around 1475 and now in the Metropolitan Museum of Art in New York, shows the moment from the apocryphal Marian narrative in which Christ crowns his mother Queen of Heaven in the celestial court. The Virgin kneels in the lower foreground, her hands folded; Christ floats above her in a circle of seraphim, lowering the crown onto her bowed head; an angel choir surrounds the central pair on every side. The composition follows the Florentine Quattrocento conventions for the subject worked out by Filippo Lippi and Verrocchio in the previous generation, but the soft chromatic palette, the elongated proportions of both figures, and the unmistakable melancholy of the Virgin's face are distinctively Botticelli. The painting was once part of the Cook Collection at Richmond and entered the Metropolitan in the early twentieth century; it remains one of the principal Botticelli religious paintings in any American collection."}
]$JSON$::jsonb
where slug in ('botticelli', 'botticelli-alessandro-di-mariano-filipepi', 'sandro-botticelli');

-- ─── William-Adolphe Bouguereau ────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"bouguereau-song-of-the-angels","paragraph":"Song of the Angels, painted in 1881 and now in the Forest Lawn Memorial-Park in Glendale, California, is among the most reproduced Bouguereau religious paintings of the entire nineteenth century. The Virgin sits asleep with the infant Christ on her lap in a glade outside a small woodland cottage; three young angels stand in close formation behind her, one holding a viola, one a viol da gamba, one a lute, performing the soft music that has lulled both mother and child into a tender post-flight sleep. The setting — a Mediterranean garden with olive and orange trees, a low stone wall, and a tiny stream — places the scene during the Holy Family's rest on the flight into Egypt. The painting was acquired by the American collector Henry Huntington in 1900 and entered the Forest Lawn collection in the 1950s where it has hung continuously since; reproductions of the composition adorn devotional materials, prayer cards, and Christmas imagery throughout the English-speaking Catholic and Protestant worlds."},
  {"artwork_slug":"bouguereau-virgin-with-angels","paragraph":"The Virgin with Angels, painted in 1881 and now at the Petit Palais in Paris, depicts the Virgin Mary seated on a low stone bench with the Christ Child sleeping in her lap, surrounded by an arc of seventeen kneeling angels singing in adoration. Bouguereau's signature combination of academic figure-drawing precision, smoothly modeled flesh tones, and a softly luminous chromatic palette of cream, rose, and pale gold reaches its supreme statement in this canvas. The composition is built on a strict bilateral symmetry that the angel arc reinforces; the Virgin's downcast eyes and the still, sleeping infant give the entire scene a meditative quietness that Bouguereau's contemporary critics, even those skeptical of his academic conservatism, repeatedly singled out for praise. The painting has been continuously reproduced as an image of Christmas devotional imagery from the year of its first exhibition to the present."},
  {"artwork_slug":"bouguereau-pieta","paragraph":"The Pietà, painted in 1876 and now in a private collection (sold at Christie's New York in 2010 for over four million dollars), depicts the Virgin holding the dead body of Christ across her lap immediately after the Deposition. Bouguereau strips the iconography of all its Renaissance and Baroque accumulations: there are no attendant figures, no Cross visible in the background, no urban Jerusalem — only the seated Virgin, the body of her son draped diagonally across her, and a circle of nine sorrowing angels that close around the central pair against a darkening sky. The painting was Bouguereau's response to the death of his own son Georges, who had died of tuberculosis at the age of sixteen in 1875; the loss is documented in the artist's correspondence as the central biographical event of his late career. The Pietà was the most personally invested religious painting Bouguereau produced and remains one of the most affecting nineteenth-century European treatments of the subject."},
  {"artwork_slug":"bouguereau-flagellation","paragraph":"The Flagellation of Our Lord Jesus Christ, painted in 1880 for the Cathedral of La Rochelle in western France where it still hangs, depicts the moment from the Passion narratives in which Christ, tied to a column in the courtyard of the Praetorium, is whipped by Roman soldiers under the orders of Pontius Pilate. Bouguereau composes the scene in a strict pyramidal structure: the half-naked figure of Christ at the center, his arms bound above his head, his body twisted in pain; two muscular Roman soldiers on either side raising their scourges in mid-stroke; a crowd of Jewish religious authorities, soldiers, and onlookers receding into the deep background under the columned portico. The painting is among Bouguereau's largest religious commissions — over three meters tall — and one of the few in his oeuvre that abandons his usual idealized smoothness for a deliberately Caravaggesque dramatic intensity. It remains in continuous liturgical use in the cathedral for which it was painted."},
  {"artwork_slug":"bouguereau-holy-family","paragraph":"The Holy Family, painted in 1863 and now in the Cleveland Museum of Art, is an early Bouguereau religious painting that already shows the chromatic and compositional habits of his mature manner. The Virgin sits in a stone interior with the Christ Child upright on her lap; the boy John the Baptist leans in from the right side, kissing the Christ Child's foot; Joseph stands behind the group at a workbench, watching. Bouguereau's lifelong fascination with the soft idealization of children, the calm reflective Virgin, and the Renaissance tradition descending from Raphael all coexist in this small early canvas. The painting was acquired by Cleveland in the early twentieth century and remains the principal Bouguereau religious painting in any major American museum collection west of the Atlantic seaboard."}
]$JSON$::jsonb
where slug = 'william-adolphe-bouguereau';

-- ─── Carl Heinrich Bloch ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"gab-the-sermon-on-the-mount-ca68774","paragraph":"The Sermon on the Mount is one of the twenty-three large religious paintings Carl Heinrich Bloch produced between 1865 and 1879 for the chapel at Frederiksborg Castle in Hillerød, Denmark — the cycle that secured his reputation across the Nordic countries and (via reproduction in the late nineteenth and twentieth centuries) across the wider Protestant world. The composition shows Christ seated on a low rock on a hillside, the assembled crowd of disciples and curious onlookers gathered around him in a loose semicircle that opens toward the viewer; the figures in the foreground listen with their faces turned in profile, the children gathered close, the Mediterranean landscape stretching behind under a soft midday sky. Bloch was an academically trained Danish painter who absorbed both the Italian Renaissance composition tradition and the contemporary Düsseldorf school's interest in legible historical narrative; his Sermon on the Mount is widely held to be the most reproduced visualization of the subject in Protestant devotional materials and has been incorporated into the visual catechetical materials of the Church of Jesus Christ of Latter-day Saints, the Church of Denmark, and many evangelical Protestant publishing houses for over a century."}
]$JSON$::jsonb
where slug in ('carl-heinrich-bloch', 'carl-bloch');
