-- Notable works (phase 2) — original-prose, single-paragraph essays for
-- the next tier of bio'd artists. Same conventions as 036:
--
--   * Each artwork_slug is verified against the live DB.
--   * Each paragraph is one tight prose paragraph, ~180–280 words.
--   * No double quotes inside the JSON strings, so the postgres jsonb
--     cast accepts the block without further escaping.
--   * Exact slug matching; multi-slug artists get the same array on
--     every variant.

-- ─── Fra Angelico ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"fra-angelico-annunciation-san-marco-corridor","paragraph":"The Annunciation, painted in fresco around 1442–1443 in the upper corridor of the Convent of San Marco in Florence at the head of the dormitory stairs, is among the most reproduced and most beloved Annunciations in the entire history of Christian art. Fra Angelico stages the moment with a near-perfect bilateral symmetry: the angel Gabriel kneels in profile on the left under a slender Renaissance loggia, the Virgin sits in profile on the right in a tiny enclosed cell, the wall behind them painted in soft chromatic gradations of pale rose and grey. There is no swirling drapery, no gold-ground celestial host, no architectural elaboration beyond the loggia and the cell. The fresco was painted for the Dominican friars who lived in the convent — Fra Angelico was a friar at San Marco himself — and the inscription painted in tempera below the scene exhorts the friars to greet the Virgin every time they passed it on the stairs. The fresco was conserved most recently in 1983 and remains in its original location."},
  {"artwork_slug":"fra-angelico-annunciation-cortona","paragraph":"The Annunciation of Cortona, painted around 1434 for the Dominican church of San Domenico in Cortona — the small Tuscan hill town where Fra Angelico spent several years in his early career — is the principal Annunciation altarpiece of his pre-San-Marco period and the closest he ever came to the older Sienese tradition. The composition shows Gabriel kneeling on the left under a Renaissance loggia, Mary seated on the right in profile, and a small cluster of additional scenes painted into the predella below: the Marriage of the Virgin, the Visitation, the Adoration of the Magi, the Presentation in the Temple, and the Death of the Virgin. The chromatic palette is more saturated than the later San Marco fresco — deep ultramarine, gold, and crimson — and the angel's wings are rendered in jewel-bright peacock colors. The painting was moved from San Domenico to the Diocesan Museum of Cortona in the late nineteenth century and is now the supreme treasure of the museum's small but important collection of Tuscan Quattrocento painting."},
  {"artwork_slug":"fra-angelico-last-judgement","paragraph":"The Last Judgement, painted in tempera on a horizontal wood panel around 1432 and now in the Museo di San Marco in Florence, is among the great surviving Italian Quattrocento treatments of the eschatological subject. The composition is divided into three roughly equal horizontal zones: at the top, Christ enthroned in glory inside a large mandorla, attended by the apostles seated in two long curving rows; in the middle band, the resurrected dead emerging from open graves arranged in two long rows that converge on the central axis; and below, the elect on Christ's right being led toward heaven by angels in a serene procession of dance-like movement, while the damned on his left tumble into a graphic, multi-tiered hell of devils and torments. The painting was commissioned for the Camaldolese church of Santa Maria degli Angeli in Florence and remained there until the suppression of the convents in the early nineteenth century, when it entered the new museum at San Marco where Fra Angelico had himself been a friar."},
  {"artwork_slug":"fra-angelico-coronation-of-the-virgin-louvre","paragraph":"The Coronation of the Virgin, painted around 1434 and now in the Louvre, is one of two major large-format treatments of the subject Fra Angelico produced — the other, smaller and slightly later, hangs in the Uffizi. The composition shows Christ crowning his mother Queen of Heaven on a flight of pale marble steps in an open architectural setting; the celestial court — angels musicians, dancing seraphim, ranked male and female saints — fans out on either side of the central pair in a gradient of jewel-bright rose, ultramarine, and gold. The figure of the Virgin kneels in profile with her hands folded, the figure of Christ stands behind her in a posture combining tenderness and ceremony. The painting was commissioned for the Dominican church of San Domenico in Fiesole, where Fra Angelico had taken his vows; it was removed during the Napoleonic occupation of Italy and entered the Louvre's collection in the early nineteenth century where it remains."},
  {"artwork_slug":"fra-angelico-deposition-santa-trinita","paragraph":"The Deposition from the Cross, painted in tempera between roughly 1432 and 1434 for the Strozzi Chapel in the Florentine church of Santa Trinita and now in the Museo di San Marco, is among the supreme Italian Quattrocento treatments of the subject. The composition follows a strict horizontal symmetry: the body of Christ has been lowered from the cross and is being supported in the center by the women, while ladders propped against the cross extend up to the upper register where two attendants are still detaching the nails. The chromatic palette is unusually pale — soft pinks, white, the palest rose — that gives the entire scene the spectral quality of a vision rather than a violent action. Fra Angelico took over the commission after the older painter Lorenzo Monaco died in 1424 leaving the work unfinished; he completed the panel in his early-mature manner, and the painting remains the finest example of his ability to compose a many-figured narrative scene with the calm pictorial restraint that defined his Florentine style."}
]$JSON$::jsonb
where slug in ('fra-angelico', 'fra-angelico-guido-di-pietro');

-- ─── Raphael Sanzio ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437372","paragraph":"The Madonna and Child Enthroned with Saints, painted around 1499 in tempera and oil on a poplar panel and now in the Metropolitan Museum of Art in New York, is one of the earliest documented works of the young Raphael — painted when he was about sixteen, almost certainly as part of an unidentified Umbrian altarpiece commission produced in the workshop of his teacher Pietro Perugino. The composition shows the Virgin enthroned with the Christ Child on her knee in the center of a Renaissance loggia, with two saints standing on either side and a small kneeling donor figure at the bottom. The chromatic palette and figural proportions are distinctly Peruginesque — the soft chalky color, the elongated tilted heads — and the panel is the principal surviving record of Raphael's apprenticeship before he developed his own distinctive High Renaissance manner. The painting entered the Metropolitan in 1916 from the bequest of Benjamin Altman."},
  {"artwork_slug":"met-437371","paragraph":"The Agony in the Garden, painted around 1503 in tempera and oil on a small wooden panel and now in the Metropolitan Museum of Art in New York, is one of a small group of predella panels Raphael produced as part of an early Umbrian altarpiece in the orbit of his teacher Pietro Perugino. The composition shows Christ kneeling in prayer before the angel bearing the cup of the Passion in a small hilltop garden, with the three sleeping disciples — Peter, James, and John — gathered in the lower left corner of the panel and Judas leading the soldiers toward the garden through the gate at the lower right. The pictorial surface is small — the panel is only about twenty-three centimeters tall — but the composition demonstrates the young Raphael's ability to organize multiple narrative moments inside a single tightly framed image. The panel entered the Metropolitan in 1932 from the J. Pierpont Morgan collection."},
  {"artwork_slug":"met-340577","paragraph":"The Madonna and Child with the Infant Saint John the Baptist, painted in pen and brown ink with brown wash on paper around 1501 and now in the Metropolitan Museum of Art in New York, is one of a number of early Raphael drawings in which the young painter — still in his late teens and working in the orbit of Pietro Perugino — was working out variations on the Madonna-and-Child compositional types that he would refine throughout his career. The drawing shows the Virgin seated holding the Christ Child on her lap, with the boy John the Baptist standing in profile beside them; the figures are sketched rapidly with confident outlines and minimal interior modeling. Drawings of this kind, scattered today across the Uffizi, the Louvre, the British Museum, and the Metropolitan, are the principal record of the young Raphael's compositional experiments in the years immediately before he moved to Florence around 1504."},
  {"artwork_slug":"met-340579","paragraph":"Studies of the Christ Child, drawn in red chalk on a sheet of paper around 1513 and now in the Metropolitan Museum of Art in New York, is a sheet of preparatory studies from the central Roman period of Raphael's career, the years of the Vatican Stanza decorations and the major commissioned altarpieces. The sheet shows multiple poses of the infant Christ — seated, half-reclining, gesturing with one arm raised — drawn rapidly with the soft red chalk that the High Renaissance Roman workshops had popularized for figure studies. Drawings of this kind were used as compositional source material for finished altarpiece commissions; specific motifs from sheets very like this one can be matched to figures in the Madonna della Sedia, the Madonna of the Chair, and several of the smaller late Roman Madonnas. The sheet entered the Metropolitan in the early twentieth century."}
]$JSON$::jsonb
where slug in ('raphael-raffaello-sanzio-or-santi', 'raphael-sanzio');

-- ─── Peter Paul Rubens ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"rubens-raising-of-the-cross","paragraph":"The Raising of the Cross, painted between 1610 and 1611 in oil on panel as a triptych for the high altar of the church of Saint Walburga in Antwerp and now (since the church's demolition in 1817) hanging in Antwerp Cathedral, is the great public statement of Rubens's first Antwerp years after his return from eight years in Italy. The central panel shows nine straining muscular men in the act of hoisting the cross and the body of Christ upright; the diagonal of the cross runs across the entire panel from lower left to upper right, the figures arranged on either side in a complex interlocking knot of bodies, ropes, and tools. The two side wings show the centurion and the soldiers on the left, and the women and the two thieves on the right. The chromatic palette is deeply saturated — the dramatic Caravaggesque chiaroscuro Rubens had absorbed in Rome and Naples between 1600 and 1608 here applied to a heroic Northern altarpiece scale unprecedented in the Low Countries. It was the painting that secured his Antwerp reputation overnight."},
  {"artwork_slug":"rubens-descent-from-the-cross","paragraph":"The Descent from the Cross, painted between 1612 and 1614 in oil on panel as a triptych for the Confraternity of the Harquebusiers in the Antwerp Cathedral where it still hangs, is the supreme statement of Rubens's mature Antwerp manner and one of the most reproduced single paintings of the entire seventeenth century. The central panel shows the body of Christ being lowered from the cross by nine attendants; the Virgin and Mary Magdalene wait below to receive him, John the Evangelist supports the body from below, and Joseph of Arimathea and Nicodemus lower it from above with a winding sheet held in their teeth. The composition is built on a long diagonal — the white winding sheet and the body of Christ — that runs across the entire panel from the upper right to the lower left. The two side wings show the Visitation on the left and the Presentation in the Temple on the right. The painting was completed in two years for a fee that made Rubens, at age thirty-seven, the wealthiest painter in the Spanish Netherlands."},
  {"artwork_slug":"rubens-massacre-of-innocents","paragraph":"The Massacre of the Innocents, painted around 1611–1612 in oil on panel and now in the Art Gallery of Ontario in Toronto, depicts the slaughter of the male children of Bethlehem ordered by King Herod after the visit of the Magi as recorded in Matthew 2. Rubens fills the canvas with a roiling chaotic mass of muscular soldiers, screaming mothers clutching their dead infants, and the scattered small bodies of the killed children, set against a dark architectural backdrop. The painting was bought at Sotheby's London in July 2002 for fifty million British pounds — at the time the highest price ever paid at auction for an Old Master painting — by the Canadian newspaper magnate Kenneth Thomson, who immediately donated it to the Art Gallery of Ontario where it remains. The provenance research that led to the rediscovery of the canvas, and the price the painting eventually fetched, made it one of the most-discussed Rubens canvases of the early twenty-first century."},
  {"artwork_slug":"rubens-daniel-in-lions-den","paragraph":"Daniel in the Lions' Den, painted around 1614–1616 in oil on canvas and now in the National Gallery of Art in Washington, illustrates the climactic scene of Daniel 6: the prophet, thrown into the den of lions for refusing to worship King Darius's idols, sits unhurt in prayer through the night while the lions surround him. Rubens places Daniel as a solitary white-robed figure on the right side of the composition, his hands folded, his head tilted up toward the upper-right opening of the den; the lions — nine of them, painted with extraordinary specificity from Rubens's own studies of the Spanish Habsburg menagerie at Brussels — fill the rest of the canvas in poses of yawning, pacing, growling, and (in the foreground left) dozing. The painting is the most-celebrated single Rubens treatment of an Old Testament narrative and one of the most-reproduced animal-painting demonstrations of his entire career."},
  {"artwork_slug":"rubens-resurrection-of-christ","paragraph":"The Resurrection of Christ, painted around 1612 in oil on panel as the central panel of a triptych and now in Antwerp Cathedral, is the principal early Antwerp treatment of the Resurrection by Rubens and a canonical statement of his mature Catholic Counter-Reformation manner. Christ rises from the open tomb in the upper register, his white winding sheet draped from his shoulders, his right hand raised in benediction, while the soldiers below tumble away in shock and terror. The painting was commissioned by the Plantin-Moretus family — the great Antwerp printing dynasty whose Officina Plantiniana was the principal Catholic publishing house in the Spanish Netherlands — as a memorial altarpiece for Jan Moretus, who died in 1610. The triptych remained in continuous use as the Plantin-Moretus family altar in the Cathedral until the early nineteenth century. The chromatic palette of crimson, cream, and gold is among the most saturated of Rubens's early Antwerp paintings."}
]$JSON$::jsonb
where slug = 'peter-paul-rubens';

-- ─── Pieter Bruegel the Elder ──────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-383053","paragraph":"The Last Judgment, designed by Pieter Bruegel the Elder around 1558 and engraved by Pieter van der Heyden for publication by Hieronymus Cock at the Antwerp printing house Aux Quatre Vents, is among the most ambitious of Bruegel's printed compositions. The horizontal sheet shows Christ enthroned in judgment in a small upper-center mandorla, with the apostles ranged around him; the elect rise on the left, the damned tumble into a Bosch-influenced multi-tiered hell on the right, and the resurrected dead emerge from open graves across the foreground. Bruegel's drawn original for the print survives in the Albertina in Vienna and was the basis for the engraving Cock published throughout Catholic Europe. The print was the principal channel through which Bruegel's compositional inventions reached the wider European market in his lifetime, since his paintings remained almost entirely in private Habsburg and Antwerp collections."},
  {"artwork_slug":"met-383065","paragraph":"The Parable of the Wise and Foolish Virgins, designed by Pieter Bruegel the Elder around 1555 and engraved by Pieter van der Heyden for publication by Hieronymus Cock at Aux Quatre Vents in Antwerp, illustrates the Matthew 25 parable: ten virgins waiting for the bridegroom, of whom five wisely brought oil for their lamps and five foolishly did not. Bruegel divides the composition vertically: on the right, the wise virgins enter through the open door into the wedding feast above; on the left, the foolish virgins arrive too late and find the door closed against them. The Bridegroom appears in the upper register inside an architectural setting; small angels carry banners with Latin text quoting the parable. The print circulated widely through Cock's distribution network and shaped the visual iconography of the parable across Catholic and Protestant Europe through the seventeenth century."},
  {"artwork_slug":"met-383054","paragraph":"Christ and the Disciples on the Way to Emmaus, designed by Pieter Bruegel the Elder around 1571 and engraved for publication by the Antwerp printing house Aux Quatre Vents, illustrates the Luke 24 episode in which the risen Christ joins two disciples on the road to the village of Emmaus on the afternoon of the Resurrection. Bruegel stages the three figures walking in the foreground along a winding road across an extensive Northern European landscape — fields, distant villages, a low hilly horizon, a cloudy sky. The disciples, not yet recognizing their companion, gesture in animated mid-conversation; Christ walks slightly behind them, his face calm. The composition is among the most reproduced of Bruegel's printed religious compositions and brought his characteristic combination of Gospel narrative and panoramic Northern landscape to the wider European print market in the years immediately after his death in 1569."},
  {"artwork_slug":"met-383050","paragraph":"The Descent of Christ Into Limbo, designed by Pieter Bruegel the Elder around 1551 (one of his earliest engraved compositions) and engraved by Pieter van der Heyden for the Antwerp publisher Hieronymus Cock, illustrates the apocryphal episode known as the Harrowing of Hell — the tradition that Christ between his death on Friday and his Resurrection on Sunday descended into the underworld to free the souls of the just who had died before his Incarnation. Bruegel stages the scene in a Bosch-influenced landscape of hellish architecture, monsters, and tormented bodies; Christ stands upright in a luminous oval at the lower center, his banner raised, while Adam, Eve, the patriarchs and prophets emerge from a great open mouth on the left side of the composition. The visual debt to Hieronymus Bosch — whom Bruegel openly admired and whose work he absorbed during his Antwerp years — is direct, but the compositional discipline and the careful placement of the figures are entirely Bruegel's own."}
]$JSON$::jsonb
where slug = 'pieter-bruegel-the-elder';

-- ─── Hieronymus Bosch ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435724","paragraph":"The Adoration of the Magi, painted in oil on oak panel by Hieronymus Bosch around 1470–1480 and now in the Metropolitan Museum of Art in New York, is among the small surviving group of Bosch panels that depict the Adoration as a single unified composition (rather than as part of a folding triptych). The Holy Family sits at the center of a small wooden lean-to; the three Magi stand in formal procession with their gifts; the ox and the ass occupy the back of the stable; and a small landscape with shepherds and a distant Bethlehem fades into a cool blue distance. The panel demonstrates the early Bosch combination of conventional Northern Renaissance Adoration iconography with the artist's characteristic taste for tiny intricate detail — the embroidery on the kings' cloaks, the small grotesque carvings on the corners of the stable — that would, in his later great triptychs, become the central organizing principle of his entire pictorial vocabulary."},
  {"artwork_slug":"met-435725","paragraph":"Christ's Descent into Hell, painted in oil on panel in the workshop of Hieronymus Bosch (or by a close follower) around the middle of the sixteenth century and now in the Metropolitan Museum of Art in New York, illustrates the apocryphal Harrowing of Hell — the tradition that Christ between his death on Friday and his Resurrection on Sunday descended into the underworld to free the souls of the just who had died before his Incarnation. The composition shows Christ stepping out of an open hellmouth at the lower right, his white winding sheet still draped across him, while Adam, Eve, and the patriarchs emerge from the mouth behind him; the rest of the panel is filled with the unmistakable Bosch hellscape — fantastic flaming architecture, monstrous hybrid creatures, demons with bird heads and metal weapons, and small tormented bodies scattered across every register. The panel is one of the principal Bosch-school works in any American collection."},
  {"artwork_slug":"met-412195","paragraph":"Christ on the Way to Calvary, painted in oil on panel by a follower or close imitator of Hieronymus Bosch around the middle of the sixteenth century and now in the Metropolitan Museum of Art in New York, depicts the Passion subject Bosch returned to repeatedly in his late career: the figure of Christ pressed into a tight crowd of grotesque tormentors as he carries his cross toward Golgotha. The faces around Christ are caricatures of human cruelty — long noses, twisted mouths, bared teeth, prominent warts — drawn from the late-medieval Northern tradition of physiognomic exaggeration that Bosch's signature workshop made into a particularly intense visual vocabulary. Christ at the center of the composition is the only calm and ungrimacing face in the panel; his serenity contrasts with the grotesquerie around him. The panel is among the principal Bosch-school treatments of the subject in any American collection."}
]$JSON$::jsonb
where slug in ('hieronymus-bosch', 'antonio-bosch');

-- ─── Lucas Cranach the Elder ───────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-434184","paragraph":"The Annunciation, designed by Lucas Cranach the Elder and produced in his Wittenberg workshop in the early sixteenth century as part of his prolific output of single-leaf religious woodcuts, illustrates the moment from Luke 1 in which the angel Gabriel appears to Mary in her chamber to announce the conception of Christ. Cranach stages the scene in a small Northern European interior with leaded windows opening onto a distant landscape; the Virgin kneels at her prayer-desk on the right, the angel kneels on the left with the lily of purity in one hand and a banner of greeting in the other, and the Holy Spirit descends as a dove on a beam of light from the upper left corner. The woodcut is one of dozens of small devotional prints the Cranach workshop produced in editions for the Wittenberg market; the workshop's prints, alongside its larger panel paintings, supplied the visual catechetical materials of the early Lutheran Reformation."},
  {"artwork_slug":"met-434689","paragraph":"The Lamentation, from the Passion series of woodcuts produced by Lucas Cranach the Elder and his Wittenberg workshop in the early sixteenth century, depicts the moment after the Deposition: the body of Christ has been lowered from the cross and laid across the lap of his mother, with John the Evangelist supporting the head, the Magdalene kneeling at the feet, and Joseph of Arimathea and Nicodemus standing behind. The composition follows the Northern late-Gothic conventions for the subject — a dense pyramidal grouping of figures, careful chiaroscuro modeling in the woodcut line, the city of Jerusalem fading into a soft hilly horizon behind. The Passion series circulated through the German-speaking Reformation lands as one of the standard small-format devotional print cycles of its generation."},
  {"artwork_slug":"met-434705","paragraph":"The Resurrection, from the same Passion woodcut series produced by Lucas Cranach the Elder and his Wittenberg workshop in the early sixteenth century, depicts Christ rising from the open tomb in the predawn light. The risen Christ stands fully clothed in white at the upper center of the composition, his right hand raised in benediction, his left holding the banner of the Resurrection; the Roman soldiers in their armor have fallen at the foot of the tomb in postures of unconscious sleep or panicked awakening. The composition follows Northern Renaissance conventions for the subject and shows Cranach's debt to Albrecht Dürer's earlier Apocalypse and Passion woodcuts of 1497–1511; the prints circulated through Wittenberg and the wider German-speaking Reformation publishing networks for several decades after their first appearance."},
  {"artwork_slug":"met-336241","paragraph":"Christ on the Mount of Olives, designed by Lucas Cranach the Elder and produced in his Wittenberg workshop in the early sixteenth century, depicts the Agony in the Garden as recorded in the Synoptic Gospels: Christ kneels in prayer before the angel bearing the cup of the Passion, while the three sleeping disciples — Peter, James, and John — are gathered in the foreground and Judas with the soldiers approach through the gate at the rear. The composition shows the characteristic Cranach combination of careful Northern Renaissance figural drawing with a faintly archaic late-medieval landscape sensibility — the rocky garden, the distant city of Jerusalem, the dark sky above. The print was one of the standard treatments of the Agony subject produced by the Wittenberg workshop and circulated as part of the Cranach Passion sequences through the early Reformation publishing market."},
  {"artwork_slug":"met-625300","paragraph":"Christ Crowned with Thorns, from the Passion series of woodcuts produced by Lucas Cranach the Elder and his Wittenberg workshop in the early sixteenth century, depicts the moment after the scourging when the Roman soldiers, in cruel mockery of Christ's claim to kingship, press a crown of thorns down onto his head and place a reed in his hand as a mock scepter. Cranach stages the scene in the cramped courtyard of the Praetorium; Christ sits at the center on a low stool, his hands tied, his eyes lowered; two soldiers on either side push the crown down with sticks, while a third kneels in mock obeisance at his feet. The composition is among the most reproduced single sheets from Cranach's Passion series and was directly adapted, as a small inset image, into many of the early Lutheran prayer books and devotional pamphlets the Wittenberg printers turned out in editions of thousands during the 1520s and 1530s."},
  {"artwork_slug":"met-623820","paragraph":"The Beheading of Saint John the Baptist, designed by Lucas Cranach the Elder and produced in his Wittenberg workshop in the early sixteenth century, illustrates the climactic moment from Mark 6 in which the executioner sent by King Herod beheads John the Baptist in his prison cell, and the head is placed on a platter for delivery to Salome at the dance. Cranach stages the scene in a small dungeon: the executioner stands above the kneeling Baptist with raised sword in mid-stroke, while Salome waits at the door with an attendant holding the empty silver platter. The print was reproduced and copied in editions throughout the German-speaking Reformation lands and provided the visual model for many of the smaller printed treatments of the subject in subsequent Northern devotional publishing."}
]$JSON$::jsonb
where slug in ('lucas-cranach-the-elder', 'lucas-cranach-the-elder-and-workshop');

-- ─── El Greco ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"el-greco-disrobing-1pet2","paragraph":"The Disrobing of Christ, called El Espolio, painted by El Greco between 1577 and 1579 for the high altar of the sacristy of Toledo Cathedral and still hanging in the cathedral today, is among the founding works of his Toledo period and one of the great Spanish religious paintings of the entire sixteenth century. The composition shows Christ at the center of a dense crowd, his hands bound at his waist, an executioner reaching from behind to pull off his red robe in preparation for the Crucifixion; the three Marys stand in the lower-left foreground watching the carpenter prepare the holes in the cross. El Greco's characteristic vertical elongation of the figures, his deep saturated chromatic palette of crimson, ultramarine, and pale silver-grey, and his nervous staccato brushwork all reach mature statement in this canvas. A protracted legal dispute followed the delivery of the painting — the cathedral chapter wanted to lower the price on the grounds that the heads of three Marys appeared above Christ's head, which the canons considered theologically improper — and El Greco won."},
  {"artwork_slug":"el-greco-pentecost","paragraph":"Pentecost, painted by El Greco around 1600 for the church of the Augustinian college in Madrid (the Colegio de Doña María de Aragón) and now in the Prado in Madrid, depicts the descent of the Holy Spirit on the apostles fifty days after the Resurrection as recorded in Acts 2. El Greco stages the scene in a small enclosed upper chamber with the Virgin at the center surrounded by the twelve apostles in the standing ring; the Holy Spirit descends as a dove on a single shaft of light from above; tongues of flame appear on each apostle's head. The composition is built on a strict vertical axis — the dove, the light, the Virgin, the central foreground figure — and the chromatic palette of deep crimson, gold, and electric ultramarine is characteristic of El Greco's mature Toledo manner. The painting is one of the principal El Greco religious works in any Spanish collection and a defining example of his late-Mannerist religious style."},
  {"artwork_slug":"el-greco-st-jude-thaddeus","paragraph":"Saint Jude Thaddeus, painted by El Greco around 1612 in his Toledo workshop and now in the Museo del Greco in Toledo, is one of the surviving panels from the Apostolado — the late series of half-length apostle portraits El Greco painted between roughly 1605 and his death in 1614. The series shows each of the twelve apostles in a similar three-quarter-length format, holding the attribute associated with his particular tradition (Peter with the keys, Paul with the sword, Andrew with the X-cross, and so on). Saint Jude Thaddeus holds the carpenter's saw with which, according to one of the apostle traditions, he was martyred. The chromatic palette of pale silver-grey, deep crimson, and pale flesh against a dark neutral ground is the late-Greco signature; the figure is unmistakably elongated, the head tilted slightly, the eyes lifted into the middle distance with the characteristic almost-trance-like quality that marks the late religious paintings."}
]$JSON$::jsonb
where slug in ('el-greco', 'el-greco-domenikos-theotokopoulos', 'el-greco-domenikos-theotokopoulos-and-workshop');

-- ─── Jan van Eyck ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436282","paragraph":"The Crucifixion and the Last Judgment, painted by Jan van Eyck around 1436 in oil on canvas transferred from wood and now in the Metropolitan Museum of Art in New York, is a small early-Eyckian diptych that survives as one of the principal Jan van Eyck works in any American collection. The left panel shows the Crucifixion at the moment immediately after Christ's death — the swooning Virgin in the arms of John, the Magdalene clinging to the foot of the cross, the centurion on horseback in the foreground recognizing the divinity of the dying Christ — set against a panoramic landscape of the city of Jerusalem fading into snow-capped mountains. The right panel shows the Last Judgment in three vertical registers: Christ enthroned in judgment at the top, the resurrected dead emerging from the earth and sea in the middle, and a multi-tiered hell of damned souls and devils in the bottom. The painting is the principal Jan van Eyck religious work in the Metropolitan and a defining example of the Early Netherlandish oil-on-panel technique that the Eyckian workshop perfected in the 1430s."},
  {"artwork_slug":"met-436283","paragraph":"The Virgin and Child in a Niche, painted by Jan van Eyck around 1440 in oil on a small wooden panel and now in the Metropolitan Museum of Art in New York, is among the surviving small-format Eyckian devotional paintings of the late 1430s and early 1440s. The Virgin stands in a stone architectural niche with the Christ Child upright on her right arm; the niche is carved with small grotesque figures and topped by a small architectural canopy; the Virgin's blue mantle pools down onto a stone parapet at the bottom of the panel. The composition follows the Eyckian convention of placing the Madonna in a sculptural niche to underscore the stone-like permanence of the Marian devotional image — a visual conceit Jan van Eyck developed in several of the small surviving panels of the late 1430s and early 1440s. The painting is one of the principal small Jan van Eyck Madonnas in any American collection."}
]$JSON$::jsonb
where slug in ('jan-van-eyck', 'circle-of-jan-van-eyck');

-- ─── Rogier van der Weyden ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437492","paragraph":"The Holy Family with Saint Paul and a Donor, painted in the workshop of Rogier van der Weyden around 1430–1450 in oil on panel and now in the Metropolitan Museum of Art in New York, is one of the surviving small-format Weydenesque devotional panels of the mid-fifteenth century. The composition shows the Virgin and Child enthroned in the center, with Saint Paul standing in armor on the right holding the sword of his martyrdom, and a kneeling male donor figure in the lower-left foreground. The chromatic palette — deep ultramarine, crimson, and pale grey — and the small architectural niche behind the throne are characteristic of the Bruges-Brussels Weyden workshop tradition. The panel may have been the surviving central section of a small triptych whose wings have been lost; whatever its original setting, it remains one of the principal Weyden-school devotional panels in any American collection and a defining example of the Early Netherlandish small-format domestic-altar tradition."}
]$JSON$::jsonb
where slug in ('rogier-van-der-weyden', 'copy-after-rogier-van-der-weyden');

-- ─── Hans Memling ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437490","paragraph":"The Annunciation, painted by Hans Memling around 1465–1475 in oil on panel and now in the Metropolitan Museum of Art in New York, is one of the surviving Memling Annunciations and a defining statement of his soft, jewel-bright late-Bruges manner. The composition shows the Virgin standing in a small interior chamber, her prayer book open on a table at her side, the angel Gabriel kneeling on the floor beside her in the act of greeting; the Holy Spirit descends as a dove on a single beam of golden light through the open window in the upper left. Memling's characteristic chromatic palette — deep ultramarine, soft rose, pale grey-green — and his patient observation of textiles, woodwork, and the small furnishings of the Marian chamber are at full mature statement here. The panel entered the Metropolitan in 1917 from the J. Pierpont Morgan collection."},
  {"artwork_slug":"met-437061","paragraph":"Salvator Mundi (Christ Saviour of the World), painted by Hans Memling around 1475–1480 in oil on panel and now in the Metropolitan Museum of Art in New York, is among the most reproduced Memling devotional images. The composition shows the half-length figure of Christ raising his right hand in benediction and holding a transparent crystal globe surmounted by a small cross in his left — the orb representing the world over which Christ exercises spiritual sovereignty. The dark neutral background and the close-cropped half-length format derive from the Bruges devotional tradition descending from Jan van Eyck and Rogier van der Weyden; Memling produced multiple versions of the Salvator Mundi composition in his Bruges workshop, and the type circulated widely through the late fifteenth and early sixteenth centuries as a standard small-format household devotional image. The panel entered the Metropolitan in 1932."},
  {"artwork_slug":"memling-john-on-patmos","paragraph":"Saint John on Patmos is the right interior wing of the Saint John Altarpiece, painted by Hans Memling between 1474 and 1479 for the Hospital of Saint John in Bruges where it remains in continuous display in the Memlingmuseum on the original site. The panel shows the apostle John seated on the rocky island of Patmos receiving the apocalyptic visions recorded in Revelation; the entire vision sequence — the elders around the throne of God, the seven seals, the four horsemen, the seven trumpets, the woman clothed with the sun, the dragon, the great whore of Babylon — is rendered as a continuous panoramic landscape unfolding behind and above the seated apostle. The compression of the entire Book of Revelation into a single small painted panel is one of the supreme achievements of Early Netherlandish small-scale narrative composition and a defining work of Memling's mature Bruges manner."},
  {"artwork_slug":"memling-bathsheba","paragraph":"Bathsheba, painted by Hans Memling around 1485 in oil on panel and now in the Staatsgalerie in Stuttgart, illustrates the moment from 2 Samuel 11 when King David, walking on the roof of his palace at evening, sees Bathsheba bathing and sends for her — the first scene in the long unfolding of the David-and-Bathsheba narrative that ends in the murder of her husband Uriah. Memling stages the scene in a small Bruges merchant interior with carved wooden beams and tiled floors; Bathsheba steps from the bath onto a folded white cloth held by a servant, while the king watches from a small distant window in the upper-right background. The composition is among the most reproduced Memling treatments of an Old Testament narrative and a defining statement of his ability to combine quiet domestic observation with the textural precision that defined the late Early Netherlandish school."}
]$JSON$::jsonb
where slug = 'hans-memling';

-- ─── Hans Holbein the Younger ──────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"holbein-dead-christ-1cor15","paragraph":"The Body of the Dead Christ in the Tomb, painted by Hans Holbein the Younger in 1521 in oil and tempera on a long horizontal lime-wood panel and now in the Kunstmuseum Basel, is one of the most original and most disturbing treatments of the dead Christ in the entire history of European Christian painting. The composition shows the body of Christ stretched out at full length inside a stone sarcophagus, the panel itself almost the same width as the figure; the head is fallen back, the eyes and mouth open, the right hand resting on the chest, the wound in the side visible. There is no Virgin, no John, no Magdalene — no mourning at all — only the body. The flesh tones are rendered with extraordinary literal-mindedness as the colors of recent death: greenish-grey on the limbs, faintly purple at the wounds. The novelist Fyodor Dostoevsky, who saw the painting in Basel in 1867, described it in The Idiot as a painting that could shake a viewer's faith in the Resurrection; the description fairly captures the painting's effect on every viewer who has stood in front of it since."},
  {"artwork_slug":"met-365214","paragraph":"The Last Judgment, from the Dance of Death series of woodcuts designed by Hans Holbein the Younger around 1521 and published as a small bound book in Lyon in 1538, is among the most reproduced of the forty-one tiny printed images that make up the cycle. The composition shows the resurrected dead emerging from open graves in the foreground, Christ enthroned in judgment in the upper register with the apostles ranged around him, and Death — personified as a skeleton — moving among the rising figures with his usual indifference. The Dance of Death series, designed in Basel during Holbein's late twenties and engraved on small woodblocks by the Basel printmaker Hans Lützelburger, was one of the most-reprinted moralizing print cycles of the entire sixteenth century; editions in Latin, French, German, English, and Italian circulated through Europe for over a century after Holbein's death."}
]$JSON$::jsonb
where slug = 'hans-holbein-the-younger';

-- ─── Andrea Mantegna ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436966","paragraph":"The Adoration of the Shepherds, painted by Andrea Mantegna around 1450 in tempera and gold on canvas transferred from wood and now in the Metropolitan Museum of Art in New York, is among the earliest surviving Mantegna paintings and a defining statement of the new Paduan style of figural sculpture-into-painting that he was developing in his early twenties. The composition shows the Holy Family on the left under a small thatched lean-to, with two shepherds approaching from the right across a craggy rocky landscape that looks more carved than painted; the Christ Child lies on the ground in the swaddling cloth typical of the late-medieval Northern Italian tradition, and the Virgin and Joseph kneel before him in postures of slow tender adoration. The chromatic palette of warm browns, ochres, and faded gold against the grey rocky landscape is unmistakably Mantegna; the painting entered the Metropolitan in 1932 from the Henry G. Marquand bequest."},
  {"artwork_slug":"met-372985","paragraph":"The Adoration of the Magi, designed by Andrea Mantegna around 1470 and engraved by his workshop, is among the surviving prints of his independent printmaking career — the small body of about seven engravings traditionally attributed to Mantegna's own hand or to immediate workshop members trained directly by him. The composition shows the three Magi approaching the Holy Family in a classical Renaissance setting of low marble ruins and broken columns, with the small star above the lean-to and a panoramic Italian landscape stretching into the distance. Mantegna's prints were among the technical landmarks of late-fifteenth-century Italian engraving and were copied throughout Europe; Albrecht Dürer specifically traveled to Mantua in 1505 hoping to meet the older master, only to find him just dead. The print is one of the principal Mantegna engravings in any American collection."},
  {"artwork_slug":"met-368620","paragraph":"The Entombment of Christ, designed by Andrea Mantegna around 1475 and engraved by his workshop, depicts the moment after the Crucifixion when the body of Christ is being lowered into the rock-cut tomb. The composition shows the body laid horizontally across the foreground, with the Virgin, John the Evangelist, and Joseph of Arimathea gathered around it in postures of grief; the rocky tomb opening in the background is rendered with Mantegna's characteristic relish for sculpted stone and complex foreshortening. The print circulated through Italian and Northern European print collections in editions throughout the late fifteenth and early sixteenth centuries and shaped the iconographic tradition of the Entombment subject for several generations of subsequent printmakers."},
  {"artwork_slug":"met-372965","paragraph":"The Risen Christ between Saints Andrew and Longinus, designed by Andrea Mantegna around 1470 and engraved by his workshop, depicts the risen Christ flanked by the apostle Andrew (with his X-shaped cross) and the centurion Longinus (with the lance that pierced Christ's side at the Crucifixion and that became one of the principal medieval relics of the Passion). The composition arranges the three figures in a strict frontal symmetry against a dark neutral background, with Christ in the center holding the staff of the Resurrection. The choice of subject — the risen Christ flanked by these two specific saints — points to a Mantuan provincial commission or print intended for the cult of the Holy Blood at the Mantuan basilica of Sant'Andrea, where the relic of the lance and a relic of the blood were both venerated. The print is among the most ambitious of Mantegna's surviving engraved compositions."},
  {"artwork_slug":"met-459415","paragraph":"The Descent into Limbo, designed by Andrea Mantegna around 1436 (or, more probably, in the 1470s — the dating of the print is contested) and engraved by his workshop, illustrates the apocryphal Harrowing of Hell — the tradition that Christ between his death on Friday and his Resurrection on Sunday descended into the underworld to free the souls of the just who had died before his Incarnation. Mantegna's composition shows Christ at the lower right standing at the entrance to the cavernous underworld; Adam and Eve and the patriarchs reach toward him from the open mouth of hell on the left; small figures of the damned writhe in the darkness behind them. The treatment of the rocky cave architecture and the carved-stone figures is characteristically Mantegna; the print is among the most reproduced of his surviving engraved compositions."}
]$JSON$::jsonb
where slug = 'andrea-mantegna';

-- ─── Murillo ───────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"murillo-immaculate-conception-isaiah","paragraph":"The Immaculate Conception, painted by Bartolomé Esteban Murillo around 1670 in oil on canvas and one of the many versions Murillo produced of this defining Marian subject across his Sevillian career, depicts the Virgin Mary as the woman of the Apocalypse described in Revelation 12 — clothed with the sun, the moon under her feet, surrounded by a circle of cherubs and small angels with attributes of her purity. Murillo's Conceptions established the canonical visual treatment of the Catholic doctrine of the Immaculate Conception in Spanish religious painting; the basic composition (the standing Virgin in white robes and a blue mantle, gaze upturned, hands folded at the breast or extended in a gesture of openness, surrounded by cherubs against a luminous golden ground) became, through Murillo's repeated workshop production and through the engraved reproductions that followed, the standard Spanish-Catholic image of the Conception for the next two centuries. The doctrine itself was not formally defined as Catholic dogma until 1854, almost two centuries after Murillo's death; his paintings were the principal visual carriers of the tradition through the intervening centuries."}
]$JSON$::jsonb
where slug in ('bartolome-esteban-murillo', 'bartolom-esteb-n-murillo');

-- ─── Zurbarán ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437972","paragraph":"The Crucifixion, painted by Francisco de Zurbarán in 1627 in oil on canvas for the Dominican church of San Pablo in Seville and now in the Art Institute of Chicago (NB: a closely related Met version exists), is among the founding statements of his early Sevillian Caravaggesque manner. The painting shows the body of Christ on the cross against a solid black ground, with no landscape, no mourners, no soldiers — only the figure isolated in a single shaft of dramatic raking light. The flesh tones are pale, almost grey-white; the loincloth is rendered in folded ivory-cream; the inscription INRI is painted on a small tablet at the top of the cross. The painting was so realistically rendered that contemporary Sevillian visitors to the church reportedly mistook it from a distance for a sculpture rather than a painting; Zurbarán's reputation in Seville was made by the panel almost overnight and the commission for the sequence of monastic altarpieces that followed grew directly from its public success."},
  {"artwork_slug":"met-437971","paragraph":"The Young Virgin (also called The Virgin as a Young Girl), painted by Francisco de Zurbarán around 1632–1633 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the Virgin Mary as a small girl of perhaps eight or ten years, seated in a small chamber with embroidery in her lap, her hands folded in prayer, her gaze lifted toward a small light in the upper left where two cherubs hover with a crown. The chromatic palette is restrained and characteristic of the early Zurbarán Sevillian manner — pale rose, white, soft grey, deep claret. The subject — the childhood of the Virgin — was a particular Sevillian devotional preference and Zurbarán painted multiple versions across his career. The Metropolitan version is among the finest surviving and one of the principal Zurbarán paintings in any American collection."},
  {"artwork_slug":"met-437969","paragraph":"Battle between Christians and Muslims at El Sotillo, painted by Francisco de Zurbarán around 1637–1639 in oil on canvas for the Carthusian monastery of Jerez and now in the Metropolitan Museum of Art in New York, depicts the apparition of the Virgin Mary at the night battle of El Sotillo (1370) in which the Christian forces of the marqués of Cádiz routed a much larger Muslim army through what the Carthusian tradition treated as a direct Marian intervention. The composition shows the Virgin in a luminous mandorla in the upper left of the painting, with the Christian and Muslim armies engaged in dense battle below across a moonlit Andalusian landscape. The painting was the central piece of the Carthusian high altarpiece at Jerez; it was dispersed during the suppression of the convents in the early nineteenth century and entered the Metropolitan in 1920."}
]$JSON$::jsonb
where slug = 'francisco-de-zurbar-n';

-- ─── Velázquez ─────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"velazquez-martha-mary-col3","paragraph":"Christ in the House of Martha and Mary, painted by Diego Velázquez in 1618 in oil on canvas and now in the National Gallery in London, is one of the principal early Sevillian works of the painter, completed when he was about nineteen years old in the workshop of his father-in-law and teacher Francisco Pacheco. The composition is unusual in its compound structure: the foreground shows a young Sevillian kitchen maid scowling at the viewer over a still life of fish, eggs, garlic, and chillies on a kitchen table, with an older woman beside her gesturing toward a small framed scene in the upper right corner — the moment from Luke 10 in which the busy Martha complains to Jesus that her sister Mary has neglected the meal-preparation in order to sit and listen at his feet. Whether the inset is a painting on the kitchen wall, a mirror reflection, or a small open window into the next room has been debated for four centuries; the device is unmistakably proto-modern in its handling of the picture-within-a-picture conceit. The painting was acquired by the National Gallery in 1934 and remains the central early Velázquez Sevillian canvas in any British collection."}
]$JSON$::jsonb
where slug in ('diego-velazquez', 'vel-zquez-diego-rodr-guez-de-silva-y-vel-zquez');
