-- Notable works (phase 3) — original-prose, single-paragraph essays for
-- the third tier of bio'd artists. Same conventions as 036 / 037: each
-- paragraph ~180–280 words, no double quotes inside the JSON strings,
-- exact slug matching, every artwork_slug verified against the live DB.

-- ─── Tintoretto ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"tintoretto-christ-washing-feet-1pet5","paragraph":"Christ Washing the Disciples' Feet, painted by Jacopo Tintoretto around 1547 and now in the Prado in Madrid (a closely related variant hangs in the Newcastle Shipley Art Gallery), is the supreme Tintoretto treatment of the John 13 episode at the Last Supper. Christ kneels before Peter at the right side of the canvas, washing the apostle's feet in a basin while Peter gestures in protest; the other apostles are scattered in animated postures across the rest of the long horizontal composition — some untying their sandals, some kneeling in conversation, some still finishing the meal at the table that runs along the back of the room. The architectural setting opens through a colonnade onto a deep panoramic landscape with distant Venetian towers. The chromatic palette of crimson, ultramarine, and burnt orange against the cool grey of the marble floor is unmistakably Tintoretto in his early-mature manner; the painting was originally commissioned for the church of San Marcuola in Venice and was sold to the Spanish royal collection in the seventeenth century."}
]$JSON$::jsonb
where slug in ('jacopo-tintoretto', 'jacopo-tintoretto-jacopo-robusti');

-- ─── Veronese ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-438134","paragraph":"Saint Catherine of Alexandria in Prison, painted by Paolo Veronese around 1580 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the legendary fourth-century Christian martyr in her cell on the eve of her execution by the Emperor Maxentius. Veronese stages the scene as an intimate vertical interior: Catherine kneels in profile in the lower right with her hands folded in prayer, her wheel of martyrdom behind her in the shadow; an angel descends from the upper left bearing a martyr's palm and a crown, surrounded by a luminous mist that fills the upper third of the canvas. The chromatic palette of ivory, rose, deep emerald, and silvery grey is characteristic of Veronese's late mature manner, when his commissions for the Venetian state and the Veneto's monastic orders had given him an unmatched fluency in jewel-bright devotional color. The painting entered the Metropolitan in 1898 from the Marquand bequest."}
]$JSON$::jsonb
where slug = 'paolo-veronese-paolo-caliari';

-- ─── Correggio ─────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435992","paragraph":"Saints Peter, Martha, Mary Magdalen, and Leonard, painted by Antonio da Correggio around 1510 in oil on canvas and now in the Metropolitan Museum of Art in New York, is among the early Correggio altarpieces that already shows the soft sfumato modeling and the warm chromatic palette that would later define the great Parma cupolas. The four saints stand in a small Renaissance interior — Peter on the left holding the keys of the kingdom, Martha with a chained dragon at her feet (the iconographic attribute of the legend in which she tamed a dragon at Tarascon), Mary Magdalen with her ointment jar, and Leonard with the broken chains he traditionally distributes to freed prisoners. The composition is built on a strict bilateral symmetry framed around an open landscape glimpsed through a colonnade behind the central group. The painting was acquired by the Metropolitan in 1912."},
  {"artwork_slug":"met-367039","paragraph":"The Adoration of the Magi, painted by Antonio da Correggio around 1512 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the visit of the three kings to the infant Christ in the small dwelling at Bethlehem. Correggio organizes the figures in a tight pyramidal grouping around the seated Virgin: the eldest king kneels in profile in the foreground, the second king stands behind with his crown removed, and the third king, traditionally identified in Renaissance iconography with the African Balthazar, stands further back holding a small golden vessel. The chromatic palette of soft rose, warm ochre, and ultramarine, and the gentle smiling Christ Child reaching toward the kneeling king's offering, are the unmistakable signatures of the early-mature Correggio manner that the Carracci would resurrect almost a century later as the principal source of the Bolognese reform of Italian painting."},
  {"artwork_slug":"met-338537","paragraph":"The Annunciation, drawn by Antonio da Correggio around 1517 in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing from the central Parma period of his career — the years immediately before he began the great cupola frescoes of San Giovanni Evangelista and the Cathedral. The drawing shows the Virgin standing on the right, her gaze lifted toward the angel Gabriel who descends from the upper left in an attitude of greeting; the Holy Spirit appears as a small dove on a single beam of light between them. Drawings of this kind were the working currency of the Renaissance Italian workshop — quick visual notations of compositions that the painter would later work up into finished altarpieces or fresco cycles. The sheet is among the principal Correggio drawings in any American collection and entered the Metropolitan in 1962."}
]$JSON$::jsonb
where slug = 'correggio-antonio-allegri';

-- ─── Giovanni Bellini ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435640","paragraph":"Madonna Adoring the Sleeping Child, painted by Giovanni Bellini around 1460 in tempera on panel and now in the Metropolitan Museum of Art in New York, is one of the earliest surviving small-format Madonnas from his Venetian workshop and a defining statement of the tender, quietly observant manner that would define his religious painting for the next half-century. The Virgin sits in profile on the right with her hands folded in prayer above the sleeping infant Christ on her lap; the chromatic palette of deep ultramarine, soft rose, and pale gold against a darkened landscape opening to a low Veneto horizon is unmistakably early-Bellini. The painting belongs to the Madonnas-with-the-Sleeping-Child compositional type Bellini would refine in dozens of later versions; the type carried forward the late-medieval Italian devotional convention of meditating on the future Passion through the figure of the sleeping infant."},
  {"artwork_slug":"met-435641","paragraph":"Madonna and Child, painted by Giovanni Bellini around 1487 in tempera and oil on panel and now in the Metropolitan Museum of Art in New York, is one of the small mature Bellini Madonnas of his middle Venetian period. The Virgin sits in three-quarter view holding the standing Christ Child against her shoulder; her gaze is downcast in soft contemplation, the Child looks out at the viewer with the unspoken solemnity that the Bellini workshop made into the standard expression for the Christ Child in mid-Quattrocento Venetian painting. The cool silvery chromatic palette and the small open landscape glimpsed beyond a low parapet at the bottom of the panel are the unmistakable signatures of the mature Bellini Madonna type that his pupils Giorgione and Titian would adapt into the next generation of Venetian religious painting."},
  {"artwork_slug":"met-435642","paragraph":"Madonna and Child with Saints, painted by Giovanni Bellini around 1500 in oil on panel and now in the Metropolitan Museum of Art in New York, is a small sacra conversazione — the Italian Renaissance compositional type in which the Madonna sits enthroned with the Christ Child surrounded by attendant saints in a unified pictorial space. Bellini's small Met version shows the Virgin and Child at the center under a dark architectural niche with two saints flanking them in three-quarter view; the chromatic palette of deep ultramarine, emerald, and warm flesh against the dark ground is characteristic of the late mature Bellini manner. The compositional type — saints arranged around the enthroned Madonna in calm devotional dialogue — was Bellini's signature contribution to Italian Renaissance altarpiece painting and the immediate ancestor of the great sacra conversazione altarpieces of his pupils Giorgione, Titian, and the next generation of Venetian masters."},
  {"artwork_slug":"met-435643","paragraph":"The Circumcision, painted by Giovanni Bellini and his workshop around 1511 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 2 in which the infant Christ, eight days after his birth, is brought to the Temple for circumcision according to Jewish law. Bellini composes the scene in a tight half-length grouping around a stone altar at the center: the priest holds the small instrument; the Virgin stands behind on the right, her hands folded in attendance; Joseph waits in the background. The painting is a workshop variant of a composition Bellini and his shop produced in multiple versions across the early sixteenth century; this Met version is among the principal surviving examples and one of the major late Bellini paintings in any American collection."},
  {"artwork_slug":"met-435644","paragraph":"Madonna and Child, painted by Giovanni Bellini around 1505 in oil on panel and now in the Metropolitan Museum of Art in New York, is one of the late half-length Madonna compositions from Bellini's last decade of work in Venice. The Virgin sits on a low stone bench in three-quarter view with the Christ Child seated upright on her lap; the chromatic palette of cool blue, warm rose, and silvery flesh against an open Veneto landscape glimpsed beyond a low parapet is the unmistakable late-Bellini signature. The painting demonstrates the compositional and chromatic discipline the eighty-year-old master continued to refine through his last years — the same discipline his Venetian successors Giorgione and Titian would carry forward into the new century. The panel entered the Metropolitan in 1908."}
]$JSON$::jsonb
where slug = 'giovanni-bellini';

-- ─── Pontormo ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-339273","paragraph":"Virgin and Child with Saint Elizabeth, the Infant John the Baptist, and an Angel, drawn by Jacopo da Pontormo around 1514 in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing from his early Florentine years in the orbit of Andrea del Sarto. The composition shows the Virgin seated holding the Christ Child, with the small John the Baptist embracing the Christ Child from the side, his mother Saint Elizabeth standing behind, and a small attending angel completing the group. Drawings of this kind were Pontormo's principal compositional currency in his early Florentine years; the figures here are sketched with the rapid confident outlines and sparse interior modeling that characterize his entire drawn output, while the staccato treatment of drapery folds and elongated proportions already anticipate the Mannerist intensities of his mature Capponi Chapel period a decade later."}
]$JSON$::jsonb
where slug = 'jacopo-da-pontormo-jacopo-carucci';

-- ─── Andrea del Sarto ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338102","paragraph":"The Birth of Saint John the Baptist, drawn by Andrea del Sarto around 1500 in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for the fresco cycle Andrea would later paint in the cloister of the Compagnia dello Scalzo in Florence. The drawing shows the moment in Luke 1 immediately after the birth: the newborn John is being washed by attendants in the lower foreground while his mother Elizabeth lies in bed in the background and a small group of women attend to the household details. Andrea's fresco cycle of the life of Saint John the Baptist at the Scalzo, executed in monochrome over almost twenty years between 1511 and 1526, is one of the supreme Florentine cloister cycles of the High Renaissance; preparatory drawings like this one are the principal record of his working method in the years immediately preceding the start of the project."}
]$JSON$::jsonb
where slug = 'andrea-del-sarto-andrea-d-agnolo';

-- ─── Guercino ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338997","paragraph":"The Raising of Lazarus, drawn by Guercino around 1614 in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is among the early masterworks of his drawn output from the Bolognese years before his summons to Rome under Pope Gregory XV. The drawing illustrates the climactic miracle of John 11: Christ stands at the lower left with his right arm extended in command, while the bound figure of Lazarus emerges upright from the open tomb in the upper right; the sisters Martha and Mary kneel between them at Christ's feet, and a small crowd of witnesses fills the background. Guercino's characteristic combination of dramatic chiaroscuro built up in dense brown wash, confident pen outlines, and crowded narrative composition reaches mature statement here. The sheet is among the principal Guercino drawings in any American collection and entered the Metropolitan in 1962."},
  {"artwork_slug":"met-338992","paragraph":"The Adoration of the Magi, drawn by Guercino around 1625 in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is from the central Roman-into-Bolognese phase of Guercino's career — the years immediately after his return from Rome following Pope Gregory XV's death. The drawing shows the Virgin and Christ Child seated under the small thatched lean-to of the Bethlehem stable while the three Magi approach in formal procession from the right; the eldest king kneels in profile in the foreground offering his gift, the second king stands waiting his turn, and the third king arrives with a small attending retinue at the rear. The composition demonstrates the late-mature Guercino's ability to organize a many-figured Adoration scene with the calm pictorial restraint that distinguished his Bolognese years from the more theatrical chiaroscuro of his Roman phase."},
  {"artwork_slug":"met-339003","paragraph":"The Virgin Immaculate, drawn by Guercino around 1651 in pen and brown ink on paper and now in the Metropolitan Museum of Art in New York, is a late drawing from the final decade of his Bolognese career. The drawing shows the Virgin Mary as the woman of the Apocalypse described in Revelation 12 — standing on a crescent moon, her hands folded at her breast, surrounded by a circle of small attendant cherubs, her gaze upturned. The Catholic doctrine of the Immaculate Conception was a particular preoccupation of seventeenth-century Bolognese religious patronage, and the standing-Virgin-on-the-crescent type that Guercino works out here was the canonical visual treatment that subsequent Spanish and Italian painting (Murillo above all) would adopt and circulate across the Catholic world. The sheet is one of the principal late Guercino drawings in any American collection."},
  {"artwork_slug":"met-339080","paragraph":"Saint Jerome Writing, drawn by Guercino in pen and brown ink with brown wash on paper from his early Bolognese workshop period and now in the Metropolitan Museum of Art in New York, depicts the early Church Father seated in his characteristic posture of scholarly attention — head lowered to a manuscript, quill in hand, his lion (the iconographic attribute that distinguishes Jerome from any other bearded saint) curled at his feet. Jerome's translation of the Bible into Latin (the Vulgate, completed around 405 AD) made him a particular favorite of Counter-Reformation patronage, and Guercino produced multiple painted and drawn treatments of the seated-Jerome subject across his career. The Met sheet is among the principal early Guercino drawings of the subject and demonstrates the rapid confident pen-and-wash technique that defined his draughtsmanship throughout his career."},
  {"artwork_slug":"met-436604","paragraph":"The Vocation of Saint Aloysius (Luigi) Gonzaga, painted by Guercino around 1645 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment in which the young Italian Jesuit saint, born into the noble Gonzaga family of Mantua and canonized in 1726, renounces his hereditary title and prepares to enter the Society of Jesus. Guercino stages the scene as a moment of vision: the young Aloysius kneels in profile at the lower right, an angel descends from the upper left bearing a lily of purity, and a small group of family attendants in the background represents the worldly inheritance the saint is in the act of refusing. The painting was commissioned in connection with Aloysius's ongoing seventeenth-century beatification process and is one of the principal late-Guercino works in any American collection."}
]$JSON$::jsonb
where slug = 'guercino-giovanni-francesco-barbieri';

-- ─── Domenico Ghirlandaio ──────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436493","paragraph":"Madonna and Child with Angels, painted by Domenico Ghirlandaio (or by his immediate workshop) around 1469 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is among the early small-format Madonnas from the Florentine workshop he ran with his brothers Davide and Benedetto. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; two child angels lean in at her shoulders to crown her with a small wreath; a gold-tooled background gives the panel the jewel-bright surface of late-medieval Florentine devotional painting at the moment immediately before the new Renaissance landscape backgrounds began to displace gold-ground convention. The young Michelangelo entered Ghirlandaio's workshop as a teenage apprentice in 1487 — almost two decades after this small panel was produced — and absorbed Ghirlandaio's compositional discipline directly. The painting is one of the principal Ghirlandaio Madonnas in any American collection."}
]$JSON$::jsonb
where slug in ('domenico-ghirlandaio', 'domenico-ghirlandaio-domenico-bigordi');

-- ─── Perugino ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437273","paragraph":"Saint John the Baptist; Saint Lucy, painted by Pietro Perugino around 1469 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is among the surviving small early Perugino panels from his Florentine workshop years before his major Roman Sistine commission of 1481–1482. The pair of saints stand in three-quarter view against a gold-tooled background — John the Baptist on the left holding a small reed cross and a banner inscribed with the Latin Ecce Agnus Dei (Behold the Lamb of God), Lucy on the right holding a small palm of martyrdom and a gold dish on which her eyes (the iconographic attribute distinguishing her from any other female saint) rest. The chromatic palette of saturated rose, ultramarine, and tooled gold demonstrates the early Perugino combination of the Florentine Renaissance figural discipline with the Umbrian-Sienese gold-ground decorative tradition that he would carry into all of his subsequent altarpieces."},
  {"artwork_slug":"met-437272","paragraph":"The Resurrection, painted by Pietro Perugino around 1497 in tempera and oil on panel and now in the Metropolitan Museum of Art in New York, depicts Christ rising from the open tomb in the predawn light — the central Resurrection composition Perugino's workshop produced in multiple variants for Umbrian and Tuscan patrons across the 1490s. Christ stands fully clothed in white at the upper center of the panel, his right hand raised in benediction, his left holding the banner of the Resurrection; the Roman soldiers below are scattered across the foreground in poses of unconscious sleep or panicked awakening. The Umbrian landscape — slim trees, a low horizon, distant blue hills — that fills the background is the unmistakable Perugino signature, the same calm pastoral setting that would become the standard Italian Renaissance backdrop for devotional altarpieces through Raphael's High Renaissance generation a few years later."}
]$JSON$::jsonb
where slug = 'perugino-pietro-di-cristoforo-vannucci';

-- ─── Filippino Lippi ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340237","paragraph":"Virgin and Child Attended by Angels, drawn by Filippino Lippi around 1457 (early in his career, in the workshop he had just entered after his father's death) in pen and brown ink on paper and now in the Metropolitan Museum of Art in New York, is among the earliest surviving Filippino drawings. The drawing shows the Virgin seated in three-quarter view holding the Christ Child upright on her lap, with two small attendant angels lean in at her shoulders. The figures are sketched rapidly with confident outlines characteristic of the late-Quattrocento Florentine workshop drawing tradition descending from Filippo Lippi (Filippino's father) and Botticelli (his master after his father's death). The sheet is one of the principal early Filippino drawings in any American collection."},
  {"artwork_slug":"met-436893","paragraph":"The Descent from the Cross, painted by Filippino Lippi (or completed by his workshop after his death) around 1477 in tempera on panel and now in the Metropolitan Museum of Art in New York, is among the surviving small Florentine altarpiece panels of his early career. The composition shows the body of Christ being lowered from the cross into the arms of the Virgin and the Magdalene at the foot of the cross; John the Evangelist supports the body from above, and Joseph of Arimathea stands on the ladder to the right detaching the nails. The chromatic palette of soft rose, blue-grey, and pale flesh against the dark sky is the unmistakable late-Quattrocento Florentine signature, and the elongated swooping figural proportions point forward to the Mannerist directions that the next Florentine generation would explore in the early sixteenth century."},
  {"artwork_slug":"met-436894","paragraph":"The Virgin of the Nativity, painted by Filippino Lippi around 1495 in tempera and oil on panel and now in the Metropolitan Museum of Art in New York, depicts the Virgin Mary in adoration before the newborn Christ Child laid on the ground — the iconographic compositional type known as the Adoration of the Christ Child that Florentine Quattrocento painting refined repeatedly for private devotional use. The Virgin kneels in profile on the right with her hands folded; the Christ Child lies on the ground on a small piece of straw in the lower center; a small angel and a tiny donor figure complete the composition. The chromatic palette of warm flesh, soft blue, and pale gold against a darkened landscape opening to a low Tuscan horizon is the unmistakable late-Quattrocento Florentine signature."},
  {"artwork_slug":"met-436892","paragraph":"Madonna and Child, painted by Filippino Lippi around 1483 in tempera on panel and now in the Metropolitan Museum of Art in New York, is one of the small Florentine devotional Madonnas from the central productive years of Filippino's career — the years of the Tornabuoni Chapel completion in Santa Maria del Carmine and the Strozzi Chapel commissions in Santa Maria Novella. The Virgin sits in three-quarter view holding the Christ Child against her chest; the chromatic palette of soft rose, pale blue, and warm flesh against a darkened ground is characteristic of his mature small-format manner. The painting belongs to the long sequence of small Madonnas that the Filippino workshop produced for private Florentine patrons throughout the 1480s and 1490s, and is one of the principal Filippino Madonnas in any American collection."}
]$JSON$::jsonb
where slug = 'filippino-lippi';

-- ─── Luca Signorelli ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437674","paragraph":"Madonna and Child, painted by Luca Signorelli around 1505 in tempera on panel and now in the Metropolitan Museum of Art in New York, is one of the late Madonnas Signorelli produced after his great Orvieto Cathedral San Brizio Chapel cycle was completed in 1504. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; the chromatic palette of warm flesh, soft rose, and earthy ochre against a darkened landscape opening to a low Umbrian horizon is characteristic of the late Signorelli manner. The painting demonstrates the same dense muscular figural drawing that distinguishes the Orvieto frescoes — even at this small intimate devotional scale — and is one of the principal late Signorelli Madonnas in any American collection."}
]$JSON$::jsonb
where slug = 'luca-signorelli-luca-d-egidio-di-luca-di-ventura';

-- ─── Jusepe de Ribera ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-441971","paragraph":"The Tears of Saint Peter, painted by Jusepe de Ribera around 1612 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the apostle Peter in the moment of his repentance after the threefold denial of Christ recorded in the Synoptic Gospels. Ribera shows the saint in three-quarter view, his eyes lifted heavenward, tears streaming down his cheeks, his clasped hands raised in supplication; the dark neutral background and the dramatic single-source raking light from the upper left are the unmistakable signatures of Ribera's early Caravaggesque manner. The Tears of Saint Peter was a particular preoccupation of seventeenth-century Counter-Reformation devotional painting — the subject combined the intimacy of personal penitence with the Catholic doctrine of the perfectibility of the apostle who had failed his Lord — and Ribera produced multiple painted versions across his career."},
  {"artwork_slug":"met-397952","paragraph":"Saint Jerome Hearing the Trumpet of the Last Judgment, painted by Jusepe de Ribera around 1616 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the early Church Father in the conventional iconographic posture of his hermit years in the Syrian desert — half-naked, kneeling on his rocks, with his lion (the saint's iconographic attribute) at his feet — but Ribera adds the dramatic moment in which an angel descends from the upper left blowing the trumpet that announces the Last Judgment. Jerome looks up in startled recognition. The composition is among the most dramatic Ribera treatments of the Jerome subject and demonstrates his characteristic ability to combine the Caravaggesque chiaroscuro with the muscular athletic figural drawing that defined Spanish Baroque religious painting in his Naples years."},
  {"artwork_slug":"met-650854","paragraph":"The Penitence of Saint Peter, painted by Jusepe de Ribera around 1621 in oil on canvas and now in the Metropolitan Museum of Art in New York, is a second Ribera treatment of the subject — Peter weeping after his denial of Christ — that he had earlier addressed in the 1612 Tears of Saint Peter. The 1621 version places the apostle in a similar three-quarter pose against a similarly dark neutral background, but the figural anatomy is more confident, the dramatic light is more sharply focused, and the compositional restraint is more austere. Ribera produced multiple versions of penitent-saint subjects across his career — the Magdalene, Jerome, Peter — that, taken together, define the Spanish Baroque devotional preoccupation with public displays of inward repentance and bodily contrition. The painting is one of the principal Ribera Peter subjects in any American collection."},
  {"artwork_slug":"met-336332","paragraph":"Adoration of the Shepherds, painted by Jusepe de Ribera around 1645 in oil on canvas and now in the Metropolitan Museum of Art in New York, is from the late Naples period of his career, the years after the Spanish viceregal patronage had stabilized his reputation as the city's leading religious painter. The composition shows the Holy Family in the center under a small thatched lean-to, with three Neapolitan-peasant shepherds gathered around the kneeling Virgin in the lower foreground; one shepherd kneels with his cap in his hands, another stands holding a small lamb as a gift, the third lifts up his hands in an attitude of recognition. The chromatic palette of warm earth tones and dramatic single-source candlelight is the unmistakable late-Ribera Naples signature, and the painting is among the principal late Ribera Adorations in any American collection."}
]$JSON$::jsonb
where slug = 'jusepe-de-ribera-called-lo-spagnoletto';

-- ─── Lucas van Leyden ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-364677","paragraph":"The Raising of Lazarus, engraved by Lucas van Leyden around 1502 — when the artist was about eight years old according to the most generous chronology, or in his early teens according to the more cautious — is one of the earliest dated prints in the Lucas van Leyden corpus and a defining statement of the precocious technical accomplishment that would make him the leading Dutch printmaker of his generation. The composition shows the climactic miracle of John 11: Christ at the right with his arm extended in command; the bound figure of Lazarus emerging upright from the open tomb at the center; the sisters Martha and Mary kneeling between them; a small crowd of witnesses gathered behind. The compositional discipline and the technical mastery of the engraved line — particularly the atmospheric distance achieved through progressive lightening of the burin — mark the print as the work of a fully formed artist regardless of which dating one accepts."},
  {"artwork_slug":"met-364658","paragraph":"David Playing the Harp Before Saul, engraved by Lucas van Leyden around 1503 in his Leiden workshop, illustrates the episode from 1 Samuel 16 in which the young shepherd David is brought to play music for the troubled King Saul — the moment that begins the long Old Testament unfolding of the David narrative. The composition shows Saul seated on his throne in the upper register, his head bowed in contemplation, with David standing in the lower foreground playing his harp; a small crowd of attendant courtiers fills the background. Lucas van Leyden's characteristic combination of dense crowded narrative composition and progressively atmospheric burin work, with figures in the foreground sharply outlined and figures in the back fading into soft tonal grey, marks the print as one of the technical landmarks of early sixteenth-century Northern engraving."},
  {"artwork_slug":"met-364755","paragraph":"Susanna and the Two Elders, engraved by Lucas van Leyden around 1503 in his Leiden workshop, illustrates the deuterocanonical narrative from Daniel 13 in which the chaste Susanna is spied upon while bathing by two elders of her community who later attempt to extort her into adultery and, when she refuses, falsely accuse her of the crime themselves. Lucas van Leyden composes the scene in his characteristic horizontal Northern landscape format — Susanna in the lower right partially undressed beside her bath, the two elders in the bushes at the lower left looking on, a panoramic Dutch coastal landscape stretching into the distance behind. The print is among the most reproduced of his Old Testament treatments and a defining example of the early sixteenth-century Northern interest in the moral and erotic complexities of the Susanna narrative."},
  {"artwork_slug":"met-364692","paragraph":"The Return of the Prodigal Son, engraved by Lucas van Leyden around 1505 in his Leiden workshop, illustrates the climactic moment of the Luke 15 parable: the father runs to embrace his returning son who, having squandered his inheritance, has returned home to throw himself at his father's feet. Lucas van Leyden composes the scene as a small intimate group in the foreground — the kneeling son embraced by the standing father — with the elder brother visible in the deeper background tending the household and the fatted calf being prepared for the celebratory meal at the upper left. The print circulated through the early sixteenth-century Dutch and German print collections and shaped the visual treatment of the Prodigal Son parable in Northern Renaissance and Reformation devotional imagery for several generations."},
  {"artwork_slug":"met-364736","paragraph":"Christ on the Mount of Olives, engraved by Lucas van Leyden around 1509 as one of the small plates from his Circular Passion series in his Leiden workshop, depicts the Agony in the Garden as recorded in the Synoptic Gospels: Christ kneels in prayer before the angel bearing the cup of the Passion, while the three sleeping disciples — Peter, James, and John — are gathered in the lower foreground and Judas with the Roman soldiers approach through the gate at the rear. The Circular Passion was a series of small round-format engravings depicting the principal Passion subjects, designed for binding into prayer books or for distribution at confraternity meetings. Lucas van Leyden's combination of dense crowded composition and atmospheric burin work translated the late-medieval Northern devotional preoccupation with the Passion into the new sixteenth-century engraved format."}
]$JSON$::jsonb
where slug = 'lucas-van-leyden';

-- ─── William Blake ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"blake-ancient-of-days","paragraph":"The Ancient of Days, designed by William Blake in 1794 as the frontispiece for his prophetic book Europe: A Prophecy and produced in his idiosyncratic relief-etched and hand-colored format, depicts the moment from Proverbs 8 (and from Blake's own mythological cycles) in which the divine figure leans down from a luminous celestial sphere with a great brass compass to measure out the boundaries of the created world. The figure — Blake's own visionary character Urizen, identified in his mythology with the moral law-giver and with the divine architect of the material universe — is shown crouched inside a fiery solar disc reaching down with the compass into the formless darkness below. The composition is among the most reproduced of Blake's prophetic illustrations and was the print he was reportedly working on as he died in 1827. Blake himself colored the surviving impressions of the design by hand in editions of a few copies; the principal surviving versions are in the Whitworth Art Gallery in Manchester, the British Museum, and the Yale Center for British Art."},
  {"artwork_slug":"blake-elohim-creating-adam","paragraph":"Elohim Creating Adam, painted by William Blake in 1795 (or 1805 — the dating of the Large Color Prints series is contested) in color print finished in pen and watercolor on paper and now in the Tate in London, depicts the moment from Genesis 2 in which the Lord forms Adam from the dust of the ground. Blake stages the scene as a fierce spiritual struggle: the great winged figure of Elohim hovers above the half-formed body of Adam, who lies on the ground with a serpent already wrapped around his thigh — the iconographic signal that Blake reads the act of creation as already entangled with the Fall and the suffering that will follow. The painting is one of the twelve large color prints Blake produced in the mid-1790s, and one of the supreme statements of his lifelong commitment to a visionary, unconventional, almost dissenting reading of the biblical narrative."},
  {"artwork_slug":"blake-nebuchadnezzar","paragraph":"Nebuchadnezzar, painted by William Blake in 1795 (or 1805 — the dating is contested) in color print finished in pen and watercolor on paper and now in the Tate in London, depicts the Babylonian king of Daniel 4 after God has driven him from human society and reduced him to crawling on all fours in the wilderness, his hair grown like eagles' feathers, his nails like birds' claws. Blake shows the king in the moment of his abasement: a heavily muscled bearded figure on hands and knees, his eyes wide with terror, his mouth open in a half-howl, in a craggy rocky landscape. The painting is one of the twelve large color prints Blake produced in the mid-1790s and a supreme statement of his interest in the Old Testament as a record of human spiritual catastrophe. Blake's Nebuchadnezzar shaped the iconographic treatment of the subject for the next two centuries; almost every subsequent depiction of the mad king refers back to it."},
  {"artwork_slug":"blake-christ-in-the-sepulchre","paragraph":"Christ in the Sepulchre, Guarded by Angels, painted by William Blake around 1805 in pen and watercolor on paper and now in the Victoria and Albert Museum in London, depicts the body of Christ laid in the rock-cut tomb between the moment of his death and the moment of his Resurrection — the day and a half between Good Friday and Easter Sunday on which medieval and early modern Christian tradition meditated as the Sabbath of the Lord's rest. Blake shows the body of Christ stretched out on a low stone slab; two enormous winged angels kneel facing each other at the head and the foot, their wings extended and meeting overhead to form a kind of canopy of feathered protection. The composition is among the most original and most affecting of Blake's biblical watercolors and a defining statement of his ability to visualize the silent, almost unspoken moments of the Christian narrative that the more conventional Renaissance and Baroque traditions had largely passed over."},
  {"artwork_slug":"blake-job-14-when-the-morning-stars-sang-together","paragraph":"When the Morning Stars Sang Together, plate 14 of Blake's Illustrations of the Book of Job (London, 1826), is among the supreme statements of his late style and one of the most reproduced single images from the entire Job series. The plate illustrates the moment from Job 38 in which God speaks to Job out of the whirlwind: Where wast thou when I laid the foundations of the earth, when the morning stars sang together and all the sons of God shouted for joy? Blake stages the moment as a vast cosmic theatre — Job and his wife and friends in the foreground recoiling in awe, the great figure of God in the upper register with arms outstretched, four angelic figures behind him representing the personified powers of creation, and a long horizontal band of small singing angels along the upper edge of the plate. The Job engravings, published in 1826 the year before Blake's death and dedicated to his patron John Linnell, are widely held to be the masterpiece of his entire engraved career."},
  {"artwork_slug":"blake-job-01-job-and-his-family","paragraph":"Job and His Family, plate 1 of Blake's Illustrations of the Book of Job (London, 1826), is the opening image of the twenty-one-engraving cycle that traces the entire Job narrative from the patriarch's pre-affliction prosperity through his sufferings, his dialogue with his three friends, the divine speech from the whirlwind, and his final restoration. The opening plate shows Job and his wife seated on either side of their large family under the spreading branches of a great tree at sunset, the household animals at their feet, the musical instruments hung silent in the tree above — Blake's small visual signal that something is wrong, that the music has stopped before the trial begins. The text border around the engraving carries scriptural quotations laid out in Blake's own characteristic typographic format. The plate sets the visual and theological tone for the entire cycle and is one of the most reproduced individual engravings from Blake's late career."}
]$JSON$::jsonb
where slug = 'william-blake';

-- ─── Martin Schongauer ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-366983","paragraph":"The Adoration of the Magi, engraved by Martin Schongauer around 1465 in his Colmar workshop and one of the technical landmarks of early Northern European engraving, illustrates the visit of the three kings to the infant Christ in the small dwelling at Bethlehem. Schongauer composes the scene in a tight horizontal grouping: the seated Virgin with the Christ Child on her lap on the right, the eldest king kneeling in profile in the foreground offering his gift, the second king standing behind with his crown removed, the third king arriving from the left with a small attending retinue. The technical accomplishment of the engraved line — patiently cross-hatched, plastically modeled, with fine atmospheric grays in the architectural background — marked the print as one of the foundational documents of the Northern late-medieval engraving tradition that Albrecht Dürer would inherit and transform a generation later."},
  {"artwork_slug":"met-336160","paragraph":"Death of the Virgin, engraved by Martin Schongauer around 1470 in his Colmar workshop, depicts the moment from the apocryphal Marian narrative in which the Virgin Mary, dying in her old age, is attended on her deathbed by the assembled apostles. Schongauer composes the scene in a small interior chamber: the Virgin lies in the bed at the lower center, the apostles gather around her in dense devotional postures of grief and prayer; Peter (identified by the pyx of the Eucharist in his hand) leans in over the bed, John (the youngest apostle) kneels at the head, and the others fill the background space. The print is among the most reproduced of Schongauer's surviving engraved compositions and a defining statement of the late-Gothic Northern devotional sensibility his Colmar workshop translated into the new engraved format."},
  {"artwork_slug":"met-338743","paragraph":"Noli me Tangere, engraved by Martin Schongauer around 1465 in his Colmar workshop, illustrates the moment from John 20 in which the risen Christ appears to Mary Magdalene in the garden outside the empty tomb on the morning of the Resurrection — the moment immediately before he addresses her with the Latin words Noli me tangere (Touch me not) that have given the iconographic subject its conventional name. Schongauer stages the encounter in a small landscape with the Magdalene kneeling in profile on the left and the half-naked risen Christ standing on the right with one hand raised in a gesture of withholding; a small Northern garden with low trees, a fence, and a distant hill fills the background. The print is one of the principal Schongauer treatments of an Easter subject and a defining statement of his ability to translate intimate Gospel encounters into the engraved devotional format."},
  {"artwork_slug":"met-367001","paragraph":"Christ as the Man of Sorrows with the Virgin and Saint John, engraved by Martin Schongauer around 1469 in his Colmar workshop, depicts one of the standard late-medieval Northern devotional subjects: the dead-but-still-standing Christ flanked by the mourning Virgin and John the Evangelist in a vertical compositional format suitable for personal contemplation. Christ stands in the center with his hands crossed at his waist showing the wounds of the Crucifixion; the Virgin on the left holds her hands folded against her cheek in grief; John on the right looks up at Christ with an expression of inward sorrow. The Man of Sorrows iconographic type, derived from the late-medieval mystical tradition of meditation on the Passion, was one of Schongauer's most-reproduced compositions; the technical accomplishment of the print and its emotional restraint together made it one of the founding documents of Northern engraved devotional imagery."}
]$JSON$::jsonb
where slug = 'martin-schongauer';

-- ─── Heemskerck ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-359446","paragraph":"Ecce Homo, designed by Maarten van Heemskerck around 1510 (probably in his early Haarlem years before the formative Italian sojourn of 1532–1537) and engraved by his workshop, depicts the moment from the Passion narratives in which Pontius Pilate presents the scourged and crowned-with-thorns Christ to the assembled crowd with the Latin words Ecce Homo (Behold the man). Heemskerck stages the scene on the small stone balcony of the Praetorium with Christ in the center, the Roman soldiers on either side of him holding the reed scepter and pointing to the wound, and Pilate standing slightly behind addressing the crowd that fills the lower foreground. The composition is among the early Heemskerck treatments of the Passion subject and demonstrates the careful Northern Renaissance figural drawing that would later be transformed by his Italian study trip into the Romanist manner that defined his mature output."},
  {"artwork_slug":"met-405360","paragraph":"Judith Slaying Holofernes, designed by Maarten van Heemskerck in 1530 (in his late pre-Roman Haarlem years) and engraved by his workshop as part of the great Story of Judith series, depicts the climactic moment of the deuterocanonical Book of Judith: the young Hebrew widow saws through the neck of the drunken Assyrian general in his command tent. Heemskerck stages the act with characteristic Northern Mannerist drama — Judith leaning back from the spurting blood with an expression of fastidious determination, the elderly servant Abra leaning in to hold open the linen sack into which the head will fall, the body of Holofernes sprawled across the bed in a complex foreshortened pose. The Story of Judith series, published in Antwerp by Hieronymus Cock at Aux Quatre Vents, was one of the most reproduced sixteenth-century Northern treatments of the Old Testament subject."},
  {"artwork_slug":"met-405357","paragraph":"Christ Driving the Money Changers from the Temple, designed by Maarten van Heemskerck in 1548 (in his mature post-Roman Haarlem years) and engraved by his workshop for publication in Antwerp by Hieronymus Cock at Aux Quatre Vents, illustrates the scene from John 2 (and parallel passages in the Synoptics) in which Christ overturns the tables of the money-changers and dove-sellers in the outer court of the Temple. Heemskerck stages the scene in an architectural setting that combines Northern Mannerist figural drawing with the Roman classical-architecture vocabulary he had absorbed during his 1532–1537 Italian sojourn — the columns and pediments of the Temple court are unmistakably Roman, the figures in their poses of flight and resistance are unmistakably Antwerp-Mannerist. The print circulated widely through the Cock distribution network and shaped the iconographic tradition of the subject for several generations."},
  {"artwork_slug":"met-385595","paragraph":"Solomon Building the Temple, designed by Maarten van Heemskerck in 1554 as one of the plates of the Story of Solomon series and engraved by his workshop for publication in Antwerp by Hieronymus Cock at Aux Quatre Vents, illustrates the great construction project from 1 Kings 6 in which Solomon erects the Temple in Jerusalem with cedar from Lebanon and stone from the quarries of Ophir. Heemskerck stages the scene as a vast architectural panorama — the temple under construction at the upper right with workers crawling over scaffolds, the hewn cedar logs being floated down from the north in the middle distance, Solomon directing the work from a small viewing platform on the left foreground, his courtiers and advisers gathered around him. The print is among the most ambitious of Heemskerck's late Old Testament narrative engravings and one of the principal sixteenth-century Northern visualizations of the Temple subject."}
]$JSON$::jsonb
where slug = 'maarten-van-heemskerck';

-- ─── Julius Schnorr von Carolsfeld ─────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"schnorr-001-first-day-of-creation-light-and-darkness","paragraph":"First Day of Creation — Light and Darkness is the opening plate of Julius Schnorr von Carolsfeld's monumental Bibel in Bildern (Bible in Pictures), a cycle of 240 wood-engravings illustrating the entire Old and New Testament published in installments between 1851 and 1860 in Leipzig by Georg Wigand. The cycle was the supreme achievement of Schnorr's late Munich-Dresden career and became, by repeated reproduction in editions across the Protestant world, one of the most reproduced illustrated Bible cycles of the entire nineteenth century. The opening plate depicts the moment from Genesis 1 in which God divides the light from the darkness on the first day of creation; Schnorr renders the divine act in a symmetrical compositional format with God enthroned in the upper register and the cosmic separation rendered as a great vertical band of contrasting tones below. The Bibel in Bildern shaped Protestant biblical illustration in the German-speaking world from its first publication through the early twentieth century."},
  {"artwork_slug":"schnorr-021-the-tower-of-babel","paragraph":"The Tower of Babel is one of the early Genesis plates of Julius Schnorr von Carolsfeld's Bibel in Bildern (1851–1860), the great cycle of 240 wood-engraved Bible illustrations that became one of the most-reproduced Protestant illustrated Bibles of the nineteenth century. The plate illustrates the great post-Flood building project on the plain of Shinar from Genesis 11; Schnorr renders the unfinished tower as a vast spiraling step-pyramid receding into low cloud cover, with hundreds of small workers scattered across its terraces hauling blocks, mixing mortar, raising scaffolds, and gesturing in dispute as the divine confusion of language begins to take effect. The composition shares stylistic kinship with Doré's almost-contemporary 1866 Tower of Babel plate, although Schnorr's cycle predated Doré's by several years and provided one of the visual sources from which Doré worked."},
  {"artwork_slug":"schnorr-013-cain-slays-abel","paragraph":"Cain Slays Abel is one of the early Genesis plates of Julius Schnorr von Carolsfeld's Bibel in Bildern (1851–1860), illustrating the first murder in human history as told in Genesis 4. Schnorr stages the scene in a wild rocky landscape; Cain swings down a heavy club in mid-strike from above the fallen Abel, whose body is sprawled across the foreground rocks beside the smoldering remains of the offering whose acceptance has provoked the killing. A small distant flock of grazing sheep — the original cause of the brothers' competing offerings — continues to feed in unaware contrast at the upper right. The composition is among the most reproduced of Schnorr's Genesis sequence and shaped the visual treatment of the subject in nineteenth-century Protestant Bible illustration; Doré's almost-contemporary 1866 treatment of the same scene draws directly on Schnorr's compositional vocabulary."},
  {"artwork_slug":"schnorr-040-joseph-interprets-pharaoh-s-dreams","paragraph":"Joseph Interprets Pharaoh's Dreams is one of the Genesis-narrative plates of Julius Schnorr von Carolsfeld's Bibel in Bildern (1851–1860), illustrating the climactic episode from Genesis 41 in which the imprisoned Joseph is summoned before the Pharaoh of Egypt to interpret the king's dreams of seven fat and seven lean cattle and seven full and seven withered ears of grain — interpretations that lead to Joseph's elevation as the second-most-powerful man in Egypt. Schnorr stages the scene in the great hall of the Egyptian court with Pharaoh enthroned at the center surrounded by his counselors and the Egyptian magicians who have failed to interpret the dreams; Joseph stands in profile on the left in the act of explaining the divine meaning of the visions. The composition demonstrates Schnorr's characteristic combination of careful nineteenth-century historical-archaeological reconstruction with the German Nazarene movement's preference for clear, legible biblical narrative."},
  {"artwork_slug":"schnorr-032-jacob-s-dream-of-the-heavenly-ladder","paragraph":"Jacob's Dream of the Heavenly Ladder is one of the Genesis-narrative plates of Julius Schnorr von Carolsfeld's Bibel in Bildern (1851–1860), illustrating the famous episode from Genesis 28 in which the patriarch Jacob, fleeing from his brother Esau, falls asleep at Bethel with a stone for his pillow and dreams of a ladder reaching from earth to heaven with angels ascending and descending upon it. Schnorr stages the scene at the bottom of a luminous diagonal — Jacob asleep on the rocky ground in the lower right, his cloak pulled around him, with the ladder of light rising into a starry sky above him and a procession of small winged angels ascending and descending on its rungs. At the top, the figure of God appears in a small mandorla. The composition is among the most reproduced of Schnorr's Genesis sequence and a defining statement of the German Nazarene movement's interest in the visionary moments of Old Testament narrative."}
]$JSON$::jsonb
where slug = 'julius-schnorr-von-carolsfeld';

-- ─── Bernhard Plockhorst ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"plockhorst-good-shepherd","paragraph":"The Good Shepherd, painted by Bernhard Plockhorst in 1878 in oil on canvas and reproduced in countless editions of devotional prints throughout the late nineteenth and twentieth centuries, depicts Christ as the Johannine Good Shepherd of John 10: a young bearded figure in a soft white robe and a blue mantle, walking through a verdant pastoral landscape carrying a small lamb in his arms while the rest of the flock follows behind. Plockhorst's combination of academic German figure-painting precision with the soft chromatic palette of late nineteenth-century Düsseldorf religious art, and his overtly tender treatment of the relationship between Christ and the lamb, made the painting one of the most-reproduced Protestant devotional images of the entire nineteenth century. Reproductions hung in Sunday-school classrooms, family parlors, and seminary common rooms across the German-speaking and English-speaking Protestant worlds for over a century after the painting's first exhibition."},
  {"artwork_slug":"plockhorst-victory-over-the-grave","paragraph":"Victory over the Grave (also called The Risen Christ), painted by Bernhard Plockhorst around 1880 in oil on canvas, depicts the moment of the Resurrection: Christ rises from the open tomb in the predawn light, his white winding sheet still draped from his shoulders, his right arm raised in the gesture of triumph, his face lifted in calm benediction. The composition follows the conventions of nineteenth-century German academic religious painting — careful figure-drawing, smoothly modeled flesh, a luminous chromatic palette of cream and pale gold against the dark stone of the tomb — and was reproduced in countless editions for Easter cards, devotional prints, and Sunday-school illustrations through the late nineteenth and early twentieth centuries. Plockhorst's particular skill at producing devotional paintings whose theological clarity made them ideal for reproduction in printed form gave him an international reach far beyond his Berlin-Weimar academic base."},
  {"artwork_slug":"plockhorst-suffer-the-children","paragraph":"Christ Blessing the Children (called Lasset die Kindlein in the original German title — from the Luther-translation of Matthew 19), painted by Bernhard Plockhorst in 1885 in oil on canvas, illustrates the moment from the Synoptic Gospels in which Christ rebukes the disciples for trying to keep the small children away from him and instead invites them to come to him. Plockhorst stages the scene as a tender outdoor encounter — Christ seated on a low stone bench under a flowering tree, several small children gathered around him in postures of trust and curiosity, with their mothers waiting in respectful attendance behind. The composition was reproduced in countless editions of Sunday-school materials, illustrated children's Bibles, and Protestant devotional cards through the late nineteenth and twentieth centuries and is among the most familiar visual treatments of the subject in Western Christian art."},
  {"artwork_slug":"plockhorst-immanuelkirche-altarpiece","paragraph":"The Immanuelkirche Altarpiece, painted by Bernhard Plockhorst in 1893 for the Immanuelkirche in Berlin where it remains in continuous liturgical use, is the great large-format public commission of his late career. The composition depicts the risen Christ seated on a celestial throne in glory surrounded by a multitude of angels and saints, with the Old and New Testament figures gathered in formal procession on either side of the central throne. The painting shows Plockhorst's characteristic combination of academic German religious-painting discipline with the bright luminous chromatic palette and the legible narrative organization that defined his mature manner. The Immanuelkirche commission gave him the opportunity to work at a scale much larger than the small devotional canvases that had built his international reputation through reproduction."},
  {"artwork_slug":"plockhorst-guardian-angel","paragraph":"The Guardian Angel (Schutzengel), painted by Bernhard Plockhorst around 1900 in oil on canvas, depicts the iconographic subject of the angel watching over a small child as the child crosses a perilous narrow footbridge over a deep ravine — the visual literalization of the Catholic and Protestant devotional tradition of meditating on the protective ministry of the angels in everyday life. Plockhorst's painting became, through endless reproduction in chromolithograph editions across the German and English-speaking Protestant world, one of the most-reproduced devotional images of the entire turn-of-the-twentieth century. The composition appeared in confirmation cards, prayer books, family parlor prints, and children's bedroom decorations for over a century, and the iconographic image of the guardian-angel-and-child has become so identified with Plockhorst's specific composition that the original is now widely treated as the definitive visualization of the subject in modern Protestant devotional art."}
]$JSON$::jsonb
where slug = 'bernhard-plockhorst';

-- ─── Heinrich Hofmann ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"hofmann-christ-in-gethsemane","paragraph":"Christ in Gethsemane, painted by Heinrich Hofmann in 1890 in oil on canvas and reproduced in countless editions of devotional prints throughout the late nineteenth and twentieth centuries, is among the most reproduced single religious paintings of any nineteenth-century European artist. Hofmann depicts Christ kneeling in prayer in the Garden of Gethsemane on the night before his arrest as recorded in the Synoptic Gospels: the figure is shown in three-quarter view, his hands folded on a low rock that serves as his altar, his face lifted toward the heavens in an attitude of intense supplication; a single shaft of luminous golden light from the upper left illuminates his face and folded hands against the dark surrounding garden. Hofmann's combination of academic German figure-painting precision with the soft luminous chromatic palette of late nineteenth-century Düsseldorf religious art, and his overtly devotional treatment of the moment of supreme spiritual struggle, made the painting one of the standard devotional images in Protestant homes, churches, and Sunday-school classrooms across the German-speaking and English-speaking worlds. The Riverside Church in New York acquired the original in 1922."},
  {"artwork_slug":"hofmann-christ-in-the-temple","paragraph":"Christ in the Temple, painted by Heinrich Hofmann in 1881 in oil on canvas and now in the Riverside Church in New York (where it hangs alongside Hofmann's Christ in Gethsemane), depicts the moment from Luke 2 in which the twelve-year-old Jesus is found by his parents in the Temple in Jerusalem in conversation with the assembled rabbis. Hofmann stages the scene as a quiet circular discussion in the Temple court: the young Jesus seated at the center, calm and self-possessed, surrounded by a group of bearded rabbis who lean in with expressions of surprised attention; the parents Joseph and Mary entering from the right side in postures of relieved discovery. The composition is among the most reproduced Hofmann religious paintings and a defining statement of the late nineteenth-century Protestant interest in the boyhood of Jesus as a subject for devotional contemplation. The Riverside Church acquired the original through John D. Rockefeller in 1922."},
  {"artwork_slug":"hofmann-christ-and-rich-young-ruler","paragraph":"Christ and the Rich Young Ruler, painted by Heinrich Hofmann in 1889 in oil on canvas, depicts the moment from the Synoptic Gospels (Matthew 19, Mark 10, Luke 18) in which a wealthy young man approaches Christ to ask what he must do to inherit eternal life and is told to sell his possessions and follow him. Hofmann stages the scene as a quiet outdoor encounter: Christ stands on the right in a soft white robe and a blue mantle, his hand raised in gentle teaching; the young ruler stands on the left in expensive Eastern dress, his face fallen in the moment of the great refusal — the moment in which, the Gospel records, he went away sorrowful, for he had great possessions. The composition was reproduced in countless editions of Sunday-school illustrations and devotional prints across the late nineteenth and twentieth centuries and is among the most familiar visual treatments of the subject in modern Protestant devotional art."},
  {"artwork_slug":"hofmann-head-of-christ","paragraph":"Head of Christ, painted by Heinrich Hofmann around 1894 as a study for the central figure of his larger Gethsemane and Christ in the Temple compositions, depicts the head of Jesus in three-quarter view against a darkened ground — a calm, soft-bearded, gentle face with brown hair falling to the shoulders and the contemplative gaze that became the canonical Hofmann visualization of Christ. The Head of Christ studies, both as standalone devotional images and as components of the larger Hofmann Gethsemane and Temple compositions, were reproduced in countless editions of devotional prints, prayer cards, Sunday-school materials, and devotional Bibles across the late nineteenth and twentieth centuries; the Hofmann face became, by the sheer scale of reproduction, one of the most familiar visualizations of Jesus in Western Christian devotional culture, particularly in the Protestant English-speaking world."},
  {"artwork_slug":"hofmann-visit-of-the-magi","paragraph":"The Visit of the Wise Men (also called The Adoration of the Magi), painted by Heinrich Hofmann around 1900 in oil on canvas, depicts the visit of the three Magi to the infant Christ as recorded in Matthew 2. Hofmann stages the scene with characteristic late-Düsseldorf academic discipline: the seated Virgin holding the standing Christ Child on her lap at the center; the eldest king kneeling in profile in the foreground offering his gift, with the second and third kings standing behind in formal attendance; Joseph waiting in the background. The chromatic palette of warm cream, soft rose, and deep saturated blue against the dark interior of the small dwelling is the unmistakable Hofmann signature. The composition was reproduced in countless editions of Christmas devotional cards and Sunday-school materials across the early twentieth century and remains one of the most reproduced Hofmann religious paintings."}
]$JSON$::jsonb
where slug = 'heinrich-hofmann';

-- ─── Jacques Callot ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-415579","paragraph":"Christ Walking on Water, Holding the Hand of Saint Peter, etched by Jacques Callot around 1607 (in his early Italian years in Rome and Florence) and now in the Metropolitan Museum of Art in New York, illustrates the climactic moment from Matthew 14 in which Peter, walking out across the water of the Sea of Galilee toward Christ, begins to sink and is caught by the outstretched hand. Callot stages the scene with characteristic dense narrative composition: Christ stands upright on the water at the right with one arm extended, gripping the wrist of the half-sunken Peter who has begun to fall; the small fishing boat with the other apostles is visible in the distance behind, tossed on the storm-roughened water. The print is among the early Callot treatments of a Gospel subject and demonstrates the technical accomplishment of the etched line that would later mature into the Lorraine Callot signature."},
  {"artwork_slug":"met-416991","paragraph":"The Last Supper, etched by Jacques Callot around 1618 as one of the plates of his Grande Passion series and now in the Metropolitan Museum of Art in New York, depicts the moment from the Synoptic Gospels at which Christ institutes the Eucharist with the apostles in the upper room on the night before his Crucifixion. Callot composes the scene at a long horizontal table with Christ in the center seated under an architectural canopy, the twelve apostles ranged on either side with John leaning into Christ's chest and Judas isolated in profile in the lower-right foreground. The Grande Passion series, etched in Florence and Lorraine across the late 1610s, represents one of the most ambitious of Callot's serial Passion projects; the technical accomplishment of the etched line — the famous échoppe needle Callot developed himself — gives the prints an atmospheric range no engraved Passion of the period had achieved."},
  {"artwork_slug":"met-419158","paragraph":"L'Adoration des Mages (The Adoration of the Magi), etched by Jacques Callot around 1621 in his late Italian years in Florence and now in the Metropolitan Museum of Art in New York, illustrates the visit of the three kings to the infant Christ as recorded in Matthew 2. Callot stages the scene as a dense crowded composition with the seated Virgin and the Christ Child at the center, the three Magi in formal attendance with their large retinue of attendants and animals filling the background, and a distant Italianate landscape with hills and small figures fading into atmospheric haze. The technical accomplishment of the print — the rich tonal range achieved through Callot's invention of the échoppe needle and his use of multiple bath-stoppings in the etching process — marks it as one of the foundational documents of seventeenth-century French printmaking."},
  {"artwork_slug":"met-417643","paragraph":"Le Souper d'Emmaüs (Supper at Emmaus, also called The Disciples at Emmaus), etched by Jacques Callot around 1620 in his late Florentine years and now in the Metropolitan Museum of Art in New York, illustrates the moment from Luke 24 in which the risen Christ is recognized by the two disciples at the inn at Emmaus when he breaks the bread at the supper table. Callot stages the scene in a small Italian inn interior: the three figures seated at a horizontal table in the foreground, Christ in the center in the act of breaking the bread, the two disciples on either side leaning back in postures of sudden recognition; an attendant servant approaches from the back with a tray. The print is among the most reproduced of Callot's Italian-period etchings and a defining statement of his ability to translate the Gospel-recognition subject into the new precise atmospheric etching format."}
]$JSON$::jsonb
where slug = 'jacques-callot';

-- ─── Hendrick Goltzius ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-345271","paragraph":"The Last Supper, engraved by Hendrick Goltzius around 1585 in his Haarlem workshop and now in the Metropolitan Museum of Art in New York, depicts the moment from the Synoptic Gospels in which Christ institutes the Eucharist with the apostles in the upper room. Goltzius composes the scene with characteristic late-Mannerist density: Christ seated at the center of a long horizontal table under an architectural canopy, the twelve apostles arranged in dramatic foreshortened postures on either side, John leaning against Christ's chest, Judas isolated in profile holding the small bag of silver. The technical accomplishment of the engraved line — the long swelling parallel strokes that became the Goltzius signature, drawn with a curved-handle burin moved in long sweeping arcs by the artist's right forearm rather than by the wrist — translated the late-Mannerist Dutch compositional sensibility into one of the most virtuoso engraved religious prints of the late sixteenth century."},
  {"artwork_slug":"met-398443","paragraph":"The Crucifixion, engraved by Hendrick Goltzius around 1585 in his Haarlem workshop and now in the Metropolitan Museum of Art in New York, depicts the moment immediately after Christ's death on the cross — the swooning Virgin in the arms of John on the left, the Magdalene clinging to the foot of the cross, the centurion on horseback in the foreground recognizing the divinity of the dying Christ, the two thieves still alive on their crosses to either side. Goltzius's characteristic combination of dramatic Mannerist figural foreshortening and the long swelling burin line that defined the late-sixteenth-century Haarlem engraving school is at full mature statement here. The print is among the principal Goltzius Crucifixion treatments and a defining example of the late-Mannerist Dutch reception of Italianizing High Renaissance religious composition."},
  {"artwork_slug":"met-649981","paragraph":"Massacre of the Innocents, engraved by Hendrick Goltzius around 1580 in his Haarlem workshop, depicts the slaughter of the male children of Bethlehem ordered by King Herod after the visit of the Magi as recorded in Matthew 2. Goltzius fills the print with a roiling chaotic mass of muscular Roman soldiers, screaming mothers clutching their dead infants, and the scattered small bodies of the killed children, set against an architectural backdrop of a Mannerist Italianate town. The compositional density and the dramatic figural foreshortening are characteristic of Goltzius's late-Mannerist Haarlem manner of the late 1570s and 1580s, the years just before his transformative Italian sojourn of 1590–1591 began to reshape his style toward a calmer, more classicizing register."},
  {"artwork_slug":"met-671513","paragraph":"The Holy Family with the Infant John the Baptist, engraved by Hendrick Goltzius around 1593 in his Haarlem workshop and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject in which the small Christ Child meets his cousin John the Baptist while their mothers — the Virgin Mary and Saint Elizabeth — and Saint Joseph attend in formal grouping. Goltzius composes the scene as a quiet domestic encounter in a small Italian Renaissance interior: the seated Virgin holds the Christ Child on her lap, the small John the Baptist embraces the Christ Child from the side, Elizabeth stands behind the Virgin, Joseph waits at the back of the room. The composition shows the lighter, more classicizing manner Goltzius adopted after his 1590–1591 Italian study trip transformed his late-Mannerist Haarlem manner toward a calmer Caravaggio-inflected register."}
]$JSON$::jsonb
where slug = 'hendrick-goltzius';

-- ─── Hans Baldung Grien ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"baldung-st-john-at-patmos","paragraph":"Saint John at Patmos, painted by Hans Baldung Grien around 1511 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the apostle John seated on the rocky island of Patmos receiving the apocalyptic visions recorded in Revelation. Baldung stages the scene as a small intimate panel: the seated apostle in profile on the right with the open book of Revelation on his knee and his quill in hand, looking up toward the upper-left where the figure of God appears in a small luminous mandorla, with an eagle (the iconographic attribute that distinguishes John from the other evangelists) at his feet. The chromatic palette of warm earth tones, deep crimson, and pale grey against the rocky landscape and a low Mediterranean horizon is characteristic of Baldung's early-mature Strasbourg manner before the great Freiburg Cathedral high altarpiece commission of 1512–1516 that would establish his reputation as one of the leading Northern German painters of his generation."}
]$JSON$::jsonb
where slug in ('hans-baldung', 'hans-baldung-called-hans-baldung-grien');

-- ─── Albrecht Altdorfer ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-430111","paragraph":"The Beautiful Virgin of Regensburg, designed by Albrecht Altdorfer around 1519–1520 and engraved or woodcut for circulation in the German-speaking Catholic Counter-Reformation print market, depicts the Marian image associated with the great popular pilgrimage to Regensburg that began suddenly in 1519 after the destruction of the city's Jewish quarter and the construction of a chapel on the site dedicated to a miraculous statue of the Virgin. Altdorfer was the city architect of Regensburg at the time, and his print of the Beautiful Virgin (Schöne Maria) circulated widely through the German Catholic devotional market in the years immediately before the Reformation began to displace the Marian-pilgrimage tradition in Lutheran territories. The composition shows the Virgin in three-quarter view holding the Christ Child against her chest, surrounded by a luminous celestial light against a dark architectural niche."},
  {"artwork_slug":"met-395998","paragraph":"Abraham's Sacrifice, designed by Albrecht Altdorfer around 1480 (or, more likely, in the early sixteenth century — the dating of his prints is contested) and engraved by his workshop, illustrates the climactic moment of Genesis 22 in which the angel descends from heaven to stop Abraham from sacrificing his son Isaac on the altar at the top of Mount Moriah. Altdorfer stages the scene with characteristic Danube-school landscape density: the rocky mountain at the upper register, the small altar at the center where Isaac kneels bound, Abraham raising the knife on the right and looking up at the descending angel, the ram caught in the thicket in the lower-left foreground. The composition combines the Northern late-Gothic devotional sensibility with the new Renaissance landscape interest that defined Altdorfer's mature work and the Danube school more broadly."},
  {"artwork_slug":"met-429722","paragraph":"Christ on the Cross (The Small Crucifixion), designed by Albrecht Altdorfer in the early sixteenth century in his Regensburg workshop, is one of the small-format engraved Crucifixions Altdorfer produced for circulation in the German Catholic devotional print market. The composition shows the body of Christ on the cross at the center of the print, with the swooning Virgin in the arms of John on the left, the Magdalene kneeling at the foot of the cross, and a small landscape with the city of Jerusalem fading into the distant background. The chromatic-tonal range achieved by Altdorfer's careful crosshatching, even at the small format characteristic of devotional engraving, demonstrates the technical accomplishment that distinguished his prints from the broader run of late-medieval German engraving."},
  {"artwork_slug":"met-430047","paragraph":"Saint George Killing the Dragon, designed by Albrecht Altdorfer in the early sixteenth century in his Regensburg workshop, depicts the iconographic subject from the late-medieval Golden Legend tradition in which the Christian knight George rescues a princess from a dragon by piercing the creature with his lance. Altdorfer stages the scene in a dense forested German landscape — the mounted George on the left thrusts his lance down through the dragon's open mouth, the princess in the lower-right foreground kneels with her hands folded in prayer, the city in the deep distance fades into atmospheric haze through the trees. The combination of dense Northern forest landscape and dramatic chivalric narrative is the unmistakable Altdorfer signature, and the print is one of the principal small-format Saint George compositions of the early sixteenth century."}
]$JSON$::jsonb
where slug = 'albrecht-altdorfer';

-- ─── Giovanni di Paolo ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436509","paragraph":"The Adoration of the Magi, painted by Giovanni di Paolo around 1455 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the visit of the three kings to the infant Christ as recorded in Matthew 2. Giovanni di Paolo stages the scene with the unmistakable Sienese narrative density of his mature manner: the seated Virgin and the Christ Child on the right, the eldest king kneeling in profile in the foreground offering his gift, the second and third kings waiting their turn behind, a procession of attendants and horses winding through a craggy elongated Tuscan landscape that bends and twists with the visionary intensity that defined his entire style. The chromatic palette of jewel-bright crimson, ultramarine, and tooled gold is the unmistakable Sienese Quattrocento signature; the painting is one of the principal Giovanni di Paolo Adorations in any American collection."},
  {"artwork_slug":"met-458978","paragraph":"Coronation of the Virgin, painted by Giovanni di Paolo around 1452 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from the apocryphal Marian narrative in which Christ crowns his mother Queen of Heaven in the celestial court. Giovanni di Paolo composes the scene with the unmistakable Sienese vertical compositional intensity: Christ and the Virgin seated together at the upper center in a small architectural niche, surrounded by a tightly packed multi-tiered host of singing angels and ranked male and female saints in jewel-bright robes against a tooled-gold background. The chromatic palette and the visionary intensity of the composition — figures stretching, bending, and floating with an almost weightless grace — are the unmistakable Giovanni di Paolo signature and a defining example of his idiosyncratic Sienese Quattrocento style."},
  {"artwork_slug":"met-436513","paragraph":"The Presentation of Christ in the Temple, painted by Giovanni di Paolo around 1430 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 2 in which the infant Christ is brought to the Temple in Jerusalem on the fortieth day after his birth for the ritual of Mosaic purification. Giovanni di Paolo stages the scene in a small architectural setting with the Virgin handing the Christ Child to the aged Simeon, who stands at a small altar with the prophet Anna in the background; Joseph waits with the offering of the two doves at the lower right. The chromatic palette of warm pastel rose, mint-green, and tooled gold is characteristic of the early Giovanni di Paolo manner before the elongated visionary style of his mature work fully developed."},
  {"artwork_slug":"met-458972","paragraph":"Madonna and Child with Saints Jerome and Agnes, painted by Giovanni di Paolo around 1462 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small late sacra conversazione — the Italian Renaissance compositional type in which the Madonna sits enthroned with the Christ Child surrounded by attendant saints in a unified pictorial space. The Virgin sits in the center under a small architectural canopy with the Christ Child standing on her lap; Saint Jerome on the left holds a small model of his church, identifying him as one of the Latin Church Fathers who translated the Bible into Latin; Saint Agnes on the right holds a small lamb (the iconographic attribute that gives her name its Latin root). The chromatic palette and the visionary elongated proportions of the figures are the unmistakable late Giovanni di Paolo signature."}
]$JSON$::jsonb
where slug = 'giovanni-di-paolo-giovanni-di-paolo-di-grazia';
