-- Notable works (phase 4) — original-prose, single-paragraph essays for
-- the fourth tier of bio'd artists. Same conventions as 036 / 037 / 038:
-- each paragraph ~180–280 words, no double quotes inside the JSON, exact
-- slug matching, every artwork_slug verified against the live DB.

-- ─── Hugo van der Goes ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436523","paragraph":"The Adoration of the Magi, painted by Hugo van der Goes (or by his immediate workshop) around 1470 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the visit of the three kings to the infant Christ as recorded in Matthew 2. Van der Goes stages the scene in a dense vertical composition: the seated Virgin and the Christ Child in the lower foreground, the eldest king kneeling in profile offering his gift, the second and third kings standing behind him in formal attendance, the small thatched lean-to of Bethlehem rising behind. The chromatic palette of saturated crimson, ultramarine, gold, and warm flesh against the soft Northern landscape opening to a low horizon is the unmistakable Bruges-Ghent Early Netherlandish signature, and the elongated proportions and intense devotional faces show the Hugo van der Goes manner that the Portinari Altarpiece in the Uffizi (his masterpiece) would refine to its supreme statement a few years later. The panel is one of the principal works in the Hugo van der Goes circle in any American collection."}
]$JSON$::jsonb
where slug = 'hugo-van-der-goes';

-- ─── Joachim Patinir ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437261","paragraph":"The Penitence of Saint Jerome, painted by Joachim Patinir (or his workshop) around 1510 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the early Church Father in the conventional iconographic posture of his hermit years in the Syrian desert — half-naked, kneeling on his rocks, beating his breast with a stone in penitence — set against the panoramic landscape that defined Patinir's revolutionary contribution to Northern painting. Patinir is widely credited as the first European master to make landscape itself the primary subject of his pictures rather than a backdrop for narrative figures; the small saint in the foreground here is dwarfed by the vast craggy mountain panorama that fills the rest of the panel, with distant towns, rivers, and a pale luminous Flemish horizon receding into atmospheric haze. The chromatic palette of warm flesh, deep crimson, and the unmistakable Patinir blue-green of the distant landscape is the founding signature of what would become the Antwerp panoramic landscape tradition."}
]$JSON$::jsonb
where slug = 'joachim-patinir';

-- ─── Jan Luyken ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"jan-luyken-de-bergrede","paragraph":"De Bergrede (The Sermon on the Mount), etched by Jan Luyken around 1684 in his Amsterdam workshop and one of the small religious illustrations he produced for the Mennonite-publisher Jacobus van der Deyster, depicts the moment in Matthew 5 in which Christ delivers the Sermon on the Mount to the assembled crowd on a hillside above the Sea of Galilee. Luyken stages the scene as a quiet pastoral encounter — Christ seated on a low rock at the upper register of the composition, the assembled disciples and listeners gathered in a loose semicircle around him in postures of attentive listening, the Mediterranean landscape stretching behind under a soft midday sky. The composition demonstrates Luyken's characteristic restraint and his Mennonite-pietist preference for the legible, calm Gospel encounter over the dramatic Baroque action scene. The print circulated through Dutch Anabaptist devotional publishing throughout the late seventeenth and eighteenth centuries."},
  {"artwork_slug":"jan-luyken-bouw-van-de-ark-van-noach","paragraph":"Bouw van de ark van Noach (The Building of Noah's Ark), etched by Jan Luyken around 1688 in his Amsterdam workshop, illustrates the great pre-Flood project from Genesis 6 in which Noah and his sons construct the wooden ark to the divine specifications. Luyken stages the scene as a busy outdoor construction yard: the half-built ark rising in the upper register with workers crawling over its scaffolds, the timber being prepared and shaped in the lower foreground, Noah directing the work from the left foreground in patriarchal robes, his three sons with their hammers and adzes scattered across the working surfaces. The print was one of the standard plates in Luyken's prolific output of Old Testament illustrations and circulated through Dutch Mennonite and broader Protestant devotional publishing for several generations after its first appearance."},
  {"artwork_slug":"jan-luyken-aanbidding-door-de-herders","paragraph":"Aanbidding door de herders (Adoration of the Shepherds), etched by Jan Luyken around 1684 in his Amsterdam workshop, depicts the moment from Luke 2 in which the shepherds, having heard the angels' announcement of the birth of Christ, arrive at the small dwelling at Bethlehem to find the newborn child laid in the manger. Luyken stages the scene as a quiet nocturnal encounter inside the small thatched stable: the seated Virgin holding the swaddled Christ Child on her lap; Joseph waiting behind her with a small lantern; the three shepherds gathered in the foreground in postures of recognition and tender adoration. The composition demonstrates Luyken's characteristic Mennonite-pietist preference for the calm, almost domestic Gospel encounter. The print circulated through Dutch and broader Protestant illustrated-Bible publishing for over a century."},
  {"artwork_slug":"jan-luyken-de-zondvloed","paragraph":"De zondvloed (The Flood), etched by Jan Luyken around 1710 in his Amsterdam workshop in the late phase of his career, depicts the moment from Genesis 7 in which the waters of the Flood overwhelm the unrighteous and the Ark floats away across the rising sea. Luyken stages the scene with characteristic late-pietist restraint — the Ark visible as a small dark silhouette in the upper distance riding the storm waves, while the foreground shows the doomed pre-Flood humans clinging to small rocky outcrops with their families and animals as the water rises around them. The composition is among the most reproduced Luyken Old Testament illustrations and a defining statement of the late seventeenth and early eighteenth-century Dutch Mennonite preoccupation with the typological reading of the Old Testament narratives of judgment and salvation."}
]$JSON$::jsonb
where slug = 'jan-luyken';

-- ─── Wenceslaus Hollar ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-360736","paragraph":"Descent from the Cross, etched by Wenceslaus Hollar around 1640 in his middle career, depicts the moment after the Crucifixion in which the body of Christ is being lowered from the cross by Joseph of Arimathea and Nicodemus, with the Virgin and Mary Magdalene gathered at the foot of the cross to receive him. Hollar stages the scene with his characteristic patient observation and finely worked etched line — the body suspended in mid-descent, the white winding sheet draped to catch it, the gathered mourners in postures of restrained sorrow against a darkened landscape with the city of Jerusalem fading into the distant background. The print is one of the early Hollar treatments of a Passion subject in his English exile period and demonstrates the gentle atmospheric tone that characterized his entire religious printmaking output."},
  {"artwork_slug":"met-360830","paragraph":"Crucifixion, etched by Wenceslaus Hollar around 1644 as one of the plates of his great Passion series produced during his Antwerp exile years (when the English Civil War interrupted his London career), depicts the moment of Christ's death on the cross. Hollar stages the scene with characteristic Bohemian-into-English topographical care: the cross at the upper center against a darkening sky; the swooning Virgin in the arms of John on the left; the Magdalene clinging to the foot of the cross; the centurion on horseback in the foreground recognizing the divinity of the dying Christ; the two thieves still alive on their crosses to either side. The Antwerp Passion series circulated widely through both the Catholic Spanish Netherlands and the Protestant English-speaking print market and was reprinted in editions for a century and a half after its first publication."},
  {"artwork_slug":"met-360832","paragraph":"Descent into Hell (The Harrowing of Hell), etched by Wenceslaus Hollar around 1644 as one of the plates of his Antwerp Passion series, illustrates the apocryphal Harrowing of Hell — the tradition that Christ between his death on Friday and his Resurrection on Sunday descended into the underworld to free the souls of the just who had died before his Incarnation. Hollar stages the scene with Bohemian late-Northern-Renaissance density: Christ steps out of the great open mouth of hell at the lower right with his banner of Resurrection raised, while Adam, Eve, and the patriarchs emerge from behind him into the upper light; the rest of the print is filled with the small writhing figures of the still-damned and the demons who guard them. The print circulated through both the Catholic and Protestant publishing networks throughout the seventeenth century."},
  {"artwork_slug":"met-360829","paragraph":"Carrying the Cross, etched by Wenceslaus Hollar around 1644 as one of the plates of his Antwerp Passion series, depicts the moment from the Synoptic Gospels in which Christ, after the scourging and the crowning with thorns, carries his cross through the streets of Jerusalem on the way to Golgotha. Hollar stages the scene with characteristic crowded Northern composition: Christ in the center stumbling under the weight of the cross, Simon of Cyrene reaching to take a portion of the burden from his shoulders, the Roman soldiers driving him forward with whips, the women of Jerusalem watching from the sides with expressions of grief. The print circulated through the Antwerp and London markets in editions for over a century and was widely reproduced in seventeenth and eighteenth-century English Protestant devotional materials."}
]$JSON$::jsonb
where slug = 'wenceslaus-hollar';

-- ─── Castiglione (Il Grechetto) ────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-335665","paragraph":"Noah Entering the Ark, etched by Giovanni Benedetto Castiglione around 1655 (the dating of his prints is somewhat contested) and now in the Metropolitan Museum of Art in New York, illustrates the moment from Genesis 7 in which the patriarch Noah leads his family and the pairs of animals into the Ark before the great Flood. Castiglione composes the scene as a panoramic procession: Noah and his family in the foreground leading a long winding line of cattle, sheep, dogs, camels, horses, and exotic animals across an Italianate landscape toward the great wooden vessel waiting on the right side of the print. The composition demonstrates Castiglione's signature combination of pastoral biblical narrative and his lifelong fascination with the painting of livestock — the genre at which he excelled above any other Italian artist of the seventeenth century. The print is among the most reproduced of his etched Genesis cycle."},
  {"artwork_slug":"met-393211","paragraph":"Noah Letting the Animals into the Ark, drawn by Giovanni Benedetto Castiglione around 1625 in oil on paper (a medium Castiglione largely invented and made his own) and now in the Metropolitan Museum of Art in New York, is a large autonomous brush-drawing of one of his favorite Old Testament subjects. The composition shows the Ark on the right side of the sheet with Noah waiting at the gangway, while the long line of animals winds across the foreground and the background — cattle, horses, lions, dogs, sheep, exotic birds — each rendered with the characteristic Castiglione fascination with animal anatomy and texture. The technique — oil paint applied with the brush directly onto blue or buff prepared paper — was Castiglione's principal contribution to the seventeenth-century drawing tradition and the immediate ancestor of the eighteenth-century brush-drawing technique that Tiepolo and Boucher would develop."},
  {"artwork_slug":"met-647338","paragraph":"Saint Francis in Ecstasy, drawn by Giovanni Benedetto Castiglione around 1645 in oil on prepared paper and now in the Metropolitan Museum of Art in New York, depicts the medieval Italian Franciscan saint in the moment of his receiving the stigmata on Mount La Verna in 1224. Castiglione stages the scene as a vertical mystical encounter: the saint kneels in profile in the lower left, his arms outstretched, his face lifted in ecstasy toward the upper-right where the seraphic vision of the wounded Christ appears in a luminous burst of light, the wounds of the stigmata rendered as small lines of golden energy descending toward the saint's hands and side. The drawing is among the principal late-Castiglione brush-drawings on the Saint Francis subject and a defining example of the painter's brushed-oil technique at full mature statement."},
  {"artwork_slug":"met-335670","paragraph":"Raising of Lazarus, etched by Giovanni Benedetto Castiglione around 1645 and now in the Metropolitan Museum of Art in New York, illustrates the climactic miracle of John 11. Castiglione composes the scene with characteristic dramatic compositional density: Christ at the lower left with his right arm extended in command, the bound figure of Lazarus emerging upright from the open tomb at the upper right, the sisters Martha and Mary kneeling between them at Christ's feet, and a small crowd of witnesses gathered behind. The print demonstrates Castiglione's mature etching technique — long swelling lines, dense crosshatched shadow, and the characteristic Italianate landscape that fills the background — and is one of the principal Castiglione religious etchings in any American collection."}
]$JSON$::jsonb
where slug = 'giovanni-benedetto-castiglione-il-grechetto';

-- ─── Del Parson ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"gab-jesus-the-christ-74e791b","paragraph":"Jesus the Christ (often known by the title Christ in a Red Robe or simply Portrait of Christ) is among the most reproduced devotional images by any twentieth-century American religious painter. Painted by Del Parson in the early 1980s, the painting depicts Christ in three-quarter view against a soft luminous ground — a calm, soft-bearded, gentle-faced figure with brown hair falling past the shoulders, dressed in a deep crimson robe under a soft white inner garment. Distributed by the Church of Jesus Christ of Latter-day Saints in Sunday-school manuals, missionary materials, devotional booklets, and chapel prints from the 1980s onward, the image has been reproduced in millions of copies across the English-speaking and Spanish-speaking Latter-day Saint world and is widely recognized far beyond Latter-day Saint circles as one of the most familiar twentieth-century portraits of Jesus."},
  {"artwork_slug":"gab-jesus-at-the-door-jesus-knocking-at-the-door-342168c","paragraph":"Jesus at the Door (also called Jesus Knocking at the Door), painted by Del Parson in the late twentieth century in oil on canvas and reproduced widely through the devotional publishing network of the Church of Jesus Christ of Latter-day Saints, depicts the iconographic image of Christ as the figure described in Revelation 3:20 — Behold, I stand at the door, and knock. Parson shows Christ standing on a small stone step before a closed wooden door, his hand raised to knock, a soft inner light around the figure illuminating the otherwise dark approach. The composition follows the Holman Hunt Light of the World tradition of the late nineteenth century but is rendered in Parson's characteristic late-twentieth-century soft-academic style. The painting is among the most reproduced of his religious works in Latter-day Saint devotional materials."},
  {"artwork_slug":"gab-the-good-samaritan-8ba875b","paragraph":"The Good Samaritan, painted by Del Parson in the late twentieth century in oil on canvas and distributed by the Church of Jesus Christ of Latter-day Saints in Sunday-school manuals and devotional materials, depicts the climactic scene of the parable from Luke 10. Parson stages the scene at the side of the road from Jerusalem to Jericho: the wounded man lies on the dusty ground in the foreground, the Samaritan kneels beside him in the act of binding the wounds with cloth from his own pack, while in the deep background the priest and the Levite who had passed by on the other side are still visible as small figures continuing their journey. The composition follows Parson's characteristic combination of warm chromatic palette and clear narrative organization that has made his parable illustrations a standard feature of late-twentieth-century Latter-day Saint Sunday-school materials."},
  {"artwork_slug":"gab-christ-healing-a-blind-man-cf7a7bc","paragraph":"Christ Healing a Blind Man, painted by Del Parson in the late twentieth century in oil on canvas and distributed by the Church of Jesus Christ of Latter-day Saints in Sunday-school manuals and devotional materials, depicts the moment from John 9 in which Christ restores sight to the man born blind. Parson stages the scene as a tender outdoor encounter: the seated blind man on the right with his hands raised toward the kneeling Christ on the left who reaches gently to apply the moistened clay to the man's eyes, with a small group of curious onlookers gathered around them in the background. The composition is one of the standard Parson Gospel-narrative illustrations used in Latter-day Saint Sunday-school curricula across the late twentieth and early twenty-first centuries."},
  {"artwork_slug":"gab-mary-and-martha-635a535","paragraph":"Mary and Martha, painted by Del Parson in the late twentieth century in oil on canvas and distributed by the Church of Jesus Christ of Latter-day Saints in Sunday-school manuals and devotional materials, depicts the moment from Luke 10 in which Christ visits the home of the two sisters and gently corrects the busy, complaining Martha by commending the listening Mary who has chosen the better part. Parson stages the scene in the small interior of a first-century Judean home: Christ seated on the right with Mary at his feet listening intently, while Martha approaches from the left from the kitchen door with a tray and a careworn expression, in the act of voicing her complaint. The composition is among the standard Parson Gospel-narrative illustrations in Latter-day Saint Sunday-school curricula."}
]$JSON$::jsonb
where slug = 'del-parson';

-- ─── Hans Schäufelein ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-666121","paragraph":"The Crucifixion, from Der beschlossen gart des rosenkranz Marie (The Closed Garden of Mary's Rosary), woodcut designed by Hans Schäufelein around 1505 for the Nuremberg printer Hans Beck, illustrates the moment of Christ's death on the cross with his customary careful Northern late-Gothic narrative density. The composition shows the body of Christ on the cross at the upper center against a darkening sky, with the swooning Virgin in the arms of John on the left, the Magdalene kneeling at the foot of the cross, the centurion on horseback recognizing the divinity of the dying Christ, and the two thieves still alive on their crosses to either side. The print belonged to the great illustrated rosary devotional book of 1505 — a Catholic spiritual handbook structured around the meditations of the rosary cycle — that Schäufelein illustrated almost in its entirety. The book is one of the principal pre-Reformation German illustrated devotional volumes."},
  {"artwork_slug":"met-666029","paragraph":"The Last Judgment, from Speculum passionis domini nostri Jesu Christi (The Mirror of the Passion of Our Lord Jesus Christ), woodcut designed by Hans Schäufelein in 1507 for the Nuremberg printer Ulrich Pinder, depicts the eschatological subject of the Second Coming and the final judgment. Schäufelein stages the scene with characteristic Nuremberg-Augsburg compositional density: Christ enthroned in glory at the upper center within a great mandorla, the apostles ranged around him, the resurrected dead emerging from open graves below, the elect being led toward heaven on the left, and the damned tumbling into a Bosch-influenced flaming hell on the right. The Speculum passionis was one of the principal illustrated devotional books of the early sixteenth century, and Schäufelein's woodcuts for it remain among the most accomplished works of his early career under Albrecht Dürer's general direction in the Nuremberg workshop."},
  {"artwork_slug":"met-441672","paragraph":"The Dormition of the Virgin (with the Carrying of the Cross on the reverse), woodcut designed by Hans Schäufelein around 1505 in his Nuremberg years and now in the Metropolitan Museum of Art in New York, depicts the moment from the apocryphal Marian narrative in which the Virgin Mary, dying in her old age, is attended on her deathbed by the assembled apostles. Schäufelein composes the scene in a small interior chamber: the Virgin lies in the bed at the lower center, the apostles gather around her in dense devotional postures of grief and prayer, with Peter (identified by the pyx of the Eucharist in his hand) at the foot of the bed and John (the youngest apostle) kneeling at the head. The reverse of the woodblock — Christ Carrying the Cross — was printed on the back of the same sheet, an unusual two-sided format that suggests a specifically devotional rather than commercial use."}
]$JSON$::jsonb
where slug = 'hans-sch-ufelein';

-- ─── Hieronymus Wierix ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-360405","paragraph":"The Annunciation (Humilis), engraved by Hieronymus Wierix around 1545 in his Antwerp workshop, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin Mary in her chamber to announce the conception of Christ. The Latin word Humilis (lowly, humble) inscribed at the foot of the print is the title of the iconographic series in which this plate belongs — a small set of devotional engravings emphasizing the Marian virtue of humility. Wierix composes the scene with characteristic Counter-Reformation Antwerp restraint: the Virgin kneels at her prayer-desk on the right, the angel kneels on the left with the lily of purity in one hand, the Holy Spirit descends as a small dove on a beam of golden light from the upper left. The print circulated through the Antwerp Jesuit publishing network in editions across the late sixteenth and seventeenth centuries."},
  {"artwork_slug":"met-360395","paragraph":"Christ's Robe Surrounded by the Instruments of the Passion, engraved by Hieronymus Wierix around 1560 in his Antwerp workshop, depicts the iconographic subject of the Arma Christi — the so-called instruments of the Passion — arranged around the central seamless robe of Christ that the Roman soldiers cast lots for at the foot of the cross. Wierix arranges the symbols (the cross, the nails, the crown of thorns, the spear, the sponge, the dice, the rooster, the column of the scourging, the ladder, the scourges) in formal symmetry around the central garment, with attendant angels in the corners holding small banners with Latin inscriptions. The Arma Christi devotion was a particular preoccupation of late-medieval and Counter-Reformation Catholic spirituality, and the Wierix engravings of the subject circulated through Catholic devotional publishing for over a century."},
  {"artwork_slug":"met-361854","paragraph":"Christ Praying in the Garden on the Mount of Olives, engraved by Hieronymus Wierix around 1560 in his Antwerp workshop, depicts the Agony in the Garden as recorded in the Synoptic Gospels: Christ kneels in prayer before the angel bearing the cup of the Passion, while the three sleeping disciples — Peter, James, and John — are gathered in the foreground and Judas with the Roman soldiers approach through the garden gate at the rear. Wierix stages the scene with characteristic Antwerp Counter-Reformation devotional restraint: the figures are clearly drawn and emotionally legible without dramatic Mannerist exaggeration, the composition is built on a strong vertical axis from the kneeling Christ to the descending angel, and the chromatic-tonal range is achieved entirely through the tightly cross-hatched engraved line. The print circulated through Catholic devotional publishing networks across Europe and the Spanish overseas missions."}
]$JSON$::jsonb
where slug = 'hieronymus-jerome-wierix';

-- ─── Marcantonio Raimondi ──────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-368552","paragraph":"The Virgin and the Young Christ, engraved by Marcantonio Raimondi around 1475 (early in his career, before his move to Rome and the great partnership with Raphael) in his Bolognese workshop, depicts the standard small-format Madonna and Child compositional type that Raimondi's Bolognese teacher Francesco Francia had refined to a high pitch of devotional sweetness. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; the chromatic-tonal range is achieved entirely through the tightly cross-hatched engraved line characteristic of late-Quattrocento Italian engraving. The print is among the early Raimondi treatments of a Marian subject and demonstrates the Bolognese workshop discipline he carried forward into the Roman years that would eventually make him the principal engraver of Raphael's compositions."},
  {"artwork_slug":"met-342711","paragraph":"The Expulsion from Paradise, from the Piccoli Santi (Small Saints) series engraved by Marcantonio Raimondi around 1495 in his early Bolognese workshop years, illustrates the climactic moment of Genesis 3 in which the angel with the flaming sword drives Adam and Eve from the Garden of Eden after the Fall. Raimondi composes the scene as a small vertical print with Adam and Eve in profile fleeing toward the lower right, the angel with the sword extended above them in the upper register, the gates of Eden visible behind. The print is among the early Raimondi treatments of a Genesis subject and demonstrates the small-format devotional engraving manner of the late Quattrocento Bolognese workshop tradition before his transformative encounter with Raphael in Rome around 1510."},
  {"artwork_slug":"met-342580","paragraph":"Saint Catherine Standing in a Niche, Resting on a Wheel, from the Piccoli Santi (Small Saints) series engraved by Marcantonio Raimondi around 1495 in his early Bolognese workshop years, depicts the legendary fourth-century Christian martyr in her conventional iconographic posture — standing in a small architectural niche with her hand resting on the wheel of her martyrdom (the wheel from which she escaped through divine intervention before her eventual beheading). The Piccoli Santi series was a small set of devotional engravings of individual saints standing in architectural niches; the format derived from the late-medieval Northern engraving tradition and was a standard Italian Quattrocento engraving genre. The print is among the early Raimondi treatments of a saint subject and an example of his Bolognese workshop discipline before Rome and Raphael."}
]$JSON$::jsonb
where slug = 'marcantonio-raimondi';

-- ─── Hans Burgkmair ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-336204","paragraph":"Saint George on Horseback, woodcut designed by Hans Burgkmair in 1508 in his Augsburg workshop, depicts the iconographic subject from the late-medieval Golden Legend tradition in which the Christian knight George rescues a princess from a dragon by piercing the creature with his lance. Burgkmair stages the scene as a vertical heraldic composition: the mounted George at the upper center in full armor, his lance thrust down through the dragon's open mouth, his horse rearing, the princess in the lower-left foreground in posture of grateful recognition. The print was one of the first chiaroscuro woodcuts produced in Germany — a printed image that combined a black line block with one or two flat tone blocks printed over it in flat color, producing what we now call a tone-print. Burgkmair's chiaroscuro Saint George is one of the foundational documents of the entire chiaroscuro woodcut tradition."},
  {"artwork_slug":"met-430685","paragraph":"The Head of Christ Crowned with Thorns, designed by Hans Burgkmair around 1498 in his early Augsburg workshop, depicts the iconographic subject of the Vir Dolorum (Man of Sorrows) — the close-cropped head of the suffering Christ presented as an autonomous devotional image for personal contemplation. Burgkmair shows the head in three-quarter view against a darkened ground, the crown of thorns pressed down on the brow, drops of blood running down the face from the puncture wounds, the eyes lowered in the attitude of inward suffering. The Vir Dolorum subject was one of the standard late-medieval and early-Renaissance Northern devotional types, intended for meditation on the Passion as a continuing personal encounter; Burgkmair's print circulated through the German-speaking Catholic devotional publishing market in editions for several decades after its first appearance."},
  {"artwork_slug":"met-384448","paragraph":"Saint Luke Painting the Virgin, woodcut designed by Hans Burgkmair around 1507 in his Augsburg workshop, depicts the iconographic subject from the medieval Golden Legend tradition in which the evangelist Luke — said to have been a painter as well as a Gospel writer — is shown painting a portrait of the Virgin Mary while she sits patiently with the Christ Child on her lap. Burgkmair stages the scene in a small Renaissance interior: the Virgin and Child seated at the right under a small architectural canopy, Luke seated in the center at his easel in the act of painting, with his attribute (the ox associated with him as the second of the four evangelists) at his feet. The composition was a particular favorite of late-medieval and Renaissance European painters' guilds, who took Luke as their patron saint."}
]$JSON$::jsonb
where slug = 'hans-burgkmair';

-- ─── Parmigianino ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-391601","paragraph":"Resurrection, etched by Parmigianino around 1515 (early in his career, in his pre-Roman Parma years) and now in the Metropolitan Museum of Art in New York, is one of the early prints by the artist who is widely credited as the introducer of etching as a serious artist's medium in Italy. The composition shows Christ rising from the open tomb in the predawn light, his right arm raised in benediction, his banner of Resurrection in his left hand, while the Roman soldiers below are scattered across the foreground in poses of unconscious sleep or panicked awakening. The technique — soft, almost drawn-in-the-air lines achieved through Parmigianino's own version of the etching needle and ground — gave the print a delicate atmospheric quality unmatched in contemporary Italian engraving. The print circulated through European print collections in editions for over a century after his early death."},
  {"artwork_slug":"met-391588","paragraph":"Entombment, etched by Parmigianino around 1520 in his late Parma years immediately before his move to Rome, depicts the moment after the Deposition in which the body of Christ is being carried by the mourners to the rock-cut tomb. Parmigianino stages the scene as a dense vertical composition: the body of Christ supported by Joseph of Arimathea and Nicodemus in the foreground, the swooning Virgin in the arms of John behind, the Magdalene kneeling at the feet, with the small landscape and the tomb opening visible in the deeper background. The etched line is the unmistakable Parmigianino signature — soft, swelling, almost drawn — and the elongated proportions and serpentine figural torsion already anticipate the Mannerist intensities of his great Roman and Bolognese paintings of the next decade."},
  {"artwork_slug":"met-366523","paragraph":"Saints Peter and John Healing the Cripples at the Gate of the Temple, drawn by Parmigianino around 1503 (early in his career, in his Parma workshop years) in pen and ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the episode from Acts 3 in which the apostles Peter and John, going up to the Temple at the hour of prayer, encounter and heal a man lame from birth who had been laid daily at the gate to ask alms. Parmigianino stages the scene as a small dense narrative encounter outside the Temple: Peter on the left with his right arm extended in command, the lame man in the foreground in the act of rising to his feet, John behind Peter watching, with a small crowd of onlookers gathered around. The drawing demonstrates the early Parmigianino draughtsmanship that the Roman years would refine to its supreme statement."}
]$JSON$::jsonb
where slug = 'parmigianino-girolamo-francesco-maria-mazzola';

-- ─── Gerard David ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436100","paragraph":"The Nativity, painted by Gerard David around 1480 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of the birth of Christ in the small dwelling at Bethlehem. David stages the scene with characteristic Bruges Early Netherlandish patience: the Virgin kneels in profile with her hands folded in adoration before the newborn Christ Child laid on her cloak in the foreground; Joseph stands at the back of the small thatched stable with a candle illuminating the Christ Child's face; the ox and the ass occupy the rear of the room; small angels descend from the upper-right with banners of greeting. The chromatic palette of saturated crimson, ultramarine, gold, and warm flesh against the soft Northern landscape opening to a low horizon is the unmistakable Gerard David signature."},
  {"artwork_slug":"met-436102","paragraph":"Virgin and Child with Four Angels, painted by Gerard David around 1510 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the enthroned Virgin and Christ Child attended by four small music-making angels. David stages the scene in a small architectural interior: the Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; two angels lean in at her shoulders to crown her with a small wreath, while two more angels in the foreground play the lute and the small portative organ. The chromatic palette of deep ultramarine, soft rose, and warm flesh against the dark architectural background is the unmistakable late-Bruges Early Netherlandish signature, and the soft observation of textiles and small surface details is characteristic of David's mature manner."},
  {"artwork_slug":"met-436104","paragraph":"The Adoration of the Magi, painted by Gerard David and his workshop around 1515 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the visit of the three kings to the infant Christ in the small dwelling at Bethlehem. David stages the scene with characteristic Bruges compositional restraint: the seated Virgin holds the Christ Child upright on her lap on the right; the eldest king kneels in profile in the foreground offering his gift; the second and third kings stand behind in formal attendance; the ox and the ass occupy the rear of the small dwelling, and a small landscape with the Magi's traveling retinue is visible through a window in the deeper background. The painting is among the principal late Gerard David Adorations in any American collection."},
  {"artwork_slug":"met-436101","paragraph":"The Rest on the Flight into Egypt, painted by Gerard David around 1512 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Holy Family pausing in their flight from Herod's persecution as recorded in Matthew 2. David stages the scene in a quiet Northern landscape: the Virgin sits in profile in the foreground with the Christ Child on her lap, peeling fruit for him; Joseph waits in the background by a small donkey; a small landscape opens to a low horizon behind. The composition is among the most reproduced of David's small devotional panels and a defining example of the Bruges Early Netherlandish workshop tradition that turned the Rest on the Flight subject into a particular specialty for private devotional commissions."}
]$JSON$::jsonb
where slug = 'gerard-david';

-- ─── Antonio Tempesta ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-400876","paragraph":"The Flight into Egypt, etched by Antonio Tempesta around 1555 in his Florentine workshop years before his move to Rome, depicts the apocryphal subject of the Holy Family fleeing from King Herod's persecution as recorded in Matthew 2. Tempesta stages the scene as a panoramic landscape with the Virgin riding on the small donkey holding the Christ Child, Joseph leading the donkey on foot, and a small attending angel guiding them along a winding road through an Italianate countryside with hills, distant towns, and small grazing animals. The print belongs to the prolific output of single-leaf religious etchings Tempesta produced for the Italian and broader European devotional print market and is one of the standard small-format treatments of the subject in late sixteenth-century Italian printmaking."},
  {"artwork_slug":"met-401297","paragraph":"Plate 3, Abraham Taking Lot and His Family to His Tents (from The Battles of the Old Testament), etched by Antonio Tempesta around 1585 in his Roman workshop, illustrates an early episode from the Genesis narratives in which Abraham receives his nephew Lot and Lot's family at his encampment. Tempesta stages the scene as a panoramic landscape encounter: Abraham at the lower right greeting the arriving party, Lot and his family in formal procession with their flocks and possessions, the encampment of tents in the deeper background, and a sweeping landscape of hills and distant towns. The plate belongs to the great Tempesta series of Old Testament battle and patriarchal scenes that circulated as small-format engraved Bibles and as standalone prints throughout the Catholic European publishing market for over a century."},
  {"artwork_slug":"met-401303","paragraph":"Plate 8, The Egyptians Drowning in the Red Sea (from The Battles of the Old Testament), etched by Antonio Tempesta around 1585 in his Roman workshop, illustrates the climactic moment of Exodus 14 in which the Lord brings the waters back over the pursuing Egyptian army after the Israelites have crossed the dry sea floor. Tempesta stages the scene with characteristic dramatic compositional density: the Israelites visible on the far shore in the upper register, the closing wall of the sea in the upper-center crashing back across the trapped Egyptian army of horse and chariot in the lower register, with Moses on the Israelite shore raising his rod in the act of commanding the waters. The print is among the most reproduced of the great Tempesta Old Testament battle series."},
  {"artwork_slug":"met-401344","paragraph":"Plate 23, Judith and Holofernes (from The Battles of the Old Testament), etched by Antonio Tempesta around 1585 in his Roman workshop, illustrates the climactic moment of the deuterocanonical Book of Judith in which the young Hebrew widow saws through the neck of the drunken Assyrian general in his command tent. Tempesta stages the act with characteristic dense narrative composition: Judith standing over the bed in the act of beheading, the elderly servant Abra holding open the linen sack to receive the head, the body of Holofernes sprawled across the bed, and the small Assyrian camp visible in the distant background outside the tent. The plate belongs to the great series of Old Testament narratives Tempesta produced in Rome through the 1580s and 1590s, prints that circulated through European Catholic publishing networks for over a century."}
]$JSON$::jsonb
where slug = 'antonio-tempesta';

-- ─── Adriaen Collaert ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"adriaen-collaert-bergrede","paragraph":"Bergrede (The Sermon on the Mount), engraved by Adriaen Collaert around 1580 in his Antwerp workshop and printed by his stepfather-in-law Philip Galle, depicts the moment in Matthew 5 in which Christ delivers the Sermon on the Mount to the assembled disciples and crowds on a hillside above the Sea of Galilee. Collaert stages the scene as a panoramic outdoor encounter — Christ seated on a low rock at the center of the composition, the assembled listeners gathered around him in a loose semicircle in the foreground, the Mediterranean landscape with distant towns and a soft horizon stretching behind. The engraved line is patiently crosshatched in the standard Antwerp post-Tridentine devotional manner, and the print circulated through the Hispano-Flemish trading network from Antwerp to Spain, the German-speaking lands, and the Spanish overseas missions for over a century."},
  {"artwork_slug":"adriaen-collaert-bruiloft-te-kana","paragraph":"Bruiloft te Kana (The Marriage at Cana), engraved by Adriaen Collaert around 1580 in his Antwerp workshop, illustrates the first public miracle of Christ as recorded in John 2: the conversion of water into wine at the wedding feast in Cana of Galilee. Collaert composes the scene as a long horizontal banquet — the bride and groom seated under a baldachin at the right, Christ and the Virgin and the disciples ranged along the left, the master of the feast tasting from one of the six enormous stone jars in the center, an attendant pouring fresh water into another jar at the moment of the miracle. The print belongs to the great Collaert Life of Christ engraved cycles that supplied the Counter-Reformation Antwerp devotional market for several generations."},
  {"artwork_slug":"adriaen-collaert-opstanding","paragraph":"Opstanding (The Resurrection), engraved by Adriaen Collaert around 1580 in his Antwerp workshop, depicts the moment of the Resurrection: Christ rises from the open tomb in the predawn light, his right arm raised in benediction, his banner of Resurrection in his left hand, while the Roman soldiers below are scattered across the foreground in poses of unconscious sleep or panicked awakening. The engraved line is patiently crosshatched in the characteristic post-Tridentine Antwerp manner; the composition belongs to the long sequence of Life of Christ Easter-cycle engravings that Collaert and his Antwerp workshop produced throughout the late sixteenth and early seventeenth centuries for distribution across the Catholic publishing world."},
  {"artwork_slug":"adriaen-collaert-voetwassing","paragraph":"Voetwassing (The Washing of Feet), engraved by Adriaen Collaert around 1570 in his early Antwerp workshop years, illustrates the moment from John 13 at the Last Supper at which Christ washes the feet of the disciples — the symbolic act of humility that institutes the practice of foot-washing in subsequent Christian liturgy. Collaert stages the scene with Antwerp post-Tridentine devotional restraint: Christ kneels in profile before Peter at the center of the composition, washing the apostle's foot in a small basin while Peter gestures in protest; the other apostles are ranged around them in a loose semicircle, untying their sandals or watching in attentive silence. The print belongs to the long sequence of Life of Christ engravings Collaert produced for the Antwerp Counter-Reformation devotional market."}
]$JSON$::jsonb
where slug = 'adriaen-collaert';

-- ─── Israhel van Meckenem ──────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-636600","paragraph":"The Betrayal and Capture of Christ, engraved by Israhel van Meckenem around 1480 in his Bocholt workshop, depicts the moment of the arrest in Gethsemane: Judas embraces Christ in the kiss of betrayal at the center of the composition while the Roman soldiers crowd in with raised lances and torches; Peter on the left side cuts off the ear of the high priest's servant Malchus; the disciples scatter in the background. Meckenem composes the scene with characteristic late-fifteenth-century Northern engraving density — figures piled into the available space with little atmospheric distance — and the careful crosshatched line gives the print the small-format devotional clarity that defined Meckenem's vast output. The print belongs to the great Passion cycle Meckenem produced in multiple editions across his career and is one of the principal Northern engraved Betrayal compositions of the entire fifteenth century."},
  {"artwork_slug":"met-363179","paragraph":"The Resurrection, engraved by Israhel van Meckenem around 1480 in his Bocholt workshop, depicts the moment of the Resurrection: Christ rises from the open stone sarcophagus in the predawn light, his right arm raised in benediction, his banner of Resurrection in his left hand, while the Roman soldiers below are scattered around the tomb in poses of unconscious sleep or panicked awakening. Meckenem composes the scene with characteristic late-fifteenth-century Northern density: the figures crowded into the small space, the architectural elements of the tomb carefully detailed, the carefully crosshatched engraved line giving the print its small-format devotional clarity. The print belongs to the Passion cycle Meckenem produced in multiple editions throughout his career and was reprinted and copied across the late fifteenth and early sixteenth centuries."},
  {"artwork_slug":"met-636651","paragraph":"The Annunciation, from The Life of the Virgin series engraved by Israhel van Meckenem around 1490 in his Bocholt workshop, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin Mary in her chamber to announce the conception of Christ. Meckenem composes the scene in a small late-medieval interior: the Virgin kneels at her prayer-desk on the right, the angel kneels on the left with the lily of purity in one hand and the banner of greeting in the other, the Holy Spirit descends as a small dove on a beam of golden light. The print belongs to the Life of the Virgin series — one of the standard late-fifteenth-century Northern engraved devotional cycles — and circulated through the Bocholt workshop's distribution network throughout the German-speaking and Low Countries devotional market."}
]$JSON$::jsonb
where slug = 'israhel-van-meckenem';

-- ─── Sebald Beham ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-334794","paragraph":"The Circumcision of Christ, engraved by Sebald Beham around 1510 in his early Nuremberg workshop years, depicts the moment from Luke 2 in which the infant Christ is brought to the Temple eight days after his birth for the ritual of circumcision required by the Mosaic law. Beham composes the scene with characteristic German Little Master density — the entire narrative compressed into a small print suitable for binding into prayer books or distribution at confraternity meetings. The priest stands at the small stone altar at the center holding the small instrument of circumcision; the Virgin stands behind on the right with her hands folded in attendance; Joseph waits at the back with the offering of the two doves required by the Mosaic law. The print belongs to the small-format devotional output of the Beham Nuremberg workshop in the years immediately before the 1525 banishment of the Beham brothers from the city for radical Protestant beliefs."},
  {"artwork_slug":"met-334783","paragraph":"The Return of the Prodigal Son, engraved by Sebald Beham around 1540 in his Frankfurt workshop years, illustrates the climactic moment of the Luke 15 parable: the father runs to embrace his returning son who, having squandered his inheritance, has returned home to throw himself at his father's feet. Beham stages the scene as a small intimate vertical composition: the kneeling son in the foreground embraced by the standing father, the elder brother visible in the deeper background tending the flocks, the fatted calf being prepared for the celebratory meal at the upper left. The print belongs to the great Beham series of small-format Old and New Testament narratives produced in Frankfurt across the 1530s and 1540s for the German Reformation publishing market."},
  {"artwork_slug":"met-334784","paragraph":"The Presentation of the Infant Jesus in the Temple, engraved by Sebald Beham around 1520 in his Nuremberg workshop years, depicts the moment from Luke 2 in which the infant Christ is brought to the Temple in Jerusalem on the fortieth day after his birth for the ritual of Mosaic purification. Beham composes the scene in a small architectural setting with characteristic German Little Master compression: the Virgin handing the Christ Child to the aged Simeon at the small stone altar, the prophet Anna in the background, Joseph at the lower right with the offering of the two doves required by the Mosaic law. The print belongs to the small-format Life of Christ devotional output of the Beham Nuremberg workshop, immediately before the 1525 trial of the Beham brothers and Georg Pencz for radical Protestant beliefs forced their temporary exile from the city."}
]$JSON$::jsonb
where slug = 'sebald-beham';

-- ─── Heinrich Aldegrever ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340674","paragraph":"Joseph and Potiphar's Wife, from The Story of Joseph series engraved by Heinrich Aldegrever in 1532 in his Soest workshop, illustrates the dramatic moment from Genesis 39 in which Potiphar's wife seizes Joseph by his garment and attempts to seduce him; he flees, leaving the garment in her hand. Aldegrever stages the scene in a small bedchamber with characteristic German Little Master density: the seated Potiphar's wife in the foreground reaching out to seize the fleeing Joseph by his cloak, Joseph already half-out of the door at the upper right with his head turned in alarm, the small interior of the room carefully detailed with wooden bedposts, embroidered cushions, and a Renaissance window. The Story of Joseph series — twelve plates illustrating the entire Joseph narrative from Genesis 37 through Genesis 47 — was one of the most reproduced of Aldegrever's Old Testament cycles and circulated through the German-speaking Reformation publishing market."},
  {"artwork_slug":"met-428383","paragraph":"Saint John, from The Four Evangelists series engraved by Heinrich Aldegrever in 1539 in his Soest workshop, depicts the youngest of the four Gospel writers seated in his characteristic posture of inspired authorship — pen in hand over an open book, his head lifted in attention to the divine revelation, his attribute (the eagle, the second of the four creatures of Revelation 4) at his feet. The Four Evangelists series — small-format individual portraits of Matthew, Mark, Luke, and John — was one of the standard German Little Master devotional cycles, used as decorative components in Lutheran prayer books, devotional pamphlets, and bound illustrated Bibles throughout the German-speaking Reformation publishing market in the second quarter of the sixteenth century."},
  {"artwork_slug":"met-428012","paragraph":"The Virgin and Child on a Crescent Moon, engraved by Heinrich Aldegrever around 1553 in his late Soest workshop years, depicts the iconographic subject of the Virgin standing on the crescent moon and surrounded by a luminous mandorla — the visual treatment derived from the woman of the Apocalypse described in Revelation 12 and the Catholic doctrine of the Immaculate Conception that the late-medieval and early-Renaissance Northern devotional tradition associated with it. Aldegrever stages the scene in his characteristic German Little Master format: the standing Virgin in the center holding the Christ Child, surrounded by a circle of small attendant cherubs against a luminous background. The print belongs to the late Aldegrever Marian devotional output and is one of the principal small-format Conception engravings of the mid-sixteenth-century German tradition."},
  {"artwork_slug":"met-336271","paragraph":"Design for a Dagger Sheath, with Cain and Abel, engraved by Heinrich Aldegrever in 1539 in his Soest workshop, is a small ornament print intended as a working pattern for a goldsmith or armorer to translate into the engraved metal of a dagger sheath. The composition shows the moment from Genesis 4 of the first murder — Cain raising his club to strike the kneeling Abel — set inside an elaborate Renaissance ornamental frame of strapwork, foliate scrolls, and grotesque masks. Aldegrever's ornament prints, which he produced alongside his religious cycles throughout his career, were used and copied by goldsmiths, joiners, and cabinetmakers throughout the German-speaking lands and the Low Countries; the combination of biblical narrative and Renaissance ornament in a single small format is characteristic of the goldsmith-trained engraver's output."}
]$JSON$::jsonb
where slug = 'heinrich-aldegrever';

-- ─── Carlo Maratti ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-400372","paragraph":"The Annunciation, drawn by Carlo Maratti around 1670 in pen and ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of his many painted Annunciation altarpieces of his late Roman career. The drawing shows the moment from Luke 1 in which the angel Gabriel appears to the Virgin in her chamber to announce the conception of Christ: the Virgin kneels at her prayer-desk on the right, the angel descends from the upper left in an attitude of greeting, the Holy Spirit appears as a small dove on a beam of light between them. Maratti's late Roman drawings — pen-and-wash compositional studies for altarpieces and ceiling decorations — are the principal record of his working method and demonstrate the calm classicizing manner that defined his entire devotional output."},
  {"artwork_slug":"met-340750","paragraph":"The Virgin Immaculate with the Four Doctors of the Church, drawn by Carlo Maratti around 1670 in his late Roman workshop, is a preparatory drawing for an altarpiece commission depicting the Catholic doctrine of the Immaculate Conception attended by the four early Latin Church Fathers — Augustine, Ambrose, Jerome, and Gregory the Great — whose theological writings were among the principal authorities for Counter-Reformation Mariology. Maratti stages the scene as a vertical composition with the standing Virgin at the upper center surrounded by attendant angels, the four bearded Latin Fathers ranged in the lower foreground in formal attendance with their books and identifying attributes. The drawing demonstrates the late Maratti workshop discipline at full mature statement."},
  {"artwork_slug":"met-816629","paragraph":"The Flight into Egypt, painted by Carlo Maratti around 1659 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Holy Family fleeing from King Herod's persecution as recorded in Matthew 2. Maratti stages the scene as a tender outdoor encounter: the Virgin riding on the small donkey holding the swaddled Christ Child, Joseph leading the donkey on foot while looking back over his shoulder for pursuit, a small attending angel guiding them along the road through an Italian landscape. The chromatic palette of warm flesh, deep crimson, and soft Italian blue against the dusty road and the soft hilly horizon is the unmistakable late-Roman Maratti signature, and the painting is one of the principal Maratti Flight scenes in any American collection."},
  {"artwork_slug":"met-369371","paragraph":"The Virgin and Joseph with the Young Jesus, drawn by Carlo Maratti around 1710 in his very late Roman workshop years, is a small preparatory drawing for one of the many small Holy Family devotional paintings produced by Maratti's workshop in the years before his death. The drawing shows the seated Virgin holding the small Christ Child standing on her lap, with Joseph behind her holding a tall flowering staff (the iconographic attribute that, in the late-medieval Marian tradition, identified Joseph as the chosen husband of the Virgin from among all the suitors). The composition demonstrates the late Maratti's reliance on the small intimate Holy Family devotional type that his Roman workshop turned out in workshop variants for private patrons throughout the late seventeenth and early eighteenth centuries."}
]$JSON$::jsonb
where slug = 'carlo-maratti';

-- ─── Cornelis Cort ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-418442","paragraph":"Saint John the Baptist in the Wilderness, engraved by Cornelis Cort around 1565 (in his Italian years working closely with Titian and the Roman painters) and now in the Metropolitan Museum of Art in New York, depicts the cousin of Christ in his desert ministry of fasting and preaching as recorded in the Gospels. The Baptist is shown in the foreground in his camel-hair garment, his hand gesturing in the act of preaching toward an unseen audience, with the small reed cross identifying him as the precursor of Christ; the rocky wilderness opens out behind into a panoramic landscape with distant hills. Cort's engraved line — the long swelling parallel strokes laid down with a curved-handle burin that became the Cort signature — gives the print an atmospheric tonal range that no Antwerp engraving of the same period had achieved. The print circulated through the Roman publishing market of Antonio Lafreri and his successors."},
  {"artwork_slug":"met-418554","paragraph":"Saint Jerome in the Desert, engraved by Cornelis Cort around 1565 in his Italian workshop years, depicts the early Church Father in the conventional iconographic posture of his hermit years — half-naked, kneeling on his rocks, beating his breast with a stone in penitence — set against a rocky desert landscape with distant hills. Cort's engraved line gives the print a particular atmospheric depth: the foreground figure of Jerome is sharply outlined and plastically modeled, the middle distance fades into soft tonal gray, and the distant hills almost disappear into a pale gray atmospheric haze. The print is one of the principal early Cort treatments of the Jerome subject, a particular preoccupation of Counter-Reformation Italian devotional painting and printmaking."},
  {"artwork_slug":"met-416726","paragraph":"The Flight into Egypt, engraved by Cornelis Cort around 1571 in his Italian workshop years (probably after a composition by the Bologna painter Lavinia Fontana or one of her circle), depicts the apocryphal subject of the Holy Family fleeing from King Herod's persecution. Cort stages the scene as a panoramic Italian landscape encounter: the Virgin riding on the donkey holding the Christ Child, Joseph leading the donkey on foot, a small attending angel guiding them along a winding road through hills with distant towns and a soft sky. The print is one of the standard late-sixteenth-century Italian-engraved treatments of the subject and was widely copied through the Roman and Antwerp publishing networks for over a century after its first publication."},
  {"artwork_slug":"met-418149","paragraph":"The Conversion of Saint Paul, engraved by Cornelis Cort in 1576 (in his late Italian years working in Rome) after a composition by Federico Zuccaro, depicts the moment from Acts 9 in which Saul falls from his horse on the road to Damascus blinded by the light from heaven. Cort stages the scene with characteristic Italian Mannerist density: Saul fallen on the ground in the foreground, his horse rearing in alarm beside him, the divine appearing as a foreshortened Christ in the upper register pulling apart the clouds and dispatching a stream of figures down toward the earthbound apostle. The print is among the principal late-Cort religious engravings and a defining example of the reproductive engraving tradition that carried Federico Zuccaro's Roman compositions across Europe."}
]$JSON$::jsonb
where slug = 'cornelis-cort';

-- ─── Pietro Testa ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-399888","paragraph":"The Sacrifice of Isaac, etched by Pietro Testa in his Roman workshop years (probably the late 1630s, the dating of his prints is somewhat contested), illustrates the climactic moment of Genesis 22 in which the angel descends to stop Abraham from sacrificing his son Isaac on the altar at the top of Mount Moriah. Testa stages the scene with characteristic Roman Baroque density: the bound Isaac kneels at the small stone altar in the foreground, Abraham raises the knife with one hand while the angel's hand grips his wrist from above, the ram caught in the thicket appears in the lower-right corner, and a panoramic landscape with distant hills fades into atmospheric haze in the background. The print demonstrates the late Testa etching technique — long swelling lines, dense crosshatched shadow, atmospheric distance — that defined his contribution to the seventeenth-century Roman printmaking tradition."},
  {"artwork_slug":"met-399897","paragraph":"The Return of the Prodigal Son, etched by Pietro Testa in his Roman workshop years, illustrates the climactic moment of the Luke 15 parable: the father runs to embrace his returning son who, having squandered his inheritance, has returned home to throw himself at his father's feet. Testa stages the scene as a tender outdoor encounter at the gate of the family estate: the kneeling son embraced by the standing father, household servants in the background preparing the celebratory meal, the elder brother visible at the upper right tending the fields. The print is among the most reproduced Testa religious etchings and demonstrates his characteristic combination of dense narrative composition with the airy classicizing landscape that filled the backgrounds of his mature prints."},
  {"artwork_slug":"met-341593","paragraph":"The Virgin Lamenting over the Dead Christ, drawn by Pietro Testa around 1612 in his Roman workshop in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his rare painted Pietà compositions. The drawing shows the seated Virgin holding the dead body of Christ across her lap in the conventional Pietà posture, with John the Evangelist standing behind to support the head and the Magdalene kneeling at the feet in attitude of grief. The drawing demonstrates Testa's elegant rapid pen-and-wash technique that the eighteenth-century connoisseurs Jean-Baptiste-Joseph Boucher and Pierre-Jean Mariette would treat as one of the supreme achievements of Italian Baroque draughtsmanship."},
  {"artwork_slug":"met-360004","paragraph":"The Adoration of the Magi, etched by Pietro Testa around 1620 in his early Roman workshop years, depicts the visit of the three kings to the infant Christ as recorded in Matthew 2. Testa stages the scene as a dense vertical composition under a great Renaissance architectural canopy: the seated Virgin and the Christ Child at the right, the eldest king kneeling in profile in the foreground offering his gift, the second and third kings with their large attending retinue filling the background, and an Italianate landscape glimpsed beyond a colonnade behind. The print is one of the principal early Testa religious etchings and a defining example of his ability to combine dense narrative figural composition with the elegant classicizing architectural setting that the Roman seventeenth-century circle of Cassiano dal Pozzo cultivated as the right pictorial setting for biblical narrative."}
]$JSON$::jsonb
where slug = 'pietro-testa';

-- ─── Federico Zuccaro ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340826","paragraph":"Christ Preaching, drawn by Federico Zuccaro around 1570 in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his many painted preaching scenes. The drawing shows Christ standing on a small platform at the upper register addressing a crowd of seated and standing listeners spread across the foreground in postures of attentive listening. The drawing demonstrates Zuccaro's characteristic late-Mannerist compositional density and the rapid confident pen-and-wash technique that the Roman workshop tradition descending from his teacher Taddeo Zuccaro had refined to a high pitch of virtuosity. The sheet is among the principal Zuccaro drawings in any American collection."},
  {"artwork_slug":"met-341702","paragraph":"Ecce Homo, drawn by Federico Zuccaro around 1540 (early in his career, in the workshop he shared with his older brother Taddeo) in red chalk on paper and now in the Metropolitan Museum of Art in New York, depicts the moment from John 19 in which Pontius Pilate presents the scourged and crowned-with-thorns Christ to the assembled crowd with the Latin words Ecce Homo (Behold the man). The drawing shows Christ in three-quarter view at the center of the small composition, his hands bound at the wrists, the crown of thorns pressed down on his brow, with two Roman soldiers on either side. The drawing demonstrates the early Zuccaro draughtsmanship in the workshop he and his brother Taddeo ran in Rome through the 1550s and 1560s before Taddeo's early death in 1566 left Federico to direct the firm alone."},
  {"artwork_slug":"met-341646","paragraph":"Paradise, drawn by Federico Zuccaro around 1565 in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for the great cupola fresco program of Florence Cathedral that Zuccaro completed between 1572 and 1579 after the death of Giorgio Vasari, who had begun the project. The drawing shows the celestial court of the blessed in heaven gathered around the central enthroned Christ in glory, with multiple registers of saints and angels disposed in the dome's curving spandrels. The cupola fresco — the Last Judgment program inside Brunelleschi's great Florence Cathedral dome — is among the largest single late-Mannerist Italian fresco projects, and preparatory drawings like this one are the principal record of the working method that produced it."},
  {"artwork_slug":"met-341618","paragraph":"Scene from the Last Judgment, Study for the Florence Cathedral Cupola Fresco, drawn by Federico Zuccaro around 1576 in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is a more advanced compositional study for one of the segments of the great Florence Cathedral cupola Last Judgment program. The drawing focuses on a single segment of the curving dome surface, working out the disposition of the resurrected dead, the attending angels, and the lower-register hellish figures in a composition that would later be transferred to the dome surface in fresco. The sheet is one of several surviving Zuccaro Florentine cupola studies and a defining document of the late-Mannerist Italian fresco workshop method."}
]$JSON$::jsonb
where slug = 'federico-zuccaro-zuccari';

-- ─── Sodoma ────────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437978","paragraph":"Christ Presented to the People (Ecce Homo), painted by Sodoma around 1540 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from John 19 in which Pontius Pilate presents the scourged and crowned-with-thorns Christ to the assembled crowd with the Latin words Ecce Homo (Behold the man). Sodoma composes the scene as a tight vertical composition: Christ stands at the center of the panel in three-quarter view, his hands bound at the waist, the crown of thorns pressed down on his brow, his face lifted in calm sorrow; the dark architectural background and the absence of attendant figures concentrate all attention on the suffering Christ. The chromatic palette of pale flesh, soft white, and deep crimson against the dark ground is the unmistakable late-Sodoma signature, and the panel is one of the principal Sodoma religious paintings in any American collection."},
  {"artwork_slug":"met-459486","paragraph":"Saint Sebastian, drawn by Sodoma around 1500 (early in his career, in his pre-Sienese Lombard workshop years) in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a small early study sheet that includes the standing nude figure of Saint Sebastian on the recto and rapid sketches of a male head on the verso. The Sebastian figure stands in the conventional iconographic posture of his martyrdom — bound to a tree, his body pierced with arrows. Sodoma painted multiple major Saint Sebastian altarpieces across his career — the Uffizi version of around 1525 was treated by Vasari as the most beautiful nude figure in Italian painting — and the Met sheet is an early study sheet that demonstrates his lifelong fascination with the male nude figure."}
]$JSON$::jsonb
where slug = 'sodoma-giovanni-antonio-bazzi';

-- ─── Jacopo Bassano ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338162","paragraph":"The Annunciation to the Shepherds, painted by Jacopo Bassano around 1510 (the dating is somewhat early — Jacopo was probably born around 1510 himself, and the painting may be slightly later) in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 2 in which the angel of the Lord appears to the shepherds in the fields outside Bethlehem to announce the birth of Christ. Bassano stages the scene with characteristic Veneto-rural compositional density: the shepherds in the foreground startled in the act of tending their flocks, the angel descending from the upper left in a luminous burst of light, the small flock of sheep scattered across the night-darkened pasture. The chromatic palette of warm earth tones and dramatic single-source angelic light is the unmistakable Bassano signature."},
  {"artwork_slug":"met-440393","paragraph":"The Baptism of Christ, painted by Jacopo Bassano around 1585 in oil on canvas and now in the Metropolitan Museum of Art in New York, is a late composition from his last decade of work in his hilltown of Bassano del Grappa. The painting depicts the moment from Matthew 3 in which John the Baptist baptizes Christ in the river Jordan: Christ stands waist-deep in the water at the lower center, his hands folded in prayer; the Baptist on the left pours water from a small shell over Christ's head; the Holy Spirit descends as a small dove on a beam of light from the upper register. The chromatic palette and the late-Mannerist compositional handling — figures slightly elongated, the atmosphere thickened with smoke and storm — are characteristic of the late Bassano workshop manner that his sons would continue into the seventeenth century."},
  {"artwork_slug":"met-372543","paragraph":"Christ Appearing to Saint Mary Magdalen (Noli Me Tangere), painted by Jacopo Bassano around 1555 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment from John 20 in which the risen Christ appears to Mary Magdalene in the garden outside the empty tomb on the morning of the Resurrection. Bassano stages the encounter in a small Veneto-rural landscape with the half-naked risen Christ standing on the right with one hand raised in the gesture of withholding (the moment immediately before he addresses the Magdalene with the Latin words Noli me tangere — Touch me not), and the Magdalene kneeling on the left in profile reaching up toward him with the open ointment jar at her feet. The composition is among the most reproduced Bassano Easter-cycle paintings."}
]$JSON$::jsonb
where slug = 'jacopo-bassano-jacopo-da-ponte';

-- ─── Pordenone ─────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340536","paragraph":"Standing Figure of Christ with Arms Upraised, drawn by Giovanni Antonio da Pordenone around 1525 in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his great Crucifixion compositions — most likely the dramatic Crucifixion fresco he painted on the entrance wall of Cremona Cathedral between 1520 and 1521. The drawing shows the figure of Christ with arms lifted in the upright posture immediately before the Crucifixion, the body modeled in the dense muscular Pordenone manner that responded directly to Michelangelo's Sistine Chapel ceiling figures (which Pordenone had seen on his Roman trip around 1517). The sheet is among the principal Pordenone drawings in any American collection."},
  {"artwork_slug":"met-340528","paragraph":"Saint Christopher Bearing the Christ Child, drawn by Giovanni Antonio da Pordenone around 1525 in red chalk on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject from the medieval Golden Legend tradition in which the giant Christopher carries the small Christ Child across a flooded river — the act for which the saint is best known and from which his name (Christo-phoros, Christ-bearer) derives. The drawing shows the standing Saint Christopher in three-quarter view holding the small Christ Child up on his shoulder; the muscular figural anatomy and the energetic chalk technique demonstrate Pordenone's Michelangelo-influenced Northern Italian manner of the early 1520s."}
]$JSON$::jsonb
where slug = 'giovanni-antonio-da-pordenone-giovanni-antonio-de-sacchis';

-- ─── Giorgio Vasari ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340935","paragraph":"Saint Paul Speaking before King Agrippa (Acts 26), drawn by Giorgio Vasari around 1573 in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of the Vatican Sala Regia frescoes that Vasari was painting in 1572–1573 for Pope Gregory XIII. The drawing illustrates the scene from Acts 26 in which the imprisoned Paul, brought before the Jewish client king Agrippa II in Caesarea, makes his great defense speech of the Gospel before the king and the Roman governor Festus. Vasari stages the scene as a late-Mannerist judicial composition with Paul standing in profile at the lower right gesturing in the act of speaking, the king and governor seated under a baldachin at the upper left in attitude of attentive listening, and a small crowd of Roman soldiers and Jewish religious authorities filling the background. The drawing is one of the principal Vasari preparatory drawings for the Sala Regia program in any American collection."}
]$JSON$::jsonb
where slug = 'giorgio-vasari';

-- ─── Jacopo Bellini ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435645","paragraph":"Madonna and Child, painted by Jacopo Bellini around 1440 in tempera on panel and now in the Metropolitan Museum of Art in New York, is one of the few surviving paintings by the founding patriarch of the Bellini Venetian dynasty. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; the chromatic palette of saturated crimson, ultramarine, and tooled gold against a patterned gold ground is characteristic of the early Quattrocento Venetian devotional manner that combined the late-medieval Italo-Byzantine gold-ground convention with the new Renaissance interest in three-dimensional figural drawing. Most of Jacopo's finished paintings have been lost; the principal record of his career is the two great surviving sketchbooks (in the Louvre and the British Museum) of detailed pen-and-ink drawings. This Met panel is among the few surviving finished paintings and a defining document of the early Venetian fifteenth-century Bellini workshop."}
]$JSON$::jsonb
where slug = 'jacopo-bellini';

-- ─── Pieter Lastman ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"pieter-lastman-the-sacrifice-of-abraham","paragraph":"The Sacrifice of Abraham, painted by Pieter Lastman in 1612 in oil on panel and now in the Louvre, depicts the climactic moment of Genesis 22 in which the angel descends from heaven to stop Abraham from sacrificing his son Isaac on the altar at the top of Mount Moriah. Lastman stages the scene with characteristic Italianate Caravaggesque drama: the bound Isaac lies face-up across the wooden firewood on the altar, Abraham raises the knife with one hand while the angel grips his wrist from above to stay the blow, the ram caught in the thicket appears in the lower-left corner, and a small landscape of the rocky mountain top fades into the deeper background. The composition was the principal source for the very young Rembrandt's own Sacrifice of Isaac compositions of the 1630s; Rembrandt entered Lastman's Amsterdam workshop as an eighteen-year-old apprentice in 1624 and absorbed the Lastman compositional vocabulary of biblical narrative directly."}
]$JSON$::jsonb
where slug = 'pieter-lastman';

-- ─── Sebastiano del Piombo ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437646","paragraph":"Madonna and Child with Saints and Donors, painted by Sebastiano del Piombo around 1505 in his early Venetian years before his move to Rome and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the enthroned Virgin and Christ Child attended by saints with a kneeling donor figure in formal devotional grouping. Sebastiano stages the scene in a small architectural niche: the seated Virgin holds the Christ Child upright on her lap in the center; two attendant saints stand on either side; a small kneeling donor figure occupies the lower foreground in formal devotional posture. The chromatic palette of saturated rose, ultramarine, and warm flesh against the deep architectural shadow is characteristic of the early Sebastiano Venetian manner before his transformative Roman move of 1511 brought him into the Michelangelo-Raphael generation that would shape his mature style."}
]$JSON$::jsonb
where slug = 'sebastiano-del-piombo';

-- ─── Andrea Solario ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437699","paragraph":"Salome with the Head of Saint John the Baptist, painted by Andrea Solario in 1507 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the moment after the beheading of John the Baptist as recorded in Mark 6 — the young Salome receiving the head of the Baptist on a platter at the request of her mother Herodias, who had instigated the killing. Solario stages the scene as a small intimate vertical composition: Salome in three-quarter view holding the platter on which the head rests, an attendant servant standing behind her, the executioner visible in the deeper background having returned with his work done. The chromatic palette of pale flesh, deep crimson, and warm ochre against a darkened ground is characteristic of Solario's mature Lombard manner. The painting belongs to the Salome compositions in which Solario specialized — a particular Lombard-into-French Renaissance type that he produced in multiple workshop variants for private patrons."},
  {"artwork_slug":"met-437698","paragraph":"Christ Blessing, painted by Andrea Solario in 1519 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the half-length figure of Christ in three-quarter view raising his right hand in benediction and holding a transparent crystal globe surmounted by a small cross in his left — the iconographic Salvator Mundi composition (Christ Saviour of the World) that Lombard and Venetian painters of the early sixteenth century made into a particular specialty. Solario stages the figure against a dark neutral background with characteristic Lombard chromatic restraint — pale flesh, deep crimson robe, warm grey ground. The composition was a particular favorite of the Lombard workshop tradition descending from Leonardo's Milanese followers, and Solario produced multiple workshop variants of the Salvator Mundi type in his late career."}
]$JSON$::jsonb
where slug = 'andrea-solario';

-- ─── Sassoferrato ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-341171","paragraph":"The Holy Family with the Infant Saint John the Baptist, drawn by Sassoferrato around 1650 in his late Roman workshop in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of his many small painted Holy Family devotional compositions. The drawing shows the seated Virgin holding the small Christ Child standing on her lap, with the small John the Baptist embracing the Christ Child from the side; Joseph stands behind the Virgin in formal attendance. The drawing demonstrates Sassoferrato's deliberately archaizing late-Quattrocento manner — figures composed in the style of Raphael and Perugino rather than in the contemporary mid-seventeenth-century Roman Baroque idiom — that defined his entire output and made him, by his own pictorial choice, the last fifteenth-century painter."}
]$JSON$::jsonb
where slug = 'sassoferrato-giovanni-battista-salvi';

-- ─── Andrea del Verrocchio ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437892","paragraph":"Madonna and Child, painted by Andrea del Verrocchio (or by the workshop he ran in Florence with Leonardo da Vinci, Pietro Perugino, and Lorenzo di Credi as his pupils in the 1470s) around 1465 in tempera on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the enthroned Virgin and Christ Child in the standard small-format Florentine Quattrocento devotional manner. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; the chromatic palette of saturated rose, ultramarine, and warm flesh against a dark architectural background is characteristic of the late-Quattrocento Florentine workshop tradition that Verrocchio was running at the height of his fame. The panel is one of the principal Verrocchio-school Madonnas in any American collection and demonstrates the compositional and chromatic discipline that the young Leonardo and the young Perugino would absorb directly during their apprenticeship years in his bottega."}
]$JSON$::jsonb
where slug = 'andrea-del-verrocchio';
