-- Wikidata Q-IDs for bio'd artists.
-- Generated by scripts/backfill-wikidata-ids.mjs.
-- Each Q-ID was selected by:
--   * Wikidata wbsearchentities lookup on the display name.
--   * wbgetentities verification of:
--       - instance_of includes human (Q5)
--       - occupation includes a recognized art occupation
--       - date_of_birth year is within ±5 of our row
-- Rows with no confident match are emitted as comments.

-- Alonso Cano (1601–1667)  →  Q378783  Spanish painter, architect and sculptor (1601-1667)
update public.artists set wikidata_id = 'Q378783' where slug in ('alonso-cano');

-- skip  Ambrogio Lorenzetti (1319–1347)  slugs='ambrogio-lorenzetti'
--   Q211562 birth-year mismatch: db=1319 wd=1290
--   Q52815202 not human (Ambrogio Lorenzetti)
--   Q131449696 not human (Ambrogio Lorenzetti (2017))

-- Anthony van Dyck (1599–1641)  →  Q150679  Flemish Baroque artist (1599–1641)
update public.artists set wikidata_id = 'Q150679' where slug in ('anthony-van-dyck');

-- Antonello da Messina (Antonello di Giovanni d'Antonio) (1430–1479)  →  Q5594  Italian Renaissance painter (1430–1479)
update public.artists set wikidata_id = 'Q5594' where slug in ('antonello-da-messina-antonello-di-giovanni-d-antonio');

-- skip  Antonio Vivarini (1440–1484)  slugs='antonio-vivarini'
--   Q935534 birth-year mismatch: db=1440 wd=1415
--   Q131837834 not human (Antonio Vivarini und seine Werkstatt: Tradition und Innovation in zwei vergessenen Altarwerken)

-- skip  Bartolomeo Vivarini (1450–1491)  slugs='bartolomeo-vivarini'
--   Q456971 birth-year mismatch: db=1450 wd=1430

-- Bernardo Strozzi (1581–1644)  →  Q437724  Italian painter (1581-1644)
update public.artists set wikidata_id = 'Q437724' where slug in ('bernardo-strozzi');

-- skip  Carlo Crivelli (1457–1495)  slugs='carlo-crivelli'
--   Q568885 not art occupation (Carlo Crivelli)
--   Q348024 birth-year mismatch: db=1457 wd=1430
--   Q2939181 not art occupation (Carlo Crivelli)

-- Daniele da Volterra (Daniele Ricciarelli) (1509–1566)  →  Q540489  Italian painter (1509-1566)
update public.artists set wikidata_id = 'Q540489' where slug in ('daniele-da-volterra-daniele-ricciarelli');

-- Federico Barocci (1535–1612)  →  Q316731  Italian painter (1535-1612)
update public.artists set wikidata_id = 'Q316731' where slug in ('federico-barocci');

-- Fra Bartolomeo (Bartolomeo di Paolo del Fattorino) (1473–1517)  →  Q7780  Italian Renaissance painter (1472-1517)
update public.artists set wikidata_id = 'Q7780' where slug in ('fra-bartolomeo-bartolomeo-di-paolo-del-fattorino');

-- skip  Gentile da Fabriano (Gentile di Niccolò di Giovanni di Massio) (1408–1427)  slugs='gentile-da-fabriano-gentile-di-niccol-di-giovanni-di-massio'
--   no candidates for "Gentile da Fabriano (Gentile di Niccolò di Giovanni di Massio)"
--   Q312393 birth-year mismatch: db=1408 wd=1370
--   Q52819009 not human (Gentile Da Fabriano)

-- Gerrit van Honthorst (1592–1656)  →  Q314548  Dutch Golden Age painter (1592-1656)
update public.artists set wikidata_id = 'Q314548' where slug in ('gerrit-van-honthorst');

-- Giovanni Battista Tiepolo (1696–1770)  →  Q186202  Italian painter (1696–1770)
update public.artists set wikidata_id = 'Q186202' where slug in ('giovanni-battista-tiepolo');

-- Giovanni Lanfranco (1582–1647)  →  Q447730  Italian painter (1582-1647)
update public.artists set wikidata_id = 'Q447730' where slug in ('giovanni-lanfranco');

-- Hendrick ter Brugghen (1588–1629)  →  Q437233  Dutch painter (1588-1629)
update public.artists set wikidata_id = 'Q437233' where slug in ('hendrick-ter-brugghen');

-- Jacob Jordaens (1593–1678)  →  Q270658  Flemish painter, draftsman and designer of prints and tapestries (1593-1678)
update public.artists set wikidata_id = 'Q270658' where slug in ('jacob-jordaens');

-- Jan Brueghel the Elder (1568–1625)  →  Q209050  Flemish painter (1568–1625)
update public.artists set wikidata_id = 'Q209050' where slug in ('jan-brueghel-the-elder');

-- Jan Lievens (1607–1674)  →  Q430783  Dutch painter (1607–1674)
update public.artists set wikidata_id = 'Q430783' where slug in ('jan-lievens');

-- Joos van Cleve (1485–1541)  →  Q153472  Flemish painter (1485–1540)
update public.artists set wikidata_id = 'Q153472' where slug in ('joos-van-cleve');

-- skip  Lippo Memmi (Filippo di Memmo) (1317–1356)  slugs='lippo-memmi-filippo-di-memmo'
--   no candidates for "Lippo Memmi (Filippo di Memmo)"
--   Q504963 birth-year mismatch: db=1317 wd=1291
--   Q103951034 not human (Lippo Memmi)

-- Lorenzo Monaco (Piero di Giovanni) (1370–1425)  →  Q155376  Italian painter (c. 1370 – c. 1425)
update public.artists set wikidata_id = 'Q155376' where slug in ('lorenzo-monaco-piero-di-giovanni');

-- Luca Giordano (1634–1705)  →  Q332494  Italian Baroque painter (1634–1705)
update public.artists set wikidata_id = 'Q332494' where slug in ('luca-giordano');

-- skip  Lucas Cranach the Younger and Workshop (1515–1586)  slugs='lucas-cranach-the-younger-and-workshop'
--   no candidates for "Lucas Cranach the Younger and Workshop"

-- Lucas Cranach the Younger (1515–1586)  →  Q170339  German Renaissance artist (1515–1586)
update public.artists set wikidata_id = 'Q170339' where slug in ('lucas-cranach-the-younger');

-- Maerten de Vos (1532–1603)  →  Q555022  Flemish draughtsman, painter (1532-1603)
update public.artists set wikidata_id = 'Q555022' where slug in ('maerten-de-vos');

-- Mattia Preti (Il Cavalier Calabrese) (1613–1699)  →  Q468632  Italian painter (1613-1699)
update public.artists set wikidata_id = 'Q468632' where slug in ('mattia-preti-il-cavalier-calabrese');

-- Pier Francesco Mola (1612–1666)  →  Q1192715  Swiss painter (1612-1666)
update public.artists set wikidata_id = 'Q1192715' where slug in ('pier-francesco-mola');

-- Pieter Aertsen (1507–1575)  →  Q326548  painter from the Northern Netherlands (1508-1575)
update public.artists set wikidata_id = 'Q326548' where slug in ('pieter-aertsen');

-- skip  Pietro Lorenzetti (1320–1344)  slugs='pietro-lorenzetti'
--   Q309635 birth-year mismatch: db=1320 wd=1280
--   Q108900486 not human (Pietro Lorenzetti)
--   Q58369744 not human (Pietro Lorenzetti: A Chronology)

-- Salvator Rosa (1615–1673)  →  Q359421  Italian painter, poet and printmaker (1615 –1673)
update public.artists set wikidata_id = 'Q359421' where slug in ('salvator-rosa');

-- Sano di Pietro (Ansano di Pietro di Mencio) (1405–1481)  →  Q1379714  Italian painter (1405–1481)
update public.artists set wikidata_id = 'Q1379714' where slug in ('sano-di-pietro-ansano-di-pietro-di-mencio');

-- skip  Sassetta (Stefano di Giovanni) (1400–1450)  slugs='sassetta-stefano-di-giovanni'
--   no candidates for "Sassetta (Stefano di Giovanni)"
--   Q362016 birth-year mismatch: db=1400 wd=1392
--   Q157880 not human (Sassetta)

-- skip  Simone Martini (1315–1344)  slugs='simone-martini'
--   Q221043 birth-year mismatch: db=1315 wd=1284
--   Q102110024 not art occupation (Simone Martini)
--   Q108538723 not art occupation (Simone Martini)

-- skip  Vincenzo Foppa (1456–1516)  slugs='vincenzo-foppa'
--   Q222923 birth-year mismatch: db=1456 wd=1427
--   Q132173170 not human (Vincenzo Foppa of Brescia, founder of the Lombard school, his life and work)


-- ─────────────────────────────────────────────────────────────────────
-- Manual overrides for the 11 phase-10 rows skipped by the strict
-- birth-year tolerance. Q-IDs taken directly from the rejection log
-- above; the correct artists were the top wbsearchentities hits, just
-- with DB birth years that drift by 10–40 years from Wikidata's.
-- ─────────────────────────────────────────────────────────────────────

-- Ambrogio Lorenzetti — Sienese painter, c.1290–1348. DB 1319 vs WD 1290.
update public.artists set wikidata_id = 'Q211562' where slug = 'ambrogio-lorenzetti';

-- Antonio Vivarini — Venetian painter, c.1415/18–1480. DB 1440 vs WD 1415.
update public.artists set wikidata_id = 'Q935534' where slug = 'antonio-vivarini';

-- Bartolomeo Vivarini — Venetian painter, c.1430/32–1499. DB 1450 vs WD 1430.
update public.artists set wikidata_id = 'Q456971' where slug = 'bartolomeo-vivarini';

-- Carlo Crivelli — Venetian-Marche painter, c.1430/35–1495. DB 1457 vs WD 1430.
update public.artists set wikidata_id = 'Q348024' where slug = 'carlo-crivelli';

-- Gentile da Fabriano — Marche-born International Gothic master, c.1370–1427.
update public.artists set wikidata_id = 'Q312393' where slug = 'gentile-da-fabriano-gentile-di-niccol-di-giovanni-di-massio';

-- Lippo Memmi — Sienese painter, c.1291–1356.
update public.artists set wikidata_id = 'Q504963' where slug = 'lippo-memmi-filippo-di-memmo';

-- "Lucas Cranach the Younger and Workshop" → principal artist Q170339.
update public.artists set wikidata_id = 'Q170339' where slug = 'lucas-cranach-the-younger-and-workshop';

-- Pietro Lorenzetti — Sienese painter, c.1280–1348. DB 1320 vs WD 1280.
update public.artists set wikidata_id = 'Q309635' where slug = 'pietro-lorenzetti';

-- Sassetta (Stefano di Giovanni) — Sienese Quattrocento, c.1392–1450.
update public.artists set wikidata_id = 'Q362016' where slug = 'sassetta-stefano-di-giovanni';

-- Simone Martini — Sienese Trecento master, c.1284–1344.
update public.artists set wikidata_id = 'Q221043' where slug = 'simone-martini';

-- Vincenzo Foppa — Lombard painter, c.1427–1515. DB 1456 vs WD 1427.
update public.artists set wikidata_id = 'Q222923' where slug = 'vincenzo-foppa';
