-- Notable works (phase 5) — original-prose, single-paragraph essays for
-- the phase-10 anchor artists. Same conventions as 036 / 037 / 038 / 039:
-- each paragraph ~180–280 words, no double quotes inside the JSON,
-- exact slug matching, every artwork_slug verified against the live DB.

-- ─── Anthony van Dyck ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436262","paragraph":"Virgin and Child with Saint Catherine of Alexandria, painted by Anthony van Dyck around 1625 in oil on canvas during his Italian sojourn (probably in Genoa, where he lived and worked between 1621 and 1627) and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the mystic marriage of Saint Catherine. The seated Virgin holds the Christ Child upright on her lap; Catherine kneels in profile on the right with her wheel of martyrdom visible behind her, and the Christ Child reaches forward to slip a small ring onto her finger. The chromatic palette of warm flesh, deep crimson, and pale blue against the darkened ground reflects van Dyck's recent Italian study of Titian and Veronese, the two great Venetian colorists whose work he absorbed during his Genoese years."},
  {"artwork_slug":"met-369073","paragraph":"Rest on the Flight into Egypt, painted by Anthony van Dyck around 1630 in oil on canvas, depicts the apocryphal subject of the Holy Family pausing in their flight from Herod's persecution as recorded in Matthew 2. Van Dyck stages the scene as a tender outdoor encounter: the seated Virgin in profile holding the swaddled Christ Child, Joseph waiting nearby with the small donkey, two attendant angels in the upper foreground playing the lute and the violin to soothe the Child to sleep. The chromatic palette of warm rose, pale silver-grey, and deep saturated blue against the soft Italian-Northern landscape combines van Dyck's Italian-period color with the careful Antwerp post-Rubensian figural drawing that defined his mature manner."},
  {"artwork_slug":"met-335448","paragraph":"Christ on the Cross (with Saint Jerome Reading by Candlelight on the verso), drawn by Anthony van Dyck around 1610 in pen and brown ink on paper and now in the Metropolitan Museum of Art in New York, is among the early van Dyck preparatory drawings from his Antwerp apprentice years in the orbit of his teacher Hendrick van Balen and (slightly later) of Peter Paul Rubens. The recto shows the body of Christ on the cross at the moment immediately after his death; the verso shows Saint Jerome — the early Church Father in his hermit years — seated reading by candlelight. The double-sided sheet demonstrates van Dyck's early facility for both the Passion subject and the Catholic devotional saint-portrait genre that would define his mature altarpiece practice."},
  {"artwork_slug":"met-335452","paragraph":"Christ and the Pharisees (with Christ and a Pharisee on the verso), drawn by Anthony van Dyck around 1610 in pen and brown ink on paper, is another early van Dyck preparatory sheet from his Antwerp workshop years. The recto shows Christ disputing with a small group of Pharisees gathered around him in the conventional iconographic composition of the Gospel-debate subject; the verso shows a single Pharisee facing Christ in a more focused two-figure composition. Such drawings — small-scale rapid studies of biblical-narrative subjects — were the working currency of the Antwerp Catholic painting workshop, and van Dyck's drawn output was particularly large and particularly accomplished even at this early stage of his career."},
  {"artwork_slug":"met-335451","paragraph":"Study of the Christ Child and the Hand of the Madonna, drawn by Anthony van Dyck around 1615 in his Antwerp workshop in pen and ink with brown wash on paper, is a small preparatory drawing for one of his early Madonna and Child compositions. The drawing shows the small Christ Child in the foreground and a separate study of the Madonna's hand reaching to touch him — the kind of focused detailed study that van Dyck would later use as the working pattern for the more finished half-length Madonnas of his Antwerp and English periods. The sheet is one of the principal early van Dyck preparatory drawings in any American collection."}
]$JSON$::jsonb
where slug = 'anthony-van-dyck';

-- ─── Giovanni Battista Tiepolo ─────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437789","paragraph":"The Adoration of the Magi, painted by Giovanni Battista Tiepolo in 1757 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the visit of the three kings to the infant Christ as recorded in Matthew 2. Tiepolo composes the scene as a luminous vertical encounter under an open architectural canopy: the seated Virgin and the Christ Child on the right, the eldest king kneeling in profile in the foreground offering his gift, the second king standing behind in formal attendance, the third king arriving with a small attending retinue. The chromatic palette of pale chalk-pink, electric blue, and silvery cool white against the bright eighteenth-century Venetian sky is the unmistakable mature-Tiepolo signature, and the painting demonstrates his characteristic ability to combine the late-Baroque grand-manner composition with a particularly Venetian luminosity of color and atmosphere."},
  {"artwork_slug":"met-438128","paragraph":"The Flight into Egypt, painted by Giovanni Battista Tiepolo in 1767 in oil on canvas during his late Madrid years and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Holy Family fleeing from King Herod's persecution. Tiepolo stages the scene as a small intimate encounter: the Virgin holding the swaddled Christ Child seated on the small donkey, Joseph leading the donkey on foot, a small attending angel guiding them across a luminous Italian landscape with distant hills fading into atmospheric haze. The chromatic palette of pale rose, silver-blue, and warm flesh against the soft sky is the unmistakable late-Tiepolo Madrid signature, painted during his last years at the Spanish royal court before his death in 1770."},
  {"artwork_slug":"met-335602","paragraph":"Adoration of the Magi, drawn by Giovanni Battista Tiepolo around 1733 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing from his middle career — the productive Venetian decade between his Würzburg trip and his eventual Madrid relocation. The drawing shows the three Magi approaching the Holy Family in his characteristic dense Baroque grouping: the seated Virgin holding the Christ Child at the center, the eldest king kneeling in profile in the foreground, the second and third kings standing in formal attendance with their large attending retinue of horses, exotic animals, and gift-bearing attendants. The drawing demonstrates the rapid confident pen-and-wash technique that defined Tiepolo's drawn output throughout his career and that the eighteenth-century connoisseurs collected as virtuoso autograph examples."},
  {"artwork_slug":"met-459683","paragraph":"The Holy Family with Saint John, painted by Giovanni Battista Tiepolo around 1751 in oil on canvas during his middle Venetian career, is one of the small intimate Holy Family devotional compositions Tiepolo produced for private patrons across his entire career. The composition shows the seated Virgin holding the small Christ Child, with the boy John the Baptist embracing the Christ Child from the side and Joseph waiting in the background. The chromatic palette of pale chalk-pink, electric blue, and silvery cool white against the soft Venetian-Baroque background is the unmistakable mature-Tiepolo signature, and the painting belongs to the long sequence of Holy Family devotional images that Tiepolo's workshop produced in workshop variants for Venetian aristocratic and ecclesiastical patrons through the 1740s and 1750s."},
  {"artwork_slug":"met-339443","paragraph":"The Virgin and Child Enthroned with Saint Sebastian and Saint Lucy, drawn by Giovanni Battista Tiepolo around 1735 in pen and brown ink with wash on paper, is a preparatory drawing for an altarpiece commission of his middle Venetian career. The drawing shows the seated Virgin with the Christ Child on her lap on a small architectural throne; Saint Sebastian stands on the left in his iconographic posture (bound to a tree, his body pierced with arrows); Saint Lucy stands on the right holding a small dish with her eyes (the iconographic attribute that distinguishes her from any other female saint). The composition demonstrates the late-Baroque sacra conversazione altarpiece type at full mature Venetian statement and is one of the principal Tiepolo preparatory drawings in any American collection."}
]$JSON$::jsonb
where slug = 'giovanni-battista-tiepolo';

-- ─── Antonello da Messina ──────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435580","paragraph":"Christ Crowned with Thorns, painted by Antonello da Messina around 1470 in oil on panel and now in the Metropolitan Museum of Art in New York, is one of the few Antonello panels in any American collection and a defining example of his ability to translate the Northern Early Netherlandish oil-painting technique into the Italian Renaissance devotional half-length figural type. The painting depicts the iconographic subject of the Vir Dolorum — the close-cropped head of the suffering Christ, his eyes lowered, the crown of thorns pressed down on his brow, drops of blood running down his face — set against a darkened ground and intended for personal devotional contemplation. The minute observation of the flesh tones and the soft sfumato modeling reflect Antonello's training in the Northern oil technique transmitted to him through his Neapolitan teacher Colantonio, and the painting is among the foundational documents of the introduction of Northern oil painting into the Italian peninsula in the second half of the fifteenth century."}
]$JSON$::jsonb
where slug = 'antonello-da-messina-antonello-di-giovanni-d-antonio';

-- ─── Carlo Crivelli ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436051","paragraph":"Madonna and Child Enthroned, painted by Carlo Crivelli around 1472 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small altarpiece panel from his early Marche years and a defining example of his idiosyncratic late-Gothic-into-Renaissance manner. The Virgin sits enthroned on an elaborate carved-and-gilded marble throne with the standing Christ Child upright on her lap; the chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable Crivelli signature, and the small surface details — the embroidered silks of the Virgin's mantle, the swag of fruit garland behind the throne, the careful botanical observation of the small flowers at her feet — demonstrate Crivelli's characteristic combination of jewel-bright color with the small intricate detail that defined his mature painted manner."},
  {"artwork_slug":"met-436053","paragraph":"Pietà, painted by Carlo Crivelli around 1476 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the seated Virgin holding the dead body of Christ across her lap immediately after the Deposition. Crivelli stages the scene with characteristic late-Gothic compositional intensity: the Virgin in three-quarter view holding the body of Christ, John the Evangelist supporting the head from behind, the Magdalene kneeling at the feet, all set against a tooled-gold background. The chromatic palette of pale flesh, deep crimson, and tooled gold is the unmistakable Crivelli signature, and the elongated figural proportions and intense devotional faces demonstrate his characteristic combination of Italian Renaissance figural drawing with the older Italian late-Gothic decorative pictorial sensibility."},
  {"artwork_slug":"met-436052","paragraph":"Madonna and Child, painted by Carlo Crivelli around 1475 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian panel from the central productive years of his Marche career. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; the chromatic palette and the careful tooled-gold background are characteristic of Crivelli's mature manner. The small surface details — the embroidered silks, the fruit garland, the botanical observation of the small plants and flowers around the figure — are the unmistakable Crivelli touches that gave his small devotional panels their distinctive jewel-bright intensity. The painting is among the principal Crivelli small Madonnas in any American collection."},
  {"artwork_slug":"met-438691","paragraph":"Saint George, painted by Carlo Crivelli around 1472 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Christian knight from the medieval Golden Legend tradition. The painting shows George in three-quarter view standing in his armor, holding a small flag-bearing lance, with the small dragon of his legendary combat at his feet. The chromatic palette of polished steel, deep crimson, and tooled gold is characteristic of Crivelli's mature manner, and the intricate observation of the armor's small surface details — the rivets, the engraved patterns, the polished plates — demonstrates his characteristic late-Gothic compositional precision. The panel was originally part of one of Crivelli's large polyptych altarpieces for one of the Marche churches and was dispersed in the eighteenth or nineteenth century."}
]$JSON$::jsonb
where slug = 'carlo-crivelli';

-- ─── Federico Barocci ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-359922","paragraph":"The Annunciation, etched by Federico Barocci around 1580 in his Urbino workshop and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin in her chamber to announce the conception of Christ. Barocci stages the scene with characteristic Counter-Reformation compositional discipline: the Virgin kneels at her prayer-desk on the right, the angel kneels on the left in an attitude of greeting, the Holy Spirit descends as a small dove on a beam of light from above. The etched line is patiently crosshatched in Barocci's distinctive late-mannerist manner — soft, slightly broken, with a particularly atmospheric tonal range. The print was widely reproduced through the European Catholic devotional engraving market for over a century after its first publication."},
  {"artwork_slug":"met-438688","paragraph":"Saint Francis, drawn by Federico Barocci around 1600 in his Urbino workshop in red and black chalk on paper and now in the Metropolitan Museum of Art in New York, depicts the medieval Italian Franciscan saint in the conventional iconographic posture of his religious meditation. The drawing shows the seated Saint Francis in his habit, his hands folded in his lap, his face lifted in an attitude of inward contemplation. The combination of red and black chalk on paper — the standard Barocci preparatory drawing technique — gives the figure a soft sfumato modeling characteristic of his late drawing style, and the sheet demonstrates the careful preparatory drawing campaigns that Barocci pursued for every painted altarpiece across his slow, deliberate career."}
]$JSON$::jsonb
where slug = 'federico-barocci';

-- ─── Joos van Cleve ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436792","paragraph":"The Crucifixion with Saints and a Donor, painted by Joos van Cleve around 1515 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of Christ's death on the cross attended by saints and a small kneeling donor figure in formal devotional grouping. The cross stands at the upper center against a darkening sky; the Virgin and John the Evangelist kneel at the foot of the cross in the conventional Northern compositional manner; two attendant saints flank them in formal symmetry; the small kneeling donor figure occupies the lower foreground in formal devotional posture. The chromatic palette and the architectural setting demonstrate the early van Cleve combination of late Early Netherlandish technique and the new Italianizing Antwerp Mannerist figural drawing that defined his mature output."},
  {"artwork_slug":"met-436795","paragraph":"Virgin and Child, painted by Joos van Cleve and his workshop around 1520 in oil on panel and now in the Metropolitan Museum of Art in New York, is one of the standard Antwerp Mannerist Marian devotional panels van Cleve and his workshop produced in dozens of variants for the Antwerp domestic and confraternal devotional market. The Virgin sits in three-quarter view holding the Christ Child against her chest, often (as in this version) with a small bunch of cherries that the Child reaches for; the setting is a small Northern interior with leaded windows opening onto a panoramic landscape. The composition was one of the most-copied Antwerp Mannerist devotional types and circulated in workshop variants across the European Catholic devotional market for several decades."},
  {"artwork_slug":"met-436791","paragraph":"The Annunciation, painted by Joos van Cleve and his workshop around 1520 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin in her chamber to announce the conception of Christ. Van Cleve stages the scene in a small Northern interior with characteristic Antwerp Mannerist compositional discipline: the Virgin kneels at her prayer-desk on the right, the angel kneels on the left with the lily of purity in one hand, the Holy Spirit descends as a small dove on a beam of golden light through the open window. The chromatic palette of saturated crimson, ultramarine, and warm flesh against the carefully detailed Northern interior is the unmistakable van Cleve workshop signature."},
  {"artwork_slug":"met-436797","paragraph":"The Holy Family, painted by Joos van Cleve and his workshop around 1520 in oil on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Virgin and Christ Child attended by Joseph in formal devotional grouping. Van Cleve composes the scene as a small horizontal interior encounter: the seated Virgin in three-quarter view holding the standing Christ Child upright on her lap, Joseph standing behind in formal attendance, the small interior carefully detailed with leaded windows opening onto a panoramic landscape. The composition belongs to the long sequence of Holy Family devotional images that the van Cleve workshop produced in workshop variants for the Antwerp Catholic devotional market across the 1520s and 1530s."}
]$JSON$::jsonb
where slug = 'joos-van-cleve';

-- ─── Salvator Rosa ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340642","paragraph":"The Raising of Lazarus, drawn by Salvator Rosa in pen and brown ink with brown wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the climactic miracle of John 11. Rosa stages the scene with characteristic dramatic compositional density: Christ at the lower left with his right arm extended in command, the bound figure of Lazarus emerging upright from the open tomb at the upper right, the sisters Martha and Mary kneeling between them at Christ's feet, and a small crowd of witnesses gathered behind. The drawing demonstrates Rosa's rapid confident pen-and-wash technique and his characteristic preference for the dramatic biblical narrative subject set in a wild rocky landscape."},
  {"artwork_slug":"met-340645","paragraph":"The Prodigal Son Kneeling Repentant among Swine, drawn by Salvator Rosa in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the moment from the Luke 15 parable in which the prodigal son, having squandered his inheritance and reduced to feeding swine, comes to himself and resolves to return to his father. Rosa stages the scene with characteristic Romantic-pastoral intensity: the kneeling son in the foreground, his hands folded in repentance, the swine scattered around him in the muddy field, a small wild landscape opening behind. The drawing demonstrates Rosa's characteristic interest in the solitary repentant figure as a subject for serious artistic attention — the same interest that defined his many painted treatments of hermit-saints."},
  {"artwork_slug":"met-340664","paragraph":"The Prodigal Son, drawn by Salvator Rosa in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a second drawing of the Luke 15 parable subject — a more focused composition than the related kneeling-among-swine sheet. The drawing shows the prodigal son in a similar repentant posture in a small pastoral landscape with the small group of swine and a few rocks. Rosa returned to the Prodigal Son subject repeatedly across his career; the parable's combination of dramatic narrative reversal and meditative pastoral setting fit Rosa's lifelong artistic interests particularly well, and the multiple surviving drawings are among the principal documents of his preparatory working method."},
  {"artwork_slug":"met-340660","paragraph":"Saint Paul, Hermit, drawn by Salvator Rosa in pen and brown ink on paper and now in the Metropolitan Museum of Art in New York, depicts the early-Church desert father Paul of Thebes — traditionally regarded as the first Christian hermit — in his solitary retreat in the Egyptian desert. Rosa stages the scene with characteristic Romantic-melancholic intensity: the seated saint in profile in his cave-like retreat, his face lifted in inward contemplation, the small landscape of rocky desert opening behind. The drawing belongs to the long sequence of hermit-saint subjects that Rosa returned to throughout his career and that defined his particular contribution to seventeenth-century Italian devotional draughtsmanship."}
]$JSON$::jsonb
where slug = 'salvator-rosa';

-- ─── Bernardo Strozzi ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437763","paragraph":"Tobias Curing His Father's Blindness, painted by Bernardo Strozzi around 1630 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the climactic moment of the deuterocanonical Book of Tobit in which the young Tobias, instructed by the angel Raphael, applies the gall of a fish to the eyes of his blind father Tobit and restores his sight. Strozzi stages the scene as a tender intimate encounter: Tobias kneels in profile on the left applying the medicament to his father's eye, the seated Tobit in three-quarter view at the right, the angel Raphael standing behind in formal attendance with the small caught fish. The chromatic palette of warm flesh, deep crimson, and silvery cool white against the dark interior is the unmistakable mature Strozzi signature. The painting is among the principal Strozzi religious works in any American collection."},
  {"artwork_slug":"met-335981","paragraph":"Saint Peter, drawn by Bernardo Strozzi around 1620 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the apostle in the conventional iconographic posture of the elder Church Father, a single bearded figure in three-quarter view with the keys of the kingdom (his iconographic attribute) at his side. The drawing demonstrates Strozzi's characteristic combination of broad confident pen technique with a particularly Genoese-Caravaggesque dramatic figural intensity, and is among the principal Strozzi preparatory drawings in any American collection. Saint-portrait drawings of this kind were the standard preparatory currency of seventeenth-century Italian altarpiece practice and were used as working patterns for finished painted altarpiece commissions."}
]$JSON$::jsonb
where slug = 'bernardo-strozzi';

-- ─── Jacob Jordaens ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-335661","paragraph":"Adoration of the Shepherds, drawn by Jacob Jordaens around 1620 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 2 in which the shepherds, having heard the angels' announcement of the birth of Christ, arrive at the small dwelling at Bethlehem to find the newborn child laid in the manger. Jordaens stages the scene with characteristic Antwerp-domestic compositional density: the seated Virgin holding the swaddled Christ Child, Joseph waiting behind, three Flemish-peasant shepherds in the foreground in postures of recognition and tender adoration. The drawing demonstrates the rapid confident pen-and-wash technique that Jordaens used as his standard preparatory currency and that the Antwerp post-Rubens generation refined to a high pitch of virtuosity."},
  {"artwork_slug":"met-335629","paragraph":"Saint Paul at Lystra, drawn by Jacob Jordaens around 1620 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the episode from Acts 14 in which the apostles Paul and Barnabas, after the healing of the lame man at Lystra, are mistaken by the Lystrans for the gods Hermes and Zeus and are about to be offered sacrifice — the moment immediately before Paul tears his garments in horrified protest. Jordaens stages the scene with characteristic Antwerp Baroque compositional drama: Paul standing on the right gesturing in protest, the priest with the sacrificial bull in the foreground, the assembled crowd of Lystrans in postures of curiosity and devotion. The drawing demonstrates Jordaens's characteristic ability to compress a complex multi-figure narrative composition into a small preparatory format."},
  {"artwork_slug":"met-399222","paragraph":"Christ Healing the Paralytic, etched by Jacob Jordaens around 1616 in his Antwerp workshop, illustrates the Gospel episode from Mark 2 in which Christ heals the paralytic man let down through the roof of the house in Capernaum. Jordaens stages the scene as a dense Antwerp Baroque interior composition: Christ standing in the center of the room with his right arm extended in command, the paralytic on his stretcher in the foreground in the act of rising, the four friends who had let him down through the roof visible at the upper register, the assembled crowd of disciples and Pharisees gathered around in postures of attentive observation. The print belongs to the relatively small body of original Jordaens etchings and demonstrates his ability to translate his characteristic painterly Baroque manner into the engraved devotional format."},
  {"artwork_slug":"met-459296","paragraph":"Dorcas Raised From the Dead by Saint Peter, drawn by Jacob Jordaens around 1667 in his late Antwerp workshop in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the episode from Acts 9 in which the apostle Peter, summoned to the bedside of the dead Dorcas (also called Tabitha) at Joppa, raises her from the dead in answer to the prayers of the Joppan widows. Jordaens stages the scene as a tender domestic encounter: Peter standing on the right with his right arm extended in command, Dorcas in the bed in the act of rising, the assembled widows gathered around in postures of grief and astonishment. The drawing belongs to the late Jordaens output and demonstrates the continued vigor of his draftsmanship into his final decade."}
]$JSON$::jsonb
where slug = 'jacob-jordaens';

-- ─── Luca Giordano ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436502","paragraph":"The Annunciation, painted by Luca Giordano around 1672 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin in her chamber to announce the conception of Christ. Giordano stages the scene with characteristic Neapolitan Baroque dramatic intensity: the Virgin kneels at her prayer-desk on the right, her face lifted in attentive recognition, the angel descends from the upper left in a luminous burst of light with the lily of purity in one hand, the Holy Spirit appears as a small dove on a beam of golden light. The chromatic palette of warm flesh, deep crimson, and luminous gold against the soft chalky background is the unmistakable mature Giordano Naples signature."},
  {"artwork_slug":"met-436503","paragraph":"The Flight into Egypt, painted by Luca Giordano in 1701 in oil on canvas during his late Naples years (after his return from Madrid) and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Holy Family fleeing from King Herod's persecution as recorded in Matthew 2. Giordano stages the scene as a dramatic outdoor encounter: the Virgin riding on the small donkey holding the swaddled Christ Child, Joseph leading the donkey on foot while looking back over his shoulder for pursuit, a small attending angel guiding them across an Italian landscape. The chromatic palette and the broad confident brushwork are the unmistakable late Giordano signature, painted in the years immediately before his death in Naples in 1705."},
  {"artwork_slug":"met-338898","paragraph":"Moses Striking the Rock, drawn by Luca Giordano around 1634 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the episode from Exodus 17 in which Moses, in answer to the Israelites' complaint of thirst at Rephidim, strikes the rock with his staff and brings forth water for the people. Giordano stages the scene as a dense crowd composition: Moses standing on the right with his staff raised in the moment of the miracle, the Israelites and their cattle pressing in from every side toward the spring of water. The drawing demonstrates the rapid confident pen-and-wash technique that Giordano used as his standard preparatory currency and that earned him the nickname Luca Fa-Presto (Luke Works-Quickly) from his Neapolitan contemporaries."},
  {"artwork_slug":"met-816243","paragraph":"The Sacrifice of Elijah, painted by Luca Giordano around 1648 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the climactic episode from 1 Kings 18 in which the prophet Elijah, in his contest with the prophets of Baal on Mount Carmel, calls down fire from heaven to consume the sacrifice and demonstrate the supremacy of the Lord. Giordano stages the scene as a dramatic outdoor encounter: Elijah standing in the foreground with his arms raised in supplication, the bull and the wood of the sacrifice arranged on the small stone altar, the descending fire from heaven illuminating the entire composition with a single shaft of golden light. The chromatic palette and the dramatic Caravaggesque chiaroscuro are characteristic of the early Giordano Naples manner before his middle and late careers softened the dramatic light into the broader painterly handling of his mature style."},
  {"artwork_slug":"met-338902","paragraph":"Saint Anne Received in Heaven by Christ and the Virgin, drawn by Luca Giordano around 1634 in pen and brown ink with wash on paper, depicts the iconographic subject from late-medieval Marian devotional tradition in which Saint Anne — the mother of the Virgin Mary, according to the apocryphal Marian narratives — is received into heaven by her daughter and grandson at her death and assumption. The drawing shows Anne kneeling at the lower right in postures of grateful arrival, with the Virgin and Christ together at the upper left receiving her into glory; small attendant angels and the saints fill the background. The drawing demonstrates Giordano's characteristic ability to compose a complex multi-figure heavenly assembly with the rapid confident pen-and-wash technique that defined his entire drawn output."}
]$JSON$::jsonb
where slug = 'luca-giordano';

-- ─── Mattia Preti ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-438824","paragraph":"Saint John the Baptist Preaching, painted by Mattia Preti around 1645 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the cousin of Christ in his desert ministry of preaching as recorded in the Synoptic Gospels. Preti stages the scene with characteristic Calabrian-Neapolitan Caravaggesque drama: the Baptist standing in the center of the composition in his camel-hair garment, his right hand raised in the act of preaching, the assembled listeners gathered around him in postures of attentive listening. The chromatic palette of warm earth tones, deep crimson, and silvery cool white against the dark background is the unmistakable mid-career Preti Roman signature, painted in the years immediately before his Maltese commission of 1661 transformed his late career."},
  {"artwork_slug":"met-437333","paragraph":"Pilate Washing His Hands, painted by Mattia Preti around 1663 in oil on canvas during his Maltese career and now in the Metropolitan Museum of Art in New York, depicts the moment from Matthew 27 in which the Roman governor Pontius Pilate publicly absolves himself of responsibility for the death of Jesus by performing the ritual hand-washing in front of the assembled crowd. Preti stages the scene as a dramatic three-quarter-length encounter: Pilate seated on the right with his hands extended over the basin, an attendant servant pouring water from a metal ewer, Christ in the deeper background with his hands bound in attendance. The chromatic palette of warm earth tones and deep saturated chiaroscuro is the unmistakable late-Preti Maltese signature, painted in the years of his decoration of the Co-Cathedral of Saint John in Valletta."}
]$JSON$::jsonb
where slug = 'mattia-preti-il-cavalier-calabrese';

-- ─── Lippo Memmi ───────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437063","paragraph":"Madonna and Child with Saints and Angels, painted by Lippo Memmi around 1345 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is one of the late Memmi sacra conversazione altarpieces from his final Sienese workshop years after his return from the Avignon papal court. The Virgin sits enthroned with the standing Christ Child upright on her lap; attendant saints and small attending angels stand on either side of the throne against the unmistakable Sienese Trecento tooled-gold background. The chromatic palette of saturated crimson, ultramarine, and tooled gold is characteristic of the late Memmi workshop manner, and the elongated figural proportions and calm devotional faces demonstrate his close stylistic relationship to his lifelong collaborator and brother-in-law Simone Martini."},
  {"artwork_slug":"met-437065","paragraph":"Saint Paul, painted by Lippo Memmi around 1325 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small panel from one of the larger Memmi polyptychs of his early-mature Sienese workshop years. The painting shows Paul standing in three-quarter view holding a small book and a sword (the iconographic attributes of his apostolic teaching and his eventual martyrdom by beheading); the chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable early Memmi signature. The panel was originally part of one of the standard Sienese Trecento polyptych altarpiece structures with the Virgin and Christ Child at the center and individual saints in the side panels."},
  {"artwork_slug":"met-458954","paragraph":"Saint Mary Magdalen, painted by Lippo Memmi around 1336 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is another small panel from one of his Sienese polyptychs. The painting shows the Magdalene standing in three-quarter view holding her ointment jar (the iconographic attribute that distinguishes her from any other female saint and that refers to the Gospel episode of her anointing of Christ's feet); the chromatic palette and the tooled-gold background are characteristic of the mid-career Memmi manner. The panel belongs to the same polyptych structure as the Saint Peter panel of the same date now also in the Metropolitan."},
  {"artwork_slug":"met-458955","paragraph":"Saint Peter, painted by Lippo Memmi around 1336 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small panel from the same Sienese polyptych as the Saint Mary Magdalen panel of the same date. The painting shows Peter standing in three-quarter view holding the keys of the kingdom and a small book — the iconographic attributes of his apostolic primacy and his role as the first leader of the early Church. The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable mid-career Memmi Sienese workshop signature."}
]$JSON$::jsonb
where slug = 'lippo-memmi-filippo-di-memmo';

-- ─── Sano di Pietro ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437602","paragraph":"The Adoration of the Magi, painted by Sano di Pietro around 1465 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the visit of the three kings to the infant Christ as recorded in Matthew 2. Sano composes the scene with characteristic Sienese Quattrocento compositional sweetness: the seated Virgin and the Christ Child on the right, the eldest king kneeling in profile in the foreground offering his gift, the second and third kings standing behind in formal attendance. The chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable Sano di Pietro signature, and the calm sweet faces and slightly elongated figural proportions demonstrate the deliberately conservative Sienese alternative to the contemporary Florentine Renaissance pictorial reform."},
  {"artwork_slug":"met-437606","paragraph":"The Massacre of the Innocents, painted by Sano di Pietro around 1465 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the slaughter of the male children of Bethlehem ordered by King Herod after the visit of the Magi as recorded in Matthew 2. Sano stages the scene with characteristic Sienese narrative density: the soldiers in the foreground in the act of killing, the screaming mothers clutching their dead infants, the small bodies of the killed children scattered across the foreground, the seated Herod presiding over the action from a small architectural throne in the upper register. The composition was likely part of a small predella series — the small narrative panels arranged below the larger central altarpiece — and is one of the principal Sano di Pietro Massacre treatments."},
  {"artwork_slug":"met-437604","paragraph":"Madonna and Child with the Dead Christ, Saints Agnes and Catherine of Alexandria, and Two Angels, painted by Sano di Pietro around 1465 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small intimate altarpiece panel that combines the iconographic subject of the Madonna and Child with the Marian Pietà type — the standing or seated Virgin holding the dead body of Christ across her lap. The composition shows the seated Virgin with both the living Christ Child on her lap and the dead body of the adult Christ supported across her knees; Saints Agnes and Catherine flank the Virgin in formal attendance, and two small attending angels complete the composition. The unusual compositional combination of the two subjects — the infancy and the Passion in the same panel — was a particular Sienese mid-fifteenth-century devotional preference."},
  {"artwork_slug":"met-458990","paragraph":"Saint Francis, painted by Sano di Pietro around 1440 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the medieval Italian Franciscan saint in the conventional iconographic posture of his religious meditation. The painting shows the seated Francis in his habit, his hands marked with the stigmata he received in his vision on Mount La Verna in 1224, his face lifted in inward contemplation. The chromatic palette of saturated brown, soft grey, and tooled gold against the patterned gold-tooled background is the unmistakable Sano di Pietro signature, and the calm sweet face is characteristic of his Sienese workshop's deliberately conservative late-medieval-into-Renaissance pictorial vocabulary."}
]$JSON$::jsonb
where slug = 'sano-di-pietro-ansano-di-pietro-di-mencio';

-- ─── Sassetta ──────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-458966","paragraph":"The Annunciation, painted by Sassetta around 1432 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin Mary in her chamber to announce the conception of Christ. Sassetta stages the scene with characteristic late-Sienese compositional sweetness: the Virgin kneels at her prayer-desk on the right, the angel kneels on the left in an attitude of greeting with the lily of purity in one hand, the Holy Spirit descends as a small dove on a beam of golden light from the upper register. The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable Sassetta signature, and the elongated figural proportions and calm devotional faces demonstrate the bridge from the Sienese Trecento tradition to the new Quattrocento International Gothic."},
  {"artwork_slug":"met-437612","paragraph":"Madonna and Child with Angels, painted by Sassetta around 1445 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian devotional panel from the late Sassetta workshop years. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; two small attending angels lean in at her shoulders to crown her with a small wreath; the chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable late Sassetta signature. The panel belongs to the small Sienese fifteenth-century devotional Madonna type that the Sassetta workshop produced in dozens of variants for the Sienese household and confraternal devotional market."}
]$JSON$::jsonb
where slug = 'sassetta-stefano-di-giovanni';

-- ─── Pietro Lorenzetti ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-438605","paragraph":"The Crucifixion, painted by Pietro Lorenzetti around 1340 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of Christ's death on the cross with the conventional Sienese Trecento attendant figures of the swooning Virgin and the mourning John the Evangelist. The cross stands at the upper center against the tooled-gold background; the swooning Virgin in the arms of the holy women on the left, the mourning John on the right, the centurion on horseback in the foreground recognizing the divinity of the dying Christ. The chromatic palette of saturated crimson, ultramarine, and tooled gold is the unmistakable mid-career Pietro Lorenzetti signature, and the figural weight and emotional gravity demonstrate the Sienese painter's debt to his Florentine contemporary Giotto's slightly earlier Paduan example."},
  {"artwork_slug":"met-436908","paragraph":"Saint Catherine of Alexandria, painted by Pietro Lorenzetti around 1337 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the legendary fourth-century Christian martyr in her conventional iconographic posture — standing in three-quarter view with her hand resting on the wheel of her martyrdom (the wheel from which she escaped through divine intervention before her eventual beheading). The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable mid-career Pietro Lorenzetti signature. The panel was originally part of one of his larger Sienese polyptych altarpieces with the Virgin and Christ Child at the center and individual saints in the side panels, and was dispersed in the eighteenth or nineteenth century."}
]$JSON$::jsonb
where slug = 'pietro-lorenzetti';

-- ─── Ambrogio Lorenzetti ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436907","paragraph":"Madonna and Child, painted by Ambrogio Lorenzetti around 1319 (early in his career) in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is one of the surviving small Marian panels from his early Sienese workshop years. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; the chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is characteristic of the early Ambrogio Lorenzetti manner. The painting demonstrates the Sienese workshop tradition descending from Duccio that Ambrogio absorbed during his apprentice years before developing his distinctive interest in legible architectural and landscape space — the interest that would culminate in the Allegories of Good and Bad Government frescoes in the Palazzo Pubblico of Siena two decades later."}
]$JSON$::jsonb
where slug = 'ambrogio-lorenzetti';

-- ─── Simone Martini ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437676","paragraph":"Saint Andrew, painted by Simone Martini around 1317 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the apostle Andrew in the conventional iconographic posture of his apostolic teaching, holding a small book and standing in three-quarter view against the unmistakable Sienese Trecento tooled-gold background. The chromatic palette of saturated rose, ultramarine, and tooled gold is the unmistakable early Simone Martini signature, and the elongated figural proportions and calm devotional face demonstrate the elegance that defined his entire Sienese workshop output. The panel was originally part of one of his larger Sienese polyptych altarpieces with the Virgin and Christ Child at the center and individual apostles in the side panels."},
  {"artwork_slug":"met-459136","paragraph":"Madonna and Child, painted by Simone Martini around 1323 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian devotional panel from his early-mature Sienese workshop years. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; the chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable Simone Martini signature, and the elongated figural proportions and calm devotional faces demonstrate the Sienese late-medieval-into-Renaissance pictorial tradition at full mature statement. The panel is one of the principal small Simone Martini Madonnas in any American collection."}
]$JSON$::jsonb
where slug = 'simone-martini';

-- ─── Lorenzo Monaco ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-470328","paragraph":"The Intercession of Christ and the Virgin, painted by Lorenzo Monaco around 1402 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject from late-medieval Christian devotional tradition in which both Christ and his mother Mary intercede with God the Father for the salvation of humanity — Christ showing the wounds of the Crucifixion and the Virgin showing her breast that suckled the infant Christ, the visible signs of their respective contributions to the work of redemption. Lorenzo Monaco stages the scene as a vertical Trinitarian composition with God the Father at the top, Christ kneeling on his right and the Virgin on his left, both in postures of intercession. The chromatic palette of saturated rose, ultramarine, and tooled gold is the unmistakable early Lorenzo Monaco signature."},
  {"artwork_slug":"met-459007","paragraph":"The Nativity, painted by Lorenzo Monaco around 1403 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of the birth of Christ in the small dwelling at Bethlehem. Lorenzo Monaco stages the scene as a small intimate vertical composition: the Virgin kneels in profile with her hands folded in adoration before the newborn Christ Child laid on her cloak in the foreground, Joseph waits in the background with a small candle, the ox and the ass occupy the rear of the small thatched stable, and small attending angels descend from the upper register with banners of greeting. The chromatic palette and the elongated figural proportions are characteristic of the mature Lorenzo Monaco Camaldolese workshop manner that defined his entire output."},
  {"artwork_slug":"met-459008","paragraph":"The Crucified Christ between the Virgin and Saint John, painted by Lorenzo Monaco around 1403 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of Christ's death on the cross with the conventional Italian Trecento attendant figures of the mourning Virgin and John the Evangelist. The cross stands at the upper center against the tooled-gold background; the Virgin on the left and John on the right are arranged in formal symmetry at the foot of the cross. The chromatic palette of saturated crimson, ultramarine, and tooled gold is the unmistakable mature Lorenzo Monaco signature, and the elongated figural proportions reflect the late-Trecento International Gothic refinement that defined his Florentine Camaldolese workshop."},
  {"artwork_slug":"met-436914","paragraph":"Noah, painted by Lorenzo Monaco around 1408 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the Old Testament patriarch in a small standing portrait. Noah stands in three-quarter view holding a small model of the Ark (the iconographic attribute that distinguishes him from any other Old Testament patriarch). The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is characteristic of the mature Lorenzo Monaco Camaldolese workshop manner, and the panel was originally part of a series of Old Testament patriarchs and prophets that the workshop produced for one of the Florentine ecclesiastical commissions of the early fifteenth century."},
  {"artwork_slug":"met-436912","paragraph":"David, painted by Lorenzo Monaco around 1408 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the Old Testament shepherd-king in a small standing portrait. David stands in three-quarter view holding a small harp (the iconographic attribute that refers to the psalms traditionally attributed to him); the chromatic palette and the tooled-gold background are characteristic of the mature Lorenzo Monaco signature. The panel belongs to the same series of Old Testament patriarchs and prophets as the Noah, Moses, and Abraham panels of the same date in the Metropolitan and is one of the principal Lorenzo Monaco workshop sequences in any American collection."}
]$JSON$::jsonb
where slug = 'lorenzo-monaco-piero-di-giovanni';

-- ─── Fra Bartolomeo ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435614","paragraph":"Madonna and Child with the Young Saint John the Baptist, painted by Fra Bartolomeo around 1492 in his early Florentine workshop years (before his Dominican vows and his entry into the convent of San Marco) in tempera and oil on panel and now in the Metropolitan Museum of Art in New York, is among the small early Madonnas from his pre-monastic period. The seated Virgin holds the Christ Child upright on her lap; the small John the Baptist stands in profile beside them, embracing the Christ Child from the side. The chromatic palette and the careful figural drawing demonstrate the early Fra Bartolomeo absorption of his teacher Cosimo Rosselli's Florentine workshop discipline at the moment immediately before he entered Florence's High Renaissance generation."},
  {"artwork_slug":"met-338151","paragraph":"The Adoration of the Magi, drawn by Fra Bartolomeo around 1495 in pen and brown ink on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing from his early Florentine workshop years. The drawing shows the visit of the three kings to the infant Christ as recorded in Matthew 2: the seated Virgin holding the Christ Child at the center, the eldest king kneeling in profile in the foreground offering his gift, the second and third kings standing behind in formal attendance with their large attending retinue. The drawing demonstrates the early Fra Bartolomeo draughtsmanship and the rapid confident pen technique that defined his preparatory working method throughout his career."},
  {"artwork_slug":"met-338145","paragraph":"The Virgin and Child, drawn by Fra Bartolomeo around 1510 in red and black chalk on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing from his mature Dominican workshop years at the convent of San Marco in Florence. The drawing shows the seated Virgin holding the standing Christ Child upright on her lap; the soft sfumato modeling derived in part from Leonardo da Vinci (whom Fra Bartolomeo met during Leonardo's second Florentine residence) and in part from Raphael (with whom he formed a close personal and stylistic friendship during Raphael's Florentine years of 1504–1508) is at full mature statement here, and the drawing is one of the principal mature Fra Bartolomeo Madonnas in any American collection."},
  {"artwork_slug":"met-338146","paragraph":"The Holy Family with Saint John the Baptist, drawn by Fra Bartolomeo around 1510 in red and black chalk on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of his mature painted Holy Family compositions. The drawing shows the seated Virgin holding the small Christ Child, with the small John the Baptist embracing the Christ Child from the side and Joseph standing in formal attendance behind. The combination of red and black chalk on paper — a particular Fra Bartolomeo technical preference — gives the figures a soft sfumato modeling characteristic of his mature Dominican workshop years at San Marco."},
  {"artwork_slug":"met-338147","paragraph":"The Annunciation, drawn by Fra Bartolomeo (with a faint view of buildings on the verso) around 1500 in pen and brown ink on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing from his early Dominican period at the convent of San Marco. The drawing shows the moment from Luke 1 in which the angel Gabriel appears to the Virgin in her chamber to announce the conception of Christ: the Virgin kneels at her prayer-desk on the right, the angel kneels on the left in an attitude of greeting, the Holy Spirit appears as a small dove on a beam of light. The drawing demonstrates the rapid confident pen technique that defined Fra Bartolomeo's preparatory working method."}
]$JSON$::jsonb
where slug = 'fra-bartolomeo-bartolomeo-di-paolo-del-fattorino';

-- ─── Antonio Vivarini ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437910","paragraph":"Saint Jerome, painted by Antonio Vivarini around 1440 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the early Church Father in the conventional iconographic posture of his hermit years in the Syrian desert — half-naked, kneeling on his rocks, beating his breast with a stone in penitence — with his lion (the iconographic attribute that distinguishes Jerome from any other bearded saint) at his feet. The chromatic palette of saturated brown, soft grey, and tooled gold against the patterned gold-tooled background is characteristic of the mid-fifteenth-century Murano-Venetian workshop manner of Antonio Vivarini, and the panel was originally part of one of his larger polyptych altarpieces with the Virgin and Christ Child at the center and individual saints in the side panels."},
  {"artwork_slug":"met-437909","paragraph":"Saint Peter Martyr Healing the Leg of a Young Man, painted by Antonio Vivarini around 1445 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts a miracle attributed to the thirteenth-century Dominican preacher and inquisitor Peter of Verona (Peter Martyr) who was canonized in 1253 after his murder by heretical assassins. The composition shows the saint kneeling on the left in his Dominican habit applying the healing touch to the leg of a young man seated in the foreground; small attendant figures of the young man's family witness the miracle in formal attendance. The chromatic palette and the careful narrative detail demonstrate the mature Antonio Vivarini Murano-Venetian workshop manner."}
]$JSON$::jsonb
where slug = 'antonio-vivarini';

-- ─── Bartolomeo Vivarini ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-459024","paragraph":"The Madonna of Humility, the Annunciation, the Nativity, painted by Bartolomeo Vivarini around 1462 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small triptych panel that combines three Marian subjects in a single small devotional format suitable for personal use. The central panel shows the Madonna of Humility (the Virgin seated on the ground rather than enthroned, an iconographic type associated with Marian humility); the side panels show the Annunciation and the Nativity in small narrative compositions. The chromatic palette and the careful figural drawing demonstrate Bartolomeo Vivarini's combination of the late-Gothic Murano-Venetian decorative tradition with the more weighty Mantegnesque figural drawing he had absorbed during his early Paduan years."},
  {"artwork_slug":"met-437912","paragraph":"The Death of the Virgin, painted by Bartolomeo Vivarini around 1484 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment from the apocryphal Marian narrative in which the Virgin Mary, dying in her old age, is attended on her deathbed by the assembled apostles. Bartolomeo composes the scene with characteristic late-fifteenth-century Venetian compositional density: the Virgin lies in the bed at the lower center, the apostles gather around her in dense devotional postures of grief and prayer, with Peter (identified by the pyx of the Eucharist in his hand) leaning in over the bed and John (the youngest apostle) kneeling at the head. The painting belongs to his mature Venetian workshop output."}
]$JSON$::jsonb
where slug = 'bartolomeo-vivarini';

-- ─── Maerten de Vos ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-348311","paragraph":"Baptism of Christ, designed by Maerten de Vos around 1550 (or perhaps slightly later) and engraved by his workshop for the Antwerp publishing market, depicts the moment from Matthew 3 in which John the Baptist baptizes Christ in the river Jordan. De Vos stages the scene with characteristic Antwerp Mannerist compositional discipline: Christ stands waist-deep in the river at the lower center, his hands folded in prayer; John on the left pours water from a small shell over Christ's head; the Holy Spirit descends as a small dove on a beam of light from the upper register; small attending angels watch from the riverbank. The print belongs to the long sequence of Life of Christ engravings de Vos designed for the Antwerp Counter-Reformation devotional market and that circulated through the broader European Catholic publishing network for over a century."},
  {"artwork_slug":"met-365054","paragraph":"Christ on the Way to Emmaus (Mark 16:12), designed by Maerten de Vos around 1579 and engraved by the Wierix workshop for the Antwerp publisher Adriaen Huybrechts, depicts the moment from Luke 24 in which the risen Christ joins two disciples on the road to the village of Emmaus on the afternoon of the Resurrection. De Vos stages the scene as a panoramic encounter: the three figures walking in the foreground along a winding road, the disciples in animated mid-conversation, the cloaked figure of Christ slightly behind them in profile. The print circulated through the Counter-Reformation Antwerp devotional engraving market and is one of the standard late-sixteenth-century Northern European visualizations of the Emmaus subject."},
  {"artwork_slug":"met-352012","paragraph":"Ecce Homo, designed by Maerten de Vos around 1584 and engraved by his workshop for the Antwerp publishing market, depicts the moment from John 19 in which Pontius Pilate presents the scourged and crowned-with-thorns Christ to the assembled crowd with the Latin words Ecce Homo (Behold the man). De Vos composes the scene with characteristic Antwerp Mannerist compositional density: Christ stands at the center on the small balcony of the Praetorium with his hands bound and the crown of thorns pressed down on his brow, two Roman soldiers on either side, Pilate slightly behind addressing the crowd that fills the lower foreground. The print belongs to the long Life of Christ engraved cycles de Vos designed for the Antwerp Counter-Reformation publishing market."},
  {"artwork_slug":"met-365053","paragraph":"Christ Appearing to Saint Peter (John 21:1-8), designed by Maerten de Vos around 1579 and engraved by the Wierix workshop for the Antwerp publisher Adriaen Huybrechts, depicts the moment from John 21 in which the risen Christ appears to the apostles fishing on the Sea of Galilee — and Peter, recognizing him from a distance, throws himself into the water and swims to shore to greet him. De Vos stages the scene as a panoramic encounter: the small fishing boat with the apostles on the lake at the upper register, Peter swimming through the water toward the shore in the middle register, Christ standing on the shore in the foreground in formal greeting. The print circulated through the Antwerp Counter-Reformation publishing market and is one of the standard late-sixteenth-century treatments of the Galilean post-Resurrection subject."},
  {"artwork_slug":"met-357201","paragraph":"Christ and the Twelve Apostles, designed by Maerten de Vos around 1592 and engraved by his workshop, depicts the iconographic subject of Christ enthroned in the center surrounded by the twelve apostles arranged in formal symmetrical attendance around him. De Vos composes the scene as a vertical hieratic composition: Christ at the upper center holding the orb of the world and raising his right hand in benediction, the twelve apostles in two rows of six on either side of his throne in their characteristic iconographic postures and attributes. The composition belongs to the standard Antwerp Counter-Reformation devotional iconographic types and circulated widely through the Catholic publishing market in the late sixteenth and early seventeenth centuries."}
]$JSON$::jsonb
where slug = 'maerten-de-vos';

-- ─── Jan Brueghel the Elder ────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-415885","paragraph":"The Good Samaritan Finds the Man, designed by Jan Brueghel the Elder around 1565 (the dating is somewhat early — Jan Brueghel was probably a child if the design is his) and engraved by his workshop, illustrates the climactic scene of the parable from Luke 10. Brueghel stages the scene at the side of the road from Jerusalem to Jericho: the wounded man lies on the dusty ground in the foreground, the Samaritan kneels beside him in the act of binding the wounds, while in the deep background the priest and the Levite who had passed by on the other side are still visible as small figures continuing their journey. The print belongs to the long sequence of biblical landscape narratives that Brueghel and his Antwerp workshop produced for the Counter-Reformation publishing market."},
  {"artwork_slug":"met-415722","paragraph":"The Thieves Robbing the Man, from the Good Samaritan series engraved by Jan Brueghel the Elder around 1593, illustrates the opening scene of the Luke 10 parable: the unnamed traveler is set upon by the bandits who beat him, strip him, and leave him half-dead by the roadside on the road from Jerusalem to Jericho. Brueghel stages the scene as a panoramic landscape encounter: the bandits surrounding the fallen traveler in the foreground, the rocky desert landscape of the Judean wilderness opening behind, and (in the deeper background) the small figures of the priest and the Levite about to encounter the wounded man on their way down the road. The print is one of the principal Jan Brueghel the Elder treatments of a Gospel parable subject."}
]$JSON$::jsonb
where slug = 'jan-brueghel-the-elder';

-- ─── Lucas Cranach the Younger ─────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-625642","paragraph":"Paul, from The Four Evangelists and Three Apostles series of woodcuts produced by Lucas Cranach the Younger and the Wittenberg workshop in the early sixteenth century, depicts the apostle in the conventional iconographic posture of his apostolic teaching — standing in three-quarter view holding a small book and a sword (the iconographic attributes of his apostolic writing and his eventual martyrdom by beheading). Cranach the Younger composes the figure with the characteristic Wittenberg-Cranach workshop signature: slim elongated proportions, careful chromatic discipline (in the printed-line context, this means precise crosshatched modeling), and a deliberate visual emphasis on Lutheran theological clarity. The print belongs to the standard Lutheran devotional output of the Wittenberg-Cranach workshop and circulated through the German Reformation publishing market for several decades."}
]$JSON$::jsonb
where slug in ('lucas-cranach-the-younger', 'lucas-cranach-the-younger-and-workshop');

-- ─── Vincenzo Foppa ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436311","paragraph":"Madonna and Child, painted by Vincenzo Foppa around 1475 in tempera and oil on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian devotional panel from his mature Lombard workshop years. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; the chromatic palette of warm flesh, deep crimson, and the unmistakable Foppa cool grey-green that defines the Lombard pictorial tradition is characteristic of his mature manner. The panel demonstrates Foppa's characteristic combination of Paduan figural discipline (descending from Squarcione and through Mantegna) and the soft chromatic warmth that defined the Lombard pictorial tradition before Leonardo's Milanese workshop years would transform it in the early sixteenth century."}
]$JSON$::jsonb
where slug = 'vincenzo-foppa';

-- ─── Gentile da Fabriano ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436452","paragraph":"Madonna and Child with Angels, painted by Gentile da Fabriano around 1408 (or possibly slightly later) in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian devotional panel from the early or middle career of the supreme Italian master of the International Gothic style. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; small attending angels lean in at her shoulders. The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable Gentile da Fabriano signature, and the elegant figural elongation and careful decorative detail demonstrate his characteristic combination of Italian Renaissance figural drawing with the older Burgundian-courtly International Gothic decorative refinement. The panel is one of the principal Gentile da Fabriano Madonnas in any American collection."}
]$JSON$::jsonb
where slug = 'gentile-da-fabriano-gentile-di-niccol-di-giovanni-di-massio';

-- ─── Daniele da Volterra ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-370853","paragraph":"Study for the Figure of Saint Peter, drawn by Daniele da Volterra around 1540 (early in his Roman career, in the workshop he ran while assisting Michelangelo) in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of his many painted altarpiece compositions. The drawing shows the apostle Peter in three-quarter view, his arms raised in a complex foreshortened pose, the muscular figural anatomy demonstrating Daniele's close absorption of the Michelangelo figural drawing tradition that he was learning at first hand during his close personal and professional association with the master in the late 1540s and 1550s. The sheet is among the principal Daniele drawings in any American collection."}
]$JSON$::jsonb
where slug = 'daniele-da-volterra-daniele-ricciarelli';

-- ─── Gerrit van Honthorst ──────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-370849","paragraph":"Susanna and the Elders, painted by Gerrit van Honthorst around 1620 in oil on canvas during his late Italian years in Rome and now in the Metropolitan Museum of Art in New York, illustrates the deuterocanonical narrative from Daniel 13 in which the chaste Susanna is spied upon while bathing by two elders of her community who later attempt to extort her into adultery and, when she refuses, falsely accuse her of the crime themselves. Honthorst stages the scene with characteristic Caravaggesque compositional drama: Susanna in the foreground partially undressed beside her bath, the two elders in the bushes at the lower left looking on, the dramatic single-source candlelit chiaroscuro defining the entire composition. The painting belongs to the late Italian-period Honthorst output that earned him the Italian nickname Gherardo delle Notti (Gerard of the Nights) for his specialty in candlelit nocturnal scenes."}
]$JSON$::jsonb
where slug = 'gerrit-van-honthorst';

-- ─── Hendrick ter Brugghen ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435817","paragraph":"The Crucifixion with the Virgin and Saint John, painted by Hendrick ter Brugghen around 1624 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment of Christ's death on the cross with the conventional Northern composition of the swooning Virgin and the mourning John the Evangelist. Ter Brugghen stages the scene with characteristic Utrecht Caravaggesque chiaroscuro: the body of Christ on the cross at the upper center against a darkening sky, the Virgin in the arms of John on the left in the foreground, both figures rendered in a particularly silvery cool chromatic palette that distinguished ter Brugghen's work from the warmer Caravaggesque manner of his Utrecht colleagues Honthorst and Baburen. The painting is among the principal ter Brugghen religious works in any American collection and a defining example of the Utrecht Caravaggesque manner at full mature statement."}
]$JSON$::jsonb
where slug = 'hendrick-ter-brugghen';

-- ─── Jan Lievens ───────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-367171","paragraph":"Adoration of the Shepherds, etched by Jan Lievens around 1620 in his Leiden workshop years (during the period he shared a studio with the young Rembrandt), depicts the moment from Luke 2 in which the shepherds, having heard the angels' announcement of the birth of Christ, arrive at the small dwelling at Bethlehem to find the newborn child laid in the manger. Lievens stages the scene with characteristic Leiden-period dramatic chiaroscuro: the seated Virgin holding the swaddled Christ Child illuminated by a single source of golden light, Joseph waiting behind, three peasant shepherds in the foreground in postures of recognition and tender adoration. The print is one of the principal early Lievens etchings and demonstrates the dramatic Caravaggesque manner that he and the young Rembrandt were both developing in their shared Leiden studio in the late 1620s."},
  {"artwork_slug":"met-747592","paragraph":"The Resurrection of Lazarus, etched by Jan Lievens around 1620 in his Leiden workshop, illustrates the climactic miracle of John 11. Lievens stages the scene with characteristic Leiden-period dramatic chiaroscuro: Christ at the lower left with his right arm extended in command, the bound figure of Lazarus emerging upright from the open tomb at the upper right, the sisters Martha and Mary kneeling between them at Christ's feet, and a small crowd of witnesses gathered behind. The print was painted in close stylistic dialogue with Rembrandt's own Lazarus etching of about 1632; the Lievens-Rembrandt Leiden studio years produced a remarkable body of paintings and etchings on shared subjects, with the two painters in stylistic competition with each other across nearly identical subject matter."},
  {"artwork_slug":"met-367172","paragraph":"Saint Jerome, etched by Jan Lievens around 1620 in his Leiden workshop, depicts the early Church Father in the conventional iconographic posture of his hermit years — half-naked, kneeling on his rocks, with his small open book and his lion (the iconographic attribute that distinguishes Jerome from any other bearded saint) at his feet. Lievens stages the scene with characteristic Leiden-period dramatic Caravaggesque chiaroscuro and a particularly strong contrast between the dark cave of the saint's retreat and the small bright opening to the sky above. The print is one of the principal early Lievens etchings and demonstrates the dense narrative composition and atmospheric tonal range that defined his Leiden-studio output."}
]$JSON$::jsonb
where slug = 'jan-lievens';

-- ─── Alonso Cano ───────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-335315","paragraph":"Virgin Interceding for Those in Purgatory, drawn by Alonso Cano around 1650 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Virgin Mary interceding with Christ for the souls in Purgatory — a particular Spanish Counter-Reformation devotional preference deriving from the Catholic doctrine that Marian intercession could shorten the time the souls of the recently dead must spend in purgatorial purification before their admission to heaven. Cano composes the scene as a vertical visionary composition: the Virgin at the upper center kneeling before Christ in attitude of supplication, the souls in Purgatory rising in the lower register through the cleansing flames toward her intercession. The drawing demonstrates Cano's characteristic combination of Sevillian draughtsmanship and the Granada-Madrid courtly devotional sensibility."},
  {"artwork_slug":"met-411391","paragraph":"Christ on the Mount of Olives (with a study of a cypress on the verso), drawn by Alonso Cano around 1640 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the Agony in the Garden as recorded in the Synoptic Gospels: Christ kneels in prayer before the angel bearing the cup of the Passion, while the three sleeping disciples are gathered in the foreground and Judas with the Roman soldiers approach through the garden gate at the rear. Cano stages the scene with characteristic Spanish Baroque dramatic compositional density. The verso of the sheet — a small study of a cypress tree — demonstrates Cano's lifelong interest in the careful botanical observation that informed his many landscape backgrounds across his painted output."},
  {"artwork_slug":"met-335321","paragraph":"Madonna and Child, drawn by Alonso Cano around 1640 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his many painted Marian compositions across his Spanish Baroque career. The drawing shows the seated Virgin in three-quarter view holding the standing Christ Child upright on her lap. The combination of pen-and-ink with the soft wash technique demonstrates the rapid confident draughtsmanship that the Sevillian workshop tradition descending from Pacheco had refined to a high pitch and that Cano absorbed during his early Sevillian apprentice years before his move to Madrid and Granada."}
]$JSON$::jsonb
where slug = 'alonso-cano';

-- ─── Pier Francesco Mola ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340806","paragraph":"Conversion of Saint Paul, drawn by Pier Francesco Mola around 1650 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the moment from Acts 9 in which Saul falls from his horse on the road to Damascus blinded by the light from heaven. Mola stages the scene with characteristic mid-seventeenth-century Roman Baroque compositional drama: Saul fallen on the ground in the foreground, his horse rearing in alarm beside him, the divine appearing as a foreshortened Christ in the upper register pulling apart the clouds. The drawing demonstrates Mola's characteristic combination of Bolognese figural discipline with the Venetian color and atmosphere that defined his mid-career Roman manner."},
  {"artwork_slug":"met-340805","paragraph":"Saint John the Baptist Preaching, drawn by Pier Francesco Mola around 1650 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the cousin of Christ in his desert ministry of preaching as recorded in the Synoptic Gospels. Mola stages the scene as a panoramic outdoor encounter: the Baptist standing at the upper center on a small rocky outcrop, his right hand raised in the act of preaching, the assembled crowd of listeners gathered around him in the foreground in postures of attentive listening, the Italian wilderness opening behind. The drawing demonstrates Mola's characteristic preference for the solitary saint-and-hermit subject set in dramatic Italian landscape."},
  {"artwork_slug":"met-437101","paragraph":"The Rest on the Flight into Egypt, painted by Pier Francesco Mola around 1636 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Holy Family pausing in their flight from Herod's persecution. Mola stages the scene as a tender outdoor encounter in a wild Italian landscape: the seated Virgin in profile holding the swaddled Christ Child, Joseph waiting nearby with the small donkey, a small landscape opening behind to a low Italian horizon. The chromatic palette and the careful atmospheric handling demonstrate Mola's characteristic combination of Bolognese figural discipline and Venetian-influenced warm color, painted in the years immediately before his return to Rome from his northern Italian study trips of the 1630s."}
]$JSON$::jsonb
where slug = 'pier-francesco-mola';

-- ─── Giovanni Lanfranco ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-339100","paragraph":"Design for a Wall Decoration with the Sacrifice of Abraham, drawn by Giovanni Lanfranco around 1620 in his early Roman workshop years in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of the wall-decoration commissions Lanfranco was producing in his early Roman career under Pope Paul V and his nephew Cardinal Scipione Borghese. The drawing shows the climactic moment of Genesis 22 in which the angel descends to stop Abraham from sacrificing his son Isaac on the altar at the top of Mount Moriah. The composition demonstrates the early Lanfranco combination of late-Carraccian figural discipline with the new Caravaggesque dramatic intensity that defined the Roman pictorial scene of the 1610s and early 1620s, in the years immediately before Lanfranco's great Sant'Andrea della Valle cupola fresco of 1625–1627 transformed his career."}
]$JSON$::jsonb
where slug = 'giovanni-lanfranco';

-- ─── Pieter Aertsen ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338133","paragraph":"Raguel's Reception of Tobias at Ecbatana, drawn by Pieter Aertsen around 1550 in pen and ink on paper and now in the Metropolitan Museum of Art in New York, illustrates an episode from the deuterocanonical Book of Tobit in which the young Tobias, traveling under the protection of the angel Raphael, arrives at the home of Raguel in the Median city of Ecbatana — the household into which Tobias will marry Raguel's daughter Sarah. Aertsen stages the scene as a large domestic interior encounter with characteristic Northern Mannerist compositional density: Raguel at the right greeting the arriving Tobias in formal welcome, the angel Raphael behind Tobias, household servants in the deeper background in postures of attentive welcome, the small interior of the Ecbatana home carefully detailed in the unmistakable Aertsen-domestic-genre manner that the artist had largely invented and was producing in dozens of variants across his Antwerp workshop years."}
]$JSON$::jsonb
where slug = 'pieter-aertsen';
