-- Wikidata Q-IDs for bio'd artists.
-- Generated by scripts/backfill-wikidata-ids.mjs.
-- Each Q-ID was selected by:
--   * Wikidata wbsearchentities lookup on the display name.
--   * wbgetentities verification of:
--       - instance_of includes human (Q5)
--       - occupation includes a recognized art occupation
--       - date_of_birth year is within ±5 of our row
-- Rows with no confident match are emitted as comments.

-- Andrea della Robbia (1435–1525)  →  Q195655  Italian Renaissance sculptor, especially in ceramics (1435–1525)
update public.artists set wikidata_id = 'Q195655' where slug in ('andrea-della-robbia');

-- Artemisia Gentileschi (1593–1654)  →  Q212657  Italian Baroque painter (1593-1651)
update public.artists set wikidata_id = 'Q212657' where slug in ('artemisia-gentileschi');

-- Aurelio Luini (1530–1593)  →  Q1071000  Italian painter (c.1530-1593)
update public.artists set wikidata_id = 'Q1071000' where slug in ('aurelio-luini');

-- Barent Fabritius (1624–1673)  →  Q261496  Dutch painter (1624-1673)
update public.artists set wikidata_id = 'Q261496' where slug in ('barent-fabritius');

-- Bramantino (Bartolomeo Suardi) (1460–1530)  →  Q7799  Italian painter and architect (1465-1530)
update public.artists set wikidata_id = 'Q7799' where slug in ('bramantino-bartolomeo-suardi');

-- Carlo Saraceni (1579–1620)  →  Q938607  Italian painter (1579-1620)
update public.artists set wikidata_id = 'Q938607' where slug in ('carlo-saraceni');

-- Cesare da Sesto (1477–1523)  →  Q1056977  Italian painter (1477-1523)
update public.artists set wikidata_id = 'Q1056977' where slug in ('cesare-da-sesto');

-- Charles Le Brun (1619–1690)  →  Q271676  17th-century French painter and art theorist (1619—1690)
update public.artists set wikidata_id = 'Q271676' where slug in ('charles-le-brun');

-- Daniele Crespi (1597–1630)  →  Q25200  Italian painter (1598-1630)
update public.artists set wikidata_id = 'Q25200' where slug in ('daniele-crespi');

-- Donatello (1386–1466)  →  Q37562  Early Renaissance Italian sculptor (1386–1466)
update public.artists set wikidata_id = 'Q37562' where slug in ('donatello');

-- Frans Floris I (1519–1570)  →  Q543948  Flemish painter (1519–1570)
update public.artists set wikidata_id = 'Q543948' where slug in ('frans-floris-i');

-- Gaudenzio Ferrari (1475–1546)  →  Q734108  Italian painter (1475–1546)
update public.artists set wikidata_id = 'Q734108' where slug in ('gaudenzio-ferrari');

-- Giovanni Battista Caracciolo (1578–1635)  →  Q2519261  Neapolitan artist and follower of Caravaggio (1578-1635)
update public.artists set wikidata_id = 'Q2519261' where slug in ('giovanni-battista-caracciolo');

-- Giovanni della Robbia (1469–1530)  →  Q1010700  Italian sculptor (1469–1529)
update public.artists set wikidata_id = 'Q1010700' where slug in ('giovanni-della-robbia');

-- Johannes Vermeer (1632–1675)  →  Q41264  Dutch painter (1632–1675)
update public.artists set wikidata_id = 'Q41264' where slug in ('johannes-vermeer');

-- Laurent de La Hyre (1606–1656)  →  Q59894  French painter and engraver (1606-1656)
update public.artists set wikidata_id = 'Q59894' where slug in ('laurent-de-la-hyre');

-- Luca della Robbia (1399–1482)  →  Q194977  Italian sculptor (1399–1482)
update public.artists set wikidata_id = 'Q194977' where slug in ('luca-della-robbia');

-- Nicolas Mignard (1606–1668)  →  Q2555178  French painter (1606-1668)
update public.artists set wikidata_id = 'Q2555178' where slug in ('nicolas-mignard');

-- Paolo Uccello (Paolo di Dono) (1397–1475)  →  Q192488  Italian painter (1397-1475)
update public.artists set wikidata_id = 'Q192488' where slug in ('paolo-uccello-paolo-di-dono');

-- Philippe de Champaigne (1602–1674)  →  Q314814  French painter (1602–1674)
update public.artists set wikidata_id = 'Q314814' where slug in ('philippe-de-champaigne');

-- Pierre Mignard (1612–1695)  →  Q360010  French painter (1612-1695)
update public.artists set wikidata_id = 'Q360010' where slug in ('pierre-mignard');

-- skip  Vittore Crivelli (1465–1502)  slugs='vittore-crivelli'
--   Q1349738 birth-year mismatch: db=1465 wd=1440


-- ─────────────────────────────────────────────────────────────────────
-- Manual override for the one skipped row above. Q-ID taken directly
-- from the rejection log; DB 1465 vs Wikidata 1440 — Wikidata's earlier
-- date is the more authoritative.
-- ─────────────────────────────────────────────────────────────────────

-- Vittore Crivelli — Venetian-Marche painter, c.1440–1502, brother of Carlo.
update public.artists set wikidata_id = 'Q1349738' where slug = 'vittore-crivelli';
