-- Notable works (phase 6) — single-paragraph essays for the phase-11
-- anchor artists. Same conventions: each paragraph ~180-280 words,
-- no double quotes inside the JSON, exact slug matching, every
-- artwork_slug verified against the live DB.

-- ─── Vermeer ───────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437877","paragraph":"Allegory of the Catholic Faith, painted by Johannes Vermeer around 1670–1672 in oil on canvas and now in the Metropolitan Museum of Art in New York, is one of just two openly religious paintings in Vermeer's surviving catalogue (the other being his early Christ in the House of Martha and Mary in Edinburgh). The painting depicts a seated woman in white-and-blue costume — the personification of Faith — with her foot resting on a globe, an apple at her feet (Eden), and a serpent crushed beneath the cornerstone, with a chalice and a crucifix on the table beside her. The composition derives from a 1644 engraved emblem in Cesare Ripa's Iconologia, the standard Italian Counter-Reformation handbook of personifications. The painting was almost certainly commissioned by a Catholic patron — Vermeer had probably converted to Catholicism in 1653 around his marriage into the Catholic Bolnes family — and is among the most-debated works in his small surviving catalogue. The painting entered the Metropolitan in 1931 and is the only Vermeer in the museum's collection."}
]$JSON$::jsonb
where slug = 'johannes-vermeer';

-- ─── Donatello ─────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-191181","paragraph":"Madonna and Child, modeled by Donatello around 1450 in painted-and-gilded stucco and now in the Metropolitan Museum of Art in New York, is one of the small low-relief Madonna compositions Donatello produced in his late Florentine workshop years for the private domestic devotional market. The Virgin sits in three-quarter view holding the Christ Child against her chest in a tender intimate posture; the relief is modeled with the soft sfumato shallow carving Donatello pioneered (the technique now called rilievo schiacciato — flattened relief) and originally polychrome painted in flesh tones for the figures and gilded for the haloes and decorative borders. Workshop and follower copies of Donatello's Madonna compositions circulated through the Florentine Quattrocento devotional market in editions; the Met version is among the principal early examples and demonstrates Donatello's foundational role in shaping the standard Florentine domestic-altar Madonna type."},
  {"artwork_slug":"met-194856","paragraph":"Virgin and Child, modeled by Donatello around 1430 in painted-and-gilded stucco and now in the Metropolitan Museum of Art in New York, is another of the small low-relief Madonna compositions from his Florentine workshop years. The composition shows the Virgin in three-quarter view with the standing Christ Child upright on her lap, the figures rendered in Donatello's characteristic soft-sfumato shallow-relief technique. The polychrome surface (now substantially worn) originally combined flesh-toned painting on the figures with gilded haloes and decorative borders. Pieces of this kind — small-format devotional reliefs intended for the private household altar of a Florentine merchant or banker — were produced in Donatello's workshop in editions and were among the most widely distributed of his domestic devotional output across Florence and the broader Tuscan region in the second quarter of the Quattrocento."},
  {"artwork_slug":"met-191892","paragraph":"Madonna and Child, modeled by Donatello around 1445 in painted-and-gilded stucco and now in the Metropolitan Museum of Art in New York, is from the middle phase of his domestic-altar Madonna series. The Virgin holds the Christ Child against her shoulder in a tender intimate compositional formula that Donatello effectively invented and that the Florentine Quattrocento tradition would replicate in dozens of follower-and-workshop variants for the next half-century. The shallow-relief modeling and the originally polychrome surface demonstrate Donatello's signature combination of sculptural innovation with the Florentine domestic devotional tradition; the type was the standard Florentine private-altar Marian image until Andrea della Robbia's polychrome glazed terracottas displaced it in the 1480s."},
  {"artwork_slug":"met-192721","paragraph":"Madonna and Child, modeled by Donatello around 1400 (early in his career, in his pre-mature Florentine workshop years) in painted-and-gilded stucco and now in the Metropolitan Museum of Art in New York, is one of the earliest dated Donatello domestic Madonnas — modeled at a moment when Donatello had just begun his independent career after leaving Lorenzo Ghiberti's Florentine workshop where he had assisted on the Baptistery doors. The composition follows the late-Trecento Florentine devotional Madonna type that Donatello was beginning to transform with his new shallow-relief sfumato technique; the panel demonstrates the Florentine workshop tradition at the moment of transition from late-medieval to fully Renaissance pictorial-sculptural vocabulary."}
]$JSON$::jsonb
where slug = 'donatello';

-- ─── Andrea della Robbia ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-205116","paragraph":"Virgin and Child, modeled by Andrea della Robbia around 1465 in glazed terracotta and now in the Metropolitan Museum of Art in New York, is one of the small-format glazed-terracotta Madonnas from his early Florentine workshop years. The composition shows the Virgin in three-quarter view holding the Christ Child upright against her chest; the figures glazed in the unmistakable Della Robbia white tin-oxide for the flesh, the drapery in deep saturated cobalt blue against the deep ultramarine ground that became the workshop signature. The roundel is among the standard Della Robbia private-devotional formats — small enough to hang above the altar in a Florentine merchant's household chapel but durable enough to survive five centuries of continuous display."},
  {"artwork_slug":"met-204567","paragraph":"Virgin Adoring the Christ Child, modeled by Andrea della Robbia around 1479 in glazed terracotta and now in the Metropolitan Museum of Art in New York, is from the central productive period of his Florentine workshop. The composition shows the Virgin kneeling in profile with her hands folded in adoration before the newborn Christ Child laid on the ground in front of her — the iconographic compositional type known as the Adoration of the Christ Child, derived from Marian devotional contemplation rather than from a specific Gospel narrative. The glazed-terracotta surface — white tin-oxide for the flesh, deep ultramarine for the ground, the carefully observed garland of fruit and flowers around the central scene — is the unmistakable Andrea della Robbia signature."},
  {"artwork_slug":"met-198564","paragraph":"Virgin Adoring the Christ Child, modeled by Andrea della Robbia around 1479 in glazed terracotta and now in the Metropolitan Museum of Art in New York, is a workshop variant of the same Adoration composition as the related 1479 panel — the Della Robbia workshop produced multiple versions of standard compositions in workshop variants for distribution across the Florentine and broader Tuscan domestic-altar market. The minor variations between versions (the precise composition of the fruit-and-flower garland, the exact angle of the Virgin's head, the small details of the surrounding architectural framing) demonstrate the workshop's standard practice of producing editions of successful compositions while preserving the supreme tin-oxide white flesh and saturated blue background that defined the Della Robbia visual brand."},
  {"artwork_slug":"met-208764","paragraph":"Nativity, modeled by Andrea della Robbia around 1485 in glazed terracotta and now in the Metropolitan Museum of Art in New York, depicts the moment of the birth of Christ in the small dwelling at Bethlehem. The composition shows the Virgin kneeling in profile in adoration before the newborn Christ Child laid on her cloak in the foreground, Joseph standing behind in formal attendance, the small thatched stable of Bethlehem rising behind. The polychrome glazed surface — flesh-white for the figures, deep ultramarine for the ground, swag-and-fruit garland borders, and the characteristic Della Robbia blue-green for the small trees and rocks — demonstrates the mature Andrea della Robbia workshop signature at the height of its commercial productivity in the 1480s."},
  {"artwork_slug":"met-186236","paragraph":"The Assumption of the Virgin, modeled by Andrea della Robbia around 1485 in glazed terracotta and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Virgin Mary's bodily assumption into heaven at her death. The Virgin floats in a luminous mandorla in the upper center of the panel; small attending angels surround her on every side; the apostles gather at the open tomb in the lower foreground in postures of astonishment. The composition was one of Andrea della Robbia's standard altarpiece subjects for Catholic Counter-Reformation parish-church commissions across Tuscany, and survives in workshop variants in numerous Tuscan ecclesiastical sites alongside the Met version."}
]$JSON$::jsonb
where slug = 'andrea-della-robbia';

-- ─── Luca della Robbia ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-204722","paragraph":"Virgin and Child in a Niche, modeled by Luca della Robbia around 1455 in glazed terracotta and now in the Metropolitan Museum of Art in New York, is one of the small early glazed-terracotta Madonnas from the workshop in the years immediately after Luca's invention of the technique around 1440. The composition shows the standing Virgin in a small architectural niche holding the Christ Child against her chest; the figures glazed in the unmistakable Della Robbia white tin-oxide for the flesh, the niche framed in deep ultramarine, the small architectural details (the carved capitals, the egg-and-dart molding around the niche frame) demonstrating Luca's combination of Florentine sculptural discipline and the new ceramic medium he had effectively invented. The piece is among the earliest small-format glazed-terracotta Madonnas in any American collection."}
]$JSON$::jsonb
where slug = 'luca-della-robbia';

-- ─── Giovanni della Robbia ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-189283","paragraph":"Kneeling Madonna, modeled by Giovanni della Robbia around 1485 in glazed terracotta and now in the Metropolitan Museum of Art in New York, is one of the early Giovanni della Robbia compositions from the years immediately after his father Andrea's death when Giovanni had just inherited direction of the family workshop. The composition shows the Virgin kneeling in profile with her hands folded in adoration before the Christ Child; the polychrome glazed surface continues the Andrea della Robbia signature combination of white tin-oxide for the flesh and deep ultramarine for the ground, but with the slightly looser figural proportions and softer compositional handling that characterize Giovanni's workshop production."},
  {"artwork_slug":"met-192684","paragraph":"Pietà, modeled by Giovanni della Robbia around 1500 in glazed terracotta and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the seated Virgin holding the dead body of Christ across her lap immediately after the Deposition. Giovanni della Robbia stages the scene with characteristic late-Della-Robbia compositional density: the Virgin in three-quarter view supporting the body of Christ, John the Evangelist standing behind in formal attendance, the Magdalene kneeling at the feet. The polychrome glazed surface — white tin-oxide for the flesh, deep saturated drapery color, the swag-of-fruit garland border that became the unmistakable Della Robbia decorative trademark — demonstrates the workshop's late-Quattrocento mature commercial productivity."},
  {"artwork_slug":"met-197028","paragraph":"Madonna and Child, modeled by Giovanni della Robbia around 1500 in glazed terracotta and now in the Metropolitan Museum of Art in New York, is one of the standard small-format Della Robbia roundels Giovanni's workshop produced in editions for the Florentine and broader Tuscan domestic-altar market. The composition shows the Virgin in three-quarter view holding the standing Christ Child upright on her lap, framed by the swag-of-fruit garland border that became the Della Robbia decorative signature. The polychrome glazed surface and the minor stylistic variations between this and Andrea's earlier comparable Madonnas demonstrate the workshop's continued productivity into the early sixteenth century before the High Renaissance taste for marble and bronze sculpture began to displace the older glazed-terracotta tradition."}
]$JSON$::jsonb
where slug = 'giovanni-della-robbia';

-- ─── Paolo Uccello ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-438028","paragraph":"The Crucifixion, painted by Paolo Uccello around 1453 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of Christ's death on the cross with the conventional Florentine Quattrocento attendant figures of the swooning Virgin and the mourning John the Evangelist. Uccello stages the scene with characteristic mid-Quattrocento Florentine compositional discipline: the cross at the upper center against a darkening sky, the swooning Virgin in the arms of the holy women on the left, John on the right in postures of restrained sorrow, the small angels in the upper register catching the falling blood from the wounds in chalices. The chromatic palette of saturated crimson, ultramarine, and tooled gold is characteristic of Uccello's mature workshop manner, and the careful linear perspective of the small landscape under the cross demonstrates his lifelong fascination with the new Renaissance science of pictorial space."}
]$JSON$::jsonb
where slug = 'paolo-uccello-paolo-di-dono';

-- ─── Artemisia Gentileschi ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"gentileschi-judith-jud8","paragraph":"Judith Beheading Holofernes, painted by Artemisia Gentileschi around 1620 in oil on canvas, depicts the climactic moment of the deuterocanonical Book of Judith in which the young Hebrew widow saws through the neck of the drunken Assyrian general in his command tent. Artemisia stages the act with extraordinary visceral physical realism: Judith leans into the body with the muscular grip of her arms, the elderly servant Abra holds open the linen sack to receive the head, the spurting blood arcs across the white sheets of the bed, the body of Holofernes pressed back against the pillow with his eyes still open. The Uffizi version of this composition (with closely related earlier and later workshop variants in Naples and Detroit) is widely held to be Artemisia's masterpiece and one of the most visceral treatments of the Judith subject in the entire history of European painting. The female-centered narrative perspective — Judith and Abra working together with the cool determination of professional craftswomen, against a male body that has been reduced from threatening tyrant to bound victim — distinguishes Artemisia's treatments sharply from her male contemporaries' versions of the subject."},
  {"artwork_slug":"met-436453","paragraph":"Esther before Ahasuerus, painted by Artemisia Gentileschi around 1620 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the climactic moment of Esther 5 in which the young Hebrew queen, having fasted three days for courage, enters the throne room of King Ahasuerus uninvited (an act punishable by death) to plead for the lives of her people the Jews. Artemisia stages the scene as a dramatic three-quarter-length encounter: Esther on the right in the act of swooning into the arms of her two attendants, the king on the left rising from his throne in startled response, his scepter extended toward her in the gesture of welcome that pardons her capital offense. The chromatic palette of saturated crimson, gold, and pale silver-blue against the dark architectural ground is characteristic of Artemisia's middle career, and the painting is one of the principal Artemisia treatments of an Old Testament heroine subject."}
]$JSON$::jsonb
where slug = 'artemisia-gentileschi';

-- ─── Bramantino ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-435768","paragraph":"Madonna and Child, painted by Bramantino around 1507 in tempera and oil on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian devotional panel from the central productive period of his Milanese workshop years. The Virgin sits in three-quarter view holding the Christ Child upright on her lap; the chromatic palette of warm flesh, deep crimson, and the cool grey-green that defines the Lombard tradition is characteristic of Bramantino's mature manner. The painting demonstrates his characteristic combination of Bramantesque architectural-perspective discipline (in the small architectural setting that frames the figures) and the soft Lombard chromatic warmth that he absorbed from his early-career exposure to Vincenzo Foppa's late workshop."}
]$JSON$::jsonb
where slug = 'bramantino-bartolomeo-suardi';

-- ─── Gaudenzio Ferrari ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338641","paragraph":"Standing Virgin Holding the Christ Child, drawn by Gaudenzio Ferrari around 1475 (early in his career — though the dating is contested; some scholars place the drawing decades later) in pen and ink on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his many painted Marian compositions. The drawing shows the standing Virgin in three-quarter view holding the small Christ Child against her chest; the rapid confident pen technique demonstrates the late-Quattrocento Lombard workshop tradition that Gaudenzio absorbed during his apprentice years before developing the distinctive Piedmontese-Northern emotional intensity that would define his mature work at the Sacro Monte sanctuary of Varallo."},
  {"artwork_slug":"met-459437","paragraph":"Madonna and Child with Saints Martin and Maurice, painted by Gaudenzio Ferrari around 1527 in oil on panel and now in the Metropolitan Museum of Art in New York, is a small altarpiece panel from the central productive period of his Lombard-Piedmontese career. The composition shows the seated Virgin holding the Christ Child upright on her lap, with two attendant saints — Martin on horseback (the iconographic attribute that distinguishes him from any other male saint) and Maurice in soldier's armor — standing on either side in formal devotional grouping. The chromatic palette of saturated crimson, ultramarine, and warm Piedmontese flesh is characteristic of Gaudenzio's mature manner, and the panel demonstrates his ability to combine the Lombard pictorial tradition with the particularly Piedmontese-Northern emotional intensity that defined his entire output."}
]$JSON$::jsonb
where slug = 'gaudenzio-ferrari';

-- ─── Frans Floris ──────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-336019","paragraph":"Christ Driving the Money Changers from the Temple, drawn by Frans Floris around 1530 (the dating is somewhat early — Floris would have been a teenager) in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the scene from John 2 (and parallel passages in the Synoptics) in which Christ overturns the tables of the money-changers and dove-sellers in the outer court of the Temple. The drawing shows Christ at the center of the composition with his arm raised in the act of driving out the merchants; the money-changers in postures of flight and resistance; the Temple architecture rising behind. The drawing demonstrates the early Floris draughtsmanship and the rapid confident pen-and-wash technique that the Antwerp Mannerist tradition would later refine in the post-Italian decades after Floris's transformative Italian sojourn of 1541–1545."}
]$JSON$::jsonb
where slug = 'frans-floris-i';

-- ─── Carlo Saraceni ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-438690","paragraph":"The Dormition of the Virgin, painted by Carlo Saraceni around 1607 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment from the apocryphal Marian narrative in which the Virgin Mary, dying in her old age, is attended on her deathbed by the assembled apostles. Saraceni stages the scene with characteristic Caravaggesque-Venetian compositional drama: the Virgin lies in the bed at the lower center, the apostles gather around her in dense devotional postures of grief and prayer, with Peter (identified by the pyx of the Eucharist in his hand) leaning in over the bed. The chromatic palette of saturated crimson, deep ultramarine, and warm flesh against the dark interior reflects Saraceni's combination of Roman Caravaggesque chiaroscuro with the warm Venetian color of his native Venice."},
  {"artwork_slug":"met-437607","paragraph":"Paradise, painted by Carlo Saraceni around 1593 (early in his career, in his Venetian apprentice years before the move to Rome) in oil on copper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the celestial court of the blessed in heaven gathered around the central enthroned figure of God. Saraceni stages the scene with characteristic late-Cinquecento Venetian compositional density: God enthroned in glory at the upper center surrounded by the choirs of angels, the saints and the blessed ranged in formal procession in the lower registers, the souls of the just rising up through the architectural levels of the heavenly hierarchy. The painting is among the early Saraceni works produced before his transformative Roman move and absorption of the Caravaggesque manner."}
]$JSON$::jsonb
where slug = 'carlo-saraceni';

-- ─── Battistello Caracciolo ────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-712946","paragraph":"The Calling of Saint Matthew, drawn by Battistello Caracciolo around 1625 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the moment from Matthew 9 in which Christ calls the tax collector Matthew to discipleship — the same subject Caravaggio had famously treated in his 1599–1600 Roman altarpiece for San Luigi dei Francesi. Battistello stages the scene with characteristic early-Neapolitan Caravaggesque compositional drama: Christ at the right with his arm extended in command, Matthew at the wooden tax-collecting table on the left in startled recognition, his small companions watching in attendance. The drawing demonstrates the Naples Caravaggesque tradition that Battistello and his generation developed directly from Caravaggio's brief but transformative Naples visit of 1606–1607."},
  {"artwork_slug":"met-812649","paragraph":"Saint John the Baptist with a Lamb, drawn by Battistello Caracciolo around 1610 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the cousin of Christ in his desert ministry holding the small lamb that became his iconographic attribute (the lamb refers to John's identification of Christ as the Lamb of God in John 1:29). Battistello stages the scene with characteristic Caravaggesque tonal restraint: the standing Baptist in three-quarter view holding the small lamb against his chest, the dark neutral background concentrating attention on the figure. The drawing demonstrates Battistello's lifelong interest in the single-figure half-length saint subject that defined the Naples Caravaggesque tradition of the early seventeenth century."}
]$JSON$::jsonb
where slug = 'giovanni-battista-caracciolo';

-- ─── Philippe de Champaigne ────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-438724","paragraph":"The Annunciation, painted by Philippe de Champaigne around 1639 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment from Luke 1 in which the angel Gabriel appears to the Virgin in her chamber to announce the conception of Christ. Philippe de Champaigne stages the scene with characteristic Paris-Flemish compositional discipline: the Virgin kneels at her prayer-desk on the right, the angel descends from the upper left in an attitude of greeting with the lily of purity in one hand, the Holy Spirit appears as a small dove on a beam of golden light from above. The chromatic palette of saturated rose, ultramarine, and warm flesh against the carefully detailed Northern interior reflects the early Champaigne combination of Flemish technique with the new Italianate Roman compositional discipline that defined his mature Paris workshop manner."},
  {"artwork_slug":"met-381975","paragraph":"The Presentation of the Virgin, drawn by Philippe de Champaigne around 1610 (early in his Brussels career, before his Paris move in 1621) in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the moment from the apocryphal Marian narrative in which the young Mary, at age three, is presented by her parents Anne and Joachim to the Temple in Jerusalem to be raised in the service of the Lord. The drawing shows the small Mary climbing the Temple steps toward the high priest who waits at the upper register, with Anne and Joachim standing in formal attendance behind. The drawing demonstrates the early Champaigne draughtsmanship before his Paris career began."},
  {"artwork_slug":"met-364540","paragraph":"View of Jerusalem with the Temple of Solomon, drawn by Philippe de Champaigne around 1610 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for an architectural-and-landscape composition of the Holy City. The drawing shows the panoramic view of Jerusalem from outside the city walls, with the great Temple of Solomon rising at the center of the composition and the surrounding city architecture and the Mount of Olives in the deeper background. The drawing reflects the seventeenth-century French interest in the careful topographical reconstruction of the Holy Land — a particular preoccupation of the Jansenist circle that would later shape Champaigne's mature Paris religious painting."}
]$JSON$::jsonb
where slug = 'philippe-de-champaigne';

-- ─── Charles Le Brun ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-434206","paragraph":"The Infant Jesus, drawn by Charles Le Brun around 1640 (early in his career, before his Italian sojourn of 1642–1646) in red and black chalk on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his early painted Marian compositions. The drawing shows the small Christ Child seated in a tender posture, his right arm raised in benediction, the soft sfumato modeling of the chalk demonstrating the early Le Brun absorption of his teacher Simon Vouet's Italianate French Baroque draughtsmanship. The drawing belongs to the early Le Brun preparatory output before his Italian sojourn transformed his style toward the Roman classicizing manner he would carry into his long French royal career."}
]$JSON$::jsonb
where slug = 'charles-le-brun';

-- ─── Laurent de La Hyre ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-384408","paragraph":"Conversion of Saint Paul, drawn by Laurent de La Hyre around 1632 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the moment from Acts 9 in which Saul falls from his horse on the road to Damascus blinded by the light from heaven. La Hyre stages the scene with characteristic Atticist compositional restraint: Saul fallen on the ground in the foreground, his horse rearing in alarm beside him, the divine appearing as a foreshortened figure in the upper register. The drawing is one of two La Hyre treatments of the Conversion subject in the Met collection (with the closely related 1637 version) and demonstrates the cool classicizing Paris manner that La Hyre helped establish across the second quarter of the seventeenth century."},
  {"artwork_slug":"met-384884","paragraph":"Raising of Lazarus, drawn by Laurent de La Hyre around 1620 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, illustrates the climactic miracle of John 11. La Hyre stages the scene with characteristic Atticist compositional discipline: Christ at the lower left with his right arm extended in command, the bound figure of Lazarus emerging upright from the open tomb at the upper right, the sisters Martha and Mary kneeling between them at Christ's feet, a small crowd of witnesses gathered behind. The drawing demonstrates the early La Hyre draughtsmanship before his characteristic cool classicizing manner had fully developed."},
  {"artwork_slug":"met-384411","paragraph":"Virgin and Child with Angels, drawn by Laurent de La Hyre around 1639 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the enthroned Virgin holding the Christ Child attended by small music-making angels. La Hyre stages the scene with characteristic cool Atticist compositional restraint: the seated Virgin in three-quarter view holding the standing Christ Child upright on her lap, two small attendant angels lean in at her shoulders. The drawing demonstrates the mature La Hyre Atticist manner — figures composed with classical figural discipline against luminous classical landscapes — that defined the Paris school in the second quarter of the seventeenth century."},
  {"artwork_slug":"met-384888","paragraph":"Holy Family with Palm, drawn by Laurent de La Hyre around 1639 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Holy Family resting under a palm tree (the iconographic detail derives from the apocryphal Pseudo-Matthew narrative of the Flight into Egypt, in which the palm tree bows down to feed the Holy Family with its fruit). La Hyre stages the scene with characteristic Atticist compositional restraint: the seated Virgin holding the Christ Child, Joseph waiting beside the small donkey, the palm tree rising overhead. The drawing demonstrates the cool classicizing Paris manner of La Hyre's mature career."},
  {"artwork_slug":"met-384966","paragraph":"The Virgin and Christ Child Served by Angels, drawn by Laurent de La Hyre around 1640 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Virgin and Christ Child attended in heavenly service by small ministering angels. La Hyre stages the scene with characteristic cool Atticist compositional restraint: the seated Virgin holding the Christ Child at the center, attendant angels offering small dishes of fruit and bowls of milk, the entire encounter set against a luminous classical landscape with distant hills. The drawing demonstrates the mature La Hyre Atticist manner at full statement and is one of the principal La Hyre Marian devotional drawings in any American collection."}
]$JSON$::jsonb
where slug = 'laurent-de-la-hyre';

-- ─── Vittore Crivelli ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436056","paragraph":"Madonna and Child with Two Angels, painted by Vittore Crivelli around 1481 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small altarpiece panel from his Marche-regional workshop years. The composition shows the Virgin in three-quarter view holding the standing Christ Child upright on her lap; two small attending angels lean in at her shoulders to offer the Christ Child small bunches of fruit. The chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable late-Crivelli workshop signature, with the characteristic swag-and-fruit garland border decoration that distinguished both Crivelli brothers' altarpiece production across the Marche region."},
  {"artwork_slug":"met-436055","paragraph":"Madonna and Child Enthroned with Two Angels and a Donor, painted by Vittore Crivelli around 1481 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small altarpiece panel from the same Marche-regional workshop period. The composition shows the Virgin enthroned with the Christ Child on her lap in the conventional sacra conversazione format, with two small attending angels at her shoulders and a small kneeling donor figure in the lower foreground. The chromatic palette and the careful tooled-gold background continue the Vittore Crivelli workshop signature, and the panel demonstrates the close stylistic relationship between Vittore's painted output and his older brother Carlo's contemporary altarpiece production in the same Marche region."}
]$JSON$::jsonb
where slug = 'vittore-crivelli';

-- ─── Daniele Crespi ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338567","paragraph":"Saint John the Baptist, Saint Benedict, King David, and Saint Lawrence, drawn by Daniele Crespi (the dating is contested — the Met lists 1597, but Daniele Crespi was likely born around that year and could not have drawn it as an infant; the drawing is more probably from the 1620s) in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, is a preparatory drawing for one of his Lombard altarpiece commissions. The drawing shows the four saints arranged in formal symmetry: John the Baptist with his small reed cross on the far left, Saint Benedict with his Benedictine habit, King David with his harp, and Saint Lawrence with his iconographic gridiron on the far right. The drawing demonstrates the early Crespi draughtsmanship before his short brilliant career was cut short by the 1630 Milan plague."}
]$JSON$::jsonb
where slug = 'daniele-crespi';

-- ─── Pierre Mignard ────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-354278","paragraph":"Christ Carrying the Cross, drawn by Pierre Mignard around 1679 in his late Paris royal-court career in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the moment from the Synoptic Gospels in which Christ, after the scourging and the crowning with thorns, carries his cross through the streets of Jerusalem on the way to Golgotha. Mignard stages the scene with characteristic late-Baroque French compositional density: Christ in the center stumbling under the weight of the cross, Simon of Cyrene reaching to take a portion of the burden from his shoulders, the Roman soldiers driving him forward, the women of Jerusalem watching from the sides with expressions of grief. The drawing demonstrates the late Mignard Paris-court draughtsmanship at full mature statement."}
]$JSON$::jsonb
where slug = 'pierre-mignard';

-- ─── Nicolas Mignard ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-393510","paragraph":"The Visitation, etched by Nicolas Mignard around 1644 in his French workshop years (Nicolas was Pierre Mignard's older brother and worked principally as a printmaker and provincial painter in Avignon and other southern French cities), depicts the moment from Luke 1 in which the Virgin Mary visits her cousin Elizabeth and the unborn John the Baptist leaps in Elizabeth's womb at the recognition of the unborn Christ Child. Nicolas Mignard stages the scene as a tender domestic encounter: the Virgin at the right in profile embracing Elizabeth at the left, both figures in postures of glad recognition, Joseph waiting in the background and the high priest Zechariah (Elizabeth's husband) standing in attendance behind her. The print belongs to the long sequence of biblical-narrative engravings that Nicolas Mignard produced for the French Catholic devotional publishing market across the middle of the seventeenth century."}
]$JSON$::jsonb
where slug = 'nicolas-mignard';

-- ─── Aurelio Luini ─────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-340671","paragraph":"The Holy Family with the Infant Baptist, Saint Elizabeth, and Saint John, drawn by Aurelio Luini around 1550 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Holy Family attended by Elizabeth and the small John the Baptist in the conventional Lombard sacra conversazione format. The drawing shows the seated Virgin holding the small Christ Child, with the small John the Baptist embracing the Christ Child from the side, Elizabeth standing behind in formal attendance, Joseph waiting in the background. The drawing demonstrates the Luini family workshop signature continued into the second half of the sixteenth century by Aurelio after his father Bernardino's death."}
]$JSON$::jsonb
where slug = 'aurelio-luini';

-- ─── Cesare da Sesto ───────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-338487","paragraph":"The Holy Family with the Infant St. John the Baptist, drawn by Cesare da Sesto around 1510 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Holy Family attended by the small John the Baptist. The drawing shows the seated Virgin holding the small Christ Child, with the small John the Baptist embracing the Christ Child from the side, Joseph waiting in the background. The drawing demonstrates the early Cesare da Sesto draughtsmanship and his characteristic combination of Leonardesque sfumato modeling with the warm Lombard chromatic palette descending from Vincenzo Foppa — the synthesis that would define his entire workshop output."}
]$JSON$::jsonb
where slug = 'cesare-da-sesto';

-- ─── Barent Fabritius ──────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-436288","paragraph":"Abraham Dismissing Hagar and Ishmael, painted by Barent Fabritius around 1658 in oil on canvas and now in the Metropolitan Museum of Art in New York, illustrates the moment from Genesis 21 in which Abraham, at the urging of his wife Sarah, sends his concubine Hagar and their son Ishmael away into the wilderness. Barent Fabritius stages the scene as a tender outdoor encounter: Hagar at the right in the act of departure, the small Ishmael at her side, Abraham at the left in profile in attitude of patriarchal reluctance, with Sarah visible in the deeper background watching from the doorway of the household. The chromatic palette of warm earth tones and dramatic Caravaggesque chiaroscuro reflects the Rembrandt workshop tradition that Barent absorbed during his apprentice years and that defined the late-Rembrandt school output of the second half of the seventeenth century."}
]$JSON$::jsonb
where slug = 'barent-fabritius';
