-- Wikidata Q-IDs for bio'd artists.
-- Generated by scripts/backfill-wikidata-ids.mjs.
-- Each Q-ID was selected by:
--   * Wikidata wbsearchentities lookup on the display name.
--   * wbgetentities verification of:
--       - instance_of includes human (Q5)
--       - occupation includes a recognized art occupation
--       - date_of_birth year is within ±5 of our row
-- Rows with no confident match are emitted as comments.

-- Alessandro Algardi (1598–1654)  →  Q336798  Italian sculptor (1598–1654)
update public.artists set wikidata_id = 'Q336798' where slug in ('alessandro-algardi');

-- Alessandro Allori (1535–1607)  →  Q333369  Italian painter (1535–1607)
update public.artists set wikidata_id = 'Q333369' where slug in ('alessandro-allori');

-- Alessandro Casolani (1552–1606)  →  Q461700  Italian painter
update public.artists set wikidata_id = 'Q461700' where slug in ('alessandro-casolani');

-- Alessandro Magnasco (1667–1749)  →  Q516941  Italian painter (1667-1749)
update public.artists set wikidata_id = 'Q516941' where slug in ('alessandro-magnasco');

-- Alessandro Tiarini (1577–1668)  →  Q2248508  Italian painter (1577-1668)
update public.artists set wikidata_id = 'Q2248508' where slug in ('alessandro-tiarini');

-- Cosmè Tura (Cosimo di Domenico di Bonaventura) (1433–1495)  →  Q7129  Italian painter (1430-1495)
update public.artists set wikidata_id = 'Q7129' where slug in ('cosm-tura-cosimo-di-domenico-di-bonaventura');

-- Francesco Salviati (Francesco de' Rossi) (1510–1563)  →  Q704594  Italian painter (1510–1563)
update public.artists set wikidata_id = 'Q704594' where slug in ('francesco-salviati-francesco-de-rossi');

-- skip  Master of the Khludov Psalter (?–?)  slugs='khludov-master'
--   no candidates for "Master of the Khludov Psalter"

-- skip  Master of the Stuttgart Psalter (?–?)  slugs='stuttgart-psalter-master'
--   no candidates for "Master of the Stuttgart Psalter"

-- skip  Master of the Utrecht Psalter (?–?)  slugs='utrecht-psalter-master'
--   no candidates for "Master of the Utrecht Psalter"

-- skip  Segna di Buonaventura (1298–1331)  slugs='segna-di-buonaventura'
--   Q929809 birth-year mismatch: db=1298 wd=1280

-- Ventura Salimbeni (1568–1613)  →  Q1397817  Italian painter (1568-1613)
update public.artists set wikidata_id = 'Q1397817' where slug in ('ventura-salimbeni');


-- ─────────────────────────────────────────────────────────────────────
-- Manual overrides:
--   * Segna di Buonaventura — Q-ID from rejection log (DB birth year
--     1298 vs Wikidata's c.1280 is too wide for the script's tolerance).
--   * The three "Master of X Psalter" entries are anonymous workshops
--     and have no individual Wikidata person Q. They are pointed at the
--     respective manuscript entities — the manuscript is the canonical
--     Wikidata reference for the unnamed master in each case.
-- ─────────────────────────────────────────────────────────────────────

-- Segna di Buonaventura — Sienese painter and Duccio pupil, c.1280–1331.
update public.artists set wikidata_id = 'Q929809' where slug = 'segna-di-buonaventura';

-- Master of the Stuttgart Psalter → the Stuttgart Psalter manuscript itself.
update public.artists set wikidata_id = 'Q1819006' where slug = 'stuttgart-psalter-master';

-- Master of the Khludov Psalter → the Chludov Psalter manuscript itself.
update public.artists set wikidata_id = 'Q1751770' where slug = 'khludov-master';

-- Master of the Utrecht Psalter → the Utrecht Psalter manuscript itself.
update public.artists set wikidata_id = 'Q1322928' where slug = 'utrecht-psalter-master';
