-- Notable works (phase 7) — single-paragraph essays for the phase-12
-- anchor artists. Same conventions as 036–045: each paragraph
-- ~180-280 words, no double quotes inside the JSON, exact slug
-- matching, every artwork_slug verified against the live DB.

-- ─── Cosmè Tura ────────────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437849","paragraph":"The Flight into Egypt, painted by Cosmè Tura around 1470 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small predella panel from one of his late Ferrarese altarpiece commissions. The painting depicts the apocryphal subject of the Holy Family fleeing King Herod's persecution as recorded in Matthew 2: the Virgin riding on the small donkey holding the swaddled Christ Child, Joseph leading the donkey on foot through a craggy rocky landscape. Tura stages the scene with characteristic late-Quattrocento Ferrarese compositional intensity — figures in extreme proportional elongation, jewel-bright color (saturated crimson and ultramarine), and the angular dry handling of the rocky terrain that became the unmistakable Tura signature. The panel was almost certainly part of one of Tura's larger Ferrara altarpieces (the dispersed Roverella Altarpiece of 1474 has been suggested) before being separated from its parent structure in the eighteenth or nineteenth century."}
]$JSON$::jsonb
where slug = 'cosm-tura-cosimo-di-domenico-di-bonaventura';

-- ─── Segna di Buonaventura ─────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-437649","paragraph":"Christ Blessing, painted by Segna di Buonaventura around 1306 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the half-length Salvator Mundi (Christ Saviour of the World) — Christ in three-quarter view raising his right hand in benediction and holding a small book in his left. The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable Sienese late-Duccian signature, and the calm devotional face demonstrates Segna's close stylistic relationship to his teacher Duccio. The panel was almost certainly part of a larger polyptych altarpiece structure with the Madonna and Child at the center and individual saints in the side panels."},
  {"artwork_slug":"met-460152","paragraph":"The Crucifixion, painted by Segna di Buonaventura around 1312 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the moment of Christ's death on the cross with the conventional Sienese Trecento attendant figures of the swooning Virgin and the mourning John the Evangelist. The cross stands at the upper center against the tooled-gold background; the Virgin in the arms of the holy women on the left and John on the right are arranged in formal symmetry at the foot of the cross. The chromatic palette and the elongated figural proportions are characteristic of Segna's late-Duccian Sienese workshop manner."},
  {"artwork_slug":"met-460151","paragraph":"Madonna and Child with Nine Angels, painted by Segna di Buonaventura around 1312 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is a small intimate Marian devotional panel from his middle Sienese workshop years. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; nine attending angels — in three rows of three — occupy the spaces around the central group. The chromatic palette of saturated crimson, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable late-Duccian Sienese signature, and the panel demonstrates Segna's close stylistic relationship to Duccio's contemporary Maestà altarpiece for Siena Cathedral."},
  {"artwork_slug":"met-437651","paragraph":"Saint John the Evangelist, painted by Segna di Buonaventura around 1315 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, depicts the youngest of the four evangelists in the conventional iconographic posture of his apostolic teaching — standing in three-quarter view holding a small book and a small palm of martyrdom. The chromatic palette of saturated rose, ultramarine, and tooled gold against the patterned gold-tooled background is the unmistakable mid-career Segna signature. The panel was originally part of one of his Sienese polyptych altarpieces with the Virgin and Christ Child at the center and individual evangelists in the side panels."},
  {"artwork_slug":"met-437650","paragraph":"Madonna and Child, painted by Segna di Buonaventura around 1315 in tempera and gold on panel and now in the Metropolitan Museum of Art in New York, is another of his small intimate Marian devotional panels. The Virgin sits in three-quarter view holding the standing Christ Child upright on her lap; the chromatic palette and the tooled-gold background continue the late-Duccian Sienese workshop signature. The painting is among the principal small Segna Madonnas in any American collection and demonstrates the patient Sienese workshop continuation of the Duccian pictorial tradition through the first generation after Duccio's death in 1319."}
]$JSON$::jsonb
where slug = 'segna-di-buonaventura';

-- ─── Ventura Salimbeni ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-341154","paragraph":"The Ascension of Christ, drawn by Ventura Salimbeni around 1595 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the moment from Acts 1 in which Christ ascends into heaven from the Mount of Olives in the presence of the assembled apostles. Salimbeni stages the scene as a vertical composition: Christ rises in the upper register surrounded by attending angels and a luminous burst of light, the apostles gather below in a tight formal grouping looking up in attitudes of astonishment and farewell. The drawing demonstrates the late-Mannerist Sienese draughtsmanship that Salimbeni and his half-brother Francesco Vanni made into the Sienese pictorial signature of the late Cinquecento."},
  {"artwork_slug":"met-459499","paragraph":"Study for the Figure of Christ in a Deposition, drawn by Ventura Salimbeni around 1600 in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a small preparatory drawing for one of his painted Deposition compositions. The drawing shows the figure of Christ in three-quarter view, his arms outstretched, his body modeled in the soft sfumato red-chalk technique that the late-Cinquecento Florentine and Sienese workshop tradition had refined to a high pitch. Such drawings — focused single-figure studies — were the standard preparatory currency for late-Mannerist Italian altarpiece practice."},
  {"artwork_slug":"met-666311","paragraph":"The Virgin Seated with the Christ Child on Her Lap, drawn by Ventura Salimbeni around 1605 in pen and ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the seated Virgin holding the small Christ Child in tender embrace. Salimbeni stages the scene with characteristic late-Mannerist Sienese compositional sweetness: the Virgin in three-quarter view, the Christ Child seated on her lap reaching up to embrace her cheek, the small attending figures of John the Baptist and other Marian devotional figures completing the composition. The drawing demonstrates the late-Mannerist Sienese workshop signature at full mature statement."}
]$JSON$::jsonb
where slug = 'ventura-salimbeni';

-- ─── Francesco Salviati ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-341159","paragraph":"Virgin and Child with Saint Anne and John the Baptist, drawn by Francesco Salviati around 1545 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the Sacred Conversation among the seated Virgin holding the small Christ Child, her mother Saint Anne, and the small John the Baptist. Salviati stages the scene with characteristic late-Mannerist compositional density: the figures arranged in a pyramidal grouping, the Christ Child reaching toward the small John the Baptist while Anne supports the Virgin from behind. The drawing demonstrates the rapid confident pen-and-wash technique and the elongated Mannerist figural proportions that defined Salviati's mid-career Roman draughtsmanship under the patronage of Cardinal Salviati and the Farnese circle."}
]$JSON$::jsonb
where slug = 'francesco-salviati-francesco-de-rossi';

-- ─── Alessandro Allori ─────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-230977","paragraph":"The Gathering of Manna, painted by Alessandro Allori around 1595 in oil on canvas and now in the Metropolitan Museum of Art in New York, illustrates the moment from Exodus 16 in which the Israelites gather the manna sent down from heaven during their wilderness wandering. Allori stages the scene with characteristic late-Mannerist Florentine compositional density: a crowd of Israelites in the foreground in dense varied postures of gathering — kneeling, standing, bending — with their pots, baskets, and cloths spread across the ground, the small white grains of manna scattered everywhere; Moses on a small rocky outcrop in the deeper background gesturing toward the descending miraculous food; the Egyptian-Sinai wilderness landscape opening behind. The chromatic palette of saturated crimson, ochre, and pale silver-blue is characteristic of Allori's mature Florentine workshop manner under Medici grand-ducal patronage."}
]$JSON$::jsonb
where slug = 'alessandro-allori';

-- ─── Alessandro Magnasco ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-335975","paragraph":"Elijah Visited by an Angel in the Wilderness (1 Kings 19), painted by Alessandro Magnasco around 1687 in oil on canvas and now in the Metropolitan Museum of Art in New York, depicts the moment from 1 Kings 19 in which the prophet Elijah, fleeing from Queen Jezebel's persecution and weary unto death in the desert, is visited by an angel who feeds him bread and water for his forty-day journey to Mount Horeb. Magnasco stages the scene with characteristic dramatic-asceticism Romantic intensity: the small figure of Elijah collapsed under a juniper tree at the lower right, the angel descending from the upper left in a luminous burst of light bearing the bread and water, the wild rocky desert landscape stretching away to a turbulent horizon. The chromatic palette of grey, ochre, brown, and crimson against the dramatic stormy sky is the unmistakable Magnasco signature, and the painting is among his principal Old Testament treatments in any American collection."}
]$JSON$::jsonb
where slug = 'alessandro-magnasco';

-- ─── Alessandro Algardi ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-334747","paragraph":"The Holy Family with Two Angels, modeled by Alessandro Algardi around 1640 in terracotta and now in the Metropolitan Museum of Art in New York, is a small bozzetto (preparatory clay model) for one of his many religious sculptural compositions. The figures show the seated Virgin holding the Christ Child, with Joseph standing in formal attendance and two small attending angels at the upper register. The terracotta surface — modeled with rapid confident touches of the sculptor's fingers and small wooden tools — demonstrates Algardi's characteristic preparatory working method: small clay studies (bozzetti) refined into larger marble or bronze sculptures for the Roman papal and aristocratic patronage. Algardi's bozzetti survive in significant numbers across the major European and American collections and are among the principal records of his Roman seventeenth-century sculptural workshop method."},
  {"artwork_slug":"met-205131","paragraph":"Madonna and Child, modeled by Alessandro Algardi around 1630 in glazed and gilded plaster and now in the Metropolitan Museum of Art in New York, is one of the small relief Madonna compositions Algardi produced in his early Roman workshop years. The composition shows the Virgin in three-quarter view holding the Christ Child against her chest, the figures rendered in shallow relief with the soft sculptural modeling that defined Algardi's mature manner. The polychrome surface — flesh tones for the figures with gilded haloes and decorative borders — derives from the Florentine Della Robbia tradition that Algardi had absorbed during his Bolognese training before his Roman move."},
  {"artwork_slug":"met-202291","paragraph":"Christ at the Column, modeled by Alessandro Algardi around 1630 in bronze and now in the Metropolitan Museum of Art in New York, depicts the iconographic subject of the scourging of Christ — the moment from the Passion narratives in which Christ, bound to the column in the courtyard of the Praetorium, is whipped by Roman soldiers. Algardi shows the half-naked figure of Christ standing with his hands bound at the column, his head fallen forward, the muscular body modeled with the dramatic Caravaggesque compositional discipline that the Bolognese-Carracci tradition had refined. The small bronze is one of dozens of devotional sculptural compositions Algardi produced for Roman aristocratic and ecclesiastical patrons in workshop variants across his career."},
  {"artwork_slug":"met-197478","paragraph":"Baptism of Christ, modeled by Alessandro Algardi around 1650 in bronze and now in the Metropolitan Museum of Art in New York, depicts the moment from Matthew 3 in which John the Baptist baptizes Christ in the river Jordan. The composition shows Christ standing with hands folded in prayer; the Baptist on the left pours water from a small shell over Christ's head; the small Holy Spirit descends as a dove on a beam of light from the upper register. The small bronze is one of Algardi's standard devotional sculptural compositions and demonstrates his characteristic ability to translate the dramatic Roman Baroque compositional vocabulary into the small-format bronze devotional medium."},
  {"artwork_slug":"met-198307","paragraph":"The Rest on the Flight into Egypt, modeled by Alessandro Algardi around 1650 in bronze and now in the Metropolitan Museum of Art in New York, depicts the apocryphal subject of the Holy Family pausing in their flight from King Herod's persecution. The composition shows the seated Virgin holding the swaddled Christ Child in tender embrace, Joseph waiting beside the small donkey, the small attending angel descending from the upper register with a small vessel. The small bronze is one of dozens of devotional sculptural compositions Algardi produced for Roman aristocratic and ecclesiastical patrons in workshop variants and small-format bronze editions across his entire career."}
]$JSON$::jsonb
where slug = 'alessandro-algardi';

-- ─── Alessandro Casolani ───────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-363208","paragraph":"Studies for a Crucifixion, drawn by Alessandro Casolani around 1590 (the dating is somewhat early — Casolani would have been in his late thirties) in red chalk on paper and now in the Metropolitan Museum of Art in New York, is a sheet of preparatory studies for one of his many painted Crucifixion altarpiece compositions. The drawing shows multiple poses of the figure of Christ on the cross — torso, arms, legs in different foreshortenings — drawn rapidly with the soft red chalk that the late-Cinquecento Tuscan workshop tradition had refined to a high pitch. Such study sheets were the standard preparatory currency for late-Mannerist Sienese altarpiece practice and demonstrate the careful figural-study working method that Casolani and his Sienese contemporaries Salimbeni and Vanni shared in the Sienese late-Mannerist tradition."}
]$JSON$::jsonb
where slug = 'alessandro-casolani';

-- ─── Alessandro Tiarini ────────────────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"met-341659","paragraph":"Elevation of the Cross, drawn by Alessandro Tiarini around 1620 in pen and brown ink with wash on paper and now in the Metropolitan Museum of Art in New York, depicts the moment from the Synoptic Gospels in which the cross of Christ is hoisted upright by the Roman soldiers at Golgotha. Tiarini stages the scene with characteristic Bolognese Baroque compositional density: the cross rising diagonally across the entire composition, the soldiers straining to hoist it upright against the pull of ropes and pulleys, the body of Christ already nailed to the cross-beam, the assembled crowd of disciples and onlookers gathered around in the lower foreground. The drawing demonstrates Tiarini's characteristic combination of Carracci classicizing figural discipline and the early-Baroque dramatic compositional intensity that the Bolognese workshop tradition had developed in the years immediately after Annibale Carracci's death."}
]$JSON$::jsonb
where slug = 'alessandro-tiarini';

-- ─── Master of the Stuttgart Psalter ───────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"stuttgart-psalter-ps072","paragraph":"Stuttgart Psalter, Psalm 72 (folio 82r), illuminated around 825 in the Carolingian abbey of Saint-Germain-des-Prés in Paris, illustrates the great royal psalm of Solomon — Give the king thy judgments, O God, and thy righteousness unto the king's son — in which the just king is invoked to deliver the poor and the needy from oppression. The illustration shows the enthroned king at the center receiving petitioners and dispensing judgment in a small architectural setting, with the small figures of the poor and the oppressed gathered at his feet. The chromatic palette of saturated rose, ultramarine, and gold against the white parchment ground demonstrates the early-Carolingian Frankish illumination signature and the Stuttgart Master's particular fondness for the dramatic narrative moment over the formal ceremonial composition."},
  {"artwork_slug":"stuttgart-psalter-ps014","paragraph":"Stuttgart Psalter, Psalm 14 (folio 20v), illuminated around 825, illustrates the opening verse of the psalm — The fool hath said in his heart, There is no God — by depicting the figure of the fool in the conventional medieval iconographic costume of the court jester, his hand raised in the gesture of denial, with the figure of God appearing in the upper register in the act of revelation that the fool is denying. The illustration combines the typological reading of the psalm (the fool as the unrepentant sinner) with the literal reading of the verse text in a single small narrative composition characteristic of the Stuttgart Psalter workshop."},
  {"artwork_slug":"stuttgart-psalter-ps091","paragraph":"Stuttgart Psalter, Psalm 91 (folio 102v), illuminated around 825, illustrates the great protection psalm — He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty — by showing the protected figure surrounded by angels and the small figure of the divine presence in the upper register. The illustration includes the small lion and the small adder mentioned in verse 13 of the psalm (Thou shalt tread upon the lion and adder) — the medieval typological reading of which identified the lion and adder with the powers of evil overcome by the divine protection. The illustration is one of the most reproduced single pages of the Stuttgart Psalter."},
  {"artwork_slug":"stuttgart-psalter-ps054","paragraph":"Stuttgart Psalter, Psalm 54 (folio 64r), illuminated around 825, illustrates the lament psalm — Save me, O God, by thy name, and judge me by thy strength — in which the psalmist appeals to the divine judgment for vindication against the unjust accusers. The Stuttgart Master shows the kneeling psalmist at the lower right with arms raised in supplication, the figure of God in the upper register in the act of receiving the prayer, and the small figures of the unjust accusers gathered around the psalmist in the foreground. The composition combines the literal reading of the psalm text with the typological identification of the psalmist with David and (through the Christological typological tradition) with Christ in his Passion."},
  {"artwork_slug":"stuttgart-psalter-ps068","paragraph":"Stuttgart Psalter, Psalm 68 (folio 78r), illuminated around 825, illustrates the great theophanic psalm — Let God arise, let his enemies be scattered — in which the divine presence appears in glory and routs the enemies of his people. The Stuttgart Master shows the enthroned figure of God at the upper center in a luminous mandorla; small angels with trumpets surround the throne; the small figures of the routed enemies tumble in disarray in the lower register. The illustration is one of the most theologically dense pages of the Stuttgart Psalter and demonstrates the early-Carolingian Frankish workshop's interest in combining the literal psalm text with the typological identification of the divine theophany with the Christological themes of the Resurrection and the Last Judgment."}
]$JSON$::jsonb
where slug = 'stuttgart-psalter-master';

-- ─── Master of the Khludov Psalter ─────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"khludov-crucifixion-iconoclasts","paragraph":"The Crucifixion with Iconoclasts (Khludov Psalter, folio 67r), illuminated around 850–875 in Constantinople, is the most famous and most polemically charged single illustration of the Khludov Psalter — and one of the principal surviving early-medieval Byzantine documents of the Iconoclast controversy. The illustration depicts the Crucifixion of Christ in the upper register: the body of Christ on the cross, the soldiers below offering him the sponge of vinegar on a long reed. In the lower register the Khludov Master directly equates the iconoclasts of the recent Byzantine controversy with the persecutors of Christ — showing two iconoclast figures (identified by their tonsure and ecclesiastical dress) whitewashing an icon of Christ with long-handled brushes and a pail of lime, while the inscription beside them quotes the psalm verse about the unjust offering vinegar mixed with gall. The polemical equation made the Khludov a central document of the post-Iconoclast Byzantine ecclesiastical-political settlement of 843."},
  {"artwork_slug":"khludov-david-composing-psalms","paragraph":"David Composing the Psalms (Khludov Psalter), illuminated around 850–875 in Constantinople, depicts the Old Testament shepherd-king and traditional author of the Psalter in the conventional iconographic posture of inspired authorship — seated with his harp on his knee, his face lifted toward the small figure of the divine presence in the upper register. The Khludov Master shows David in royal Byzantine costume rather than in the conventional medieval shepherd's robe, reflecting the Constantinople workshop's particular emphasis on the kingly authority of the psalmist. The illustration is one of the standard Khludov compositions and serves as a kind of frontispiece to the entire Psalter narrative."},
  {"artwork_slug":"khludov-fiery-furnace","paragraph":"The Fiery Furnace (Khludov Psalter, Psalm 66), illuminated around 850–875 in Constantinople, illustrates the climactic episode from Daniel 3 in which Shadrach, Meshach, and Abednego are cast into the burning furnace by King Nebuchadnezzar for refusing to worship the golden image, but are protected from the flames by the divine intervention of an angel. The Khludov Master shows the three young men standing unharmed inside the furnace with their hands raised in prayer; the angel descends from the upper register to protect them; the flames lick around them but do not touch them. The illustration combines the literal Daniel narrative with the typological reading that identifies the three Hebrew youths with the steadfast Christians who refused to worship the iconoclast political authorities."},
  {"artwork_slug":"khludov-jonah","paragraph":"Jonah Prefiguring the Resurrection (Khludov Psalter), illuminated around 850–875 in Constantinople, illustrates the climactic episode from Jonah 2 in which the prophet Jonah, swallowed by the great fish for three days and three nights, is delivered from its belly onto dry land — the Old Testament event that Christ himself identified as the typological prefiguration of his own three-day death and Resurrection (Matthew 12:39–40). The Khludov Master shows the great fish disgorging Jonah onto the shore in a tight composition that emphasizes the typological reading of the moment as a Christological prefiguration. The illustration is among the most reproduced of the Khludov Old Testament-Christological typological compositions."},
  {"artwork_slug":"khludov-rivers-of-babylon","paragraph":"By the Rivers of Babylon (Khludov Psalter), illuminated around 850–875 in Constantinople, illustrates the famous lament psalm 137 — By the rivers of Babylon, there we sat down, yea, we wept, when we remembered Zion. We hanged our harps upon the willows in the midst thereof — by depicting the exiled Israelites seated on a riverbank under the willows with their small harps hanging in the trees above them and their faces lifted in attitudes of grief. The Khludov Master combines the literal reading of the psalm verse with the typological reading of the Babylonian exile as the figure of all subsequent exile and longing for the heavenly Jerusalem; the illustration is one of the most reproduced of the Khludov compositions and shaped the iconographic tradition of the subject in subsequent Byzantine psalter illustration."}
]$JSON$::jsonb
where slug = 'khludov-master';

-- ─── Master of the Utrecht Psalter ─────────────────────────────────────
update public.artists
set notable_works = $JSON$[
  {"artwork_slug":"utrecht-psalter-psalm-150","paragraph":"Utrecht Psalter, Psalm 150, illuminated around 825 at the Carolingian abbey of Hautvillers near Reims, illustrates the great closing psalm of the Psalter — Praise ye the Lord. Praise God in his sanctuary: praise him in the firmament of his power... Praise him with the sound of the trumpet: praise him with the psaltery and harp. Praise him with the timbrel and dance: praise him with stringed instruments and organs. Praise him upon the loud cymbals: praise him upon the high sounding cymbals. The Utrecht Master fills the small horizontal pen drawing with figures playing every musical instrument named in the psalm text — trumpets, psalteries, harps, timbrels, dancers, organs, cymbals — in a panoramic praise composition that became the canonical visualization of the subject in subsequent medieval European psalter illustration."},
  {"artwork_slug":"utrecht-psalter-psalm-91","paragraph":"Utrecht Psalter, Psalm 91, illuminated around 825 at Hautvillers, illustrates the great protection psalm — He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty — by depicting the protected figure at the lower center surrounded by attending angels, with the small lion and adder of verse 13 (Thou shalt tread upon the lion and adder) at his feet and the figure of the divine presence in the upper register. The Utrecht Master's rapid expressive pen line gives the composition the characteristic liveliness of the entire manuscript. The illustration was directly imitated by the later medieval English copies of the Utrecht Psalter — the Harley Psalter, the Eadwine Psalter, and the Paris Psalter — across the eleventh, twelfth, and thirteenth centuries."},
  {"artwork_slug":"utrecht-psalter-psalm-46","paragraph":"Utrecht Psalter, Psalm 46, illuminated around 825 at Hautvillers, illustrates the great refuge psalm — God is our refuge and strength, a very present help in trouble. Therefore will not we fear, though the earth be removed, and though the mountains be carried into the midst of the sea — by depicting a panoramic landscape of mountains being carried into the sea, with the small figures of the protected city of God at the upper register surrounded by the divine presence and the attending angels. The Utrecht Master's characteristic rapid expressive pen line and the panoramic landscape composition demonstrate the entire manuscript's pictorial signature at full statement."},
  {"artwork_slug":"utrecht-psalter-psalm-107","paragraph":"Utrecht Psalter, Psalm 107, illuminated around 825 at Hautvillers, illustrates the great praise-and-deliverance psalm — O give thanks unto the Lord, for he is good: for his mercy endureth for ever — by depicting the four kinds of deliverance described in the psalm text in four small narrative scenes within the single horizontal composition: the wanderers in the desert, the prisoners in chains, the sick on their beds, and the sailors on the storm-tossed sea. The four-fold compositional structure demonstrates the Utrecht Master's characteristic ability to compress a complex multi-scene narrative into a single horizontal pen drawing."},
  {"artwork_slug":"utrecht-psalter-psalm-145","paragraph":"Utrecht Psalter, Psalm 145, illuminated around 825 at Hautvillers, illustrates the great kingly praise psalm — I will extol thee, my God, O king; and I will bless thy name for ever and ever — by depicting the enthroned figure of God at the upper center surrounded by attending angels, with the small figures of the praising humans gathered in the lower register in postures of adoration and praise. The Utrecht Master's rapid expressive pen line and the careful panoramic landscape setting demonstrate the entire manuscript's pictorial signature at full mature statement and explain why the manuscript was directly imitated as the visual model for the principal medieval English psalter illustration tradition for the next four centuries."}
]$JSON$::jsonb
where slug = 'utrecht-psalter-master';
